#include "kart_demo_data.h"

#include <string.h>

#define DYNAMICS(mass_, air_, drag_, forward_, backward_, grip_brake_, slip_brake_, steer_, constraint_, front_grip_, rear_grip_, trigger_, trigger_time_, slip_, escape_, corner_) \
    { (mass_), (air_), (drag_), (forward_), (backward_), (grip_brake_), \
      (slip_brake_), (steer_), (constraint_), (front_grip_), (rear_grip_), \
      (trigger_), (trigger_time_), (slip_), (escape_), (corner_), 0.07f, 0.01f, \
      1.2f, 0.18f, 0.75f, 0.09f, 0.20f, 1.0f, 0.12f, \
      0.25f, 0.02f, \
      45.0f, 0.12f, 1200.0f }

#define PRACTICE_DYNAMICS \
    DYNAMICS(100.0f, 3.0f, 0.740f, 2000.0f, 1500.0f, 1800.0f, 1200.0f, \
             10.0f, 22.0f, 5.0f, 5.0f, 0.2f, 0.2f, 0.2f, 1500.0f, 0.2f)
#define STANDARD_DYNAMICS \
    DYNAMICS(100.0f, 3.0f, 0.725f, 3300.0f, 2000.0f, 2000.0f, 1500.0f, \
             10.0f, 28.0f, 5.0f, 5.0f, 0.2f, 0.2f, 0.2f, 4000.0f, 0.05f)
#define MARATHON_DYNAMICS \
    DYNAMICS(100.0f, 3.0f, 0.622f, 3000.0f, 2000.0f, 1500.0f, 1500.0f, \
             10.0f, 26.0f, 5.0f, 5.0f, 0.2f, 0.2f, 0.2f, 4000.0f, 0.2f)
#define SABER_DYNAMICS \
    DYNAMICS(100.0f, 3.0f, 0.786f, 3550.0f, 2000.0f, 3000.0f, 1500.0f, \
             10.0f, 29.0f, 5.0f, 5.0f, 0.2f, 0.2f, 0.2f, 4000.0f, 0.0f)
#define SOLID_DYNAMICS \
    DYNAMICS(100.0f, 3.0f, 0.855f, 3800.0f, 2000.0f, 2500.0f, 1500.0f, \
             10.0f, 30.0f, 5.0f, 5.0f, 0.2f, 0.2f, 0.2f, 4000.0f, 0.0f)
#define KART_DEFAULT_MAX_BOOSTERS 2u
#define KART(name_, dynamics_, half_width_, half_length_, height_) \
    { (name_), dynamics_, { (half_width_), (half_length_), 0.5f, 1.0f }, \
      (height_), KART_DEFAULT_MAX_BOOSTERS }

/* Exact model-root AABBs and parameter.xml values extracted from the 2004
   demo's kart.rho. The archive spells Cotton as "cotten". */
static const KartDemoKartSpec KARTS[] = {
    KART("practice1", PRACTICE_DYNAMICS, 0.7644821f, 0.81728435f, 0.81284374f),
    KART("burst1", PRACTICE_DYNAMICS, 0.7863699f, 0.86079025f, 0.81284374f),
    KART("burst2", STANDARD_DYNAMICS, 0.7489265f, 0.9987979f, 0.81284374f),
    KART("burst3", STANDARD_DYNAMICS, 0.8080695f, 1.06789325f, 0.81284374f),
    KART("burst4", STANDARD_DYNAMICS, 0.8378915f, 1.0619645f, 0.83439654f),
    KART("burst5", STANDARD_DYNAMICS, 0.8338487f, 1.1471490f, 0.9270710f),
    KART("cotten1", STANDARD_DYNAMICS, 0.7802979f, 0.8544110f, 0.81284374f),
    KART("cotten2", STANDARD_DYNAMICS, 0.7802979f, 0.98605945f, 0.81284374f),
    KART("cotten3", STANDARD_DYNAMICS, 0.8656463f, 1.09538875f, 0.81284374f),
    KART("cotten4", STANDARD_DYNAMICS, 0.8792389f, 1.0857897f, 0.87846375f),
    KART("cotten5", STANDARD_DYNAMICS, 0.87533175f, 1.13917575f, 0.9822382f),
    KART("marathon1", MARATHON_DYNAMICS, 0.74652725f, 0.8395150f, 0.81284374f),
    KART("marathon2", MARATHON_DYNAMICS, 0.78619005f, 0.9645016f, 0.81284374f),
    KART("marathon3", MARATHON_DYNAMICS, 0.90422895f, 1.0765728f, 0.81284374f),
    KART("marathon4", MARATHON_DYNAMICS, 0.84413935f, 1.1062925f, 0.81284374f),
    KART("marathon5", MARATHON_DYNAMICS, 0.8707624f, 1.24406455f, 0.9171259f),
    KART("saber1", SABER_DYNAMICS, 0.7815945f, 0.91753305f, 0.8148401f),
    KART("saber2", SABER_DYNAMICS, 0.7266946f, 1.04699875f, 0.81284374f),
    KART("saber3", SABER_DYNAMICS, 0.9616292f, 1.07968415f, 0.81284374f),
    KART("saber4", SABER_DYNAMICS, 0.91966365f, 1.1252806f, 0.83305377f),
    KART("saber5", SABER_DYNAMICS, 0.8918933f, 1.3687856f, 0.99534184f),
    KART("solid1", SOLID_DYNAMICS, 0.7267921f, 0.83080195f, 0.81284374f),
    KART("solid2", SOLID_DYNAMICS, 0.7744493f, 0.97958995f, 0.81284374f),
    KART("solid3", SOLID_DYNAMICS, 0.8325483f, 1.08305655f, 0.81284374f),
    KART("solid4", SOLID_DYNAMICS, 0.79691135f, 1.0517733f, 0.81284374f),
    KART("solid5", SOLID_DYNAMICS, 0.93279995f, 1.1436093f, 0.9673969f),
};

#define TRACK(asset_, display_, mode_, difficulty_, min_x_, min_y_, min_z_, max_x_, max_y_, max_z_, \
              start_kind_, start_axis_, start_x_, start_y_, start_z_) \
    { (asset_), (display_), (mode_), (difficulty_), { (min_x_), (min_y_), (min_z_) }, \
      { (max_x_), (max_y_), (max_z_) }, true, (start_kind_), (start_axis_), \
      { (start_x_), (start_y_), (start_z_) } }

/* The synthetic reference track: no mesh, so the simulators fall back to the
   flat ground plane and the cyan AABB walls. Its footprint matches Forest Log
   (896.391 x 807.183) and it is centred on the world origin, which makes it the
   clearest scene for reading the world axis gizmo. */
#define FLAT_TRACK(asset_, display_, mode_, half_x_, half_y_, height_) \
    { (asset_), (display_), (mode_), 0, { -(half_x_), -(half_y_), 0.0f }, \
      { (half_x_), (half_y_), (height_) }, false, KART_TRACK_START_NONE, \
      KART_TRACK_AXIS_NONE, { 0.0f, 0.0f, 0.0f } }

/* All values below are regenerated by DeveloperTools/AssetPipeline/derive_track_constants.py from the
   KTRK exports, so the AABB, the embedded scene, the safety wall, the minimap
   normalization and the spawn all come from one source.

   AABB      full mesh-vertex bounds, as recorded in the KTRK header.
   start x/y centroid of the road-flagged mesh whose texture contains "start".
   start z   that quad's plane, used as the scene ground height.

   The racing direction's sign is not in the mesh data; see KartTrackStartKind. */
static const KartDemoTrackSpec TRACKS[] = {
    FLAT_TRACK("flat_test", "테스트 평지", "테스트", 448.1955f, 403.5915f, 120.0f),
    /* RoadObj01@s0 / de_sand_road01_start, aspect 3.04 */
    TRACK("desert_I01", "사막 지옥의 모래구덩이", "아이템", 2,
          27.22131f, 17.29889f, 6.201988f, 976.4961f, 1240.95f, 131.7757f,
          KART_TRACK_START_AXIS_CLEAR, KART_TRACK_AXIS_Y, 535.2981f, 643.5748f, 30.19893f),
    /* road_..03@s0 / road_ston_start, aspect 5.57 */
    TRACK("desert_I02", "사막 피라미드 탐험", "아이템", 2,
          15.52185f, 21.88702f, 15.50548f, 716.0608f, 1257.209f, 131.0995f,
          KART_TRACK_START_AXIS_CLEAR, KART_TRACK_AXIS_Y, 270.9646f, 765.0216f, 21.74277f),
    /* RoadObj02@s11 / de_sand_road01_start, aspect 3.30 */
    TRACK("desert_R01", "사막 빙글빙글 공사장", "스피드", 4,
          -75.36597f, 49.39597f, 5.913539f, 1131.802f, 986.7229f, 152.137f,
          KART_TRACK_START_AXIS_CLEAR, KART_TRACK_AXIS_Y, 264.6601f, 490.8936f, 37.98141f),
    /* RoadObj01@s4 / F_roadstart01, aspect 4.13; direction checked against the original. */
    TRACK("forest_I01", "포레스트 통나무", "아이템", 1,
          13.48803f, 27.24757f, 1.752445f, 909.879f, 834.4304f, 118.1231f,
          KART_TRACK_START_CONFIRMED, KART_TRACK_AXIS_Y, 758.6121f, 484.8074f, 27.07603f),
    /* RoadObj01@s11 / F_roadstart01, aspect 4.96 */
    TRACK("forest_I02", "포레스트 버섯동굴", "아이템", 2,
          82.21716f, -140.4142f, -1.271019f, 754.2902f, 1395.292f, 113.3375f,
          KART_TRACK_START_AXIS_CLEAR, KART_TRACK_AXIS_Y, 224.0634f, 553.9555f, 31.909f),
    /* RoadObj01@s1 / F_roadstart01, aspect 4.32 */
    TRACK("forest_R02", "포레스트 지그재그", "스피드", 4,
          -7.913147f, -134.8193f, -0.718708f, 1084.896f, 1392.051f, 172.8659f,
          KART_TRACK_START_AXIS_CLEAR, KART_TRACK_AXIS_Y, 738.7255f, 341.9955f, 60.39529f),
    /* RoadObj03@s1 / ice_road_start_G, aspect 2.37 - too square to trust the axis. */
    TRACK("ice_I01", "아이스 갈라진 빙산", "아이템→현재 스피드", 4,
          24.31265f, 60.53888f, 1.654024f, 1107.896f, 1165.535f, 318.2377f,
          KART_TRACK_START_AXIS_WEAK, KART_TRACK_AXIS_Y, 405.2543f, 737.3219f, 15.57826f),
    /* r_<hangul>+@s1 / ice_i02_start, aspect 1.92 - a start pad rather than a
       stripe, and flagged as scenery because its node name is Korean. */
    TRACK("ice_I02", "아이스 상어의 무덤", "아이템", 1,
          93.76453f, 55.66373f, -5.161366f, 870.5864f, 896.9417f, 313.5863f,
          KART_TRACK_START_AXIS_WEAK, KART_TRACK_AXIS_Y, 381.7374f, 456.2767f, 13.87031f),
    /* RoadObj01@s0 / road_snow_start, aspect 1.94 - too square to trust the axis. */
    TRACK("ice_R01", "아이스 설산 다운힐", "스피드", 5,
          40.15965f, -209.4469f, 11.96741f, 1979.582f, 1983.356f, 796.1914f,
          KART_TRACK_START_AXIS_WEAK, KART_TRACK_AXIS_X, 1088.797f, 1561.169f, 530.375f),
    /* RoadObj01@s6 / cement06_start, aspect 5.37 */
    TRACK("village_I01", "빌리지 시계탑", "아이템", 2,
          6.550034f, 13.51373f, 0.5811663f, 723.9319f, 1013.374f, 87.23308f,
          KART_TRACK_START_AXIS_CLEAR, KART_TRACK_AXIS_X, 314.5892f, 152.8071f, 13.29302f),
    /* RoadObj03@s7 / cement06_start, aspect 5.84 */
    TRACK("village_I02", "빌리지 손가락", "아이템→현재 스피드", 3,
          -2.671448f, 11.83069f, -1.29806f, 561.3079f, 682.4102f, 49.30659f,
          KART_TRACK_START_AXIS_CLEAR, KART_TRACK_AXIS_Y, 119.2628f, 337.893f, 8.578018f),
    /* RoadObj01@s5 / cement_start, aspect 5.94; direction checked against the original. */
    TRACK("village_R01", "빌리지 고가의 질주", "스피드", 2,
          -36.535f, -111.3333f, 2.849871f, 1239.292f, 1600.784f, 106.8285f,
          KART_TRACK_START_CONFIRMED, KART_TRACK_AXIS_Y, 143.6366f, 523.2488f, 26.84984f),
    /* RoadObj01a@s1 / cement01_start, aspect 6.28 */
    TRACK("village_R03", "빌리지 붐힐터널", "스피드", 4,
          23.36246f, 46.18066f, 8.646021f, 1213.144f, 1447.473f, 90.51943f,
          KART_TRACK_START_AXIS_CLEAR, KART_TRACK_AXIS_Y, 215.792f, 600.6079f, 27.30944f),
};

unsigned int kart_demo_kart_count(void)
{
    return (unsigned int)(sizeof(KARTS) / sizeof(KARTS[0]));
}

const KartDemoKartSpec *kart_demo_kart_at(unsigned int index)
{
    return index < kart_demo_kart_count() ? &KARTS[index] : NULL;
}

const KartDemoKartSpec *kart_demo_find_kart(const char *asset_name)
{
    unsigned int i;
    if (asset_name == NULL) return NULL;
    for (i = 0; i < kart_demo_kart_count(); ++i)
        if (strcmp(KARTS[i].asset_name, asset_name) == 0) return &KARTS[i];
    return NULL;
}

const KartDemoKartSpec *kart_demo_default_kart(void)
{
    /* The original demo's kartlist.xml offers only burst3; cotten5 is a
       simulator-side choice, not the demo's selection. */
    return kart_demo_find_kart("cotten5");
}

_Static_assert(
    sizeof(TRACKS) / sizeof(TRACKS[0]) == KART_DEMO_TRACK_COUNT,
    "KART_DEMO_TRACK_COUNT must match TRACKS[]; the demos' scene and minimap "
    "resource tables are indexed in the same order");

unsigned int kart_demo_track_count(void)
{
    return (unsigned int)(sizeof(TRACKS) / sizeof(TRACKS[0]));
}

const KartDemoTrackSpec *kart_demo_track_at(unsigned int index)
{
    return index < kart_demo_track_count() ? &TRACKS[index] : NULL;
}

const KartDemoTrackSpec *kart_demo_find_track(const char *asset_name)
{
    unsigned int i;
    if (asset_name == NULL) return NULL;
    for (i = 0; i < kart_demo_track_count(); ++i)
        if (strcmp(TRACKS[i].asset_name, asset_name) == 0) return &TRACKS[i];
    return NULL;
}

const KartDemoTrackSpec *kart_demo_default_track(void)
{
    /* Start on the synthetic flat track: no mesh, so what is on screen is only
       the recovered physics against a known ground plane and known walls. */
    return kart_demo_find_track("flat_test");
}

float kart_demo_track_width(const KartDemoTrackSpec *track)
{
    return track != NULL ? track->maximum.x - track->minimum.x : 0.0f;
}

float kart_demo_track_length(const KartDemoTrackSpec *track)
{
    return track != NULL ? track->maximum.y - track->minimum.y : 0.0f;
}

bool kart_demo_track_start_position(
    const KartDemoTrackSpec *track,
    KartVec3 *position)
{
    if (track == NULL || position == NULL) return false;
    if (track->start_kind == KART_TRACK_START_NONE) return false;
    *position = (KartVec3){
        kart_demo_track_mirror_x(track)
            ? (track->minimum.x + track->maximum.x) * 0.5f - track->start_line.x
            : track->start_line.x - (track->minimum.x + track->maximum.x) * 0.5f,
        track->start_line.y - (track->minimum.y + track->maximum.y) * 0.5f,
        0.0f,
    };
    return true;
}

bool kart_demo_track_start_orientation(
    const KartDemoTrackSpec *track,
    KartQuat *orientation)
{
    if (track == NULL || orientation == NULL) return false;
    /* A track with no start line still gets the same facing as every other
       track. Only its spawn position falls back to the bounds centre; leaving
       the raw default here would point it at -Y, opposite to all 13 real
       tracks, which is confusing on the flat reference track.

       The default body basis initializes forward to -Y and body-right to +X.
       Both cases below are stated directly in world axes, the same frame the
       simulators' axis gizmo shows, so the scene's X mirror does not enter
       into them.

       A start line whose stripe runs along X is driven along Y, and the
       assumed direction is world +Y. A 180-degree Z rotation turns forward
       from -Y to +Y and body-right from +X to -X together, so steering and
       camera handedness are preserved.

       A stripe running along Y is driven along X, assumed world +X. That is
       the same pose turned a further -90 degrees about Z, which puts
       body-right at +Y and preserves handedness in the same way. */
    if (track->start_axis == KART_TRACK_AXIS_X) {
        const float half_root_two = 0.70710678f;
        *orientation = (KartQuat){
            .w = half_root_two, .x = 0.0f, .y = 0.0f, .z = half_root_two};
        return true;
    }
    *orientation = (KartQuat){.w = 0.0f, .x = 0.0f, .y = 0.0f, .z = 1.0f};
    return true;
}

bool kart_demo_track_mirror_x(const KartDemoTrackSpec *track)
{
    /* The KTRK exporter keeps the original axes, whose X runs opposite to the
       simulator's display convention. That is a property of the export, not of
       any one track, so every scene uses the same mirror. */
    return track != NULL;
}

float kart_demo_track_scene_ground_z(const KartDemoTrackSpec *track)
{
    if (track == NULL) return 0.0f;
    if (track->start_kind == KART_TRACK_START_NONE) return track->minimum.z;
    return track->start_line.z;
}

float kart_demo_track_fall_limit(const KartDemoTrackSpec *track)
{
    /* Clearance below the lowest scene geometry. Wide enough that a kart
       bouncing hard off a steep face is never mistaken for a fall. */
    const float margin = 40.0f;
    float floor_z;
    if (track == NULL) return -margin;
    /* Scene vertices are shifted so the start-line plane sits at world z 0. */
    floor_z = track->minimum.z - kart_demo_track_scene_ground_z(track);
    if (floor_z > 0.0f) floor_z = 0.0f;
    return floor_z - margin;
}

const char *kart_demo_track_start_kind_label(const KartDemoTrackSpec *track)
{
    if (track == NULL) return "";
    switch (track->start_kind) {
    case KART_TRACK_START_CONFIRMED: return "confirmed";
    case KART_TRACK_START_AXIS_CLEAR: return "assumed dir";
    case KART_TRACK_START_AXIS_WEAK: return "assumed axis";
    case KART_TRACK_START_NONE: break;
    }
    return "no start line";
}
