Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 0049e800
ENTRY 0049e800
NAME FUN_0049e800
SIGNATURE undefined1 __fastcall FUN_0049e800(int param_1)
BODY [[0049e800, 0049e810]]


undefined1 __fastcall FUN_0049e800(int param_1)

{
  return *(undefined1 *)(param_1 + 8);
}



================================================================================
REQUESTED 0049e820
ENTRY 0049e820
NAME FUN_0049e820
SIGNATURE undefined1 __fastcall FUN_0049e820(int param_1)
BODY [[0049e820, 0049e830]]


undefined1 __fastcall FUN_0049e820(int param_1)

{
  return *(undefined1 *)(param_1 + 9);
}



================================================================================
REQUESTED 004b0640
ENTRY 004b0640
NAME FUN_004b0640
SIGNATURE undefined4 __fastcall FUN_004b0640(int param_1)
BODY [[004b0640, 004b0650]]


undefined4 __fastcall FUN_004b0640(int param_1)

{
  return *(undefined4 *)(param_1 + 0xc);
}



================================================================================
REQUESTED 0049e840
ENTRY 0049e840
NAME FUN_0049e840
SIGNATURE undefined4 __fastcall FUN_0049e840(int param_1)
BODY [[0049e840, 0049e850]]


undefined4 __fastcall FUN_0049e840(int param_1)

{
  return *(undefined4 *)(param_1 + 0x10);
}



================================================================================
REQUESTED 0049e860
ENTRY 0049e860
NAME FUN_0049e860
SIGNATURE void * __thiscall FUN_0049e860(void * this, void * param_1)
BODY [[0049e860, 0049e87e]]


void * __thiscall FUN_0049e860(void *this,void *param_1)

{
  FUN_00418970(param_1,(undefined4 *)((int)this + 0x14));
  return param_1;
}



================================================================================
REQUESTED 0049e880
ENTRY 0049e880
NAME FUN_0049e880
SIGNATURE float10 __fastcall FUN_0049e880(int param_1)
BODY [[0049e880, 0049e890]]


float10 __fastcall FUN_0049e880(int param_1)

{
  return (float10)*(float *)(param_1 + 0x18);
}



================================================================================
REQUESTED 0049e8a0
ENTRY 0049e8a0
NAME FUN_0049e8a0
SIGNATURE float10 __fastcall FUN_0049e8a0(int param_1)
BODY [[0049e8a0, 0049e8b0]]


float10 __fastcall FUN_0049e8a0(int param_1)

{
  return (float10)*(float *)(param_1 + 0x1c);
}



================================================================================
REQUESTED 0049e8c0
ENTRY 0049e8c0
NAME FUN_0049e8c0
SIGNATURE undefined4 __fastcall FUN_0049e8c0(int param_1)
BODY [[0049e8c0, 0049e8d0]]


undefined4 __fastcall FUN_0049e8c0(int param_1)

{
  return *(undefined4 *)(param_1 + 0x20);
}



================================================================================
REQUESTED 0049e8e0
ENTRY 0049e8e0
NAME FUN_0049e8e0
SIGNATURE undefined4 __fastcall FUN_0049e8e0(int param_1)
BODY [[0049e8e0, 0049e8f0]]


undefined4 __fastcall FUN_0049e8e0(int param_1)

{
  return *(undefined4 *)(param_1 + 0x24);
}



================================================================================
REQUESTED 0049e900
ENTRY 0049e900
NAME FUN_0049e900
SIGNATURE void * __thiscall FUN_0049e900(void * this, void * param_1)
BODY [[0049e900, 0049e91e]]


void * __thiscall FUN_0049e900(void *this,void *param_1)

{
  FUN_00418970(param_1,(undefined4 *)((int)this + 0x28));
  return param_1;
}



================================================================================
REQUESTED 0049e920
ENTRY 0049e920
NAME FUN_0049e920
SIGNATURE void * __thiscall FUN_0049e920(void * this, void * param_1)
BODY [[0049e920, 0049e93e]]


void * __thiscall FUN_0049e920(void *this,void *param_1)

{
  FUN_00418970(param_1,(undefined4 *)((int)this + 0x2c));
  return param_1;
}



================================================================================
REQUESTED 0049e940
ENTRY 0049e940
NAME FUN_0049e940
SIGNATURE undefined4 __thiscall FUN_0049e940(void * this, int param_1)
BODY [[0049e940, 0049e985]]


uint __thiscall FUN_0049e940(void *this,int param_1)

{
  char cVar1;
  undefined3 extraout_var;
  uint uVar3;
  void *pvVar2;
  
  if (*(int *)((int)this + 0x18) == 0) {
LAB_0049e971:
    *(int *)((int)this + 0x18) = param_1;
    uVar3 = CONCAT31((int3)((uint)this >> 8),1);
  }
  else {
    pvVar2 = this;
    if (*(int *)((int)this + 0x18) != param_1) {
      cVar1 = FUN_0049e990(*(void **)((int)this + 0x18),param_1);
      pvVar2 = (void *)CONCAT31(extraout_var,cVar1);
      if (cVar1 == '\0') goto LAB_0049e971;
    }
    uVar3 = (uint)pvVar2 & 0xffffff00;
  }
  return uVar3;
}



================================================================================
REQUESTED 0049eac0
ENTRY 0049eac0
NAME FUN_0049eac0
SIGNATURE undefined __thiscall FUN_0049eac0(void * this, undefined1 param_1)
BODY [[0049eac0, 0049ead5]]


void __thiscall FUN_0049eac0(void *this,undefined1 param_1)

{
  *(undefined1 *)((int)this + 2) = param_1;
  return;
}



================================================================================
REQUESTED 0049eae0
ENTRY 0049eae0
NAME FUN_0049eae0
SIGNATURE undefined __thiscall FUN_0049eae0(void * this, undefined1 param_1)
BODY [[0049eae0, 0049eaf5]]


void __thiscall FUN_0049eae0(void *this,undefined1 param_1)

{
  *(undefined1 *)((int)this + 3) = param_1;
  return;
}



================================================================================
REQUESTED 0049eb00
ENTRY 0049eb00
NAME FUN_0049eb00
SIGNATURE undefined __fastcall FUN_0049eb00(int param_1)
BODY [[0049eb00, 0049eb29]]


void __fastcall FUN_0049eb00(int param_1)

{
  int iVar1;
  undefined1 local_c [8];
  
  iVar1 = param_1;
  FUN_00418970(&stack0xffffffec,(undefined4 *)&stack0x00000004);
  FUN_004187d0((void *)(param_1 + 0x18),local_c,iVar1);
  return;
}



================================================================================
REQUESTED 0044fdf0
ENTRY 0044fdf0
NAME FUN_0044fdf0
SIGNATURE undefined __thiscall FUN_0044fdf0(void * this, undefined4 param_1)
BODY [[0044fdf0, 0044fe05]]


void __thiscall FUN_0044fdf0(void *this,undefined4 param_1)

{
  *(undefined4 *)((int)this + 0x1c) = param_1;
  return;
}



================================================================================
REQUESTED 00497360
ENTRY 00497360
NAME FUN_00497360
SIGNATURE undefined __thiscall FUN_00497360(void * this, undefined4 param_1)
BODY [[00497360, 00497375]]


void __thiscall FUN_00497360(void *this,undefined4 param_1)

{
  *(undefined4 *)((int)this + 0x20) = param_1;
  return;
}



================================================================================
REQUESTED 00438630
ENTRY 00438630
NAME FUN_00438630
SIGNATURE undefined __thiscall FUN_00438630(void * this, undefined4 param_1)
BODY [[00438630, 00438645]]


void __thiscall FUN_00438630(void *this,undefined4 param_1)

{
  *(undefined4 *)((int)this + 0x24) = param_1;
  return;
}



================================================================================
REQUESTED 0049eb30
ENTRY 0049eb30
NAME FUN_0049eb30
SIGNATURE undefined __thiscall FUN_0049eb30(void * this, int param_1)
BODY [[0049eb30, 0049eb54]]


void __thiscall FUN_0049eb30(void *this,int param_1)

{
  *(int *)((int)this + 0x28) = param_1;
  DAT_005bbff8 = (&PTR_DAT_0059aa38)[param_1];
  return;
}



================================================================================
REQUESTED 0043d800
ENTRY 0043d800
NAME FUN_0043d800
SIGNATURE undefined __fastcall FUN_0043d800(int param_1)
BODY [[0043d800, 0043d829]]


void __fastcall FUN_0043d800(int param_1)

{
  int iVar1;
  undefined1 local_c [8];
  
  iVar1 = param_1;
  FUN_00418970(&stack0xffffffec,(undefined4 *)&stack0x00000004);
  FUN_004187d0((void *)(param_1 + 0x2c),local_c,iVar1);
  return;
}



================================================================================
REQUESTED 0049eb60
ENTRY 0049eb60
NAME FUN_0049eb60
SIGNATURE undefined __fastcall FUN_0049eb60(int param_1)
BODY [[0049eb60, 0049eb89]]


void __fastcall FUN_0049eb60(int param_1)

{
  int iVar1;
  undefined1 local_c [8];
  
  iVar1 = param_1;
  FUN_00418970(&stack0xffffffec,(undefined4 *)&stack0x00000004);
  FUN_004187d0((void *)(param_1 + 0x30),local_c,iVar1);
  return;
}



