Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00481cd0
ENTRY 00481cd0
NAME FUN_00481cd0
SIGNATURE undefined __cdecl FUN_00481cd0(float * param_1, float param_2, float * param_3, float * param_4)
BODY [[00481cd0, 00481db6]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl FUN_00481cd0(float *param_1,float param_2,float *param_3,float *param_4)

{
  float10 fVar1;
  float local_8;
  
  fVar1 = FUN_0042b800(param_3,param_4);
  if (param_2 < _DAT_005710b8 == (param_2 == _DAT_005710b8)) {
    fVar1 = FUN_00482590(_DAT_00571490 - param_2,(float)fVar1);
    fVar1 = (float10)_DAT_00571490 - fVar1;
  }
  else {
    fVar1 = FUN_00482590(param_2,(float)fVar1);
  }
  local_8 = (float)fVar1;
  *param_1 = (*param_4 - *param_3) * local_8 + *param_3;
  param_1[1] = (param_4[1] - param_3[1]) * local_8 + param_3[1];
  param_1[2] = (param_4[2] - param_3[2]) * local_8 + param_3[2];
  param_1[3] = (param_4[3] - param_3[3]) * local_8 + param_3[3];
  FUN_00482490(param_1);
  return;
}



