Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00444b92
ENTRY 00444b80
NAME FUN_00444b80
SIGNATURE undefined4 * __fastcall FUN_00444b80(undefined4 * param_1)
BODY [[00444b80, 00444bd3]]


undefined4 * __fastcall FUN_00444b80(undefined4 *param_1)

{
  FUN_00444b40(param_1);
  *param_1 = &PTR_FUN_00572650;
  CSize::CSize((CSize *)(param_1 + 5));
  CSize::CSize((CSize *)(param_1 + 10));
  CSize::CSize((CSize *)(param_1 + 0x10));
  param_1[3] = 0;
  FUN_00444c00(param_1,0);
  return param_1;
}



================================================================================
REQUESTED 00444bea
ENTRY 00444be0
NAME FUN_00444be0
SIGNATURE undefined __fastcall FUN_00444be0(undefined4 * param_1)
BODY [[00444be0, 00444bfb]]


void __fastcall FUN_00444be0(undefined4 *param_1)

{
  *param_1 = &PTR_FUN_00572650;
  FUN_00444b60(param_1);
  return;
}



================================================================================
REQUESTED 00445392
ENTRY 00445380
NAME FUN_00445380
SIGNATURE undefined4 * __fastcall FUN_00445380(undefined4 * param_1)
BODY [[00445380, 004453e9]]


undefined4 * __fastcall FUN_00445380(undefined4 *param_1)

{
  FUN_00444b40(param_1);
  *param_1 = &PTR_FUN_005726f4;
  FUN_004b30e0(param_1 + 3);
  FUN_004b30e0(param_1 + 4);
  param_1[6] = 0;
  FUN_0044bde0(param_1 + 3,0);
  FUN_0044bde0(param_1 + 4,0);
  *(undefined1 *)(param_1 + 2) = 0;
  param_1[5] = 0;
  return param_1;
}



================================================================================
REQUESTED 004453fa
ENTRY 004453f0
NAME _AFX_EDIT_STATE::~_AFX_EDIT_STATE
SIGNATURE void __thiscall ~_AFX_EDIT_STATE(_AFX_EDIT_STATE * this)
BODY [[004453f0, 00445421]]


/* Library Function - Single Match
    public: virtual __thiscall _AFX_EDIT_STATE::~_AFX_EDIT_STATE(void)
   
   Library: Visual Studio 2008 Debug */

void __thiscall _AFX_EDIT_STATE::~_AFX_EDIT_STATE(_AFX_EDIT_STATE *this)

{
  *(undefined ***)this = &PTR_FUN_005726f4;
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)(this + 0x10));
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)(this + 0xc));
  FUN_00444b60((undefined4 *)this);
  return;
}



