Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00413650
ENTRY 00413650
NAME FUN_00413650
SIGNATURE void * __thiscall FUN_00413650(void * this, void * param_1)
BODY [[00413650, 0041368a]]


void * __thiscall FUN_00413650(void *this,void *param_1)

{
                    /* WARNING: Load size is inaccurate */
  FUN_004135a0(param_1,-*this,-*(float *)((int)this + 4),-*(float *)((int)this + 8));
  return param_1;
}



================================================================================
REQUESTED 004135d0
ENTRY 004135d0
NAME FUN_004135d0
SIGNATURE undefined4 * __thiscall FUN_004135d0(void * this, undefined4 * param_1)
BODY [[004135d0, 00413601]]


undefined4 * __thiscall FUN_004135d0(void *this,undefined4 *param_1)

{
  *(undefined4 *)this = *param_1;
  *(undefined4 *)((int)this + 4) = param_1[1];
  *(undefined4 *)((int)this + 8) = param_1[2];
  return (undefined4 *)this;
}



================================================================================
REQUESTED 004137a0
ENTRY 004137a0
NAME FUN_004137a0
SIGNATURE undefined4 * __thiscall FUN_004137a0(void * this, undefined4 * param_1)
BODY [[004137a0, 004137c0]]


undefined4 * __thiscall FUN_004137a0(void *this,undefined4 *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  
  puVar2 = (undefined4 *)this;
  for (iVar1 = 9; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = *param_1;
    param_1 = param_1 + 1;
    puVar2 = puVar2 + 1;
  }
  return (undefined4 *)this;
}



