Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004c17d0
ENTRY 004c17d0
NAME FUN_004c17d0
SIGNATURE undefined __thiscall FUN_004c17d0(void * this, undefined4 param_1, undefined4 * param_2, undefined4 param_3)
BODY [[004c17d0, 004c1c5c]]


void __thiscall FUN_004c17d0(void *this,undefined4 param_1,undefined4 *param_2,undefined4 param_3)

{
  undefined1 uVar1;
  void *pvVar2;
  uint uVar3;
  int *piVar4;
  int iVar5;
  undefined4 *extraout_EAX;
  float10 fVar6;
  undefined4 *puVar7;
  int *piVar8;
  undefined4 *puVar9;
  int *piVar10;
  CDialogTemplate *pCVar11;
  undefined4 uVar12;
  float fVar13;
  undefined4 *local_98;
  int local_90;
  int local_8c;
  char local_85;
  int local_84;
  int local_80;
  char local_79;
  int local_78;
  int local_74;
  char local_6d;
  int local_6c;
  int local_68;
  char local_61;
  int local_60;
  int local_5c;
  char local_55;
  CDialogTemplate local_54 [4];
  int local_50 [3];
  undefined4 *local_44;
  int local_40;
  int local_3c;
  int local_38;
  char local_31;
  int local_30;
  int local_2c;
  int local_28;
  int local_24;
  char local_1d;
  CDialogTemplate local_18 [4];
  shared_ptr<class___ExceptionPtr> local_14 [4];
  CDialogTemplate local_10 [4];
  int local_c;
  int local_8;
  
  puVar7 = param_2;
  puVar9 = param_2;
  uVar12 = param_3;
  FUN_004815c0(&stack0xffffff5c,&param_1);
  FUN_004be9b0(this,puVar7,puVar9,uVar12);
  FUN_00401f80(&local_8,(int *)&DAT_005ac53c);
  FUN_0040cd80(&local_24,L"camera");
  piVar4 = &local_24;
  pvVar2 = (void *)FUN_00427130(&param_1);
  uVar3 = FUN_0047a360(pvVar2,piVar4);
  local_1d = (char)uVar3;
  FUN_0040dab0(&local_24);
  if (local_1d != '\0') {
    FUN_0040cd80(&local_28,L"");
    FUN_0040cd80(&local_2c,L"camera");
    piVar4 = &local_28;
    piVar10 = &local_2c;
    piVar8 = &local_30;
    pvVar2 = (void *)FUN_00427130(&param_1);
    piVar4 = (int *)FUN_0047a7f0(pvVar2,piVar8,piVar10,piVar4);
    FUN_0040c210(&local_8,piVar4);
    FUN_0040dab0(&local_30);
    FUN_0040dab0(&local_2c);
    FUN_0040dab0(&local_28);
  }
  FUN_0040cd80(&local_38,L"scene");
  piVar4 = &local_38;
  pvVar2 = (void *)FUN_00427130(&param_1);
  uVar3 = FUN_0047a360(pvVar2,piVar4);
  local_31 = (char)uVar3;
  FUN_0040dab0(&local_38);
  if (local_31 != '\0') {
    FUN_0040cd80(&local_3c,L"");
    FUN_0040cd80(&local_40,L"scene");
    piVar4 = &local_3c;
    piVar10 = &local_40;
    piVar8 = &local_c;
    pvVar2 = (void *)FUN_00427130(&param_1);
    FUN_0047a7f0(pvVar2,piVar8,piVar10,piVar4);
    FUN_0040dab0(&local_40);
    FUN_0040dab0(&local_3c);
    local_44 = (undefined4 *)FUN_00478523(0x688);
    if (local_44 == (undefined4 *)0x0) {
      local_98 = (undefined4 *)0x0;
    }
    else {
      local_98 = FUN_004aaa20(local_44);
    }
    FUN_0045b690(local_10,(int)local_98,'\x01');
    FUN_004a95b0(local_18,&local_c,param_2);
    FUN_00469690(&stack0xffffff64,(int *)local_18);
    iVar5 = FUN_00427130((undefined4 *)local_10);
    FUN_0044c2c0(iVar5);
    FUN_0045b5d0(&stack0xffffff64,(undefined4 *)local_10);
    FUN_004c1410((int)this);
    FUN_0040cd80(local_50,L"cameraName");
    piVar4 = local_50;
    pCVar11 = local_54;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_18);
    FUN_004980e0(pvVar2,pCVar11,piVar4);
    FUN_004c1db0(local_14,extraout_EAX);
    CDialogTemplate::~CDialogTemplate(local_54);
    FUN_0040dab0(local_50);
    iVar5 = FUN_00427130((undefined4 *)local_14);
    if (iVar5 != 0) {
      std::shared_ptr<class___ExceptionPtr>::operator=
                ((shared_ptr<class___ExceptionPtr> *)((int)this + 500),local_14);
    }
    CDialogTemplate::~CDialogTemplate((CDialogTemplate *)local_14);
    CDialogTemplate::~CDialogTemplate(local_18);
    CDialogTemplate::~CDialogTemplate(local_10);
    FUN_0040dab0(&local_c);
  }
  FUN_0040cd80(&local_5c,L"clearZBefore");
  piVar4 = &local_5c;
  pvVar2 = (void *)FUN_00427130(&param_1);
  uVar3 = FUN_0047a360(pvVar2,piVar4);
  local_55 = (char)uVar3;
  FUN_0040dab0(&local_5c);
  if (local_55 != '\0') {
    FUN_0040cd80(&local_60,L"clearZBefore");
    uVar1 = 0;
    piVar4 = &local_60;
    pvVar2 = (void *)FUN_00427130(&param_1);
    uVar1 = FUN_0047a470(pvVar2,piVar4,uVar1);
    FUN_004c1750(this,uVar1);
    FUN_0040dab0(&local_60);
  }
  FUN_0040cd80(&local_68,L"clearZAfter");
  piVar4 = &local_68;
  pvVar2 = (void *)FUN_00427130(&param_1);
  uVar3 = FUN_0047a360(pvVar2,piVar4);
  local_61 = (char)uVar3;
  FUN_0040dab0(&local_68);
  if (local_61 != '\0') {
    FUN_0040cd80(&local_6c,L"clearZAfter");
    uVar1 = 0;
    piVar4 = &local_6c;
    pvVar2 = (void *)FUN_00427130(&param_1);
    uVar1 = FUN_0047a470(pvVar2,piVar4,uVar1);
    FUN_004c1790(this,uVar1);
    FUN_0040dab0(&local_6c);
  }
  FUN_0040cd80(&local_74,L"nearPlane");
  piVar4 = &local_74;
  pvVar2 = (void *)FUN_00427130(&param_1);
  uVar3 = FUN_0047a360(pvVar2,piVar4);
  local_6d = (char)uVar3;
  FUN_0040dab0(&local_74);
  if (local_6d != '\0') {
    FUN_0040cd80(&local_78,L"nearPlane");
    fVar13 = 0.0;
    piVar4 = &local_78;
    iVar5 = FUN_00427130(&param_1);
    fVar6 = FUN_0047a720(iVar5,piVar4,fVar13);
    FUN_0045ce30(this,(float)fVar6);
    FUN_0040dab0(&local_78);
  }
  FUN_0040cd80(&local_80,L"farPlane");
  piVar4 = &local_80;
  pvVar2 = (void *)FUN_00427130(&param_1);
  uVar3 = FUN_0047a360(pvVar2,piVar4);
  local_79 = (char)uVar3;
  FUN_0040dab0(&local_80);
  if (local_79 != '\0') {
    FUN_0040cd80(&local_84,L"farPlane");
    fVar13 = 0.0;
    piVar4 = &local_84;
    iVar5 = FUN_00427130(&param_1);
    fVar6 = FUN_0047a720(iVar5,piVar4,fVar13);
    FUN_0045ce60(this,(float)fVar6);
    FUN_0040dab0(&local_84);
  }
  FUN_0040cd80(&local_8c,L"fov");
  piVar4 = &local_8c;
  pvVar2 = (void *)FUN_00427130(&param_1);
  uVar3 = FUN_0047a360(pvVar2,piVar4);
  local_85 = (char)uVar3;
  FUN_0040dab0(&local_8c);
  if (local_85 != '\0') {
    FUN_0040cd80(&local_90,L"fov");
    fVar13 = 0.0;
    piVar4 = &local_90;
    iVar5 = FUN_00427130(&param_1);
    fVar6 = FUN_0047a720(iVar5,piVar4,fVar13);
    FUN_0045ce90(this,(float)fVar6);
    FUN_0040dab0(&local_90);
  }
  FUN_0040dab0(&local_8);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_1);
  return;
}



