Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00434d40
ENTRY 00434d40
NAME FUN_00434d40
SIGNATURE undefined4 __cdecl FUN_00434d40(float * param_1, float * param_2, float * param_3, float * param_4)
BODY [[00434d40, 004355a1]]


undefined4 __cdecl FUN_00434d40(float *param_1,float *param_2,float *param_3,float *param_4)

{
  float fVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  undefined4 uVar5;
  int iVar6;
  float10 fVar7;
  float local_68;
  float local_48;
  float local_44;
  float local_40;
  float local_3c;
  float local_38;
  float *local_34;
  float local_30;
  float local_2c;
  float *local_28;
  float local_24;
  float local_20;
  float local_1c;
  float local_18;
  float local_14;
  float local_10;
  float local_c;
  float local_8;
  
  local_28 = param_3;
  local_34 = param_4;
  local_20 = *param_3 - *param_2;
  local_1c = param_3[1] - param_2[1];
  local_18 = param_3[2] - param_2[2];
  fVar1 = *param_4 - *param_3;
  fVar2 = param_4[1] - param_3[1];
  fVar3 = param_4[2] - param_3[2];
  local_14 = *param_2 - *param_4;
  local_10 = param_2[1] - param_4[1];
  local_c = param_2[2] - param_4[2];
  fVar7 = (float10)FUN_00431b70();
  local_8 = (float)fVar7;
  fVar7 = (float10)FUN_00431b70();
  local_38 = (float)fVar7;
  fVar7 = (float10)FUN_00431b70();
  fVar4 = local_18 * param_2[1] - local_1c * param_2[2];
  local_24 = local_18 * local_34[1] - local_1c * local_34[2];
  local_68 = fVar4;
  if (fVar4 < local_24) {
    local_68 = local_24;
    local_24 = fVar4;
  }
  fVar4 = local_38 * param_1[2] + (float)fVar7 * param_1[1];
  if ((fVar4 < local_24) || (local_68 < -fVar4)) {
    uVar5 = 0;
  }
  else {
    local_2c = local_20 * param_2[2] + -local_18 * *param_2;
    local_24 = local_20 * local_34[2] + -local_18 * *local_34;
    local_68 = local_2c;
    if (local_2c < local_24) {
      local_68 = local_24;
      local_24 = local_2c;
    }
    fVar4 = local_8 * param_1[2] + (float)fVar7 * *param_1;
    if ((fVar4 < local_24) || (local_68 < -fVar4)) {
      uVar5 = 0;
    }
    else {
      local_3c = local_1c * *local_28 - local_20 * local_28[1];
      local_30 = local_1c * *local_34 - local_20 * local_34[1];
      local_68 = local_30;
      local_24 = local_3c;
      if (local_30 < local_3c) {
        local_68 = local_3c;
        local_24 = local_30;
      }
      fVar4 = local_8 * param_1[1] + local_38 * *param_1;
      if ((fVar4 < local_24) || (local_68 < -fVar4)) {
        uVar5 = 0;
      }
      else {
        fVar7 = (float10)FUN_00431b70();
        local_8 = (float)fVar7;
        fVar7 = (float10)FUN_00431b70();
        local_38 = (float)fVar7;
        fVar7 = (float10)FUN_00431b70();
        fVar4 = fVar3 * param_2[1] - fVar2 * param_2[2];
        local_24 = fVar3 * local_34[1] - fVar2 * local_34[2];
        local_68 = fVar4;
        if (fVar4 < local_24) {
          local_68 = local_24;
          local_24 = fVar4;
        }
        fVar4 = local_38 * param_1[2] + (float)fVar7 * param_1[1];
        if ((fVar4 < local_24) || (local_68 < -fVar4)) {
          uVar5 = 0;
        }
        else {
          fVar4 = fVar1 * param_2[2] + -fVar3 * *param_2;
          local_30 = fVar1 * local_34[2] + -fVar3 * *local_34;
          local_68 = fVar4;
          local_24 = local_30;
          if (fVar4 < local_30) {
            local_68 = local_30;
            local_24 = fVar4;
          }
          fVar4 = local_8 * param_1[2] + (float)fVar7 * *param_1;
          if ((fVar4 < local_24) || (local_68 < -fVar4)) {
            uVar5 = 0;
          }
          else {
            local_2c = fVar2 * *param_2 - fVar1 * param_2[1];
            local_3c = fVar2 * *local_28 - fVar1 * local_28[1];
            local_68 = local_2c;
            local_24 = local_3c;
            if (local_2c < local_3c) {
              local_68 = local_3c;
              local_24 = local_2c;
            }
            fVar4 = local_8 * param_1[1] + local_38 * *param_1;
            if ((fVar4 < local_24) || (local_68 < -fVar4)) {
              uVar5 = 0;
            }
            else {
              fVar7 = (float10)FUN_00431b70();
              local_8 = (float)fVar7;
              fVar7 = (float10)FUN_00431b70();
              local_38 = (float)fVar7;
              fVar7 = (float10)FUN_00431b70();
              fVar4 = local_c * param_2[1] - local_10 * param_2[2];
              local_24 = local_c * local_28[1] - local_10 * local_28[2];
              local_68 = fVar4;
              if (fVar4 < local_24) {
                local_68 = local_24;
                local_24 = fVar4;
              }
              fVar4 = local_38 * param_1[2] + (float)fVar7 * param_1[1];
              if ((fVar4 < local_24) || (local_68 < -fVar4)) {
                uVar5 = 0;
              }
              else {
                local_2c = local_14 * param_2[2] + -local_c * *param_2;
                local_24 = local_14 * local_28[2] + -local_c * *local_28;
                local_68 = local_2c;
                if (local_2c < local_24) {
                  local_68 = local_24;
                  local_24 = local_2c;
                }
                fVar4 = local_8 * param_1[2] + (float)fVar7 * *param_1;
                if ((fVar4 < local_24) || (local_68 < -fVar4)) {
                  uVar5 = 0;
                }
                else {
                  local_3c = local_10 * *local_28 - local_14 * local_28[1];
                  local_30 = local_10 * *local_34 - local_14 * local_34[1];
                  local_68 = local_30;
                  local_24 = local_3c;
                  if (local_30 < local_3c) {
                    local_68 = local_3c;
                    local_24 = local_30;
                  }
                  fVar4 = local_8 * param_1[1] + local_38 * *param_1;
                  if ((fVar4 < local_24) || (local_68 < -fVar4)) {
                    uVar5 = 0;
                  }
                  else {
                    local_68 = *param_2;
                    local_24 = local_68;
                    if (*local_28 < local_68) {
                      local_24 = *local_28;
                    }
                    if (local_68 < *local_28) {
                      local_68 = *local_28;
                    }
                    if (*local_34 < local_24) {
                      local_24 = *local_34;
                    }
                    if (local_68 < *local_34) {
                      local_68 = *local_34;
                    }
                    if ((*param_1 < local_24) || (local_68 < -*param_1)) {
                      uVar5 = 0;
                    }
                    else {
                      local_68 = param_2[1];
                      local_24 = local_68;
                      if (local_28[1] < local_68) {
                        local_24 = local_28[1];
                      }
                      if (local_68 < local_28[1]) {
                        local_68 = local_28[1];
                      }
                      if (local_34[1] < local_24) {
                        local_24 = local_34[1];
                      }
                      if (local_68 < local_34[1]) {
                        local_68 = local_34[1];
                      }
                      if ((param_1[1] < local_24) || (local_68 < -param_1[1])) {
                        uVar5 = 0;
                      }
                      else {
                        local_68 = param_2[2];
                        local_24 = local_68;
                        if (local_28[2] < local_68) {
                          local_24 = local_28[2];
                        }
                        if (local_68 < local_28[2]) {
                          local_68 = local_28[2];
                        }
                        if (local_34[2] < local_24) {
                          local_24 = local_34[2];
                        }
                        if (local_68 < local_34[2]) {
                          local_68 = local_34[2];
                        }
                        if ((param_1[2] < local_24) || (local_68 < -param_1[2])) {
                          uVar5 = 0;
                        }
                        else {
                          local_48 = local_1c * fVar3 - local_18 * fVar2;
                          local_44 = local_18 * fVar1 - local_20 * fVar3;
                          local_40 = local_20 * fVar2 - local_1c * fVar1;
                          iVar6 = FUN_00435b10(&local_48,
                                               -(local_40 * param_2[2] +
                                                local_44 * param_2[1] + local_48 * *param_2),
                                               (int)param_1);
                          if (iVar6 == 0) {
                            uVar5 = 0;
                          }
                          else {
                            uVar5 = 1;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return uVar5;
}



================================================================================
REQUESTED 004bc200
ENTRY 004bc200
NAME FUN_004bc200
SIGNATURE undefined __thiscall FUN_004bc200(void * this, float * param_1, float * param_2, void * param_3)
BODY [[004bc200, 004bc523]]


void __thiscall FUN_004bc200(void *this,float *param_1,float *param_2,void *param_3)

{
  float fVar1;
  float fVar2;
  bool bVar3;
  void *pvVar4;
  float *pfVar5;
  int *piVar6;
  int iVar7;
  ulonglong uVar8;
  undefined1 local_a0 [8];
  undefined1 local_98 [8];
  uint local_90;
  undefined1 local_8c [12];
  undefined1 local_80 [12];
  undefined1 local_74 [12];
  int *local_68;
  undefined4 *local_64;
  int local_60 [2];
  int local_58;
  int local_54;
  uint local_50;
  int local_4c;
  float local_48;
  float local_44;
  int local_40;
  float local_3c;
  float local_38;
  float local_34;
  uint local_30;
  int local_2c;
  float local_28;
  float local_24;
  int local_20;
  int local_1c;
  int local_18;
  float local_14;
  float local_10;
  float local_c;
  int local_8;
  
  local_3c = param_1[2];
  pvVar4 = FUN_00418710(local_74,param_1,param_2);
  fVar1 = *(float *)((int)pvVar4 + 8);
  local_34 = fVar1;
  if (fVar1 < local_3c) {
    local_34 = local_3c;
    local_44 = fVar1;
    local_3c = fVar1;
  }
  local_38 = *param_1;
  local_24 = param_1[1];
  pfVar5 = (float *)FUN_00418710(local_80,param_1,param_2);
  local_14 = *pfVar5;
  pvVar4 = FUN_00418710(local_8c,param_1,param_2);
  fVar2 = local_38;
  fVar1 = *(float *)((int)pvVar4 + 4);
  local_10 = fVar1;
  if (fVar1 < local_24) {
    local_38 = local_14;
    local_14 = fVar2;
    local_48 = local_24;
    local_10 = local_24;
    local_24 = fVar1;
  }
  uVar8 = FUN_00478a48();
  local_20 = (int)uVar8 << 2;
  uVar8 = FUN_00478a48();
  local_40 = (int)uVar8 << 2;
  uVar8 = FUN_00478a48();
  local_2c = (int)uVar8 << 2;
  if (local_40 < local_2c) {
    local_c = (local_38 - local_14) / (local_24 - local_10);
    local_28 = (local_14 * local_24 - local_38 * local_10) / (local_24 - local_10);
  }
  for (local_4c = local_40; local_4c <= local_2c; local_4c = local_4c + 1) {
    if (local_4c == local_2c) {
      uVar8 = FUN_00478a48();
      local_8 = (int)uVar8;
    }
    else {
      uVar8 = FUN_00478a48();
      local_8 = (int)uVar8;
    }
    local_8 = local_8 << 2;
    local_1c = FUN_0047e650(local_20,local_8);
    local_18 = FUN_0046fe30(local_20,local_8);
    local_30 = ((int)((local_18 - local_1c) + (local_18 - local_1c >> 0x1f & 3U)) >> 2) + 1;
    for (local_50 = 0; local_50 < local_30; local_50 = local_50 + 1) {
      local_58 = (int)(local_4c + (local_4c >> 0x1f & 3U)) >> 2;
      local_54 = ((int)(local_1c + (local_1c >> 0x1f & 3U)) >> 2) + local_50;
      if ((((-1 < local_58) && (local_58 < 0x7d1)) && (-1 < local_54)) && (local_54 < 0x7d1)) {
        piVar6 = (int *)FUN_004bc770(local_98,local_54,local_58);
        local_90 = FUN_004bc7a0(piVar6);
        FUN_004bc850((void *)((int)this + 0xc),local_60,(int *)&local_90);
        piVar6 = (int *)FUN_004bc810((void *)((int)this + 0xc),local_a0);
        bVar3 = FUN_004d33f0(local_60,piVar6);
        if (bVar3) {
          iVar7 = FUN_00417de0(local_60);
          local_64 = (undefined4 *)(iVar7 + 4);
          local_68 = (int *)FUN_00427130(local_64);
          while( true ) {
            piVar6 = (int *)FUN_004b9c00((int)local_64);
            if (local_68 == piVar6) break;
            iVar7 = FUN_00427130(local_68);
            if (local_3c < *(float *)(iVar7 + 0x38) != (local_3c == *(float *)(iVar7 + 0x38))) {
              iVar7 = FUN_00427130(local_68);
              if (*(float *)(iVar7 + 0x34) <= local_34) {
                FUN_004bc8f0(param_3,local_68);
              }
            }
            local_68 = local_68 + 1;
          }
        }
      }
    }
    local_20 = local_8;
  }
  return;
}



================================================================================
REQUESTED 004bc530
ENTRY 004bc530
NAME FUN_004bc530
SIGNATURE undefined __thiscall FUN_004bc530(void * this, undefined4 * param_1, undefined4 * param_2, undefined4 * param_3, void * param_4)
BODY [[004bc530, 004bc740]]


void __thiscall
FUN_004bc530(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,void *param_4)

{
  bool bVar1;
  undefined4 *puVar2;
  float *pfVar3;
  float *extraout_EAX;
  int *piVar4;
  int iVar5;
  ulonglong uVar6;
  float *pfVar7;
  undefined1 local_b4 [8];
  undefined1 local_ac [8];
  uint local_a4;
  undefined1 local_a0 [24];
  undefined1 local_88 [48];
  undefined1 local_58 [12];
  int *local_4c;
  undefined4 *local_48;
  int local_44 [2];
  int local_3c;
  int local_38;
  float local_34;
  float local_30;
  float local_2c;
  float local_28;
  float local_24;
  float local_20;
  float local_1c;
  float local_18;
  int local_14;
  int local_10;
  int local_c;
  int local_8;
  
  puVar2 = (undefined4 *)FUN_00413650(param_3,local_58);
  FUN_0047ee10(&local_34,puVar2,param_3);
  pfVar7 = &local_34;
  pfVar3 = (float *)FUN_00449b00(local_88,param_2,param_1);
  FUN_0047eab0(local_a0,pfVar3,pfVar7);
  local_34 = *extraout_EAX;
  local_30 = extraout_EAX[1];
  local_2c = extraout_EAX[2];
  local_28 = extraout_EAX[3];
  local_24 = extraout_EAX[4];
  local_20 = extraout_EAX[5];
  uVar6 = FUN_00478a48();
  local_10 = (int)uVar6;
  uVar6 = FUN_00478a48();
  local_8 = (int)uVar6;
  uVar6 = FUN_00478a48();
  local_c = (int)uVar6;
  uVar6 = FUN_00478a48();
  local_14 = (int)uVar6;
  local_1c = local_2c;
  local_18 = local_20;
  for (local_38 = local_8; local_38 < local_14; local_38 = local_38 + 1) {
    for (local_3c = local_10; local_3c < local_c; local_3c = local_3c + 1) {
      if ((((-1 < local_38) && (local_38 < 0x7d1)) && (-1 < local_3c)) && (local_3c < 0x7d1)) {
        piVar4 = (int *)FUN_004bc770(local_ac,local_3c,local_38);
        local_a4 = FUN_004bc7a0(piVar4);
        FUN_004bc850((void *)((int)this + 0xc),local_44,(int *)&local_a4);
        piVar4 = (int *)FUN_004bc810((void *)((int)this + 0xc),local_b4);
        bVar1 = FUN_004d33f0(local_44,piVar4);
        if (bVar1) {
          iVar5 = FUN_00417de0(local_44);
          local_48 = (undefined4 *)(iVar5 + 4);
          local_4c = (int *)FUN_00427130(local_48);
          while( true ) {
            piVar4 = (int *)FUN_004b9c00((int)local_48);
            if (local_4c == piVar4) break;
            iVar5 = FUN_00427130(local_4c);
            if (local_1c < *(float *)(iVar5 + 0x38) != (local_1c == *(float *)(iVar5 + 0x38))) {
              iVar5 = FUN_00427130(local_4c);
              if (*(float *)(iVar5 + 0x34) <= local_18) {
                FUN_004bc8f0(param_4,local_4c);
              }
            }
            local_4c = local_4c + 1;
          }
        }
      }
    }
  }
  return;
}



================================================================================
REQUESTED 00432100
ENTRY 00432100
NAME FUN_00432100
SIGNATURE void * __cdecl FUN_00432100(void * param_1, undefined4 * param_2)
BODY [[00432100, 0043214d]]


void * __cdecl FUN_00432100(void *param_1,undefined4 *param_2)

{
  FUN_0042b510(param_1,*param_2,param_2[3],param_2[6],param_2[1],param_2[4],param_2[7],param_2[2],
               param_2[5],param_2[8]);
  return param_1;
}



================================================================================
REQUESTED 00433950
ENTRY 00433950
NAME FUN_00433950
SIGNATURE undefined __fastcall FUN_00433950(undefined4 * param_1)
BODY [[00433950, 00433974]]


void __fastcall FUN_00433950(undefined4 *param_1)

{
  shared_ptr<class___ExceptionPtr> *psVar1;
  shared_ptr<class___ExceptionPtr> *psVar2;
  
  psVar1 = (shared_ptr<class___ExceptionPtr> *)FUN_004b9c00((int)param_1);
  psVar2 = (shared_ptr<class___ExceptionPtr> *)FUN_00427130(param_1);
  FUN_00433980(param_1,psVar2,psVar1);
  return;
}



================================================================================
REQUESTED 004b9c00
ENTRY 004b9c00
NAME FUN_004b9c00
SIGNATURE undefined4 __fastcall FUN_004b9c00(int param_1)
BODY [[004b9c00, 004b9c10]]


undefined4 __fastcall FUN_004b9c00(int param_1)

{
  return *(undefined4 *)(param_1 + 4);
}



================================================================================
REQUESTED 0042ef90
ENTRY 0042ef90
NAME FUN_0042ef90
SIGNATURE undefined1 __fastcall FUN_0042ef90(int param_1)
BODY [[0042ef90, 0042f455]]


undefined1 __fastcall FUN_0042ef90(int param_1)

{
  undefined1 uVar1;
  char cVar2;
  float *pfVar3;
  void *this;
  undefined4 *puVar4;
  float10 fVar5;
  float10 fVar6;
  CSize *pCVar7;
  float fVar8;
  float fVar9;
  undefined1 local_bc [12];
  float local_b0;
  float local_ac [2];
  undefined1 local_a4 [16];
  undefined1 local_94 [12];
  undefined1 local_88 [12];
  undefined1 local_7c [12];
  undefined1 local_70 [12];
  undefined1 local_64 [12];
  undefined1 local_58 [12];
  undefined1 local_4c [12];
  uint local_40;
  uint local_3c;
  float local_38;
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  CSize local_28 [12];
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  undefined4 local_c;
  uint local_8;
  
  *(undefined1 *)(param_1 + 0x301) = *(undefined1 *)(param_1 + 0x300);
  *(undefined1 *)(param_1 + 0x300) = 0;
  for (local_8 = 0; local_8 < 4; local_8 = local_8 + 1) {
    FUN_00426c20(local_28);
    CSize::CSize((CSize *)&local_34);
    local_34 = *(undefined4 *)(param_1 + 0x2c);
    local_30 = *(undefined4 *)(param_1 + 0x30);
    local_2c = *(undefined4 *)(param_1 + 0x34);
    fVar9 = 0.8;
    fVar8 = *(float *)(param_1 + 0x224 + local_8 * 4);
    pfVar3 = (float *)FUN_00418790(local_4c,(float *)(param_1 + 0x1c0),*(float *)(param_1 + 300));
    pfVar3 = (float *)FUN_00418790(local_58,pfVar3,fVar8);
    pfVar3 = (float *)FUN_00418790(local_64,pfVar3,fVar9);
    FUN_00418680(&local_34,pfVar3);
    fVar9 = 0.8;
    fVar8 = *(float *)(param_1 + 0x234 + local_8 * 4);
    pfVar3 = (float *)FUN_00418790(local_70,(float *)(param_1 + 0x1d8),*(float *)(param_1 + 0x130));
    pfVar3 = (float *)FUN_00418790(local_7c,pfVar3,fVar8);
    pfVar3 = (float *)FUN_00418790(local_88,pfVar3,fVar9);
    FUN_00418680(&local_34,pfVar3);
    pfVar3 = (float *)FUN_00418790(local_94,(float *)(param_1 + 0x1cc),*(float *)(param_1 + 0x2a8));
    FUN_00418680(&local_34,pfVar3);
    fVar8 = -2.0;
    pfVar3 = (float *)FUN_00418790(local_a4,(float *)(param_1 + 0x1cc),*(float *)(param_1 + 0x2a8));
    FUN_00418790(&stack0xffffff1c,pfVar3,fVar8);
    FUN_004135d0(&stack0xffffff10,&local_34);
    pCVar7 = local_28;
    this = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
    cVar2 = FUN_00432fc0(this,(undefined4 *)pCVar7);
    *(char *)(param_1 + local_8 + 0x244) = cVar2;
    if (*(char *)(param_1 + local_8 + 0x244) == '\0') {
      *(undefined4 *)(param_1 + 0x298 + local_8 * 4) = 0;
      *(undefined4 *)(param_1 + 0x278 + local_8 * 4) = 0;
      *(undefined4 *)(param_1 + 0x288 + local_8 * 4) = 0;
    }
    else {
      *(undefined1 *)(param_1 + 0x300) = 1;
      *(undefined4 *)(param_1 + 0xd8) = local_c;
      puVar4 = (undefined4 *)(param_1 + 0x248 + local_8 * 0xc);
      *puVar4 = local_1c;
      puVar4[1] = local_18;
      puVar4[2] = local_14;
      fVar5 = FUN_00428460((float *)local_28,(float *)(param_1 + 0x1cc));
      fVar6 = FUN_00428460((float *)(param_1 + 0x2c),(float *)(param_1 + 0x1cc));
      local_38 = (float)((float10)(float)fVar5 - (fVar6 - (float10)*(float *)(param_1 + 0x2a8)));
      *(undefined4 *)(param_1 + 0x298 + local_8 * 4) =
           *(undefined4 *)(param_1 + 0x278 + local_8 * 4);
      local_ac[0] = *(float *)(param_1 + 0x2a8) + *(float *)(param_1 + 0x2a8);
      local_b0 = 0.0;
      pfVar3 = FUN_00431ea0(&local_38,local_ac);
      pfVar3 = FUN_0042afa0(&local_b0,pfVar3);
      *(float *)(param_1 + 0x278 + local_8 * 4) = *pfVar3;
      *(float *)(param_1 + 0x288 + local_8 * 4) =
           *(float *)(param_1 + 0x278 + local_8 * 4) - *(float *)(param_1 + 0x298 + local_8 * 4);
    }
  }
  *(undefined1 *)(param_1 + 0x1a4) = *(undefined1 *)(param_1 + 0x300);
  puVar4 = FUN_004135a0(local_bc,0,0,0);
  *(undefined4 *)(param_1 + 0x1a8) = *puVar4;
  *(undefined4 *)(param_1 + 0x1ac) = puVar4[1];
  *(undefined4 *)(param_1 + 0x1b0) = puVar4[2];
  if (*(char *)(param_1 + 0x300) == '\0') {
    if (*(char *)(param_1 + 0x301) != '\0') {
      *(undefined1 *)(param_1 + 0x301) = 0;
    }
  }
  else {
    local_3c = 0;
    for (local_40 = 0; local_40 < 4; local_40 = local_40 + 1) {
      if (*(char *)(param_1 + local_40 + 0x244) != '\0') {
        local_3c = local_3c + 1;
        FUN_00418680((void *)(param_1 + 0x1a8),(float *)(param_1 + 0x248 + local_40 * 0xc));
      }
    }
    FUN_004320c0((void *)(param_1 + 0x1a8),(float)local_3c);
    if (*(char *)(param_1 + 0x301) == '\0') {
      *(undefined1 *)(param_1 + 0x301) = 1;
    }
    else {
      *(undefined1 *)(param_1 + 0x301) = 0;
    }
  }
  uVar1 = *(undefined1 *)(param_1 + 0x300);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return uVar1;
}



================================================================================
REQUESTED 00430830
ENTRY 00430830
NAME FUN_00430830
SIGNATURE undefined1 __thiscall FUN_00430830(void * this, void * param_1)
BODY [[00430830, 00430ec6]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 __thiscall FUN_00430830(void *this,void *param_1)

{
  uint uVar1;
  float *pfVar2;
  float *pfVar3;
  undefined4 *puVar4;
  float10 fVar5;
  float10 fVar6;
  undefined1 auStack_1e0 [4];
  undefined4 uStack_1dc;
  undefined1 auStack_1d4 [28];
  undefined4 uStack_1b8;
  float fVar7;
  float local_19c;
  float local_194;
  float local_17c;
  float local_178;
  float local_174;
  float local_170;
  float local_16c;
  float local_168;
  undefined1 local_164 [12];
  undefined1 local_158 [12];
  undefined1 local_14c [12];
  undefined1 local_140 [12];
  undefined1 local_134 [12];
  float local_128;
  float local_124;
  undefined1 local_120 [12];
  undefined1 local_114 [12];
  undefined1 local_108 [12];
  undefined1 local_fc [12];
  undefined1 local_f0 [12];
  undefined1 local_e4 [12];
  undefined1 local_d8 [24];
  float local_c0 [2];
  float local_b8;
  float local_b4 [2];
  float local_ac;
  float local_a8;
  float local_a4;
  float local_a0;
  float local_9c;
  float local_98 [3];
  float local_8c;
  float local_88;
  float local_84;
  float local_80;
  float local_7c;
  float local_78;
  float local_74;
  float local_70;
  float local_6c;
  char local_65;
  CSize local_64 [12];
  float local_58 [2];
  float local_50;
  undefined4 local_44 [3];
  undefined4 local_38 [3];
  undefined1 local_29;
  undefined4 local_28 [9];
  
  local_29 = 1;
  FUN_00426c20(local_64);
  FUN_004135a0(local_44,*(undefined4 *)((int)this + 300),*(undefined4 *)((int)this + 0x130),
               0x3f333333);
  FUN_004137a0(local_28,(undefined4 *)((int)this + 0x38));
  FUN_00418710(local_38,(float *)((int)this + 0x2c),(float *)((int)this + 0x1cc));
  uStack_1b8 = 0x4308b7;
  FUN_004135d0(&stack0xfffffe50,local_44);
  uStack_1dc = 0x4308c5;
  FUN_004137a0(auStack_1d4,local_28);
  FUN_004135d0(auStack_1e0,local_38);
  uVar1 = FUN_00433310(param_1,(undefined4 *)local_64);
  local_65 = (char)uVar1;
  while (local_65 != '\0') {
    fVar5 = FUN_00428460(local_58,(float *)((int)this + 0x5c));
    if (fVar5 < (float10)DAT_00571808) {
      *(undefined4 *)((int)this + 0x2c0) = 0;
      local_29 = 0;
      CSize::CSize((CSize *)&local_74);
      CSize::CSize((CSize *)&local_80);
      fVar5 = FUN_00428460((float *)((int)this + 0x5c),local_58);
      pfVar2 = (float *)FUN_00418790(local_d8,local_58,(float)fVar5);
      local_74 = *pfVar2;
      local_70 = pfVar2[1];
      local_6c = pfVar2[2];
      pfVar2 = (float *)FUN_00418750(local_e4,(float *)((int)this + 0x5c),&local_74);
      local_80 = *pfVar2;
      local_7c = pfVar2[1];
      local_78 = pfVar2[2];
      if (local_50 <= _DAT_00571d48) {
        *(undefined1 *)((int)this + 0x2dc) = 0;
        *(undefined1 *)((int)this + 0x2f8) = 1;
        fVar5 = (float10)FUN_004136f0(&local_74);
        *(float *)((int)this + 0x2fc) = (float)fVar5;
        FUN_00428500(local_98,&local_80);
        fVar5 = (float10)FUN_004136f0(&local_80);
        local_a8 = (float)fVar5;
        CSize::CSize((CSize *)&local_a4);
        local_124 = local_a8 * _DAT_00571d40;
        fVar5 = (float10)FUN_004136f0(&local_74);
        local_128 = (float)(fVar5 * (float10)_DAT_00571d3c);
        pfVar2 = FUN_00431ea0(&local_128,&local_124);
        pfVar2 = (float *)FUN_00418790(local_134,local_98,*pfVar2);
        pfVar3 = (float *)FUN_00418790(local_140,&local_74,-1.5);
        pfVar2 = (float *)FUN_00418750(local_14c,pfVar3,pfVar2);
        local_a4 = *pfVar2;
        local_a0 = pfVar2[1];
        fVar7 = pfVar2[2];
        local_9c = fVar7;
        pfVar2 = (float *)FUN_004135a0(local_158,0,0,0x3f800000);
        pfVar2 = (float *)FUN_00418790(local_164,pfVar2,fVar7);
        FUN_00432070(&local_a4,pfVar2);
        FUN_00418680((void *)((int)this + 0x5c),&local_a4);
        fVar5 = FUN_00428460(local_58,(float *)((int)this + 0x1d8));
        local_88 = (float)fVar5;
        fVar5 = FUN_00428460(local_58,(float *)((int)this + 0x1c0));
        local_8c = (float)fVar5;
        fVar5 = (float10)FUN_00431b70();
        fVar6 = (float10)FUN_00431b70();
        if ((float10)(float)fVar5 <= fVar6) {
          FUN_004135d0(local_c0,&DAT_005b16cc);
          if (local_8c <= DAT_00571808) {
            local_19c = 1.0;
          }
          else {
            local_19c = -1.0;
          }
          FUN_00428460(local_58,(float *)((int)this + 0x5c));
          fVar5 = (float10)FUN_00431b70();
          local_174 = (float)fVar5;
          local_178 = 30.0;
          local_17c = 1.0;
          local_19c = local_88 * local_19c;
          pfVar2 = FUN_00431ea0(&local_178,&local_174);
          pfVar2 = FUN_0042afa0(&local_17c,pfVar2);
          local_b8 = local_19c * *pfVar2;
          fVar5 = FUN_00428460(local_c0,(float *)((int)this + 0x68));
          if (fVar5 < (float10)_DAT_00571490 != (fVar5 == (float10)_DAT_00571490)) {
            FUN_00418680((void *)((int)this + 0x68),local_c0);
          }
        }
        else {
          FUN_004135d0(local_b4,&DAT_005b16cc);
          if (local_88 <= DAT_00571808) {
            local_194 = -1.0;
          }
          else {
            local_194 = 1.0;
          }
          FUN_00428460(local_58,(float *)((int)this + 0x5c));
          fVar5 = (float10)FUN_00431b70();
          local_168 = (float)fVar5;
          local_16c = 30.0;
          local_170 = 1.0;
          local_194 = local_8c * local_194;
          pfVar2 = FUN_00431ea0(&local_16c,&local_168);
          pfVar2 = FUN_0042afa0(&local_170,pfVar2);
          local_ac = local_194 * *pfVar2;
          fVar5 = FUN_00428460(local_b4,(float *)((int)this + 0x68));
          if (fVar5 < (float10)_DAT_00571490 != (fVar5 == (float10)_DAT_00571490)) {
            FUN_00418680((void *)((int)this + 0x68),local_b4);
          }
        }
      }
      else {
        pfVar2 = &local_80;
        pfVar3 = (float *)FUN_00418790(local_f0,&local_74,-0.2);
        puVar4 = (undefined4 *)FUN_00418710(local_fc,pfVar3,pfVar2);
        *(undefined4 *)((int)this + 0x5c) = *puVar4;
        *(undefined4 *)((int)this + 0x60) = puVar4[1];
        *(undefined4 *)((int)this + 100) = puVar4[2];
        fVar5 = (float10)FUN_004136f0(&local_74);
        *(float *)((int)this + 0x304) = (float)fVar5;
        pfVar3 = (float *)((int)this + 0x1c0);
        pfVar2 = (float *)FUN_00428490(local_108,local_58,(float *)((int)this + 0x1cc));
        fVar5 = FUN_00428460(pfVar2,pfVar3);
        local_84 = (float)fVar5;
        *(float *)((int)this + 0x68) = *(float *)((int)this + 0x68) - local_84 * _DAT_00571d44;
        pfVar2 = (float *)FUN_00413650((void *)((int)this + 0x1d8),local_114);
        pfVar3 = (float *)FUN_00428490(local_120,local_58,(float *)((int)this + 0x1cc));
        fVar5 = FUN_00428460(pfVar3,pfVar2);
        local_84 = (float)fVar5;
        *(float *)((int)this + 0x6c) = *(float *)((int)this + 0x6c) - local_84 * _DAT_00571d44;
      }
    }
    uStack_1b8 = 0x430e8e;
    FUN_004135d0(&stack0xfffffe50,local_44);
    uStack_1dc = 0x430e9c;
    FUN_004137a0(auStack_1d4,local_28);
    FUN_004135d0(auStack_1e0,local_38);
    uVar1 = FUN_00433310(param_1,(undefined4 *)local_64);
    local_65 = (char)uVar1;
  }
  return local_29;
}



