Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00428460
ENTRY 00428460
NAME FUN_00428460
SIGNATURE float10 __cdecl FUN_00428460(float * param_1, float * param_2)
BODY [[00428460, 0042848a]]


float10 __cdecl FUN_00428460(float *param_1,float *param_2)

{
  return (float10)param_1[2] * (float10)param_2[2] +
         (float10)param_1[1] * (float10)param_2[1] + (float10)*param_1 * (float10)*param_2;
}



================================================================================
REQUESTED 00428490
ENTRY 00428490
NAME FUN_00428490
SIGNATURE void * __cdecl FUN_00428490(void * param_1, float * param_2, float * param_3)
BODY [[00428490, 004284f5]]


void * __cdecl FUN_00428490(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,param_2[1] * param_3[2] - param_2[2] * param_3[1],
               param_2[2] * *param_3 - *param_2 * param_3[2],
               *param_2 * param_3[1] - param_2[1] * *param_3);
  return param_1;
}



================================================================================
REQUESTED 00428500
ENTRY 00428500
NAME FUN_00428500
SIGNATURE void * __cdecl FUN_00428500(void * param_1, float * param_2)
BODY [[00428500, 00428529]]


void * __cdecl FUN_00428500(void *param_1,float *param_2)

{
  float10 fVar1;
  
  fVar1 = (float10)FUN_004136f0(param_2);
  FUN_00428530(param_1,param_2,(float)fVar1);
  return param_1;
}



================================================================================
REQUESTED 00431ea0
ENTRY 00431ea0
NAME FUN_00431ea0
SIGNATURE float * __cdecl FUN_00431ea0(float * param_1, float * param_2)
BODY [[00431ea0, 00431ed1]]


float * __cdecl FUN_00431ea0(float *param_1,float *param_2)

{
  undefined4 local_c;
  
  if (*param_1 <= *param_2) {
    local_c = param_1;
  }
  else {
    local_c = param_2;
  }
  return local_c;
}



================================================================================
REQUESTED 00432070
ENTRY 00432070
NAME FUN_00432070
SIGNATURE float * __thiscall FUN_00432070(void * this, float * param_1)
BODY [[00432070, 004320b2]]


float * __thiscall FUN_00432070(void *this,float *param_1)

{
                    /* WARNING: Load size is inaccurate */
  *(float *)this = *this - *param_1;
  *(float *)((int)this + 4) = *(float *)((int)this + 4) - param_1[1];
  *(float *)((int)this + 8) = *(float *)((int)this + 8) - param_1[2];
  return (float *)this;
}



================================================================================
REQUESTED 00418680
ENTRY 00418680
NAME FUN_00418680
SIGNATURE float * __thiscall FUN_00418680(void * this, float * param_1)
BODY [[00418680, 004186c2]]


float * __thiscall FUN_00418680(void *this,float *param_1)

{
                    /* WARNING: Load size is inaccurate */
  *(float *)this = *this + *param_1;
  *(float *)((int)this + 4) = *(float *)((int)this + 4) + param_1[1];
  *(float *)((int)this + 8) = *(float *)((int)this + 8) + param_1[2];
  return (float *)this;
}



================================================================================
REQUESTED 00413730
ENTRY 00413730
NAME FUN_00413730
SIGNATURE undefined __fastcall FUN_00413730(undefined4 param_1)
BODY [[00413730, 00413742]]


void __fastcall FUN_00413730(undefined4 param_1)

{
  _CIsqrt(param_1);
  return;
}



================================================================================
REQUESTED 0042ef90
ENTRY 0042ef90
NAME FUN_0042ef90
SIGNATURE undefined1 __fastcall FUN_0042ef90(int param_1)
BODY [[0042ef90, 0042f455]]


undefined1 __fastcall FUN_0042ef90(int param_1)

{
  undefined1 uVar1;
  char cVar2;
  float *pfVar3;
  void *this;
  undefined4 *puVar4;
  float10 fVar5;
  float10 fVar6;
  CSize *pCVar7;
  float fVar8;
  float fVar9;
  undefined1 local_bc [12];
  float local_b0;
  float local_ac [2];
  undefined1 local_a4 [16];
  undefined1 local_94 [12];
  undefined1 local_88 [12];
  undefined1 local_7c [12];
  undefined1 local_70 [12];
  undefined1 local_64 [12];
  undefined1 local_58 [12];
  undefined1 local_4c [12];
  uint local_40;
  uint local_3c;
  float local_38;
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  CSize local_28 [12];
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  undefined4 local_c;
  uint local_8;
  
  *(undefined1 *)(param_1 + 0x301) = *(undefined1 *)(param_1 + 0x300);
  *(undefined1 *)(param_1 + 0x300) = 0;
  for (local_8 = 0; local_8 < 4; local_8 = local_8 + 1) {
    FUN_00426c20(local_28);
    CSize::CSize((CSize *)&local_34);
    local_34 = *(undefined4 *)(param_1 + 0x2c);
    local_30 = *(undefined4 *)(param_1 + 0x30);
    local_2c = *(undefined4 *)(param_1 + 0x34);
    fVar9 = 0.8;
    fVar8 = *(float *)(param_1 + 0x224 + local_8 * 4);
    pfVar3 = (float *)FUN_00418790(local_4c,(float *)(param_1 + 0x1c0),*(float *)(param_1 + 300));
    pfVar3 = (float *)FUN_00418790(local_58,pfVar3,fVar8);
    pfVar3 = (float *)FUN_00418790(local_64,pfVar3,fVar9);
    FUN_00418680(&local_34,pfVar3);
    fVar9 = 0.8;
    fVar8 = *(float *)(param_1 + 0x234 + local_8 * 4);
    pfVar3 = (float *)FUN_00418790(local_70,(float *)(param_1 + 0x1d8),*(float *)(param_1 + 0x130));
    pfVar3 = (float *)FUN_00418790(local_7c,pfVar3,fVar8);
    pfVar3 = (float *)FUN_00418790(local_88,pfVar3,fVar9);
    FUN_00418680(&local_34,pfVar3);
    pfVar3 = (float *)FUN_00418790(local_94,(float *)(param_1 + 0x1cc),*(float *)(param_1 + 0x2a8));
    FUN_00418680(&local_34,pfVar3);
    fVar8 = -2.0;
    pfVar3 = (float *)FUN_00418790(local_a4,(float *)(param_1 + 0x1cc),*(float *)(param_1 + 0x2a8));
    FUN_00418790(&stack0xffffff1c,pfVar3,fVar8);
    FUN_004135d0(&stack0xffffff10,&local_34);
    pCVar7 = local_28;
    this = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
    cVar2 = FUN_00432fc0(this,(undefined4 *)pCVar7);
    *(char *)(param_1 + local_8 + 0x244) = cVar2;
    if (*(char *)(param_1 + local_8 + 0x244) == '\0') {
      *(undefined4 *)(param_1 + 0x298 + local_8 * 4) = 0;
      *(undefined4 *)(param_1 + 0x278 + local_8 * 4) = 0;
      *(undefined4 *)(param_1 + 0x288 + local_8 * 4) = 0;
    }
    else {
      *(undefined1 *)(param_1 + 0x300) = 1;
      *(undefined4 *)(param_1 + 0xd8) = local_c;
      puVar4 = (undefined4 *)(param_1 + 0x248 + local_8 * 0xc);
      *puVar4 = local_1c;
      puVar4[1] = local_18;
      puVar4[2] = local_14;
      fVar5 = FUN_00428460((float *)local_28,(float *)(param_1 + 0x1cc));
      fVar6 = FUN_00428460((float *)(param_1 + 0x2c),(float *)(param_1 + 0x1cc));
      local_38 = (float)((float10)(float)fVar5 - (fVar6 - (float10)*(float *)(param_1 + 0x2a8)));
      *(undefined4 *)(param_1 + 0x298 + local_8 * 4) =
           *(undefined4 *)(param_1 + 0x278 + local_8 * 4);
      local_ac[0] = *(float *)(param_1 + 0x2a8) + *(float *)(param_1 + 0x2a8);
      local_b0 = 0.0;
      pfVar3 = FUN_00431ea0(&local_38,local_ac);
      pfVar3 = FUN_0042afa0(&local_b0,pfVar3);
      *(float *)(param_1 + 0x278 + local_8 * 4) = *pfVar3;
      *(float *)(param_1 + 0x288 + local_8 * 4) =
           *(float *)(param_1 + 0x278 + local_8 * 4) - *(float *)(param_1 + 0x298 + local_8 * 4);
    }
  }
  *(undefined1 *)(param_1 + 0x1a4) = *(undefined1 *)(param_1 + 0x300);
  puVar4 = FUN_004135a0(local_bc,0,0,0);
  *(undefined4 *)(param_1 + 0x1a8) = *puVar4;
  *(undefined4 *)(param_1 + 0x1ac) = puVar4[1];
  *(undefined4 *)(param_1 + 0x1b0) = puVar4[2];
  if (*(char *)(param_1 + 0x300) == '\0') {
    if (*(char *)(param_1 + 0x301) != '\0') {
      *(undefined1 *)(param_1 + 0x301) = 0;
    }
  }
  else {
    local_3c = 0;
    for (local_40 = 0; local_40 < 4; local_40 = local_40 + 1) {
      if (*(char *)(param_1 + local_40 + 0x244) != '\0') {
        local_3c = local_3c + 1;
        FUN_00418680((void *)(param_1 + 0x1a8),(float *)(param_1 + 0x248 + local_40 * 0xc));
      }
    }
    FUN_004320c0((void *)(param_1 + 0x1a8),(float)local_3c);
    if (*(char *)(param_1 + 0x301) == '\0') {
      *(undefined1 *)(param_1 + 0x301) = 1;
    }
    else {
      *(undefined1 *)(param_1 + 0x301) = 0;
    }
  }
  uVar1 = *(undefined1 *)(param_1 + 0x300);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return uVar1;
}



