Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00475f00
ENTRY 00475f00
NAME FUN_00475f00
SIGNATURE undefined1 __fastcall FUN_00475f00(void * param_1)
BODY [[00475f00, 00476aa8]]


undefined1 __fastcall FUN_00475f00(void *param_1)

{
  char cVar1;
  shared_ptr<class___ExceptionPtr> sVar2;
  BOOL BVar3;
  DWORD _Seed;
  byte *pbVar4;
  undefined *puVar5;
  shared_ptr<class___ExceptionPtr> *psVar6;
  uint uVar7;
  undefined4 *puVar8;
  int iVar9;
  undefined4 uVar10;
  undefined4 uVar11;
  int *piVar12;
  int *piVar13;
  DWORD *pDVar14;
  undefined4 uVar15;
  undefined4 extraout_ECX;
  undefined4 extraout_ECX_00;
  undefined4 extraout_ECX_01;
  char cVar16;
  float10 fVar17;
  float fVar18;
  float fVar19;
  undefined4 uStack_10c;
  undefined1 *puVar20;
  CDialogTemplate *pCVar21;
  int iVar22;
  float fVar23;
  undefined1 uVar24;
  float fVar25;
  int local_c0 [2];
  int local_b8;
  int local_b4;
  int local_b0;
  int local_ac;
  int local_a8;
  int local_a4;
  int local_a0;
  int local_9c;
  int local_98;
  int local_94;
  int local_90;
  int local_8c;
  int local_88;
  int local_84;
  int local_80;
  int local_7c;
  int local_78;
  int local_74;
  undefined1 local_6f;
  undefined1 local_6e;
  undefined1 local_6d;
  undefined1 local_6c;
  undefined1 local_6b;
  undefined1 local_6a;
  undefined1 local_69;
  int local_4c [4];
  int local_3c [6];
  int local_24 [2];
  CDialogTemplate local_1c [4];
  CDialogTemplate local_18 [4];
  CDialogTemplate local_14 [4];
  CDialogTemplate local_10 [4];
  CDialogTemplate local_c [4];
  CDialogTemplate local_8 [4];
  
  FUN_00483040((int)param_1);
  BVar3 = IsDebuggerPresent();
  if (BVar3 == 0) {
    FUN_0040baa0(FUN_00477520);
    FUN_0040baf0();
  }
  timeBeginPeriod(1);
  _Seed = timeGetTime();
  srand(_Seed);
  FUN_004096f0();
  FUN_00479090();
  pbVar4 = FUN_004777d0();
  FUN_00483180(pbVar4);
  puVar5 = FUN_0040c0f0();
  FUN_004a4250((int)puVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_00419810();
  FUN_004a0d00(psVar6);
  FUN_0040c100();
  cVar1 = FUN_004a2660();
  if (cVar1 == '\0') {
    local_69 = 0;
  }
  else {
    puVar5 = FUN_004777e0();
    uVar7 = FUN_004ac3e0(puVar5);
    if ((uVar7 & 0xff) == 0) {
      local_69 = 0;
    }
    else {
      puVar5 = FUN_0044c040();
      uVar7 = FUN_0040fc50((int)puVar5);
      if ((uVar7 & 0xff) == 0) {
        local_69 = 0;
      }
      else {
        cVar1 = '\0';
        puVar5 = FUN_0044c040();
        sVar2 = (shared_ptr<class___ExceptionPtr>)FUN_00477650((int)puVar5);
        psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_0040ec80();
        cVar1 = FUN_0041eb20(psVar6,sVar2,cVar1);
        if (cVar1 == '\0') {
          local_69 = 0;
        }
        else {
          puVar5 = FUN_00417e10();
          uVar7 = FUN_0040f810((int)puVar5);
          if ((uVar7 & 0xff) == 0) {
            local_69 = 0;
          }
          else {
            puVar8 = (undefined4 *)FUN_00454060();
            uVar7 = FUN_00421db0(puVar8);
            if ((uVar7 & 0xff) == 0) {
              local_69 = 0;
            }
            else {
              puVar5 = FUN_00454070();
              uVar7 = FUN_0040e210(puVar5);
              if ((uVar7 & 0xff) == 0) {
                local_69 = 0;
              }
              else {
                puVar20 = &stack0xffffff14;
                puVar5 = FUN_0040ec80();
                FUN_0040fb40(puVar5,puVar20);
                puVar5 = FUN_0045cce0();
                uVar7 = FUN_0040c680(puVar5);
                if ((uVar7 & 0xff) == 0) {
                  local_69 = 0;
                }
                else {
                  puVar5 = FUN_0044c040();
                  cVar1 = FUN_004d8030(puVar5);
                  if (cVar1 == '\0') {
                    puVar5 = FUN_0042d0c0();
                    uVar7 = FUN_0041cd60((int)puVar5);
                    if ((uVar7 & 0xff) == 0) {
                      return 0;
                    }
                  }
                  uVar7 = FUN_004771c0((int)param_1);
                  if ((uVar7 & 0xff) == 0) {
                    local_69 = 0;
                  }
                  else {
                    puVar5 = FUN_0044c040();
                    uVar7 = FUN_00477630((int)puVar5);
                    puVar5 = FUN_0044c040();
                    iVar9 = FUN_0049e8e0((int)puVar5);
                    cVar16 = iVar9 == 0x10;
                    puVar5 = FUN_0044c040();
                    cVar1 = FUN_00477670((int)puVar5);
                    cVar1 = '\x01' - (cVar1 != '\0');
                    puVar5 = FUN_0044c040();
                    uVar10 = FUN_0049e8c0((int)puVar5);
                    puVar5 = FUN_0044c040();
                    uVar11 = FUN_0044bcf0((int)puVar5);
                    uVar15 = *(undefined4 *)((int)param_1 + 0x58);
                    puVar5 = FUN_0040c0f0();
                    uVar7 = FUN_004a4290(puVar5,uVar15,uVar11,uVar10,cVar1,cVar16,uVar7);
                    if ((uVar7 & 0xff) == 0) {
                      local_69 = 0;
                    }
                    else {
                      FUN_0040f6e0(local_24,"toon");
                      piVar12 = local_24;
                      puVar20 = &stack0xffffff10;
                      piVar13 = piVar12;
                      puVar5 = FUN_0040ec80();
                      FUN_0040fb40(puVar5,puVar20);
                      pCVar21 = local_1c;
                      puVar5 = FUN_0040c100();
                      FUN_004a2690(puVar5,pCVar21,piVar12,piVar13);
                      FUN_0040dab0(local_24);
                      puVar20 = &stack0xffffff14;
                      iVar22 = 1;
                      uVar10 = 0;
                      iVar9 = 1;
                      uVar15 = extraout_ECX;
                      FUN_004815c0(&stack0xffffff04,(int *)local_1c);
                      puVar5 = FUN_0040c0f0();
                      FUN_004a4cc0(puVar5,puVar20,uVar15,iVar9,uVar10,iVar22);
                      puVar5 = FUN_004777e0();
                      FUN_00477800((int)puVar5);
                      fVar25 = 4.0;
                      fVar23 = 1.4;
                      iVar9 = 0;
                      FUN_004777e0();
                      FUN_004ac5a0(iVar9,fVar23,fVar25);
                      fVar25 = 20.0;
                      fVar23 = 15.0;
                      iVar9 = 1;
                      FUN_004777e0();
                      FUN_004ac5a0(iVar9,fVar23,fVar25);
                      CDialogTemplate::~CDialogTemplate(local_1c);
                      FUN_0040c560(*(undefined4 *)((int)param_1 + 0x58));
                      cVar16 = '\x01';
                      cVar1 = '\x01';
                      uVar15 = *(undefined4 *)((int)param_1 + 0x58);
                      puVar5 = FUN_004777f0();
                      FUN_004de8b0(puVar5,uVar15,cVar1,cVar16);
                      puVar5 = FUN_0041e9f0();
                      uVar7 = FUN_004d8af0(puVar5);
                      if ((uVar7 & 0xff) == 0) {
                        local_69 = 0;
                      }
                      else {
                        puVar5 = FUN_0044c040();
                        fVar17 = FUN_004776d0((int)puVar5);
                        fVar23 = (float)fVar17;
                        puVar5 = FUN_0041e9f0();
                        FUN_004d8ee0(puVar5,fVar23);
                        puVar5 = FUN_0044c040();
                        fVar17 = FUN_004776f0((int)puVar5);
                        fVar23 = (float)fVar17;
                        puVar5 = FUN_0041e9f0();
                        FUN_004d8fb0(puVar5,fVar23);
                        puVar5 = FUN_0044c040();
                        cVar1 = FUN_00477690((int)puVar5);
                        if (cVar1 != '\0') {
                          uVar24 = 1;
                          puVar5 = FUN_0041e9f0();
                          FUN_004d8d10(puVar5,uVar24);
                        }
                        puVar5 = FUN_0044c040();
                        cVar1 = FUN_004776b0((int)puVar5);
                        if (cVar1 != '\0') {
                          uVar24 = 1;
                          puVar5 = FUN_0041e9f0();
                          FUN_004d8de0(puVar5,uVar24);
                        }
                        pCVar21 = local_10;
                        puVar5 = FUN_0040ec80();
                        FUN_004391a0(puVar5,pCVar21);
                        piVar12 = (int *)FUN_00427130((undefined4 *)local_10);
                        uVar10 = 0x6c6d78;
                        uVar15 = extraout_ECX_00;
                        FUN_0040cd80(&stack0xffffff0c,L"frame");
                        piVar13 = (int *)FUN_0040c190(local_3c,uVar15,uVar10);
                        FID_conflict_operator_(&stack0xffffff0c,piVar13);
                        (**(code **)(*piVar12 + 0x3c))();
                        FUN_0040c020(local_3c);
                        piVar12 = (int *)FUN_00427130((undefined4 *)local_10);
                        uVar10 = 0x6c6d78;
                        uStack_10c = 0x4763ca;
                        uVar15 = extraout_ECX_01;
                        FUN_0040cd80(&stack0xfffffefc,L"font");
                        piVar13 = (int *)FUN_0040c190(local_4c,uVar15,uVar10);
                        uStack_10c = 0x4763dd;
                        FID_conflict_operator_(&stack0xfffffefc,piVar13);
                        uStack_10c = 0x4763f2;
                        (**(code **)(*piVar12 + 0x3c))();
                        uStack_10c = 0x4763fa;
                        FUN_0040c020(local_4c);
                        FUN_00469690(&uStack_10c,(int *)local_18);
                        FUN_0047bac0(local_14);
                        FUN_00469690(&uStack_10c,(int *)local_c);
                        FUN_0047bac0(local_8);
                        FUN_0049bbe0(&uStack_10c,0,'\x01');
                        FUN_004815c0(&stack0xfffffef0,(int *)local_14);
                        FUN_004815c0(&stack0xfffffeec,(int *)local_8);
                        FUN_00469690(&stack0xfffffee8,(int *)local_10);
                        fVar19 = 100.0;
                        fVar18 = 1.0;
                        puVar5 = FUN_0044c040();
                        uVar7 = FUN_0049e8c0((int)puVar5);
                        fVar23 = (float)uVar7;
                        puVar5 = FUN_0044c040();
                        uVar7 = FUN_0044bcf0((int)puVar5);
                        fVar25 = (float)uVar7;
                        uVar15 = *(undefined4 *)((int)param_1 + 0x58);
                        puVar5 = FUN_00454080();
                        FUN_004ca6c0(puVar5,uVar15,fVar25,fVar23,fVar18,fVar19);
                        uStack_10c = 0x4764df;
                        pDVar14 = (DWORD *)FUN_0044fbf0();
                        uStack_10c = 0x4764e6;
                        uVar7 = FUN_004dcf90(pDVar14);
                        if ((uVar7 & 0xff) == 0) {
                          local_69 = 0;
                          uStack_10c = 0x4764f9;
                          CDialogTemplate::~CDialogTemplate(local_8);
                          uStack_10c = 0x476501;
                          CDialogTemplate::~CDialogTemplate(local_14);
                          uStack_10c = 0x476509;
                          CDialogTemplate::~CDialogTemplate(local_c);
                          uStack_10c = 0x476511;
                          CDialogTemplate::~CDialogTemplate(local_18);
                          uStack_10c = 0x476519;
                          CDialogTemplate::~CDialogTemplate(local_10);
                        }
                        else {
                          uStack_10c = 0x47652b;
                          puVar5 = FUN_0044fb40();
                          uStack_10c = 0x476532;
                          cVar1 = FUN_0041dde0(puVar5);
                          if (cVar1 == '\0') {
                            local_6a = 0;
                            uStack_10c = 0x476545;
                            CDialogTemplate::~CDialogTemplate(local_8);
                            uStack_10c = 0x47654d;
                            CDialogTemplate::~CDialogTemplate(local_14);
                            uStack_10c = 0x476555;
                            CDialogTemplate::~CDialogTemplate(local_c);
                            uStack_10c = 0x47655d;
                            CDialogTemplate::~CDialogTemplate(local_18);
                            uStack_10c = 0x476565;
                            CDialogTemplate::~CDialogTemplate(local_10);
                            local_69 = local_6a;
                          }
                          else {
                            uStack_10c = 0x476577;
                            puVar5 = FUN_00417e20();
                            uStack_10c = 0x47657e;
                            uVar7 = FUN_004147e0((int)puVar5);
                            if ((uVar7 & 0xff) == 0) {
                              local_6b = 0;
                              uStack_10c = 0x476591;
                              CDialogTemplate::~CDialogTemplate(local_8);
                              uStack_10c = 0x476599;
                              CDialogTemplate::~CDialogTemplate(local_14);
                              uStack_10c = 0x4765a1;
                              CDialogTemplate::~CDialogTemplate(local_c);
                              uStack_10c = 0x4765a9;
                              CDialogTemplate::~CDialogTemplate(local_18);
                              uStack_10c = 0x4765b1;
                              CDialogTemplate::~CDialogTemplate(local_10);
                              local_69 = local_6b;
                            }
                            else {
                              uStack_10c = 0x4765c3;
                              puVar8 = (undefined4 *)FUN_00459710();
                              uStack_10c = 0x4765ca;
                              uVar7 = FUN_00420810(puVar8);
                              if ((uVar7 & 0xff) == 0) {
                                local_6c = 0;
                                uStack_10c = 0x4765dd;
                                CDialogTemplate::~CDialogTemplate(local_8);
                                uStack_10c = 0x4765e5;
                                CDialogTemplate::~CDialogTemplate(local_14);
                                uStack_10c = 0x4765ed;
                                CDialogTemplate::~CDialogTemplate(local_c);
                                uStack_10c = 0x4765f5;
                                CDialogTemplate::~CDialogTemplate(local_18);
                                uStack_10c = 0x4765fd;
                                CDialogTemplate::~CDialogTemplate(local_10);
                                local_69 = local_6c;
                              }
                              else {
                                uStack_10c = *(undefined4 *)((int)param_1 + 0x58);
                                uVar10 = 0;
                                uVar15 = (*(code *)PTR_FUN_005a6d78)();
                                puVar5 = FUN_00454050();
                                uVar7 = FUN_004142f0(puVar5,uVar15,uVar10);
                                if ((uVar7 & 0xff) == 0) {
                                  local_6d = 0;
                                  CDialogTemplate::~CDialogTemplate(local_8);
                                  CDialogTemplate::~CDialogTemplate(local_14);
                                  CDialogTemplate::~CDialogTemplate(local_c);
                                  CDialogTemplate::~CDialogTemplate(local_18);
                                  CDialogTemplate::~CDialogTemplate(local_10);
                                  local_69 = local_6d;
                                }
                                else {
                                  puVar5 = FUN_00449850();
                                  uVar7 = FUN_00462030((int)puVar5);
                                  if ((uVar7 & 0xff) == 0) {
                                    local_6e = 0;
                                    CDialogTemplate::~CDialogTemplate(local_8);
                                    CDialogTemplate::~CDialogTemplate(local_14);
                                    CDialogTemplate::~CDialogTemplate(local_c);
                                    CDialogTemplate::~CDialogTemplate(local_18);
                                    CDialogTemplate::~CDialogTemplate(local_10);
                                    local_69 = local_6e;
                                  }
                                  else {
                                    uVar7 = FUN_004612f0();
                                    if ((uVar7 & 0xff) == 0) {
                                      local_6f = 0;
                                      CDialogTemplate::~CDialogTemplate(local_8);
                                      CDialogTemplate::~CDialogTemplate(local_14);
                                      CDialogTemplate::~CDialogTemplate(local_c);
                                      CDialogTemplate::~CDialogTemplate(local_18);
                                      CDialogTemplate::~CDialogTemplate(local_10);
                                      local_69 = local_6f;
                                    }
                                    else {
                                      FUN_0040cd80(&local_74,L"logo");
                                      FUN_0040cd80(&local_78,L"LogoStage");
                                      piVar12 = &local_74;
                                      piVar13 = &local_78;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_78);
                                      FUN_0040dab0(&local_74);
                                      FUN_0040cd80(&local_7c,L"newRider");
                                      FUN_0040cd80(&local_80,L"NewRiderStage");
                                      piVar12 = &local_7c;
                                      piVar13 = &local_80;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_80);
                                      FUN_0040dab0(&local_7c);
                                      FUN_0040cd80(&local_84,L"selectRider");
                                      FUN_0040cd80(&local_88,L"SelectRiderStage");
                                      piVar12 = &local_84;
                                      piVar13 = &local_88;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_88);
                                      FUN_0040dab0(&local_84);
                                      FUN_0040cd80(&local_8c,L"mainMenu");
                                      FUN_0040cd80(&local_90,L"MainMenuStage");
                                      piVar12 = &local_8c;
                                      piVar13 = &local_90;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_90);
                                      FUN_0040dab0(&local_8c);
                                      FUN_0040cd80(&local_94,L"selectChallenge");
                                      FUN_0040cd80(&local_98,L"SelectChallengeStage");
                                      piVar12 = &local_94;
                                      piVar13 = &local_98;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_98);
                                      FUN_0040dab0(&local_94);
                                      FUN_0040cd80(&local_9c,L"readyChallenge");
                                      FUN_0040cd80(&local_a0,L"ReadyChallengeStage");
                                      piVar12 = &local_9c;
                                      piVar13 = &local_a0;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_a0);
                                      FUN_0040dab0(&local_9c);
                                      FUN_0040cd80(&local_a4,L"howto");
                                      FUN_0040cd80(&local_a8,L"HowtoStage");
                                      piVar12 = &local_a4;
                                      piVar13 = &local_a8;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_a8);
                                      FUN_0040dab0(&local_a4);
                                      FUN_0040cd80(&local_ac,L"timeChallenge");
                                      FUN_0040cd80(&local_b0,L"TimeChallengeStage");
                                      piVar12 = &local_ac;
                                      piVar13 = &local_b0;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_b0);
                                      FUN_0040dab0(&local_ac);
                                      FUN_0040cd80(&local_b4,L"shadowAttack");
                                      FUN_0040cd80(&local_b8,L"ShadowAttackStage");
                                      piVar12 = &local_b4;
                                      piVar13 = &local_b8;
                                      puVar5 = FUN_00449850();
                                      FUN_004621c0(puVar5,piVar13,piVar12);
                                      FUN_0040dab0(&local_b8);
                                      FUN_0040dab0(&local_b4);
                                      FUN_0040cd80(local_c0,L"LogoStage");
                                      puVar8 = (undefined4 *)FUN_00449850();
                                      FUN_0045b690(&stack0xfffffef0,0,'\x01');
                                      (**(code **)*puVar8)();
                                      FUN_0040dab0(local_c0);
                                      puVar5 = FUN_0044c040();
                                      cVar1 = FUN_004d8030(puVar5);
                                      if ((cVar1 == '\0') &&
                                         (cVar1 = FUN_00476d20(param_1), cVar1 == '\0')) {
                                        CDialogTemplate::~CDialogTemplate(local_8);
                                        CDialogTemplate::~CDialogTemplate(local_14);
                                        CDialogTemplate::~CDialogTemplate(local_c);
                                        CDialogTemplate::~CDialogTemplate(local_18);
                                        CDialogTemplate::~CDialogTemplate(local_10);
                                        return 0;
                                      }
                                      CDialogTemplate::~CDialogTemplate(local_8);
                                      CDialogTemplate::~CDialogTemplate(local_14);
                                      CDialogTemplate::~CDialogTemplate(local_c);
                                      CDialogTemplate::~CDialogTemplate(local_18);
                                      CDialogTemplate::~CDialogTemplate(local_10);
                                      local_69 = 1;
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return local_69;
}



================================================================================
REQUESTED 00464b90
ENTRY 00464b90
NAME FUN_00464b90
SIGNATURE undefined __thiscall FUN_00464b90(void * this, undefined4 param_1)
BODY [[00464b90, 00464bb2]]


void __thiscall FUN_00464b90(void *this,undefined4 param_1)

{
  *(undefined4 *)((int)this + 0x20c) = param_1;
  *(undefined1 *)((int)this + 0x1fc) = 1;
  return;
}



