Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004122e0
ENTRY 004122e0
NAME FUN_004122e0
SIGNATURE int __fastcall FUN_004122e0(int param_1)
BODY [[004122e0, 004122f0]]


int __fastcall FUN_004122e0(int param_1)

{
  return param_1 + 0x2c;
}



================================================================================
REQUESTED 00412300
ENTRY 00412300
NAME FUN_00412300
SIGNATURE int __fastcall FUN_00412300(int param_1)
BODY [[00412300, 00412310]]


int __fastcall FUN_00412300(int param_1)

{
  return param_1 + 0x38;
}



================================================================================
REQUESTED 004285b0
ENTRY 004285b0
NAME FUN_004285b0
SIGNATURE undefined __thiscall FUN_004285b0(void * this, int param_1, undefined4 * param_2)
BODY [[004285b0, 004285ea]]


void __thiscall FUN_004285b0(void *this,int param_1,undefined4 *param_2)

{
  *(undefined4 *)((int)this + param_1 * 4) = *param_2;
  *(undefined4 *)((int)this + param_1 * 4 + 0xc) = param_2[1];
  *(undefined4 *)((int)this + param_1 * 4 + 0x18) = param_2[2];
  return;
}



================================================================================
REQUESTED 00424010
ENTRY 00424010
NAME FUN_00424010
SIGNATURE undefined4 * __fastcall FUN_00424010(undefined4 * param_1)
BODY [[00424010, 0042408e]]


undefined4 * __fastcall FUN_00424010(undefined4 *param_1)

{
  undefined4 uVar1;
  CSize local_5;
  
  FUN_0042dcc0(param_1);
  *param_1 = &PTR_FUN_00571700;
  FUN_004b30e0(param_1 + 6);
  uVar1 = CSize::CSize(&local_5);
  FUN_00401310(param_1 + 7,uVar1);
  FUN_00493460();
  CSize::CSize((CSize *)(param_1 + 10));
  CSize::CSize((CSize *)(param_1 + 0xd));
  FUN_004b30e0(param_1 + 0x16);
  FUN_004b30e0(param_1 + 0x17);
  FUN_004794a0((int)(param_1 + 0x19));
  return param_1;
}



================================================================================
REQUESTED 00426b80
ENTRY 00426b80
NAME FUN_00426b80
SIGNATURE undefined4 * __fastcall FUN_00426b80(undefined4 * param_1)
BODY [[00426b80, 00426bca]]


undefined4 * __fastcall FUN_00426b80(undefined4 *param_1)

{
  FUN_004b30e0(param_1);
  _vector_constructor_iterator_(param_1 + 1,0xc,3,CSize::CSize);
  _vector_constructor_iterator_(param_1 + 10,0xc,3,CSize::CSize);
  CSize::CSize((CSize *)(param_1 + 0x13));
  return param_1;
}



================================================================================
REQUESTED 00426ad0
ENTRY 00426ad0
NAME FUN_00426ad0
SIGNATURE undefined4 * __fastcall FUN_00426ad0(undefined4 * param_1)
BODY [[00426ad0, 00426b43]]


undefined4 * __fastcall FUN_00426ad0(undefined4 *param_1)

{
  undefined4 uVar1;
  CSize local_7;
  CSize local_6;
  CSize local_5;
  
  FUN_004b30e0(param_1);
  uVar1 = CSize::CSize(&local_5);
  FUN_00401310(param_1 + 2,uVar1);
  FUN_00493460();
  uVar1 = CSize::CSize(&local_6);
  FUN_00401310(param_1 + 5,uVar1);
  FUN_00493460();
  uVar1 = CSize::CSize(&local_7);
  FUN_00401310(param_1 + 8,uVar1);
  FUN_00493460();
  FUN_00426b50((int)param_1);
  return param_1;
}



================================================================================
REQUESTED 004267c0
ENTRY 004267c0
NAME FUN_004267c0
SIGNATURE undefined __thiscall FUN_004267c0(void * this, undefined4 param_1, float param_2, undefined4 * param_3, undefined4 * param_4)
BODY [[004267c0, 0042699e]]


void __thiscall
FUN_004267c0(void *this,undefined4 param_1,float param_2,undefined4 *param_3,undefined4 *param_4)

{
  int iVar1;
  void *pvVar2;
  float *pfVar3;
  undefined4 *puVar4;
  float10 fVar5;
  float fVar6;
  undefined1 local_7c [12];
  undefined1 local_70 [12];
  undefined1 local_64 [12];
  undefined1 local_58 [12];
  undefined1 local_4c [12];
  undefined1 local_40 [12];
  undefined1 local_34 [12];
  float local_28;
  float local_24;
  float local_20;
  int local_1c;
  int local_18 [2];
  float local_10;
  float local_c;
  float *local_8;
  
  FUN_004096d0((void *)((int)this + 100),local_18,&param_1);
  iVar1 = FUN_00417de0(local_18);
  local_1c = *(int *)(iVar1 + 4);
  iVar1 = FUN_00417de0(local_18);
  local_10 = *(float *)(iVar1 + 0x10);
  while (DAT_00571808 < param_2) {
    if (local_10 + param_2 <= *(float *)(local_1c + 0x2c)) {
      local_10 = local_10 + param_2;
      param_2 = 0.0;
    }
    else {
      param_2 = param_2 - (*(float *)(local_1c + 0x2c) - local_10);
      iVar1 = FUN_00460370((void *)(local_1c + 8),0);
      local_1c = FUN_00427130((undefined4 *)(iVar1 + 4));
      local_10 = 0.0;
    }
  }
  local_c = 0.0;
  local_8 = (float *)FUN_00427130((undefined4 *)(local_1c + 0x20));
  while( true ) {
    iVar1 = FUN_004b9c00(local_1c + 0x20);
    if (local_8 == (float *)(iVar1 + -0x18)) {
      return;
    }
    pvVar2 = FUN_00418750(local_34,local_8 + 6,local_8);
    fVar5 = (float10)FUN_004136f0(pvVar2);
    local_20 = (float)fVar5;
    local_24 = local_c + local_20;
    if ((local_c < local_10 != (local_c == local_10)) && (local_10 <= local_24)) break;
    local_8 = local_8 + 6;
    local_c = local_24;
  }
  fVar6 = (local_10 - local_c) / local_20;
  local_28 = fVar6;
  pfVar3 = (float *)FUN_00418750(local_40,local_8 + 9,local_8 + 3);
  pfVar3 = (float *)FUN_00418790(local_4c,pfVar3,fVar6);
  puVar4 = (undefined4 *)FUN_00418710(local_58,local_8 + 3,pfVar3);
  *param_4 = *puVar4;
  param_4[1] = puVar4[1];
  param_4[2] = puVar4[2];
  fVar6 = local_28;
  pfVar3 = (float *)FUN_00418750(local_64,local_8 + 6,local_8);
  pfVar3 = (float *)FUN_00418790(local_70,pfVar3,fVar6);
  puVar4 = (undefined4 *)FUN_00418710(local_7c,local_8,pfVar3);
  *param_3 = *puVar4;
  param_3[1] = puVar4[1];
  param_3[2] = puVar4[2];
  return;
}



================================================================================
REQUESTED 00426fc0
ENTRY 00426fc0
NAME FUN_00426fc0
SIGNATURE int __fastcall FUN_00426fc0(int param_1)
BODY [[00426fc0, 00426fd5]]


int __fastcall FUN_00426fc0(int param_1)

{
  int iVar1;
  
  iVar1 = FUN_004b9c00(param_1);
  return iVar1 + -4;
}



================================================================================
REQUESTED 004d2be0
ENTRY 004d2be0
NAME FUN_004d2be0
SIGNATURE undefined __fastcall FUN_004d2be0(undefined4 * param_1)
BODY [[004d2be0, 004d2bf2]]


void __fastcall FUN_004d2be0(undefined4 *param_1)

{
  FUN_00427130(param_1);
  return;
}



================================================================================
REQUESTED 00428490
ENTRY 00428490
NAME FUN_00428490
SIGNATURE void * __cdecl FUN_00428490(void * param_1, float * param_2, float * param_3)
BODY [[00428490, 004284f5]]


void * __cdecl FUN_00428490(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,param_2[1] * param_3[2] - param_2[2] * param_3[1],
               param_2[2] * *param_3 - *param_2 * param_3[2],
               *param_2 * param_3[1] - param_2[1] * *param_3);
  return param_1;
}



================================================================================
REQUESTED 004136f0
ENTRY 004136f0
NAME FUN_004136f0
SIGNATURE undefined __fastcall FUN_004136f0(undefined4 param_1)
BODY [[004136f0, 0041372c]]


void __fastcall FUN_004136f0(undefined4 param_1)

{
  FUN_00413730(param_1);
  return;
}



================================================================================
REQUESTED 00418750
ENTRY 00418750
NAME FUN_00418750
SIGNATURE void * __cdecl FUN_00418750(void * param_1, float * param_2, float * param_3)
BODY [[00418750, 0041878d]]


void * __cdecl FUN_00418750(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,*param_2 - *param_3,param_2[1] - param_3[1],param_2[2] - param_3[2]);
  return param_1;
}



================================================================================
REQUESTED 00428530
ENTRY 00428530
NAME FUN_00428530
SIGNATURE void * __cdecl FUN_00428530(void * param_1, float * param_2, float param_3)
BODY [[00428530, 00428565]]


void * __cdecl FUN_00428530(void *param_1,float *param_2,float param_3)

{
  FUN_004135a0(param_1,*param_2 / param_3,param_2[1] / param_3,param_2[2] / param_3);
  return param_1;
}



================================================================================
REQUESTED 0040c210
ENTRY 0040c210
NAME FUN_0040c210
SIGNATURE void * __thiscall FUN_0040c210(void * this, int * param_1)
BODY [[0040c210, 0040c22b]]


void * __thiscall FUN_0040c210(void *this,int *param_1)

{
  FUN_0040c230(this,param_1);
  return this;
}



================================================================================
REQUESTED 004ba800
ENTRY 004ba800
NAME FUN_004ba800
SIGNATURE undefined __thiscall FUN_004ba800(void * this, int * param_1)
BODY [[004ba800, 004ba86b]]


void __thiscall FUN_004ba800(void *this,int *param_1)

{
  int iVar1;
  void *pvVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  
  FUN_004b6fb0(this,param_1);
  iVar3 = (int)this + 0x24;
  iVar5 = (int)this + 0x20;
  iVar1 = (int)this + 0x1c;
  iVar4 = (int)this + 0x18;
  pvVar2 = FUN_004ba9c0(param_1,(int)this + 0x10);
  pvVar2 = FUN_004014a0(pvVar2,iVar4);
  pvVar2 = FUN_004014a0(pvVar2,iVar1);
  pvVar2 = FUN_004014a0(pvVar2,iVar5);
  FUN_004014a0(pvVar2,iVar3);
  return;
}



================================================================================
REQUESTED 004bae10
ENTRY 004bae10
NAME FUN_004bae10
SIGNATURE void * __thiscall FUN_004bae10(void * this, void * param_1, undefined4 * param_2)
BODY [[004bae10, 004bae8c]]


void * __thiscall FUN_004bae10(void *this,void *param_1,undefined4 *param_2)

{
  char cVar1;
  int *piVar2;
  int iVar3;
  void *pvVar4;
  undefined4 *puVar5;
  int *local_8;
  
  local_8 = (int *)FUN_00427130((undefined4 *)((int)this + 0x10));
  while( true ) {
    piVar2 = (int *)FUN_004b9c00((int)this + 0x10);
    if (local_8 == piVar2) {
      FUN_0045b690(param_1,0,'\x01');
      return param_1;
    }
    puVar5 = param_2;
    iVar3 = FUN_00427130(local_8);
    pvVar4 = (void *)FUN_00418620(iVar3);
    cVar1 = FUN_0040f240(pvVar4,puVar5);
    if (cVar1 != '\0') break;
    local_8 = local_8 + 1;
  }
  FUN_00469690(param_1,local_8);
  return param_1;
}



================================================================================
REQUESTED 00427bf0
ENTRY 00427bf0
NAME FUN_00427bf0
SIGNATURE void * __cdecl FUN_00427bf0(void * param_1, undefined4 * param_2)
BODY [[00427bf0, 00427c21]]


void * __cdecl FUN_00427bf0(void *param_1,undefined4 *param_2)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 uVar3;
  TypeDescriptor *pTVar4;
  TypeDescriptor *pTVar5;
  undefined4 uVar6;
  char cVar7;
  
  cVar7 = '\x01';
  uVar6 = 0;
  pTVar5 = &the::ToRoad::RTTI_Type_Descriptor;
  pTVar4 = &the::TrackObject::RTTI_Type_Descriptor;
  uVar3 = 0;
  uVar1 = FUN_00427130(param_2);
  iVar2 = __RTDynamicCast(uVar1,uVar3,pTVar4,pTVar5,uVar6);
  FUN_0045b690(param_1,iVar2,cVar7);
  return param_1;
}



