Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00428790
ENTRY 00428790
NAME FUN_00428790
SIGNATURE int __fastcall FUN_00428790(int param_1)
BODY [[00428790, 004287a0]]


int __fastcall FUN_00428790(int param_1)

{
  return param_1 + 0x14;
}



================================================================================
REQUESTED 00453fc0
ENTRY 00453fc0
NAME FUN_00453fc0
SIGNATURE undefined __fastcall FUN_00453fc0(int param_1)
BODY [[00453fc0, 00453fe3]]


void __fastcall FUN_00453fc0(int param_1)

{
  std::shared_ptr<class___ExceptionPtr>::operator=
            ((shared_ptr<class___ExceptionPtr> *)(param_1 + 0x18),
             (shared_ptr<class___ExceptionPtr> *)&stack0x00000004);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return;
}



