Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00424e00
ENTRY 00424e00
NAME FUN_00424e00
SIGNATURE undefined __stdcall FUN_00424e00(undefined4 param_1, undefined4 * param_2, uint param_3, uint * param_4, undefined4 param_5, char param_6)
BODY [[00424e00, 00425fd4]]


void FUN_00424e00(undefined4 param_1,undefined4 *param_2,uint param_3,uint *param_4,
                 undefined4 param_5,char param_6)

{
  char cVar1;
  undefined4 uVar2;
  int iVar3;
  undefined4 *puVar4;
  void *pvVar5;
  shared_ptr<class___ExceptionPtr> *psVar6;
  uint uVar7;
  ushort *puVar8;
  float *pfVar9;
  int *piVar10;
  uint *puVar11;
  undefined4 extraout_ECX;
  float *pfVar12;
  bool bVar13;
  float10 fVar14;
  int *piVar15;
  CDialogTemplate *pCVar16;
  undefined1 uVar17;
  wchar_t *pwVar18;
  int iVar19;
  undefined1 *puVar20;
  undefined4 *local_1b0;
  undefined4 *local_1a4;
  float local_19c;
  undefined4 *local_198;
  undefined4 *local_194;
  undefined1 local_188 [23];
  CSize local_171;
  int local_170;
  char local_169;
  int local_168;
  char local_161;
  undefined4 *local_160;
  undefined1 local_15c [12];
  undefined1 local_150 [12];
  undefined1 local_144 [12];
  undefined1 local_138 [12];
  undefined4 *local_12c;
  int local_128;
  int local_124;
  int local_120;
  char local_119;
  int local_118;
  int local_114;
  char local_10d;
  int local_10c;
  int local_108;
  char local_101;
  CDialogTemplate local_100 [4];
  CDialogTemplate local_fc [4];
  int local_f8;
  int local_f4;
  int local_f0;
  char local_e9;
  undefined4 *local_e8;
  CSize local_e1;
  shared_ptr<class___ExceptionPtr> local_e0 [4];
  shared_ptr<class___ExceptionPtr> local_dc [4];
  float *local_d8;
  int local_d4;
  shared_ptr<class___ExceptionPtr> *local_d0;
  shared_ptr<class___ExceptionPtr> local_cc [4];
  shared_ptr<class___ExceptionPtr> local_c8 [4];
  int local_c4 [3];
  undefined4 *local_b8;
  uint local_b4;
  int *local_b0;
  int *local_ac;
  uint local_a8;
  undefined4 local_a4;
  undefined4 local_a0;
  undefined4 local_9c;
  undefined4 local_98;
  undefined4 local_94;
  undefined4 local_90;
  uint local_8c;
  uint local_88;
  int local_84;
  int local_80;
  undefined4 local_7c;
  undefined4 local_78;
  undefined4 local_74;
  undefined4 local_70;
  undefined4 local_6c;
  undefined4 local_68;
  shared_ptr<class___ExceptionPtr> *local_64;
  shared_ptr<class___ExceptionPtr> local_60 [4];
  shared_ptr<class___ExceptionPtr> local_5c [4];
  shared_ptr<class___ExceptionPtr> local_58 [4];
  float *local_54;
  uint local_50;
  int local_4c;
  int local_48;
  int local_44;
  int *local_40;
  uint local_3c;
  uint local_38;
  uint local_34;
  char local_2d;
  shared_ptr<class___ExceptionPtr> local_2c [4];
  uint local_28;
  uint local_24;
  uint local_20;
  undefined4 *local_1c;
  int local_18 [3];
  shared_ptr<class___ExceptionPtr> local_c [7];
  undefined1 local_5;
  
  local_5 = 0;
  uVar2 = CSize::CSize(&local_e1);
  FUN_00401310(local_18,uVar2);
  FUN_00493460();
  local_e8 = (undefined4 *)FUN_00478523(0x30);
  if (local_e8 == (undefined4 *)0x0) {
    local_194 = (undefined4 *)0x0;
  }
  else {
    local_194 = FUN_00426ad0(local_e8);
  }
  FUN_0049bbe0(local_c,(int)local_194,'\x01');
  iVar3 = FUN_00427130((undefined4 *)local_c);
  *(uint *)(iVar3 + 4) = param_3;
  *param_4 = param_3;
  iVar3 = FUN_00427130(&param_1);
  puVar4 = (undefined4 *)FUN_0047b3a0(iVar3);
  local_1c = (undefined4 *)FUN_00427130(puVar4);
  do {
    iVar3 = FUN_00427130(&param_1);
    iVar3 = FUN_0047b3a0(iVar3);
    puVar4 = (undefined4 *)FUN_004b9c00(iVar3);
    if (local_1c == puVar4) {
      if (param_6 != '\0') {
        SafeRWList<>((undefined4 *)local_e0);
        iVar19 = 0;
        puVar4 = (undefined4 *)FUN_004d2be0(param_2);
        iVar3 = FUN_00427130(puVar4);
        psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_00460370((void *)(iVar3 + 0x14),iVar19);
        std::shared_ptr<class___ExceptionPtr>::operator=(local_e0,psVar6);
        psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_0044cfd0(local_18,0);
        std::shared_ptr<class___ExceptionPtr>::operator=(local_dc,psVar6);
        psVar6 = local_e0;
        iVar19 = 0;
        puVar4 = (undefined4 *)FUN_004d2be0(param_2);
        iVar3 = FUN_00427130(puVar4);
        pvVar5 = (void *)FUN_00460370((void *)(iVar3 + 0x14),iVar19);
        FUN_00426c50(pvVar5,psVar6);
        psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_004d2be0(param_2);
        std::shared_ptr<class___ExceptionPtr>::operator=(local_dc,psVar6);
        psVar6 = local_e0;
        puVar4 = (undefined4 *)FUN_0044cfd0(local_18,0);
        iVar3 = FUN_00427130(puVar4);
        FUN_00426e70((void *)(iVar3 + 8),(int *)psVar6);
        FUN_00426c00((CDialogTemplate *)local_e0);
      }
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)local_c);
      FUN_00426fe0(local_18);
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_1);
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_5);
      return;
    }
    local_5 = 0;
    pwVar18 = L"road";
    piVar10 = &local_f0;
    pvVar5 = (void *)FUN_00427130(local_1c);
    pvVar5 = FUN_0047bf50(pvVar5,piVar10);
    local_e9 = FUN_0040ce00(pvVar5,pwVar18);
    FUN_0040dab0(&local_f0);
    if (local_e9 == '\0') {
      pwVar18 = L"plane";
      piVar10 = &local_168;
      pvVar5 = (void *)FUN_00427130(local_1c);
      pvVar5 = FUN_0047bf50(pvVar5,piVar10);
      local_161 = FUN_0040ce00(pvVar5,pwVar18);
      FUN_0040dab0(&local_168);
      if (local_161 == '\0') {
        pwVar18 = L"branch";
        piVar10 = &local_170;
        pvVar5 = (void *)FUN_00427130(local_1c);
        pvVar5 = FUN_0047bf50(pvVar5,piVar10);
        local_169 = FUN_0040ce00(pvVar5,pwVar18);
        FUN_0040dab0(&local_170);
        if (local_169 != '\0') {
          local_5 = 1;
          local_a8 = param_3;
          iVar3 = FUN_00427130(local_1c);
          puVar4 = (undefined4 *)FUN_0047b3a0(iVar3);
          local_ac = (int *)FUN_00427130(puVar4);
          while( true ) {
            iVar3 = FUN_00427130(local_1c);
            iVar3 = FUN_0047b3a0(iVar3);
            piVar10 = (int *)FUN_004b9c00(iVar3);
            if (local_ac == piVar10) break;
            uVar2 = CSize::CSize(&local_171);
            FUN_00401310(local_c4,uVar2);
            FUN_00493460();
            cVar1 = '\0';
            uVar2 = extraout_ECX;
            FUN_00469690(&stack0xfffffe40,&param_5);
            puVar11 = &local_b4;
            uVar7 = *param_4;
            piVar10 = local_c4;
            piVar15 = piVar10;
            FUN_004815c0(&stack0xfffffe30,local_ac);
            FUN_00424e00(piVar10,piVar15,uVar7,puVar11,uVar2,cVar1);
            puVar11 = FUN_00427c30(&local_b4,&local_a8);
            local_a8 = *puVar11;
            SafeRWList<>((undefined4 *)local_cc);
            iVar19 = 0;
            puVar4 = (undefined4 *)FUN_004d2be0(local_c4);
            iVar3 = FUN_00427130(puVar4);
            psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_00460370((void *)(iVar3 + 0x14),iVar19)
            ;
            std::shared_ptr<class___ExceptionPtr>::operator=(local_cc,psVar6);
            puVar4 = (undefined4 *)FUN_004d2be0(local_c4);
            iVar3 = FUN_00427130(puVar4);
            FUN_00426ee0((undefined4 *)(iVar3 + 0x14));
            local_d0 = (shared_ptr<class___ExceptionPtr> *)FUN_00427130(local_18);
            while (psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_004b9c00((int)local_18),
                  local_d0 != psVar6) {
              std::shared_ptr<class___ExceptionPtr>::operator=(local_c8,local_d0);
              psVar6 = local_cc;
              puVar4 = (undefined4 *)FUN_004d2be0(local_c4);
              iVar3 = FUN_00427130(puVar4);
              FUN_00426e70((void *)(iVar3 + 0x14),(int *)psVar6);
              psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_004d2be0(local_c4);
              std::shared_ptr<class___ExceptionPtr>::operator=(local_c8,psVar6);
              psVar6 = local_cc;
              iVar3 = FUN_00427130((undefined4 *)local_d0);
              FUN_00426e70((void *)(iVar3 + 8),(int *)psVar6);
              local_d0 = local_d0 + 4;
            }
            puVar4 = (undefined4 *)FUN_00426fc0((int)local_c4);
            iVar3 = FUN_00427130(puVar4);
            local_b8 = (undefined4 *)(iVar3 + 0x14);
            local_d4 = FUN_00427130(local_b8);
            while (iVar3 = FUN_004b9c00((int)local_b8), local_d4 != iVar3) {
              psVar6 = local_c;
              iVar19 = 0;
              iVar3 = FUN_00427130((undefined4 *)(local_d4 + 4));
              iVar3 = FUN_00460370((void *)(iVar3 + 8),iVar19);
              std::shared_ptr<class___ExceptionPtr>::operator=
                        ((shared_ptr<class___ExceptionPtr> *)(iVar3 + 4),psVar6);
              local_d4 = local_d4 + 8;
            }
            iVar19 = 0;
            puVar4 = (undefined4 *)FUN_00426fc0((int)local_c4);
            iVar3 = FUN_00427130(puVar4);
            psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_00460370((void *)(iVar3 + 0x14),iVar19)
            ;
            std::shared_ptr<class___ExceptionPtr>::operator=(local_cc,psVar6);
            iVar19 = 0;
            puVar4 = (undefined4 *)FUN_00426fc0((int)local_c4);
            iVar3 = FUN_00427130(puVar4);
            iVar3 = FUN_00460370((void *)(iVar3 + 0x14),iVar19);
            std::shared_ptr<class___ExceptionPtr>::operator=
                      (local_c8,(shared_ptr<class___ExceptionPtr> *)(iVar3 + 4));
            psVar6 = local_cc;
            iVar3 = FUN_00427130((undefined4 *)local_c);
            FUN_00426e70((void *)(iVar3 + 0x14),(int *)psVar6);
            local_b0 = (int *)FUN_00427130(local_c4);
            while (iVar3 = FUN_004b9c00((int)local_c4), local_b0 != (int *)(iVar3 + -4)) {
              FUN_00427010(param_2,local_b0);
              local_b0 = local_b0 + 1;
            }
            iVar3 = FUN_00427130(local_1c);
            puVar4 = (undefined4 *)FUN_0047b3a0(iVar3);
            piVar10 = (int *)FUN_00427130(puVar4);
            if (local_ac == piVar10) {
              puVar4 = (undefined4 *)FUN_00426fc0((int)local_c4);
              iVar3 = FUN_00427130(puVar4);
              piVar10 = (int *)(iVar3 + 0x20);
              iVar3 = FUN_00427130((undefined4 *)local_c);
              FUN_00427860((void *)(iVar3 + 0x20),piVar10);
              iVar3 = FUN_00427130((undefined4 *)local_c);
              *(undefined4 *)(iVar3 + 0x2c) = 0;
              iVar3 = FUN_00427130((undefined4 *)local_c);
              local_d8 = (float *)FUN_00427130((undefined4 *)(iVar3 + 0x20));
              while( true ) {
                pfVar12 = local_d8 + 6;
                iVar3 = FUN_00427130((undefined4 *)local_c);
                pfVar9 = (float *)FUN_004b9c00(iVar3 + 0x20);
                if (pfVar12 == pfVar9) break;
                iVar3 = FUN_00427130((undefined4 *)local_c);
                pvVar5 = FUN_00418750(local_188,local_d8 + 6,local_d8);
                fVar14 = (float10)FUN_004136f0(pvVar5);
                *(float *)(iVar3 + 0x2c) = (float)(fVar14 + (float10)*(float *)(iVar3 + 0x2c));
                local_d8 = local_d8 + 6;
              }
            }
            FUN_00426c00((CDialogTemplate *)local_cc);
            FUN_00426fe0(local_c4);
            local_ac = local_ac + 1;
          }
          iVar19 = local_a8 - 1;
          iVar3 = FUN_00427130((undefined4 *)local_c);
          *(int *)(iVar3 + 4) = iVar19;
          FUN_00427010(param_2,(int *)local_c);
          FUN_00427080(local_18);
          FUN_00427010(local_18,(int *)local_c);
          puVar4 = (undefined4 *)FUN_00478523(0x30);
          if (puVar4 == (undefined4 *)0x0) {
            local_1b0 = (undefined4 *)0x0;
          }
          else {
            local_1b0 = FUN_00426ad0(puVar4);
          }
          FUN_00426e30(local_c,(int)local_1b0);
          iVar3 = FUN_00427130((undefined4 *)local_c);
          *(uint *)(iVar3 + 4) = local_a8;
          *param_4 = local_a8;
        }
      }
    }
    else {
      FUN_004b30e0((undefined4 *)local_2c);
      FUN_0040cd80(&local_f4,L"name");
      piVar10 = &local_f4;
      piVar15 = &local_f8;
      pvVar5 = (void *)FUN_00427130(local_1c);
      puVar4 = (undefined4 *)FUN_0047a2b0(pvVar5,piVar15,piVar10);
      pCVar16 = local_fc;
      pvVar5 = (void *)FUN_00427130(&param_5);
      puVar4 = (undefined4 *)FUN_004bae10(pvVar5,pCVar16,puVar4);
      psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_00427bf0(local_100,puVar4);
      std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
      CDialogTemplate::~CDialogTemplate(local_100);
      CDialogTemplate::~CDialogTemplate(local_fc);
      FUN_0040dab0(&local_f8);
      FUN_0040dab0(&local_f4);
      iVar3 = FUN_00427130((undefined4 *)local_2c);
      local_40 = (int *)FUN_00428790(iVar3);
      local_3c = 0;
      local_24 = FUN_00426d80(local_40);
      local_28 = local_24 - 1;
      local_2d = 0;
      local_20 = local_24;
      FUN_0040cd80(&local_108,L"start");
      piVar10 = &local_108;
      pvVar5 = (void *)FUN_00427130(local_1c);
      uVar7 = FUN_0047a360(pvVar5,piVar10);
      local_101 = (char)uVar7;
      FUN_0040dab0(&local_108);
      if (local_101 != '\0') {
        FUN_0040cd80(&local_10c,L"start");
        piVar15 = &local_10c;
        piVar10 = &local_44;
        pvVar5 = (void *)FUN_00427130(local_1c);
        FUN_0047a2b0(pvVar5,piVar10,piVar15);
        FUN_0040dab0(&local_10c);
        for (local_38 = 0; local_38 < local_20; local_38 = local_38 + 1) {
          piVar10 = &local_44;
          pvVar5 = (void *)FUN_00426da0(local_40,local_38);
          cVar1 = FUN_0040f240(pvVar5,piVar10);
          if (cVar1 != '\0') {
            local_3c = local_38;
            break;
          }
        }
        FUN_0040dab0(&local_44);
      }
      FUN_0040cd80(&local_114,L"end");
      piVar10 = &local_114;
      pvVar5 = (void *)FUN_00427130(local_1c);
      uVar7 = FUN_0047a360(pvVar5,piVar10);
      local_10d = (char)uVar7;
      FUN_0040dab0(&local_114);
      if (local_10d != '\0') {
        FUN_0040cd80(&local_118,L"end");
        piVar15 = &local_118;
        piVar10 = &local_48;
        pvVar5 = (void *)FUN_00427130(local_1c);
        FUN_0047a2b0(pvVar5,piVar10,piVar15);
        FUN_0040dab0(&local_118);
        for (local_38 = 0; local_38 < local_20; local_38 = local_38 + 1) {
          piVar10 = &local_48;
          pvVar5 = (void *)FUN_00426da0(local_40,local_38);
          cVar1 = FUN_0040f240(pvVar5,piVar10);
          if (cVar1 != '\0') {
            local_28 = local_38;
            break;
          }
        }
        FUN_0040dab0(&local_48);
      }
      FUN_0040cd80(&local_120,L"final");
      piVar10 = &local_120;
      pvVar5 = (void *)FUN_00427130(local_1c);
      uVar7 = FUN_0047a360(pvVar5,piVar10);
      local_119 = (char)uVar7;
      FUN_0040dab0(&local_120);
      if (local_119 != '\0') {
        FUN_0040cd80(&local_124,L"final");
        piVar15 = &local_124;
        piVar10 = &local_4c;
        pvVar5 = (void *)FUN_00427130(local_1c);
        FUN_0047a2b0(pvVar5,piVar10,piVar15);
        FUN_0040dab0(&local_124);
        for (local_38 = 0; local_38 < local_20; local_38 = local_38 + 1) {
          piVar10 = &local_4c;
          pvVar5 = (void *)FUN_00426da0(local_40,local_38);
          cVar1 = FUN_0040f240(pvVar5,piVar10);
          if (cVar1 != '\0') {
            local_24 = local_38;
            break;
          }
        }
        FUN_0040dab0(&local_4c);
      }
      FUN_0040cd80(&local_128,L"reverse");
      uVar17 = 0;
      piVar10 = &local_128;
      pvVar5 = (void *)FUN_00427130(local_1c);
      local_2d = FUN_0047a470(pvVar5,piVar10,uVar17);
      FUN_0040dab0(&local_128);
      local_50 = local_3c;
      while( true ) {
        if (local_2d == '\0') {
          if (local_50 == local_20 - 1) {
            local_34 = 0;
          }
          else {
            local_34 = local_50 + 1;
          }
        }
        else {
          local_34 = local_50;
          if (local_50 == 0) {
            local_34 = local_20;
          }
          local_34 = local_34 - 1;
        }
        local_12c = (undefined4 *)FUN_00478523(0x5c);
        if (local_12c == (undefined4 *)0x0) {
          local_198 = (undefined4 *)0x0;
        }
        else {
          local_198 = FUN_00426b80(local_12c);
        }
        FUN_0049bbe0(local_60,(int)local_198,'\x01');
        iVar19 = 0;
        iVar3 = FUN_00426da0(local_40,local_50);
        puVar8 = (ushort *)FUN_00426d20((void *)(iVar3 + 0x10),iVar19);
        uVar7 = (uint)*puVar8;
        iVar3 = FUN_00426da0(local_40,local_50);
        puVar4 = (undefined4 *)FUN_00426d00((void *)(iVar3 + 4),uVar7);
        iVar3 = FUN_00427130((undefined4 *)local_60);
        *(undefined4 *)(iVar3 + 4) = *puVar4;
        *(undefined4 *)(iVar3 + 8) = puVar4[1];
        *(undefined4 *)(iVar3 + 0xc) = puVar4[2];
        iVar19 = 0;
        iVar3 = FUN_00426da0(local_40,local_50);
        iVar3 = FUN_00426d20((void *)(iVar3 + 0x10),iVar19);
        uVar7 = (uint)*(ushort *)(iVar3 + ((local_2d != '\0') + 1) * 2);
        iVar3 = FUN_00426da0(local_40,local_50);
        puVar4 = (undefined4 *)FUN_00426d00((void *)(iVar3 + 4),uVar7);
        iVar3 = FUN_00427130((undefined4 *)local_60);
        *(undefined4 *)(iVar3 + 0x10) = *puVar4;
        *(undefined4 *)(iVar3 + 0x14) = puVar4[1];
        *(undefined4 *)(iVar3 + 0x18) = puVar4[2];
        iVar19 = 0;
        iVar3 = FUN_00426da0(local_40,local_50);
        iVar3 = FUN_00426d20((void *)(iVar3 + 0x10),iVar19);
        uVar7 = (uint)*(ushort *)(iVar3 + (2 - (uint)(local_2d != '\0')) * 2);
        iVar3 = FUN_00426da0(local_40,local_50);
        puVar4 = (undefined4 *)FUN_00426d00((void *)(iVar3 + 4),uVar7);
        iVar3 = FUN_00427130((undefined4 *)local_60);
        *(undefined4 *)(iVar3 + 0x1c) = *puVar4;
        *(undefined4 *)(iVar3 + 0x20) = puVar4[1];
        *(undefined4 *)(iVar3 + 0x24) = puVar4[2];
        iVar19 = 1;
        iVar3 = FUN_00426da0(local_40,local_50);
        puVar8 = (ushort *)FUN_00426d20((void *)(iVar3 + 0x10),iVar19);
        uVar7 = (uint)*puVar8;
        iVar3 = FUN_00426da0(local_40,local_50);
        puVar4 = (undefined4 *)FUN_00426d00((void *)(iVar3 + 4),uVar7);
        iVar3 = FUN_00427130((undefined4 *)local_60);
        *(undefined4 *)(iVar3 + 0x28) = *puVar4;
        *(undefined4 *)(iVar3 + 0x2c) = puVar4[1];
        *(undefined4 *)(iVar3 + 0x30) = puVar4[2];
        iVar19 = 1;
        iVar3 = FUN_00426da0(local_40,local_50);
        iVar3 = FUN_00426d20((void *)(iVar3 + 0x10),iVar19);
        uVar7 = (uint)*(ushort *)(iVar3 + ((local_2d != '\0') + 1) * 2);
        iVar3 = FUN_00426da0(local_40,local_50);
        puVar4 = (undefined4 *)FUN_00426d00((void *)(iVar3 + 4),uVar7);
        iVar3 = FUN_00427130((undefined4 *)local_60);
        *(undefined4 *)(iVar3 + 0x34) = *puVar4;
        *(undefined4 *)(iVar3 + 0x38) = puVar4[1];
        *(undefined4 *)(iVar3 + 0x3c) = puVar4[2];
        iVar19 = 1;
        iVar3 = FUN_00426da0(local_40,local_50);
        iVar3 = FUN_00426d20((void *)(iVar3 + 0x10),iVar19);
        uVar7 = (uint)*(ushort *)(iVar3 + (2 - (uint)(local_2d != '\0')) * 2);
        iVar3 = FUN_00426da0(local_40,local_50);
        puVar4 = (undefined4 *)FUN_00426d00((void *)(iVar3 + 4),uVar7);
        iVar3 = FUN_00427130((undefined4 *)local_60);
        *(undefined4 *)(iVar3 + 0x40) = *puVar4;
        *(undefined4 *)(iVar3 + 0x44) = puVar4[1];
        *(undefined4 *)(iVar3 + 0x48) = puVar4[2];
        if (local_2d == '\0') {
          local_19c = 1.0;
        }
        else {
          local_19c = -1.0;
        }
        iVar19 = 0;
        iVar3 = FUN_00426da0(local_40,local_50);
        iVar3 = FUN_00426d60((void *)(iVar3 + 0x2c),iVar19);
        puVar4 = (undefined4 *)FUN_00428420(local_138,local_19c,(float *)(iVar3 + 0xc));
        iVar3 = FUN_00427130((undefined4 *)local_60);
        *(undefined4 *)(iVar3 + 0x4c) = *puVar4;
        *(undefined4 *)(iVar3 + 0x50) = puVar4[1];
        *(undefined4 *)(iVar3 + 0x54) = puVar4[2];
        bVar13 = local_24 != local_50;
        iVar3 = FUN_00427130((undefined4 *)local_60);
        *(char *)(iVar3 + 0x58) = '\x01' - bVar13;
        SafeRWList<>((undefined4 *)local_5c);
        std::shared_ptr<class___ExceptionPtr>::operator=(local_5c,local_60);
        std::shared_ptr<class___ExceptionPtr>::operator=(local_58,local_c);
        bVar13 = FUN_00426fa0(local_18);
        if (bVar13) {
          FUN_00426e30(local_58,0);
          psVar6 = local_5c;
          iVar3 = FUN_00427130((undefined4 *)local_c);
          FUN_00426e70((void *)(iVar3 + 0x14),(int *)psVar6);
        }
        else {
          local_64 = (shared_ptr<class___ExceptionPtr> *)FUN_00427130(local_18);
          while (psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_004b9c00((int)local_18),
                local_64 != psVar6) {
            psVar6 = local_5c;
            iVar3 = FUN_00427130((undefined4 *)local_64);
            FUN_00426e70((void *)(iVar3 + 8),(int *)psVar6);
            std::shared_ptr<class___ExceptionPtr>::operator=(local_58,local_64);
            psVar6 = local_5c;
            iVar3 = FUN_00427130((undefined4 *)local_c);
            FUN_00426e70((void *)(iVar3 + 0x14),(int *)psVar6);
            local_64 = local_64 + 4;
          }
        }
        if (local_2d == '\0') {
          iVar3 = FUN_00426da0(local_40,local_50);
          local_88 = FUN_00426d40((int *)(iVar3 + 0x2c));
          for (local_8c = 0; local_8c < local_88; local_8c = local_8c + 1) {
            FUN_00426c20((CSize *)&local_a4);
            uVar7 = local_8c;
            iVar3 = FUN_00426da0(local_40,local_50);
            puVar4 = (undefined4 *)FUN_00426d60((void *)(iVar3 + 0x2c),uVar7);
            local_a4 = *puVar4;
            local_a0 = puVar4[1];
            local_9c = puVar4[2];
            uVar7 = local_8c;
            iVar3 = FUN_00426da0(local_40,local_50);
            iVar3 = FUN_00426d60((void *)(iVar3 + 0x2c),uVar7);
            local_98 = *(undefined4 *)(iVar3 + 0xc);
            local_94 = *(undefined4 *)(iVar3 + 0x10);
            local_90 = *(undefined4 *)(iVar3 + 0x14);
            puVar4 = &local_a4;
            iVar3 = FUN_00427130((undefined4 *)local_c);
            FUN_00426f30((void *)(iVar3 + 0x20),puVar4);
          }
        }
        else {
          iVar3 = FUN_00426da0(local_40,local_34);
          local_80 = FUN_00426d40((int *)(iVar3 + 0x2c));
          FUN_00426c20((CSize *)&local_7c);
          local_84 = local_80;
          while (local_84 = local_84 + -1, local_84 != 0) {
            iVar3 = local_84;
            iVar19 = FUN_00426da0(local_40,local_34);
            puVar4 = (undefined4 *)FUN_00426d60((void *)(iVar19 + 0x2c),iVar3);
            local_7c = *puVar4;
            local_78 = puVar4[1];
            local_74 = puVar4[2];
            puVar20 = local_144;
            iVar3 = local_84;
            iVar19 = FUN_00426da0(local_40,local_34);
            iVar3 = FUN_00426d60((void *)(iVar19 + 0x2c),iVar3);
            puVar4 = (undefined4 *)FUN_00413650((void *)(iVar3 + 0xc),puVar20);
            local_70 = *puVar4;
            local_6c = puVar4[1];
            local_68 = puVar4[2];
            puVar4 = &local_7c;
            iVar3 = FUN_00427130((undefined4 *)local_c);
            FUN_00426f30((void *)(iVar3 + 0x20),puVar4);
          }
          iVar19 = 0;
          iVar3 = FUN_00426da0(local_40,local_34);
          puVar4 = (undefined4 *)FUN_00426d60((void *)(iVar3 + 0x2c),iVar19);
          local_7c = *puVar4;
          local_78 = puVar4[1];
          local_74 = puVar4[2];
          puVar20 = local_150;
          iVar19 = 0;
          iVar3 = FUN_00426da0(local_40,local_34);
          iVar3 = FUN_00426d60((void *)(iVar3 + 0x2c),iVar19);
          puVar4 = (undefined4 *)FUN_00413650((void *)(iVar3 + 0xc),puVar20);
          local_70 = *puVar4;
          local_6c = puVar4[1];
          local_68 = puVar4[2];
          puVar4 = &local_7c;
          iVar3 = FUN_00427130((undefined4 *)local_c);
          FUN_00426f30((void *)(iVar3 + 0x20),puVar4);
        }
        iVar3 = FUN_00427130((undefined4 *)local_c);
        *(undefined4 *)(iVar3 + 0x2c) = 0;
        iVar3 = FUN_00427130((undefined4 *)local_c);
        local_54 = (float *)FUN_00427130((undefined4 *)(iVar3 + 0x20));
        while( true ) {
          pfVar12 = local_54 + 6;
          iVar3 = FUN_00427130((undefined4 *)local_c);
          pfVar9 = (float *)FUN_004b9c00(iVar3 + 0x20);
          if (pfVar12 == pfVar9) break;
          iVar3 = FUN_00427130((undefined4 *)local_c);
          pvVar5 = FUN_00418750(local_15c,local_54 + 6,local_54);
          fVar14 = (float10)FUN_004136f0(pvVar5);
          *(float *)(iVar3 + 0x2c) = (float)(fVar14 + (float10)*(float *)(iVar3 + 0x2c));
          local_54 = local_54 + 6;
        }
        FUN_00427010(param_2,(int *)local_c);
        FUN_00427080(local_18);
        FUN_00427010(local_18,(int *)local_c);
        local_160 = (undefined4 *)FUN_00478523(0x30);
        if (local_160 == (undefined4 *)0x0) {
          local_1a4 = (undefined4 *)0x0;
        }
        else {
          local_1a4 = FUN_00426ad0(local_160);
        }
        FUN_00426e30(local_c,(int)local_1a4);
        iVar3 = FUN_00427130((undefined4 *)local_c);
        *(uint *)(iVar3 + 4) = *param_4 + 1;
        *param_4 = *(uint *)(iVar3 + 4);
        if (local_50 == local_28) break;
        FUN_00426c00((CDialogTemplate *)local_5c);
        CDialogTemplate::~CDialogTemplate((CDialogTemplate *)local_60);
        local_50 = local_34;
      }
      FUN_00426c00((CDialogTemplate *)local_5c);
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)local_60);
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)local_2c);
    }
    local_1c = local_1c + 1;
  } while( true );
}



================================================================================
REQUESTED 004511b0
ENTRY 004511b0
NAME FUN_004511b0
SIGNATURE undefined __fastcall FUN_004511b0(void * param_1)
BODY [[004511b0, 00451da9]]


void __fastcall FUN_004511b0(void *param_1)

{
  int iVar1;
  undefined *puVar2;
  undefined4 *puVar3;
  int *piVar4;
  int *piVar5;
  shared_ptr<class___ExceptionPtr> *psVar6;
  undefined4 uVar7;
  uint uVar8;
  void *pvVar9;
  undefined4 extraout_ECX;
  undefined4 extraout_ECX_00;
  undefined4 extraout_ECX_01;
  undefined4 extraout_ECX_02;
  undefined4 extraout_ECX_03;
  undefined4 extraout_ECX_04;
  undefined4 extraout_ECX_05;
  undefined4 extraout_ECX_06;
  undefined4 extraout_ECX_07;
  undefined4 uVar10;
  CDialogTemplate *pCVar11;
  undefined1 uVar12;
  uint uVar13;
  char cVar14;
  undefined4 uVar15;
  undefined4 *local_1a8;
  undefined4 *local_18c;
  int local_178 [3];
  CDialogTemplate local_16c [20];
  CDialogTemplate local_158 [7];
  CSize local_151 [5];
  int local_14c [3];
  CDialogTemplate local_140 [8];
  CDialogTemplate local_138 [4];
  undefined4 *local_134;
  CDialogTemplate local_12c [8];
  int local_124 [3];
  CDialogTemplate local_118 [4];
  int local_114 [2];
  CDialogTemplate local_10c [8];
  int local_104 [3];
  CDialogTemplate local_f8 [4];
  int local_f4 [2];
  CDialogTemplate local_ec [8];
  int local_e4 [3];
  CDialogTemplate local_d8 [4];
  int local_d4 [2];
  CDialogTemplate local_cc [8];
  int local_c4 [3];
  CDialogTemplate local_b8 [4];
  int local_b4 [2];
  CDialogTemplate local_ac [8];
  int local_a4 [3];
  CDialogTemplate local_98 [4];
  int local_94 [2];
  CDialogTemplate local_8c [8];
  int local_84 [3];
  CDialogTemplate local_78 [4];
  int local_74;
  int local_70 [4];
  undefined4 *local_60;
  CDialogTemplate local_58 [4];
  int local_54 [6];
  int local_3c [3];
  uint local_30;
  shared_ptr<class___ExceptionPtr> local_2c [4];
  int local_28;
  CDialogTemplate local_24 [4];
  CDialogTemplate local_20 [4];
  int local_1c [6];
  
  FUN_00469690(&stack0xfffffe44,(int *)&stack0x00000004);
  FUN_0044d460(param_1);
  FUN_00427130((undefined4 *)&stack0x00000004);
  local_28 = __RTDynamicCast();
  FUN_0040c210((void *)((int)param_1 + 0xc4),(int *)(local_28 + 0x24));
  local_60 = (undefined4 *)FUN_00478523(0x78);
  if (local_60 == (undefined4 *)0x0) {
    local_18c = (undefined4 *)0x0;
  }
  else {
    local_18c = FUN_00424010(local_60);
  }
  FUN_0044bde0((void *)((int)param_1 + 0xcc),(int)local_18c);
  FUN_00469690(&stack0xfffffe44,(int *)(local_28 + 0x14));
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0xcc));
  FUN_004240f0(iVar1);
  cVar14 = '\x01';
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x4c));
  FUN_0045b690(&stack0xfffffe44,iVar1,cVar14);
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0xcc));
  FUN_00453fc0(iVar1);
  FUN_0045b5d0(&stack0xfffffe44,(undefined4 *)((int)param_1 + 0xcc));
  puVar2 = FUN_0042af90();
  FUN_0042bb70((int)puVar2);
  FUN_0040cd80(local_70,L"");
  FUN_00461c90((int *)(local_28 + 8),local_70,0x11);
  FUN_0040dab0(local_70);
  FUN_004b30e0((undefined4 *)local_2c);
  FUN_0040cd80(&local_74,L"kart");
  piVar4 = &local_74;
  pCVar11 = local_78;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar11,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar15 = 0x766177;
  uVar7 = extraout_ECX;
  FUN_0040cd80(&stack0xfffffe3c,L"motor");
  piVar5 = (int *)FUN_0040c190(local_84,uVar7,uVar15);
  FID_conflict_operator_(&stack0xfffffe3c,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_8c);
  CDialogTemplate::~CDialogTemplate(local_78);
  FUN_0040c020(local_84);
  FUN_0040dab0(&local_74);
  FUN_00469690(&stack0xfffffe34,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x124) = uVar7;
  uVar13 = 3;
  uVar8 = *(uint *)((int)param_1 + 0x124);
  puVar2 = FUN_0041e9f0();
  uVar8 = FUN_004da090(puVar2,uVar8,uVar13);
  *(uint *)((int)param_1 + 0x128) = uVar8;
  uVar7 = 0;
  iVar1 = *(int *)((int)param_1 + 0x128);
  puVar2 = FUN_0041e9f0();
  FUN_004dae60(puVar2,iVar1,uVar7);
  iVar1 = *(int *)((int)param_1 + 0x128);
  puVar2 = FUN_0041e9f0();
  FUN_004da4d0(puVar2,iVar1);
  FUN_0040cd80(local_94,L"kart");
  piVar4 = local_94;
  pCVar11 = local_98;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar11,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar15 = 0x766177;
  uVar7 = extraout_ECX_00;
  FUN_0040cd80(&stack0xfffffe2c,L"drift");
  piVar5 = (int *)FUN_0040c190(local_a4,uVar7,uVar15);
  FID_conflict_operator_(&stack0xfffffe2c,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_ac);
  CDialogTemplate::~CDialogTemplate(local_98);
  FUN_0040c020(local_a4);
  FUN_0040dab0(local_94);
  FUN_00469690(&stack0xfffffe24,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x130) = uVar7;
  *(undefined1 *)((int)param_1 + 0x138) = 0;
  FUN_0040cd80(local_b4,L"kart");
  piVar4 = local_b4;
  pCVar11 = local_b8;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar11,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar15 = 0x766177;
  uVar7 = extraout_ECX_01;
  FUN_0040cd80(&stack0xfffffe1c,L"crash");
  piVar5 = (int *)FUN_0040c190(local_c4,uVar7,uVar15);
  FID_conflict_operator_(&stack0xfffffe1c,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_cc);
  CDialogTemplate::~CDialogTemplate(local_b8);
  FUN_0040c020(local_c4);
  FUN_0040dab0(local_b4);
  FUN_00469690(&stack0xfffffe14,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x13c) = uVar7;
  FUN_0040cd80(local_d4,L"kart");
  piVar4 = local_d4;
  pCVar11 = local_d8;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar11,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar15 = 0x766177;
  uVar7 = extraout_ECX_02;
  FUN_0040cd80(&stack0xfffffe0c,L"shock");
  piVar5 = (int *)FUN_0040c190(local_e4,uVar7,uVar15);
  FID_conflict_operator_(&stack0xfffffe0c,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_ec);
  CDialogTemplate::~CDialogTemplate(local_d8);
  FUN_0040c020(local_e4);
  FUN_0040dab0(local_d4);
  FUN_00469690(&stack0xfffffe04,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x140) = uVar7;
  FUN_0040cd80(local_f4,L"booster");
  piVar4 = local_f4;
  pCVar11 = local_f8;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420520(puVar2,pCVar11,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar15 = 0x766177;
  uVar7 = extraout_ECX_03;
  FUN_0040cd80(&stack0xfffffdfc,L"booster");
  piVar5 = (int *)FUN_0040c190(local_104,uVar7,uVar15);
  FID_conflict_operator_(&stack0xfffffdfc,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_10c);
  CDialogTemplate::~CDialogTemplate(local_f8);
  FUN_0040c020(local_104);
  FUN_0040dab0(local_f4);
  FUN_00469690(&stack0xfffffdf4,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x144) = uVar7;
  FUN_0040cd80(local_114,L"etc");
  piVar4 = local_114;
  pCVar11 = local_118;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar11,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar15 = 0x766177;
  uVar7 = extraout_ECX_04;
  FUN_0040cd80(&stack0xfffffdec,L"wrongway");
  piVar5 = (int *)FUN_0040c190(local_124,uVar7,uVar15);
  FID_conflict_operator_(&stack0xfffffdec,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_12c);
  CDialogTemplate::~CDialogTemplate(local_118);
  FUN_0040c020(local_124);
  FUN_0040dab0(local_114);
  FUN_00469690(&stack0xfffffde4,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x148) = uVar7;
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)local_2c);
  local_30 = 0;
  while( true ) {
    iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    uVar8 = FUN_004496b0((int *)(iVar1 + 0x18));
    if (uVar8 <= local_30) break;
    uVar12 = 1;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + local_30 * 4 + 0x54));
    FUN_00453fa0(pvVar9,uVar12);
    piVar4 = (int *)FUN_00427130((undefined4 *)((int)param_1 + local_30 * 4 + 0x54));
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0xcc));
    FUN_00424530(pvVar9,piVar4);
    local_30 = local_30 + 1;
  }
  *(undefined1 *)((int)param_1 + 0xd0) = 0;
  *(undefined4 *)((int)param_1 + 0xd4) = 0;
  *(undefined4 *)((int)param_1 + 0x110) = 0;
  *(undefined4 *)((int)param_1 + 0x114) = 0;
  *(undefined4 *)((int)param_1 + 0x118) = 0;
  *(undefined4 *)((int)param_1 + 0x11c) = 0;
  *(undefined4 *)((int)param_1 + 0x108) = *(undefined4 *)(local_28 + 0x28);
  *(undefined4 *)((int)param_1 + 0x10c) = 1;
  uVar7 = *(undefined4 *)((int)param_1 + 0x10c);
  pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0xcc));
  FUN_004247e0(pvVar9,uVar7);
  *(undefined4 *)((int)param_1 + 0x14c) = 0;
  *(undefined4 *)((int)param_1 + 0x150) = 0;
  local_134 = (undefined4 *)FUN_00478523(0x174);
  if (local_134 == (undefined4 *)0x0) {
    local_1a8 = (undefined4 *)0x0;
  }
  else {
    local_1a8 = FUN_00497db0(local_134);
  }
  FUN_0044bde0((void *)((int)param_1 + 200),(int)local_1a8);
  piVar4 = (int *)FUN_00427130((undefined4 *)((int)param_1 + 0x44));
  FUN_00469690(&stack0xfffffde4,(int *)((int)param_1 + 200));
  puVar3 = (undefined4 *)(**(code **)(*piVar4 + 0x1c))();
  iVar1 = FUN_00427130(puVar3);
  FUN_00413b10(iVar1);
  CDialogTemplate::~CDialogTemplate(local_138);
  if (*(char *)(local_28 + 0x2c) == '\0') {
    FUN_0044bde0((void *)((int)param_1 + 0xd8),0);
  }
  else {
    pCVar11 = local_140;
    puVar2 = FUN_00449850();
    puVar3 = (undefined4 *)FUN_00462230(puVar2,pCVar11);
    piVar4 = (int *)FUN_00427130(puVar3);
    uVar15 = 0x7331;
    uVar7 = extraout_ECX_05;
    FUN_0040cd80(&stack0xfffffdd8,L"arrow");
    piVar5 = (int *)FUN_0040c190(local_14c,uVar7,uVar15);
    FID_conflict_operator_(&stack0xfffffdd8,piVar5);
    (**(code **)(*piVar4 + 0x3c))();
    CDialogTemplate::~CDialogTemplate(local_140);
    FUN_0040c020(local_14c);
    cVar14 = '\x01';
    iVar1 = FUN_00427130((undefined4 *)local_58);
    FUN_00412d50(local_54,iVar1,cVar14);
    FUN_00412dd0(local_54,(void *)((int)param_1 + 0xd8));
    uVar7 = CSize::CSize(local_151);
    FUN_00401310(local_3c,uVar7);
    FUN_00493460();
    pCVar11 = local_158;
    puVar2 = FUN_00449850();
    piVar4 = (int *)FUN_00462230(puVar2,pCVar11);
    FUN_00438890(local_3c,piVar4);
    CDialogTemplate::~CDialogTemplate(local_158);
    piVar4 = local_3c;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0xd8));
    FUN_004a8e90(pvVar9,piVar4);
    FUN_00469690(&stack0xfffffde0,(int *)((int)param_1 + 0xd8));
    iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 200));
    FUN_00413b10(iVar1);
    *(undefined4 *)((int)param_1 + 0xf8) = 0;
    FUN_00438860(local_3c);
    FUN_00412da0(local_54);
    CDialogTemplate::~CDialogTemplate(local_58);
  }
  FUN_0040cd80(&stack0xfffffde0,L"start");
  iVar1 = FUN_0044fac0((int)param_1);
  FUN_0044ba20(iVar1);
  FUN_0040cd80(&stack0xfffffde0,L"clear");
  iVar1 = FUN_0044fac0((int)param_1);
  FUN_0044ba20(iVar1);
  FUN_0040cd80(&stack0xfffffde0,L"retire");
  iVar1 = FUN_0044fac0((int)param_1);
  FUN_0044ba20(iVar1);
  pCVar11 = local_16c;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_004391a0(puVar2,pCVar11);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar15 = 0x7331;
  uVar7 = extraout_ECX_06;
  FUN_0040cd80(&stack0xfffffdd8,L"readyCamera");
  piVar5 = (int *)FUN_0040c190(local_178,uVar7,uVar15);
  FID_conflict_operator_(&stack0xfffffdd8,piVar5);
  (**(code **)(*piVar4 + 0x3c))();
  CDialogTemplate::~CDialogTemplate(local_16c);
  FUN_0040c020(local_178);
  cVar14 = '\x01';
  iVar1 = FUN_00427130((undefined4 *)local_24);
  FUN_00412d50(local_1c,iVar1,cVar14);
  FUN_004b30e0((undefined4 *)local_20);
  FUN_00412dd0(local_1c,local_20);
  cVar14 = '\x01';
  uVar10 = 0;
  uVar15 = 0;
  uVar7 = extraout_ECX_07;
  FUN_0040cd80(&stack0xfffffdc4,L"KartReCameraman");
  FUN_0044f810(param_1,uVar7,uVar15,uVar10,cVar14);
  uVar7 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
  pvVar9 = (void *)FUN_00453ff0((int)param_1);
  FUN_00497340(pvVar9,uVar7);
  FUN_00469690(&stack0xfffffdd0,(int *)local_20);
  iVar1 = FUN_00453ff0((int)param_1);
  FUN_00445590(iVar1);
  uVar12 = 1;
  pvVar9 = (void *)FUN_00453ff0((int)param_1);
  FUN_004a1ac0(pvVar9,uVar12);
  CDialogTemplate::~CDialogTemplate(local_20);
  FUN_00412da0(local_1c);
  CDialogTemplate::~CDialogTemplate(local_24);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return;
}



