Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00426470
ENTRY 00426470
NAME FUN_00426470
SIGNATURE undefined1 __thiscall FUN_00426470(void * this, int param_1, int * param_2, undefined4 * param_3)
BODY [[00426470, 0042666b]]


undefined1 __thiscall FUN_00426470(void *this,int param_1,int *param_2,undefined4 *param_3)

{
  bool bVar1;
  int *piVar2;
  uint uVar3;
  int iVar4;
  int *piVar5;
  undefined4 *puVar6;
  undefined1 auStack_50 [4];
  undefined4 uStack_4c;
  undefined4 uStack_44;
  int *local_14;
  undefined1 local_9;
  undefined4 *local_8;
  
  piVar2 = (int *)FUN_00426cc0(param_1);
  local_9 = 0;
  *param_3 = 0;
  uVar3 = FUN_00426ce0(piVar2);
  if (uVar3 < 2) {
    local_9 = 0;
  }
  else {
    for (local_8 = (undefined4 *)FUN_00427130(piVar2); iVar4 = FUN_004b9c00((int)piVar2),
        local_8 != (undefined4 *)(iVar4 + -0xc); local_8 = local_8 + 3) {
      for (local_14 = (int *)FUN_00427130((undefined4 *)(*param_2 + 8));
          piVar5 = (int *)FUN_004b9c00(*param_2 + 8), local_14 != piVar5; local_14 = local_14 + 2) {
        uStack_4c = 0x426512;
        FUN_004135d0(&uStack_44,local_8 + 3);
        FUN_004135d0(auStack_50,local_8);
        FUN_004815c0(&stack0xffffffac,local_14);
        iVar4 = FUN_00425fe0();
        if (0 < iVar4) {
          puVar6 = (undefined4 *)((int)this + 0x58);
          iVar4 = FUN_00427130(local_14 + 1);
          uStack_44 = 0x426555;
          bVar1 = FUN_00427c60(iVar4,puVar6);
          if (bVar1) {
            *param_3 = 1;
          }
          else {
            iVar4 = FUN_00427130(local_14);
            if ((*(char *)(iVar4 + 0x58) != '\0') &&
               (iVar4 = FUN_004248e0((int)this), iVar4 == *(int *)((int)this + 0x60))) {
              *param_3 = 1;
            }
          }
          iVar4 = FUN_00427130(local_14 + 1);
          *param_2 = iVar4;
          local_9 = 1;
          goto LAB_004264b3;
        }
      }
      for (local_14 = (int *)FUN_00427130((undefined4 *)(*param_2 + 0x14));
          piVar5 = (int *)FUN_004b9c00(*param_2 + 0x14), local_14 != piVar5; local_14 = local_14 + 2
          ) {
        uStack_4c = 0x4265f3;
        FUN_004135d0(&uStack_44,local_8 + 3);
        FUN_004135d0(auStack_50,local_8);
        FUN_004815c0(&stack0xffffffac,local_14);
        iVar4 = FUN_00425fe0();
        if (iVar4 < 0) {
          uStack_44 = 0x426630;
          bVar1 = FUN_00427c60(*param_2,(undefined4 *)((int)this + 0x58));
          if (bVar1) {
            *param_3 = 0xffffffff;
          }
          iVar4 = FUN_00427130(local_14 + 1);
          *param_2 = iVar4;
          local_9 = 1;
          break;
        }
      }
LAB_004264b3:
    }
  }
  return local_9;
}



