Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004bae10
ENTRY 004bae10
NAME FUN_004bae10
SIGNATURE void * __thiscall FUN_004bae10(void * this, void * param_1, undefined4 * param_2)
BODY [[004bae10, 004bae8c]]


void * __thiscall FUN_004bae10(void *this,void *param_1,undefined4 *param_2)

{
  char cVar1;
  int *piVar2;
  int iVar3;
  void *pvVar4;
  undefined4 *puVar5;
  int *local_8;
  
  local_8 = (int *)FUN_00427130((undefined4 *)((int)this + 0x10));
  while( true ) {
    piVar2 = (int *)FUN_004b9c00((int)this + 0x10);
    if (local_8 == piVar2) {
      FUN_0045b690(param_1,0,'\x01');
      return param_1;
    }
    puVar5 = param_2;
    iVar3 = FUN_00427130(local_8);
    pvVar4 = (void *)FUN_00418620(iVar3);
    cVar1 = FUN_0040f240(pvVar4,puVar5);
    if (cVar1 != '\0') break;
    local_8 = local_8 + 1;
  }
  FUN_00469690(param_1,local_8);
  return param_1;
}



================================================================================
REQUESTED 00427bf0
ENTRY 00427bf0
NAME FUN_00427bf0
SIGNATURE void * __cdecl FUN_00427bf0(void * param_1, undefined4 * param_2)
BODY [[00427bf0, 00427c21]]


void * __cdecl FUN_00427bf0(void *param_1,undefined4 *param_2)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 uVar3;
  TypeDescriptor *pTVar4;
  TypeDescriptor *pTVar5;
  undefined4 uVar6;
  char cVar7;
  
  cVar7 = '\x01';
  uVar6 = 0;
  pTVar5 = &the::ToRoad::RTTI_Type_Descriptor;
  pTVar4 = &the::TrackObject::RTTI_Type_Descriptor;
  uVar3 = 0;
  uVar1 = FUN_00427130(param_2);
  iVar2 = __RTDynamicCast(uVar1,uVar3,pTVar4,pTVar5,uVar6);
  FUN_0045b690(param_1,iVar2,cVar7);
  return param_1;
}



