Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00449550
ENTRY 00449550
NAME FUN_00449550
SIGNATURE undefined __fastcall FUN_00449550(undefined4 param_1)
BODY [[00449550, 00449562]]


void __fastcall FUN_00449550(undefined4 param_1)

{
  _CItan(param_1);
  return;
}



