Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004529d0
ENTRY 004529d0
NAME FUN_004529d0
SIGNATURE undefined __thiscall FUN_004529d0(void * this, uint param_1, int param_2, int param_3, char param_4)
BODY [[004529d0, 00452b93]]


void __thiscall FUN_004529d0(void *this,uint param_1,int param_2,int param_3,char param_4)

{
  void *this_00;
  float10 fVar1;
  float local_20;
  float local_18;
  
  this_00 = (void *)FUN_00427130((undefined4 *)((int)this + param_2 * 4 + 0x50));
  switch(param_3) {
  case 0:
  case 1:
    if (param_4 == '\0') {
      if (((param_3 == 0) && (fVar1 = FUN_00454010((int)this_00), (float10)DAT_00571808 < fVar1)) ||
         ((param_3 == 1 && (fVar1 = FUN_00454010((int)this_00), fVar1 < (float10)DAT_00571808)))) {
        FUN_00431940(this_00,0);
      }
    }
    else if (param_3 == 0) {
      FUN_00431940(this_00,0x3f800000);
    }
    else {
      FUN_00431940(this_00,0xbf800000);
    }
    goto LAB_00452a8d;
  case 2:
    if (param_4 == '\0') {
      local_18 = 0.0;
    }
    else {
      local_18 = 1.0;
    }
    FUN_00431960(this_00,local_18 != DAT_00571808);
    if (((*(int *)((int)this + 0x114) != 0) && (param_1 <= *(int *)((int)this + 0x114) + 100U)) &&
       (*(int *)((int)this + 0x114) - 100U <= param_1)) {
      FUN_00431ab0(this_00,1000);
    }
    break;
  case 3:
    if (param_4 == '\0') {
      local_20 = 0.0;
    }
    else {
      local_20 = 1.0;
    }
    FUN_004319f0(this_00,local_20 != DAT_00571808);
    break;
  case 4:
    *(char *)((int)this + 0xd0) = param_4 != '\0';
LAB_00452a8d:
    if (param_4 == '\0') {
      FUN_00431a30(this_00,'\0');
    }
    else if ((*(char *)((int)this + 0xd0) != '\0') &&
            (fVar1 = FUN_00454010((int)this_00), (float10)DAT_00571808 != fVar1)) {
      FUN_00431a30(this_00,'\x01');
    }
  }
  return;
}



================================================================================
REQUESTED 00457ac0
ENTRY 00457ac0
NAME FUN_00457ac0
SIGNATURE undefined __thiscall FUN_00457ac0(void * this, uint param_1, int param_2, int param_3, char param_4)
BODY [[00457ac0, 00457ce9]]


void __thiscall FUN_00457ac0(void *this,uint param_1,int param_2,int param_3,char param_4)

{
  char cVar1;
  int *this_00;
  void *this_01;
  float10 fVar2;
  int iVar3;
  uint uVar4;
  float local_20;
  float local_18;
  
  this_00 = (int *)FUN_00427130((undefined4 *)((int)this + param_2 * 4 + 0x50));
  switch(param_3) {
  case 0:
  case 1:
    if (param_4 == '\0') {
      if (((param_3 == 0) && (fVar2 = FUN_00454010((int)this_00), (float10)DAT_00571808 < fVar2)) ||
         ((param_3 == 1 && (fVar2 = FUN_00454010((int)this_00), fVar2 < (float10)DAT_00571808)))) {
        FUN_00431940(this_00,0);
      }
    }
    else if (param_3 == 0) {
      FUN_00431940(this_00,0x3f800000);
    }
    else {
      FUN_00431940(this_00,0xbf800000);
    }
    goto LAB_00457b7d;
  case 2:
    if (param_4 == '\0') {
      local_18 = 0.0;
    }
    else {
      local_18 = 1.0;
    }
    FUN_00431960(this_00,local_18 != DAT_00571808);
    if (((*(int *)((int)this + 0xe0) != 0) && (param_1 <= *(int *)((int)this + 0xe0) + 100U)) &&
       (*(int *)((int)this + 0xe0) - 100U <= param_1)) {
      FUN_00431ab0(this_00,1000);
    }
    break;
  case 3:
    if (param_4 == '\0') {
      local_20 = 0.0;
    }
    else {
      local_20 = 1.0;
    }
    FUN_004319f0(this_00,local_20 != DAT_00571808);
  case 5:
    if (((param_4 != '\0') && (cVar1 = (**(code **)(*this_00 + 0x68))(), cVar1 == '\0')) &&
       (*(int *)((int)this + 0xec) != 0)) {
      *(int *)((int)this + 0xec) = *(int *)((int)this + 0xec) + -1;
      FUN_00431ab0(this_00,3000);
      uVar4 = 0xffffffff;
      iVar3 = *(int *)((int)this + 0xec);
      this_01 = (void *)FUN_0044fac0((int)this);
      FUN_00455770(this_01,iVar3,uVar4);
    }
    break;
  case 4:
    *(char *)((int)this + 0xcc) = param_4 != '\0';
LAB_00457b7d:
    if (param_4 == '\0') {
      FUN_00431a30(this_00,'\0');
    }
    else if ((*(char *)((int)this + 0xcc) != '\0') &&
            (fVar2 = FUN_00454010((int)this_00), (float10)DAT_00571808 != fVar2)) {
      FUN_00431a30(this_00,'\x01');
    }
  }
  return;
}



