Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00419820
ENTRY 00419820
NAME FUN_00419820
SIGNATURE undefined __thiscall FUN_00419820(void * this, int * param_1)
BODY [[00419820, 00419c1b]]


void __thiscall FUN_00419820(void *this,int *param_1)

{
  char local_1c;
  char local_1b;
  char local_1a;
  char local_19;
  char local_18;
  char local_17;
  char local_16;
  char local_15;
  char local_14;
  char local_13;
  char local_12;
  char local_11;
  uint local_10;
  uint local_c;
  CDialogTemplate local_8 [4];
  
  FUN_0041a9a0(this,param_1);
  FUN_004014a0(param_1,&local_c);
  FUN_00419c50((void *)((int)this + 0xc),local_c);
  FUN_004b30e0((undefined4 *)local_8);
  for (local_10 = 0; local_10 < local_c; local_10 = local_10 + 1) {
    FUN_00419ce0(param_1,local_8);
    FUN_00469690(&stack0xffffffd8,(int *)local_8);
    FUN_00413b10((int)this);
  }
  CDialogTemplate::~CDialogTemplate(local_8);
  FUN_00419d10(param_1,(int)this + 0x18);
  FUN_00419d50(param_1,(int)this + 0x54);
  FUN_00493b20(param_1,(int)this + 0x6c);
  FUN_00401c50(param_1,(int)this + 0x70,4);
  FUN_00419d50(param_1,(int)this + 0x74);
  FUN_00401c50(param_1,(int)this + 0x8c,4);
  FUN_00493b20(param_1,(int)this + 0x90);
  FUN_0044bde0((void *)((int)this + 0x94),0);
  FUN_00493b20(param_1,&local_11);
  if (local_11 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0x94));
  }
  FUN_0044bde0((void *)((int)this + 0x98),0);
  FUN_00493b20(param_1,&local_12);
  if (local_12 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0x98));
  }
  FUN_0044bde0((void *)((int)this + 0x9c),0);
  FUN_00493b20(param_1,&local_13);
  if (local_13 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0x9c));
  }
  FUN_0044bde0((void *)((int)this + 0xa0),0);
  FUN_00493b20(param_1,&local_14);
  if (local_14 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0xa0));
  }
  FUN_0044bde0((void *)((int)this + 0xa4),0);
  FUN_00493b20(param_1,&local_15);
  if (local_15 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0xa4));
  }
  FUN_0044bde0((void *)((int)this + 0xa8),0);
  FUN_00493b20(param_1,&local_16);
  if (local_16 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0xa8));
  }
  FUN_0044bde0((void *)((int)this + 0xac),0);
  FUN_00493b20(param_1,&local_17);
  if (local_17 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0xac));
  }
  FUN_0044bde0((void *)((int)this + 0xb0),0);
  FUN_00493b20(param_1,&local_18);
  if (local_18 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0xb0));
  }
  FUN_0044bde0((void *)((int)this + 0xb4),0);
  FUN_00493b20(param_1,&local_19);
  if (local_19 != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0xb4));
  }
  FUN_0044bde0((void *)((int)this + 0xb8),0);
  FUN_00493b20(param_1,&local_1a);
  if (local_1a != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0xb8));
  }
  FUN_0044bde0((void *)((int)this + 0xbc),0);
  FUN_00493b20(param_1,&local_1b);
  if (local_1b != '\0') {
    FUN_00419ce0(param_1,(void *)((int)this + 0xbc));
  }
  FUN_0040e9c0((void *)((int)this + 0xc0),0);
  FUN_00493b20(param_1,&local_1c);
  if (local_1c != '\0') {
    FUN_00419c20(param_1,(void *)((int)this + 0xc0));
  }
  FUN_00499c70((int)this);
  return;
}



================================================================================
REQUESTED 0041a9d0
ENTRY 0041a9d0
NAME FUN_0041a9d0
SIGNATURE undefined __thiscall FUN_0041a9d0(void * this, int * param_1)
BODY [[0041a9d0, 0041ae1a]]


void __thiscall FUN_0041a9d0(void *this,int *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  undefined4 *local_c;
  
  FUN_0041b850(this,param_1);
  iVar1 = size((int *)((int)this + 0xc));
  FUN_004066c0(param_1,iVar1);
  local_c = (undefined4 *)FUN_00427130((undefined4 *)((int)this + 0xc));
  while( true ) {
    puVar2 = (undefined4 *)FUN_004b9c00((int)this + 0xc);
    if (local_c == puVar2) break;
    FUN_00495250(param_1,local_c);
    local_c = local_c + 1;
  }
  FUN_0041ae40(param_1,(int)this + 0x18);
  FUN_0041ae80(param_1,(undefined4 *)((int)this + 0x54));
  FUN_00402670(param_1,*(undefined1 *)((int)this + 0x6c));
  FUN_00401ce0(param_1,(int)this + 0x70,4);
  FUN_0041ae80(param_1,(undefined4 *)((int)this + 0x74));
  FUN_00401ce0(param_1,(int)this + 0x8c,4);
  FUN_00402670(param_1,*(undefined1 *)((int)this + 0x90));
  iVar1 = FUN_00417940((int *)((int)this + 0x94));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0x94));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x98));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0x98));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x9c));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0x9c));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xa0));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0xa0));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xa4));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0xa4));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xa8));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0xa8));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xac));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0xac));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xb0));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0xb0));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xb4));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0xb4));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xb8));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0xb8));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xbc));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250(param_1,(undefined4 *)((int)this + 0xbc));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xc0));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_0041ae20(param_1,(undefined4 *)((int)this + 0xc0));
  }
  return;
}



================================================================================
REQUESTED 0041b880
ENTRY 0041b880
NAME FUN_0041b880
SIGNATURE undefined __thiscall FUN_0041b880(void * this, int * param_1)
BODY [[0041b880, 0041bc7b]]


void __thiscall FUN_0041b880(void *this,int *param_1)

{
  char local_1c;
  char local_1b;
  char local_1a;
  char local_19;
  char local_18;
  char local_17;
  char local_16;
  char local_15;
  char local_14;
  char local_13;
  char local_12;
  char local_11;
  uint local_10;
  uint local_c;
  CDialogTemplate local_8 [4];
  
  FUN_0041bfc0(this,param_1);
  FUN_00406820(param_1,&local_c);
  FUN_00419c50((void *)((int)this + 0xc),local_c);
  FUN_004b30e0((undefined4 *)local_8);
  for (local_10 = 0; local_10 < local_c; local_10 = local_10 + 1) {
    FUN_0041bd20(param_1,local_8);
    FUN_00469690(&stack0xffffffd8,(int *)local_8);
    FUN_00413b10((int)this);
  }
  CDialogTemplate::~CDialogTemplate(local_8);
  FUN_0041bcb0(param_1,(undefined4 *)((int)this + 0x18));
  FUN_0041bcf0(param_1,(undefined4 *)((int)this + 0x54));
  FUN_00402690(param_1,(undefined1 *)((int)this + 0x6c));
  FUN_004024a0(param_1,(undefined4 *)((int)this + 0x70),4);
  FUN_0041bcf0(param_1,(undefined4 *)((int)this + 0x74));
  FUN_004024a0(param_1,(undefined4 *)((int)this + 0x8c),4);
  FUN_00402690(param_1,(undefined1 *)((int)this + 0x90));
  FUN_0044bde0((void *)((int)this + 0x94),0);
  FUN_00402690(param_1,&local_11);
  if (local_11 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0x94));
  }
  FUN_0044bde0((void *)((int)this + 0x98),0);
  FUN_00402690(param_1,&local_12);
  if (local_12 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0x98));
  }
  FUN_0044bde0((void *)((int)this + 0x9c),0);
  FUN_00402690(param_1,&local_13);
  if (local_13 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0x9c));
  }
  FUN_0044bde0((void *)((int)this + 0xa0),0);
  FUN_00402690(param_1,&local_14);
  if (local_14 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0xa0));
  }
  FUN_0044bde0((void *)((int)this + 0xa4),0);
  FUN_00402690(param_1,&local_15);
  if (local_15 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0xa4));
  }
  FUN_0044bde0((void *)((int)this + 0xa8),0);
  FUN_00402690(param_1,&local_16);
  if (local_16 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0xa8));
  }
  FUN_0044bde0((void *)((int)this + 0xac),0);
  FUN_00402690(param_1,&local_17);
  if (local_17 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0xac));
  }
  FUN_0044bde0((void *)((int)this + 0xb0),0);
  FUN_00402690(param_1,&local_18);
  if (local_18 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0xb0));
  }
  FUN_0044bde0((void *)((int)this + 0xb4),0);
  FUN_00402690(param_1,&local_19);
  if (local_19 != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0xb4));
  }
  FUN_0044bde0((void *)((int)this + 0xb8),0);
  FUN_00402690(param_1,&local_1a);
  if (local_1a != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0xb8));
  }
  FUN_0044bde0((void *)((int)this + 0xbc),0);
  FUN_00402690(param_1,&local_1b);
  if (local_1b != '\0') {
    FUN_0041bd20(param_1,(void *)((int)this + 0xbc));
  }
  FUN_0040e9c0((void *)((int)this + 0xc0),0);
  FUN_00402690(param_1,&local_1c);
  if (local_1c != '\0') {
    FUN_0041bc80(param_1,(void *)((int)this + 0xc0));
  }
  FUN_00499c70((int)this);
  return;
}



================================================================================
REQUESTED 0041bff0
ENTRY 0041bff0
NAME FUN_0041bff0
SIGNATURE undefined __thiscall FUN_0041bff0(void * this, int * param_1)
BODY [[0041bff0, 0041c43a]]


void __thiscall FUN_0041bff0(void *this,int *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  undefined4 *local_c;
  
  FUN_0041c6b0(this,param_1);
  iVar1 = size((int *)((int)this + 0xc));
  FUN_00406980(param_1,iVar1);
  local_c = (undefined4 *)FUN_00427130((undefined4 *)((int)this + 0xc));
  while( true ) {
    puVar2 = (undefined4 *)FUN_004b9c00((int)this + 0xc);
    if (local_c == puVar2) break;
    FUN_004a03c0(param_1,local_c);
    local_c = local_c + 1;
  }
  FUN_0041c460(param_1,(undefined4 *)((int)this + 0x18));
  FUN_0041c4a0(param_1,(undefined4 *)((int)this + 0x54));
  FUN_00493b40(param_1,*(undefined1 *)((int)this + 0x6c));
  FUN_00402500(param_1,(undefined4 *)((int)this + 0x70),4);
  FUN_0041c4a0(param_1,(undefined4 *)((int)this + 0x74));
  FUN_00402500(param_1,(undefined4 *)((int)this + 0x8c),4);
  FUN_00493b40(param_1,*(undefined1 *)((int)this + 0x90));
  iVar1 = FUN_00417940((int *)((int)this + 0x94));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0x94));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x98));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0x98));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x9c));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0x9c));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xa0));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0xa0));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xa4));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0xa4));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xa8));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0xa8));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xac));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0xac));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xb0));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0xb0));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xb4));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0xb4));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xb8));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0xb8));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xbc));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0(param_1,(undefined4 *)((int)this + 0xbc));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0xc0));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_0041c440(param_1,(undefined4 *)((int)this + 0xc0));
  }
  return;
}



================================================================================
REQUESTED 00428820
ENTRY 00428820
NAME FUN_00428820
SIGNATURE undefined4 * __fastcall FUN_00428820(undefined4 * param_1)
BODY [[00428820, 00428a62]]


undefined4 * __fastcall FUN_00428820(undefined4 *param_1)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  CSize local_5;
  
  FUN_0042dcc0(param_1);
  *param_1 = &PTR_FUN_00571824;
  FUN_004b30e0(param_1 + 6);
  FUN_004b30e0(param_1 + 7);
  CSize::CSize((CSize *)(param_1 + 8));
  CSize::CSize((CSize *)(param_1 + 0xb));
  CSize::CSize((CSize *)(param_1 + 0xe));
  CSize::CSize((CSize *)(param_1 + 0x17));
  CSize::CSize((CSize *)(param_1 + 0x1a));
  CSize::CSize((CSize *)(param_1 + 0x1d));
  CSize::CSize((CSize *)(param_1 + 0x20));
  CSize::CSize((CSize *)(param_1 + 0x29));
  FUN_004bf5d0(param_1 + 0x3d);
  FUN_004bf5d0(param_1 + 0x40);
  uVar1 = CSize::CSize(&local_5);
  FUN_00401310(param_1 + 0x42,uVar1);
  FUN_00493460();
  FUN_0044bde0(param_1 + 6,0);
  param_1[0xb] = DAT_005b16cc;
  param_1[0xc] = DAT_005b16d0;
  param_1[0xd] = DAT_005b16d4;
  puVar3 = &DAT_005b17ec;
  puVar4 = param_1 + 0xe;
  for (iVar2 = 9; iVar2 != 0; iVar2 = iVar2 + -1) {
    *puVar4 = *puVar3;
    puVar3 = puVar3 + 1;
    puVar4 = puVar4 + 1;
  }
  param_1[0x17] = DAT_005b16cc;
  param_1[0x18] = DAT_005b16d0;
  param_1[0x19] = DAT_005b16d4;
  param_1[0x1a] = DAT_005b16cc;
  param_1[0x1b] = DAT_005b16d0;
  param_1[0x1c] = DAT_005b16d4;
  param_1[0x1d] = DAT_005b16cc;
  param_1[0x1e] = DAT_005b16d0;
  param_1[0x1f] = DAT_005b16d4;
  puVar3 = &DAT_005b17ec;
  puVar4 = param_1 + 0x20;
  for (iVar2 = 9; iVar2 != 0; iVar2 = iVar2 + -1) {
    *puVar4 = *puVar3;
    puVar3 = puVar3 + 1;
    puVar4 = puVar4 + 1;
  }
  param_1[0x3c] = 0;
  *(undefined1 *)(param_1 + 0x33) = 1;
  *(undefined1 *)((int)param_1 + 0xcd) = 0;
  *(undefined1 *)((int)param_1 + 0xce) = 0;
  param_1[0x34] = 0;
  *(undefined1 *)(param_1 + 0x35) = 0;
  param_1[0x36] = 0;
  *(undefined1 *)(param_1 + 0x37) = 0;
  param_1[0x38] = 0;
  *(undefined1 *)(param_1 + 0x39) = 0;
  *(undefined1 *)((int)param_1 + 0xe5) = 0;
  *(undefined1 *)((int)param_1 + 0xe6) = 0;
  param_1[0x3a] = 0xffffffff;
  param_1[0x3b] = 0;
  *(undefined1 *)(param_1 + 0x46) = 0;
  param_1[0x45] = 0;
  *(undefined1 *)((int)param_1 + 0x119) = 0;
  return param_1;
}



================================================================================
REQUESTED 00428d30
ENTRY 00428d30
NAME FUN_00428d30
SIGNATURE undefined __thiscall FUN_00428d30(void * this, uint param_1)
BODY [[00428d30, 00428f63]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall FUN_00428d30(void *this,uint param_1)

{
  char cVar1;
  undefined4 *puVar2;
  undefined4 *puVar3;
  CSize *pCVar4;
  void *pvVar5;
  float *pfVar6;
  undefined *puVar7;
  int iVar8;
  float10 fVar9;
  undefined1 uVar10;
  undefined4 *puVar11;
  undefined1 *puVar12;
  undefined1 local_ac [12];
  undefined1 local_a0 [12];
  undefined1 local_94 [12];
  undefined1 local_88 [36];
  undefined1 local_64 [12];
  undefined1 local_58 [60];
  float local_1c;
  float local_18;
  float local_14;
  CSize local_10 [12];
  
  if (*(char *)((int)this + 0x119) != '\0') {
    FUN_004299e0(this,param_1);
  }
  puVar11 = (undefined4 *)&DAT_005b16fc;
  puVar2 = (undefined4 *)
           FUN_00418710(local_64,(float *)((int)this + 0x2c),(float *)((int)this + 0x74));
  puVar3 = (undefined4 *)
           FUN_0042b370(local_88,(float *)((int)this + 0x38),(float *)((int)this + 0x80));
  pCVar4 = FUN_0042b5c0(local_58,puVar3,puVar2,puVar11);
  pvVar5 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
  FUN_00413c50(pvVar5,(undefined4 *)pCVar4);
  if (*(char *)((int)this + 0xcc) == '\0') {
    cVar1 = '\x01' - (param_1 % 200 < 100);
    pvVar5 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
    FUN_0042b8c0(pvVar5,cVar1);
  }
  else {
    uVar10 = 1;
    pvVar5 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
    FUN_0042b8c0(pvVar5,uVar10);
  }
  fVar9 = (float10)FUN_004136f0((int)this + 0x5c);
  *(float *)((int)this + 200) = (float)(fVar9 * (float10)_DAT_00571924);
  if (*(float *)((int)this + 200) == DAT_00571808) {
    puVar2 = (undefined4 *)((int)this + 0x38);
    puVar3 = (undefined4 *)((int)this + 0xa4);
    for (iVar8 = 9; iVar8 != 0; iVar8 = iVar8 + -1) {
      *puVar3 = *puVar2;
      puVar2 = puVar2 + 1;
      puVar3 = puVar3 + 1;
    }
  }
  else {
    CSize::CSize((CSize *)&local_1c);
    CSize::CSize(local_10);
    pfVar6 = (float *)FUN_00413650((void *)((int)this + 0x5c),local_94);
    local_1c = *pfVar6;
    local_18 = pfVar6[1];
    local_14 = pfVar6[2];
    FUN_00413750(&local_1c);
    FUN_0042b330((void *)((int)this + 0x38),2,(undefined4 *)local_10);
    FUN_004285b0((void *)((int)this + 0xa4),1,&local_1c);
    FUN_004285b0((void *)((int)this + 0xa4),2,(undefined4 *)local_10);
    puVar12 = local_ac;
    pvVar5 = FUN_00428490(local_a0,(float *)local_10,&local_1c);
    puVar2 = (undefined4 *)FUN_00413650(pvVar5,puVar12);
    FUN_004285b0((void *)((int)this + 0xa4),0,puVar2);
  }
  puVar7 = FUN_0042af90();
  cVar1 = FUN_0042a2b0((int)puVar7);
  if (cVar1 != '\0') {
    FUN_00428fa0(this,param_1);
  }
  return;
}



