Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00425fe0
ENTRY 00425fe0
NAME FUN_00425fe0
SIGNATURE undefined4 __stdcall FUN_00425fe0(void)
BODY [[00425fe0, 004260d0]]


undefined4 FUN_00425fe0(void)

{
  int iVar1;
  uint uVar2;
  float *pfVar3;
  float *pfVar4;
  undefined4 uVar5;
  float10 fVar6;
  undefined1 local_20 [28];
  
  FUN_00418750(&stack0xffffffc4,(float *)&stack0x00000014,(float *)&stack0x00000008);
  FUN_004135d0(&stack0xffffffb8,(undefined4 *)&stack0x00000008);
  iVar1 = FUN_00427130((undefined4 *)&stack0x00000004);
  uVar2 = FUN_00434b40((float *)(iVar1 + 4));
  if ((uVar2 & 0xff) == 0) {
    FUN_00418750(&stack0xffffffc4,(float *)&stack0x00000014,(float *)&stack0x00000008);
    FUN_004135d0(&stack0xffffffb8,(undefined4 *)&stack0x00000008);
    iVar1 = FUN_00427130((undefined4 *)&stack0x00000004);
    uVar2 = FUN_00434b40((float *)(iVar1 + 0x28));
    if ((uVar2 & 0xff) == 0) {
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
      return 0;
    }
  }
  iVar1 = FUN_00427130((undefined4 *)&stack0x00000004);
  pfVar3 = (float *)(iVar1 + 0x4c);
  pfVar4 = (float *)FUN_00418750(local_20,(float *)&stack0x00000014,(float *)&stack0x00000008);
  fVar6 = FUN_00428460(pfVar4,pfVar3);
  if (fVar6 < (float10)DAT_00571808) {
    CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
    uVar5 = 0xffffffff;
  }
  else {
    CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
    uVar5 = 1;
  }
  return uVar5;
}



