Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 0040f810
ENTRY 0040f810
NAME FUN_0040f810
SIGNATURE undefined4 __fastcall FUN_0040f810(int param_1)
BODY [[0040f810, 0040fac4]]


undefined4 __fastcall FUN_0040f810(int param_1)

{
  undefined *this;
  undefined4 *puVar1;
  int *piVar2;
  int *piVar3;
  int iVar4;
  void *pvVar5;
  undefined4 extraout_EAX;
  undefined4 extraout_ECX;
  CDialogTemplate *pCVar6;
  long lVar7;
  undefined4 uVar8;
  undefined4 uVar9;
  int local_58;
  int local_54;
  int local_50;
  int local_4c;
  int local_48;
  int local_44;
  int local_40;
  int local_3c [3];
  int local_30 [3];
  CDialogTemplate local_24 [4];
  CDialogTemplate local_20 [4];
  CDialogTemplate local_1c [4];
  undefined4 *local_18;
  undefined4 *local_14;
  CDialogTemplate local_10 [4];
  int local_c;
  CDialogTemplate local_8 [4];
  
  FUN_0040fb60();
  pCVar6 = local_24;
  this = FUN_0040ec80();
  puVar1 = (undefined4 *)FUN_0040fb40(this,pCVar6);
  piVar2 = (int *)FUN_00427130(puVar1);
  uVar9 = 0x6c6d78;
  uVar8 = extraout_ECX;
  FUN_0040cd80(&stack0xffffff90,L"colortable");
  piVar3 = (int *)FUN_0040c190(local_30,uVar8,uVar9);
  FID_conflict_operator_(&stack0xffffff90,piVar3);
  (**(code **)(*piVar2 + 0x3c))();
  CDialogTemplate::~CDialogTemplate(local_24);
  FUN_0040c020(local_30);
  FUN_00469690(&stack0xffffff88,(int *)local_8);
  FUN_0047bac0(local_10);
  iVar4 = FUN_00427130((undefined4 *)local_10);
  local_14 = (undefined4 *)FUN_0047b3a0(iVar4);
  local_c = 0;
  local_18 = (undefined4 *)FUN_00427130(local_14);
  while( true ) {
    puVar1 = (undefined4 *)FUN_004b9c00((int)local_14);
    if (local_18 == puVar1) break;
    FUN_0040cd80(local_3c,L"base");
    piVar2 = local_3c;
    pCVar6 = local_20;
    pvVar5 = (void *)FUN_00427130(local_18);
    FUN_0047b1a0(pvVar5,pCVar6,piVar2);
    FUN_0040dab0(local_3c);
    FUN_0040cd80(&local_40,L"high");
    piVar2 = &local_40;
    pCVar6 = local_1c;
    pvVar5 = (void *)FUN_00427130(local_18);
    FUN_0047b1a0(pvVar5,pCVar6,piVar2);
    FUN_0040dab0(&local_40);
    FUN_0040cd80(&local_44,L"r");
    lVar7 = 0;
    piVar2 = &local_44;
    pvVar5 = (void *)FUN_00427130((undefined4 *)local_20);
    lVar7 = FUN_0047a650(pvVar5,piVar2,lVar7);
    *(char *)(param_1 + 2 + local_c * 4) = (char)lVar7;
    FUN_0040dab0(&local_44);
    FUN_0040cd80(&local_48,L"g");
    lVar7 = 0;
    piVar2 = &local_48;
    pvVar5 = (void *)FUN_00427130((undefined4 *)local_20);
    lVar7 = FUN_0047a650(pvVar5,piVar2,lVar7);
    *(char *)(param_1 + 1 + local_c * 4) = (char)lVar7;
    FUN_0040dab0(&local_48);
    FUN_0040cd80(&local_4c,L"b");
    lVar7 = 0;
    piVar2 = &local_4c;
    pvVar5 = (void *)FUN_00427130((undefined4 *)local_20);
    lVar7 = FUN_0047a650(pvVar5,piVar2,lVar7);
    *(char *)(param_1 + local_c * 4) = (char)lVar7;
    FUN_0040dab0(&local_4c);
    *(undefined1 *)(param_1 + 3 + local_c * 4) = 0xff;
    FUN_0040cd80(&local_50,L"r");
    lVar7 = 0;
    piVar2 = &local_50;
    pvVar5 = (void *)FUN_00427130((undefined4 *)local_1c);
    lVar7 = FUN_0047a650(pvVar5,piVar2,lVar7);
    *(char *)(param_1 + 0x102 + local_c * 4) = (char)lVar7;
    FUN_0040dab0(&local_50);
    FUN_0040cd80(&local_54,L"g");
    lVar7 = 0;
    piVar2 = &local_54;
    pvVar5 = (void *)FUN_00427130((undefined4 *)local_1c);
    lVar7 = FUN_0047a650(pvVar5,piVar2,lVar7);
    *(char *)(param_1 + 0x101 + local_c * 4) = (char)lVar7;
    FUN_0040dab0(&local_54);
    FUN_0040cd80(&local_58,L"b");
    lVar7 = 0;
    piVar2 = &local_58;
    pvVar5 = (void *)FUN_00427130((undefined4 *)local_1c);
    lVar7 = FUN_0047a650(pvVar5,piVar2,lVar7);
    *(char *)(param_1 + 0x100 + local_c * 4) = (char)lVar7;
    FUN_0040dab0(&local_58);
    *(undefined1 *)(param_1 + 0x103 + local_c * 4) = 0xff;
    CDialogTemplate::~CDialogTemplate(local_1c);
    CDialogTemplate::~CDialogTemplate(local_20);
    local_18 = local_18 + 1;
    local_c = local_c + 1;
  }
  CDialogTemplate::~CDialogTemplate(local_10);
  CDialogTemplate::~CDialogTemplate(local_8);
  return CONCAT31((int3)((uint)extraout_EAX >> 8),1);
}



================================================================================
REQUESTED 00464e90
ENTRY 00464e90
NAME FUN_00464e90
SIGNATURE undefined __thiscall FUN_00464e90(void * this, undefined4 param_1, undefined4 * param_2, undefined4 param_3)
BODY [[00464e90, 0046501e]]


void __thiscall FUN_00464e90(void *this,undefined4 param_1,undefined4 *param_2,undefined4 param_3)

{
  void *pvVar1;
  uint uVar2;
  undefined1 *puVar3;
  int *piVar4;
  undefined4 *puVar5;
  int *piVar6;
  undefined4 *puVar7;
  undefined4 uVar8;
  long lVar9;
  int local_38 [2];
  int local_30;
  char local_29;
  int local_28;
  int local_24;
  char local_1d;
  int local_1c;
  int local_18 [2];
  int local_10;
  char local_9;
  
  puVar5 = param_2;
  puVar7 = param_2;
  uVar8 = param_3;
  FUN_004815c0(&stack0xffffffb8,&param_1);
  FUN_00463320(this,puVar5,puVar7,uVar8);
  FUN_0040cd80(&local_10,L"kart");
  piVar4 = &local_10;
  pvVar1 = (void *)FUN_00427130(&param_1);
  uVar2 = FUN_0047a360(pvVar1,piVar4);
  local_9 = (char)uVar2;
  FUN_0040dab0(&local_10);
  if (local_9 != '\0') {
    FUN_0040cd80(local_18,L"burst1");
    FUN_0040cd80(&local_1c,L"kart");
    puVar3 = &stack0xffffffc0;
    piVar4 = local_18;
    piVar6 = &local_1c;
    pvVar1 = (void *)FUN_00427130(&param_1);
    FUN_0047a7f0(pvVar1,puVar3,piVar6,piVar4);
    FUN_00464b20((int)this);
    FUN_0040dab0(&local_1c);
    FUN_0040dab0(local_18);
  }
  FUN_0040cd80(&local_24,L"kartColor");
  piVar4 = &local_24;
  pvVar1 = (void *)FUN_00427130(&param_1);
  uVar2 = FUN_0047a360(pvVar1,piVar4);
  local_1d = (char)uVar2;
  FUN_0040dab0(&local_24);
  if (local_1d != '\0') {
    FUN_0040cd80(&local_28,L"kartColor");
    lVar9 = 0;
    piVar4 = &local_28;
    pvVar1 = (void *)FUN_00427130(&param_1);
    lVar9 = FUN_0047a650(pvVar1,piVar4,lVar9);
    FUN_00464b90(this,lVar9);
    FUN_0040dab0(&local_28);
  }
  FUN_0040cd80(&local_30,L"kartRect");
  piVar4 = &local_30;
  pvVar1 = (void *)FUN_00427130(&param_1);
  uVar2 = FUN_0047a360(pvVar1,piVar4);
  local_29 = (char)uVar2;
  FUN_0040dab0(&local_30);
  if (local_29 != '\0') {
    FUN_0040cd80(local_38,L"kartRect");
    puVar3 = &stack0xffffffb4;
    puVar5 = &DAT_005b195c;
    piVar4 = local_38;
    pvVar1 = (void *)FUN_00427130(&param_1);
    FUN_0047b060(pvVar1,puVar3,piVar4,puVar5);
    FUN_00464be0((int)this);
    FUN_0040dab0(local_38);
  }
  FUN_00464c50((int)this);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_1);
  return;
}



================================================================================
REQUESTED 00428ad0
ENTRY 00428ad0
NAME FUN_00428ad0
SIGNATURE undefined __fastcall FUN_00428ad0(int param_1)
BODY [[00428ad0, 00428c3f]]


void __fastcall FUN_00428ad0(int param_1)

{
  void *pvVar1;
  int *piVar2;
  int *piVar3;
  int *piVar4;
  long lVar5;
  int local_28;
  int local_24;
  int local_20;
  int local_1c;
  int local_18;
  int local_14;
  int local_10;
  int local_c;
  int local_8;
  
  FUN_0040cd80(&local_8,L"burst1");
  FUN_0040cd80(&local_c,L"kartName");
  piVar2 = &local_8;
  piVar4 = &local_c;
  piVar3 = &local_10;
  pvVar1 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
  piVar2 = (int *)FUN_0047a7f0(pvVar1,piVar3,piVar4,piVar2);
  FUN_0040c210((void *)(param_1 + 0xf4),piVar2);
  FUN_0040dab0(&local_10);
  FUN_0040dab0(&local_c);
  FUN_0040dab0(&local_8);
  FUN_0040cd80(&local_14,L"kartColor");
  lVar5 = 0;
  piVar2 = &local_14;
  pvVar1 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
  lVar5 = FUN_0047a650(pvVar1,piVar2,lVar5);
  *(long *)(param_1 + 0xf8) = lVar5;
  FUN_0040dab0(&local_14);
  FUN_0040cd80(&local_18,L"kartNumber");
  lVar5 = 9;
  piVar2 = &local_18;
  pvVar1 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
  lVar5 = FUN_0047a650(pvVar1,piVar2,lVar5);
  *(long *)(param_1 + 0xfc) = lVar5;
  FUN_0040dab0(&local_18);
  FUN_0040cd80(&local_1c,L"dao");
  FUN_0040cd80(&local_20,L"characterName");
  piVar2 = &local_1c;
  piVar4 = &local_20;
  piVar3 = &local_24;
  pvVar1 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
  piVar2 = (int *)FUN_0047a7f0(pvVar1,piVar3,piVar4,piVar2);
  FUN_0040c210((void *)(param_1 + 0x100),piVar2);
  FUN_0040dab0(&local_24);
  FUN_0040dab0(&local_20);
  FUN_0040dab0(&local_1c);
  FUN_0040cd80(&local_28,L"characterColor");
  lVar5 = 0;
  piVar2 = &local_28;
  pvVar1 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
  lVar5 = FUN_0047a650(pvVar1,piVar2,lVar5);
  *(long *)(param_1 + 0x104) = lVar5;
  FUN_0040dab0(&local_28);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000008);
  return;
}



