Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00416ff0
ENTRY 00416ff0
NAME FUN_00416ff0
SIGNATURE undefined __cdecl FUN_00416ff0(undefined4 param_1, undefined4 param_2, undefined4 param_3)
BODY [[00416ff0, 0041715f]]


void __cdecl FUN_00416ff0(undefined4 param_1,undefined4 param_2,uint param_3)

{
  int iVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  uint local_2c;
  byte *local_28;
  int local_24;
  uint local_20;
  byte *local_c;
  int local_8;
  
  iVar1 = FUN_00427130(&param_2);
  local_8 = FUN_00418a60(iVar1);
  iVar1 = FUN_00427130(&param_1);
  local_c = (byte *)FUN_00418a60(iVar1);
  iVar1 = FUN_00427130(&param_2);
  iVar1 = FUN_004abcc0(iVar1);
  iVar2 = FUN_00427130(&param_1);
  iVar2 = FUN_004abcc0(iVar2);
  iVar3 = FUN_00427130(&param_2);
  uVar4 = FUN_004b9c00(iVar3);
  iVar3 = FUN_00427130(&param_2);
  uVar5 = FUN_004b0640(iVar3);
  for (local_20 = 0; local_20 < uVar5; local_20 = local_20 + 1) {
    local_24 = local_8;
    local_28 = local_c;
    for (local_2c = 0; local_2c < uVar4; local_2c = local_2c + 1) {
      uVar6 = (uint)*(byte *)(local_24 + 3);
      iVar3 = 0xff - uVar6;
      local_28[2] = (byte)((uint)local_28[2] * iVar3 + (param_3 >> 0x10 & 0xff) * uVar6 >> 8);
      local_28[1] = (byte)((uint)local_28[1] * iVar3 + (param_3 >> 8 & 0xff) * uVar6 >> 8);
      *local_28 = (byte)((uint)*local_28 * iVar3 + (param_3 & 0xff) * uVar6 >> 8);
      local_28[3] = 0xff;
      local_28 = local_28 + 4;
      local_24 = local_24 + 4;
    }
    local_8 = local_8 + iVar1;
    local_c = local_c + iVar2;
  }
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_1);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_2);
  return;
}



================================================================================
REQUESTED 004a6eb0
ENTRY 004a6eb0
NAME FUN_004a6eb0
SIGNATURE void * __cdecl FUN_004a6eb0(void * param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5)
BODY [[004a6eb0, 004a7402]]


/* WARNING: Variable defined which should be unmapped: param_1 */

void * __cdecl
FUN_004a6eb0(void *param_1,undefined4 param_2,undefined4 param_3,uint param_4,uint param_5)

{
  void *pvVar1;
  int *piVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  undefined1 *puVar6;
  undefined1 local_94 [12];
  undefined1 local_88 [4];
  undefined1 local_84 [4];
  uint local_80;
  uint local_7c;
  uint local_78;
  uint local_74;
  uint local_70;
  uint local_6c;
  uint local_68;
  uint local_64;
  uint local_60;
  uint local_5c;
  uint local_58;
  uint local_54;
  byte *local_50;
  byte *local_4c;
  undefined1 *local_48;
  uint local_44;
  int local_40;
  int local_3c;
  uint local_38;
  uint local_34;
  uint local_30;
  uint local_2c;
  uint local_28;
  uint local_24;
  byte *local_20;
  uint local_1c;
  CDialogTemplate local_18 [4];
  undefined1 *local_14;
  byte *local_10;
  int local_c;
  uint local_8;
  
  puVar6 = local_84;
  pvVar1 = (void *)FUN_00427130(&param_2);
  piVar2 = (int *)FUN_00418a40(pvVar1,puVar6);
  iVar3 = FUN_004a41e0(piVar2);
  iVar4 = FUN_004a41e0(&DAT_005b283c);
  if (iVar3 == iVar4) {
    puVar6 = local_88;
    pvVar1 = (void *)FUN_00427130(&param_3);
    piVar2 = (int *)FUN_00418a40(pvVar1,puVar6);
    iVar3 = FUN_004a41e0(piVar2);
    iVar4 = FUN_004a41e0(&DAT_005b283c);
    if (iVar3 == iVar4) {
      iVar3 = FUN_00427130(&param_2);
      iVar3 = FUN_004b9c00(iVar3);
      iVar4 = FUN_00427130(&param_3);
      iVar4 = FUN_004b9c00(iVar4);
      if (iVar3 == iVar4) {
        iVar3 = FUN_00427130(&param_2);
        iVar3 = FUN_004b0640(iVar3);
        iVar4 = FUN_00427130(&param_3);
        iVar4 = FUN_004b0640(iVar4);
        if (iVar3 == iVar4) {
          iVar3 = FUN_00427130(&param_2);
          local_30 = FUN_004b9c00(iVar3);
          iVar3 = FUN_00427130(&param_2);
          local_2c = FUN_004b0640(iVar3);
          FUN_00418970(&stack0xffffff64,&DAT_005b283c);
          FUN_00465200(local_18,local_30,local_2c);
          iVar3 = FUN_00427130(&param_2);
          local_20 = (byte *)FUN_00418a60(iVar3);
          iVar3 = FUN_00427130(&param_3);
          local_10 = (byte *)FUN_00418a60(iVar3);
          iVar3 = FUN_00427130((undefined4 *)local_18);
          local_14 = (undefined1 *)FUN_00418a60(iVar3);
          iVar3 = FUN_00427130(&param_2);
          local_40 = FUN_004abcc0(iVar3);
          iVar3 = FUN_00427130(&param_3);
          local_c = FUN_004abcc0(iVar3);
          iVar3 = FUN_00427130((undefined4 *)local_18);
          local_3c = FUN_004abcc0(iVar3);
          local_1c = param_4 >> 0x10 & 0xff;
          local_8 = param_4 >> 8 & 0xff;
          local_28 = param_4 & 0xff;
          local_38 = param_5 >> 0x10 & 0xff;
          local_34 = param_5 >> 8 & 0xff;
          local_24 = param_5 & 0xff;
          for (local_44 = 0; local_44 < local_2c; local_44 = local_44 + 1) {
            local_4c = local_20;
            local_50 = local_10;
            local_48 = local_14;
            for (local_54 = 0; local_54 < local_30; local_54 = local_54 + 1) {
              local_74 = (uint)local_4c[3];
              local_64 = (uint)local_4c[2];
              local_5c = (uint)local_4c[1];
              local_60 = (uint)*local_4c;
              local_58 = (uint)local_50[3];
              local_80 = (uint)local_50[2];
              uVar5 = (uint)local_50[1];
              local_7c = (uint)*local_50;
              local_70 = uVar5;
              if (((local_80 == 0xff) && (uVar5 == 0)) && (local_7c == 0xff)) {
                FUN_00418970(&stack0xffffff64,(undefined4 *)&DAT_005b18f0);
                FUN_004187d0(local_48,local_94,uVar5);
              }
              else {
                if (((local_64 < 0x80) && (local_5c < 0x80)) && (local_60 < 0x80)) {
                  local_78 = ((0xff - local_74) * local_1c) / 0xff + (local_64 * local_74) / 0xff;
                  if (0xff < local_78) {
                    local_78 = 0xff;
                  }
                  local_6c = ((0xff - local_74) * local_8) / 0xff + (local_5c * local_74) / 0xff;
                  if (0xff < local_6c) {
                    local_6c = 0xff;
                  }
                  local_68 = ((0xff - local_74) * local_28) / 0xff + (local_60 * local_74) / 0xff;
                  if (0xff < local_68) {
                    local_68 = 0xff;
                  }
                }
                else {
                  local_78 = ((0xff - local_74) * local_1c) / 0xff + (local_38 * local_74) / 0xff;
                  if (0xff < local_78) {
                    local_78 = 0xff;
                  }
                  local_6c = ((0xff - local_74) * local_8) / 0xff + (local_34 * local_74) / 0xff;
                  if (0xff < local_6c) {
                    local_6c = 0xff;
                  }
                  local_68 = ((0xff - local_74) * local_28) / 0xff + (local_24 * local_74) / 0xff;
                  if (0xff < local_68) {
                    local_68 = 0xff;
                  }
                }
                local_78 = ((0xff - local_58) * local_78) / 0xff + (local_80 * local_58) / 0xff;
                if (0xff < local_78) {
                  local_78 = 0xff;
                }
                local_6c = ((0xff - local_58) * local_6c) / 0xff + (uVar5 * local_58) / 0xff;
                if (0xff < local_6c) {
                  local_6c = 0xff;
                }
                local_68 = ((0xff - local_58) * local_68) / 0xff + (local_7c * local_58) / 0xff;
                if (0xff < local_68) {
                  local_68 = 0xff;
                }
                local_48[2] = (undefined1)local_78;
                local_48[1] = (undefined1)local_6c;
                *local_48 = (undefined1)local_68;
                local_48[3] = 0xff;
              }
              local_4c = local_4c + 4;
              local_50 = local_50 + 4;
              local_48 = local_48 + 4;
            }
            local_20 = local_20 + local_40;
            local_10 = local_10 + local_c;
            local_14 = local_14 + local_3c;
          }
          FUN_004815c0(param_1,(int *)local_18);
          CDialogTemplate::~CDialogTemplate(local_18);
          CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_2);
          CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_3);
          return param_1;
        }
      }
    }
  }
  FUN_0049bbe0(param_1,0,'\x01');
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_2);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&param_3);
  return param_1;
}



================================================================================
REQUESTED 004a6120
ENTRY 004a6120
NAME FUN_004a6120
SIGNATURE undefined1 __stdcall FUN_004a6120(void)
BODY [[004a6120, 004a6775]]


undefined1 FUN_004a6120(void)

{
  bool bVar1;
  char cVar2;
  int iVar3;
  int iVar4;
  void *pvVar5;
  int *piVar6;
  undefined4 *puVar7;
  int extraout_ECX;
  uint uVar8;
  int extraout_ECX_00;
  int extraout_ECX_01;
  int extraout_ECX_02;
  int extraout_ECX_03;
  undefined4 *puVar9;
  undefined1 *puVar10;
  undefined1 *puVar11;
  undefined1 local_e4 [8];
  undefined1 local_dc [7];
  undefined1 local_d5;
  undefined1 local_c8 [16];
  undefined1 local_b8 [16];
  undefined1 local_a8 [4];
  undefined1 local_a4 [4];
  undefined1 local_a0 [8];
  undefined1 local_98 [4];
  undefined1 local_94 [4];
  undefined1 local_90 [8];
  undefined1 local_88 [4];
  undefined1 local_84 [4];
  undefined1 local_80 [4];
  undefined1 local_7c [4];
  undefined1 local_78 [4];
  undefined1 local_74 [4];
  undefined1 local_70 [8];
  undefined1 local_68 [7];
  undefined1 local_61;
  uint local_60;
  uint local_5c;
  int local_58;
  int local_54;
  int local_50;
  int local_4c;
  int local_48;
  int local_44;
  CSize local_40 [4];
  uint local_3c;
  int local_38;
  uint local_34;
  int local_30;
  undefined4 *local_2c;
  undefined4 *local_28;
  uint local_24;
  int local_20;
  uint local_1c;
  int local_18;
  undefined4 *local_14;
  undefined4 *local_10;
  uint local_c;
  uint local_8;
  
  iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
  iVar3 = FUN_004b9c00(iVar3);
  iVar4 = FUN_00427130((undefined4 *)&stack0x00000008);
  iVar4 = FUN_004b9c00(iVar4);
  if (iVar3 == iVar4) {
    iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
    iVar3 = FUN_004b0640(iVar3);
    iVar4 = FUN_00427130((undefined4 *)&stack0x00000008);
    iVar4 = FUN_004b0640(iVar4);
    if (iVar3 == iVar4) {
      iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
      local_c = FUN_004b9c00(iVar3);
      iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
      local_8 = FUN_004b0640(iVar3);
      puVar10 = &stack0xffffff00;
      iVar3 = extraout_ECX;
      pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
      FUN_00418a40(pvVar5,puVar10);
      puVar10 = local_68;
      pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
      pvVar5 = FUN_00418a40(pvVar5,puVar10);
      bVar1 = FUN_00418800(pvVar5,iVar3);
      if (bVar1) {
        puVar10 = local_70;
        pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
        piVar6 = (int *)FUN_00418a40(pvVar5,puVar10);
        cVar2 = FUN_004a1fd0(piVar6);
        if (cVar2 == '\0') {
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000008);
          local_10 = (undefined4 *)FUN_00418a60(iVar3);
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
          local_14 = (undefined4 *)FUN_00418a60(iVar3);
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000008);
          local_18 = FUN_004abcc0(iVar3);
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
          local_20 = FUN_004abcc0(iVar3);
          puVar10 = local_74;
          pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
          puVar7 = (undefined4 *)FUN_00418a40(pvVar5,puVar10);
          iVar3 = FUN_00418990(puVar7);
          iVar4 = FUN_00427130((undefined4 *)&stack0x00000004);
          iVar4 = FUN_004b9c00(iVar4);
          local_1c = iVar3 * iVar4;
          for (local_24 = 0; local_24 < local_8; local_24 = local_24 + 1) {
            puVar7 = local_10;
            puVar9 = local_14;
            for (uVar8 = local_1c >> 2; uVar8 != 0; uVar8 = uVar8 - 1) {
              *puVar9 = *puVar7;
              puVar7 = puVar7 + 1;
              puVar9 = puVar9 + 1;
            }
            for (uVar8 = local_1c & 3; uVar8 != 0; uVar8 = uVar8 - 1) {
              *(undefined1 *)puVar9 = *(undefined1 *)puVar7;
              puVar7 = (undefined4 *)((int)puVar7 + 1);
              puVar9 = (undefined4 *)((int)puVar9 + 1);
            }
            local_10 = (undefined4 *)((int)local_10 + local_18);
            local_14 = (undefined4 *)((int)local_14 + local_20);
          }
        }
        else {
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000008);
          local_28 = (undefined4 *)FUN_00418a60(iVar3);
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
          local_2c = (undefined4 *)FUN_00418a60(iVar3);
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000008);
          local_30 = FUN_004abcc0(iVar3);
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
          local_38 = FUN_004abcc0(iVar3);
          puVar10 = local_78;
          pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
          puVar7 = (undefined4 *)FUN_00418a40(pvVar5,puVar10);
          iVar3 = FUN_00418990(puVar7);
          iVar4 = FUN_00427130((undefined4 *)&stack0x00000004);
          uVar8 = FUN_004b9c00(iVar4);
          local_34 = iVar3 * (uVar8 >> 2);
          for (local_3c = 0; local_3c < local_8 >> 2; local_3c = local_3c + 1) {
            puVar7 = local_28;
            puVar9 = local_2c;
            for (uVar8 = local_34 >> 2; uVar8 != 0; uVar8 = uVar8 - 1) {
              *puVar9 = *puVar7;
              puVar7 = puVar7 + 1;
              puVar9 = puVar9 + 1;
            }
            for (uVar8 = local_34 & 3; uVar8 != 0; uVar8 = uVar8 - 1) {
              *(undefined1 *)puVar9 = *(undefined1 *)puVar7;
              puVar7 = (undefined4 *)((int)puVar7 + 1);
              puVar9 = (undefined4 *)((int)puVar9 + 1);
            }
            local_28 = (undefined4 *)((int)local_28 + local_30);
            local_2c = (undefined4 *)((int)local_2c + local_38);
          }
        }
LAB_004a6753:
        CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
        CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000008);
        return 1;
      }
      puVar10 = local_7c;
      pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
      piVar6 = (int *)FUN_00418a40(pvVar5,puVar10);
      cVar2 = FUN_004a1fd0(piVar6);
      if (cVar2 == '\0') {
        puVar10 = local_80;
        pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
        piVar6 = (int *)FUN_00418a40(pvVar5,puVar10);
        cVar2 = FUN_004a1fd0(piVar6);
        if (cVar2 == '\0') {
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000008);
          local_48 = FUN_00418a60(iVar3);
          iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
          local_50 = FUN_00418a60(iVar3);
          puVar10 = local_84;
          pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
          puVar7 = (undefined4 *)FUN_00418a40(pvVar5,puVar10);
          local_54 = FUN_00418990(puVar7);
          puVar10 = local_88;
          pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
          puVar7 = (undefined4 *)FUN_00418a40(pvVar5,puVar10);
          local_44 = FUN_00418990(puVar7);
          CSize::CSize(local_40);
          for (local_5c = 0; local_5c < local_8; local_5c = local_5c + 1) {
            local_58 = local_48;
            local_4c = local_50;
            for (local_60 = 0; local_60 < local_c; local_60 = local_60 + 1) {
              puVar11 = &stack0xffffff00;
              puVar10 = local_90;
              iVar3 = local_58;
              uVar8 = local_60;
              pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
              pvVar5 = FUN_00418a40(pvVar5,puVar10);
              FUN_004189b0(pvVar5,puVar11,iVar3);
              FUN_004187d0(local_40,local_94,uVar8);
              FUN_00418970(&stack0xffffff00,(undefined4 *)local_40);
              puVar10 = local_98;
              iVar3 = local_4c;
              pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
              FUN_00418a40(pvVar5,puVar10);
              FUN_004651d0(iVar3);
              local_58 = local_58 + local_54;
              local_4c = local_4c + local_44;
            }
            iVar3 = FUN_00427130((undefined4 *)&stack0x00000008);
            iVar3 = FUN_004abcc0(iVar3);
            local_48 = iVar3 + local_48;
            iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
            iVar3 = FUN_004abcc0(iVar3);
            local_50 = iVar3 + local_50;
          }
          goto LAB_004a6753;
        }
      }
      puVar10 = local_a0;
      pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
      piVar6 = (int *)FUN_00418a40(pvVar5,puVar10);
      cVar2 = FUN_004a1fd0(piVar6);
      iVar3 = extraout_ECX_00;
      if (cVar2 != '\0') {
        puVar10 = local_a4;
        pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
        piVar6 = (int *)FUN_00418a40(pvVar5,puVar10);
        cVar2 = FUN_004a1fd0(piVar6);
        iVar3 = extraout_ECX_01;
        if (cVar2 == '\0') {
          FUN_00418970(&stack0xffffff00,(undefined4 *)&DAT_005b28cc);
          puVar10 = local_a8;
          pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
          pvVar5 = FUN_00418a40(pvVar5,puVar10);
          bVar1 = FUN_00418800(pvVar5,iVar3);
          uVar8 = (uint)bVar1;
          if (uVar8 == 0) {
            FUN_00418970(&stack0xffffff00,(undefined4 *)&DAT_005b28e4);
            puVar10 = local_b8;
            pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
            pvVar5 = FUN_00418a40(pvVar5,puVar10);
            bVar1 = FUN_00418800(pvVar5,uVar8);
            if (bVar1) {
              FUN_004815c0(&stack0xffffff00,(int *)&stack0x00000008);
              FUN_004815c0(&stack0xfffffefc,(int *)&stack0x00000004);
              FUN_004a6b10();
            }
            else {
              iVar3 = extraout_ECX_02;
              FUN_00418970(&stack0xffffff00,(undefined4 *)&DAT_005b28fc);
              puVar10 = local_c8;
              pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
              pvVar5 = FUN_00418a40(pvVar5,puVar10);
              bVar1 = FUN_00418800(pvVar5,iVar3);
              if (!bVar1) {
                local_d5 = 0;
                CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
                CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000008);
                return local_d5;
              }
              FUN_004815c0(&stack0xffffff00,(int *)&stack0x00000008);
              FUN_004815c0(&stack0xfffffefc,(int *)&stack0x00000004);
              FUN_004a6c50();
            }
          }
          else {
            FUN_004815c0(&stack0xffffff00,(int *)&stack0x00000008);
            FUN_004815c0(&stack0xfffffefc,(int *)&stack0x00000004);
            FUN_004a6920();
          }
          goto LAB_004a6753;
        }
      }
      FUN_00418970(&stack0xffffff00,(undefined4 *)&DAT_005b28cc);
      puVar10 = local_dc;
      pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000008);
      pvVar5 = FUN_00418a40(pvVar5,puVar10);
      bVar1 = FUN_00418800(pvVar5,iVar3);
      if (bVar1) {
        iVar3 = extraout_ECX_03;
        FUN_00418970(&stack0xffffff00,(undefined4 *)&DAT_005b28e4);
        puVar10 = local_e4;
        pvVar5 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
        pvVar5 = FUN_00418a40(pvVar5,puVar10);
        bVar1 = FUN_00418800(pvVar5,iVar3);
        if (bVar1) {
          FUN_004815c0(&stack0xffffff00,(int *)&stack0x00000008);
          FUN_004815c0(&stack0xfffffefc,(int *)&stack0x00000004);
          FUN_004a6d90();
          goto LAB_004a6753;
        }
      }
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000008);
      return 0;
    }
  }
  local_61 = 0;
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000008);
  return local_61;
}



================================================================================
REQUESTED 004194a0
ENTRY 004194a0
NAME FUN_004194a0
SIGNATURE void * __thiscall FUN_004194a0(void * this, void * param_1)
BODY [[004194a0, 004194c0]]


void * __thiscall FUN_004194a0(void *this,void *param_1)

{
  FUN_004815c0(param_1,(int *)((int)this + 0x240));
  return param_1;
}



================================================================================
REQUESTED 00419500
ENTRY 00419500
NAME FUN_00419500
SIGNATURE void * __thiscall FUN_00419500(void * this, void * param_1)
BODY [[00419500, 00419520]]


void * __thiscall FUN_00419500(void *this,void *param_1)

{
  FUN_004815c0(param_1,(int *)((int)this + 0x244));
  return param_1;
}



================================================================================
REQUESTED 004194d0
ENTRY 004194d0
NAME FUN_004194d0
SIGNATURE undefined __fastcall FUN_004194d0(int param_1)
BODY [[004194d0, 004194f6]]


void __fastcall FUN_004194d0(int param_1)

{
  std::shared_ptr<class___ExceptionPtr>::operator=
            ((shared_ptr<class___ExceptionPtr> *)(param_1 + 0x240),
             (shared_ptr<class___ExceptionPtr> *)&stack0x00000004);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return;
}



================================================================================
REQUESTED 00419530
ENTRY 00419530
NAME FUN_00419530
SIGNATURE undefined __fastcall FUN_00419530(int param_1)
BODY [[00419530, 00419556]]


void __fastcall FUN_00419530(int param_1)

{
  std::shared_ptr<class___ExceptionPtr>::operator=
            ((shared_ptr<class___ExceptionPtr> *)(param_1 + 0x244),
             (shared_ptr<class___ExceptionPtr> *)&stack0x00000004);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return;
}



