Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004193e0
ENTRY 004193e0
NAME FUN_004193e0
SIGNATURE void * __thiscall FUN_004193e0(void * this, void * param_1)
BODY [[004193e0, 00419400]]


void * __thiscall FUN_004193e0(void *this,void *param_1)

{
  FUN_004815c0(param_1,(int *)((int)this + 0x238));
  return param_1;
}



================================================================================
REQUESTED 00419440
ENTRY 00419440
NAME FUN_00419440
SIGNATURE void * __thiscall FUN_00419440(void * this, void * param_1)
BODY [[00419440, 00419460]]


void * __thiscall FUN_00419440(void *this,void *param_1)

{
  FUN_004815c0(param_1,(int *)((int)this + 0x23c));
  return param_1;
}



================================================================================
REQUESTED 004194a0
ENTRY 004194a0
NAME FUN_004194a0
SIGNATURE void * __thiscall FUN_004194a0(void * this, void * param_1)
BODY [[004194a0, 004194c0]]


void * __thiscall FUN_004194a0(void *this,void *param_1)

{
  FUN_004815c0(param_1,(int *)((int)this + 0x240));
  return param_1;
}



================================================================================
REQUESTED 00419500
ENTRY 00419500
NAME FUN_00419500
SIGNATURE void * __thiscall FUN_00419500(void * this, void * param_1)
BODY [[00419500, 00419520]]


void * __thiscall FUN_00419500(void *this,void *param_1)

{
  FUN_004815c0(param_1,(int *)((int)this + 0x244));
  return param_1;
}



================================================================================
REQUESTED 004195c0
ENTRY 004195c0
NAME FUN_004195c0
SIGNATURE void * __thiscall FUN_004195c0(void * this, void * param_1)
BODY [[004195c0, 004195e0]]


void * __thiscall FUN_004195c0(void *this,void *param_1)

{
  FUN_00418970(param_1,(undefined4 *)((int)this + 0x24c));
  return param_1;
}



================================================================================
REQUESTED 00419560
ENTRY 00419560
NAME FUN_00419560
SIGNATURE void * __thiscall FUN_00419560(void * this, void * param_1)
BODY [[00419560, 00419580]]


void * __thiscall FUN_00419560(void *this,void *param_1)

{
  FUN_00418970(param_1,(undefined4 *)((int)this + 0x248));
  return param_1;
}



