Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 0040fb80
ENTRY 0040fb80
NAME FUN_0040fb80
SIGNATURE CSize * __fastcall FUN_0040fb80(CSize * param_1)
BODY [[0040fb80, 0040fc4e]]


CSize * __fastcall FUN_0040fb80(CSize *param_1)

{
  ulong uVar1;
  
  CSize::CSize(param_1);
  FUN_004bf5d0(param_1 + 0x10);
  FUN_004bf5d0(param_1 + 0x14);
  *param_1 = (CSize)0x1;
  *(undefined4 *)(param_1 + 4) = 0x13;
  uVar1 = inet_addr("211.218.235.32");
  *(ulong *)(param_1 + 8) = uVar1;
  *(undefined4 *)(param_1 + 8) = *(undefined4 *)(param_1 + 8);
  *(undefined2 *)(param_1 + 0xc) = 0x9471;
  param_1[0x18] = (CSize)0x0;
  *(undefined4 *)(param_1 + 0x1c) = 800;
  *(undefined4 *)(param_1 + 0x20) = 600;
  *(undefined4 *)(param_1 + 0x24) = 0x20;
  *(undefined4 *)(param_1 + 0x28) = 0;
  param_1[0x2c] = (CSize)0x0;
  param_1[0x2d] = (CSize)0x0;
  param_1[0x2e] = (CSize)0x0;
  param_1[0x2f] = (CSize)0x0;
  param_1[0x30] = (CSize)0x0;
  param_1[0x31] = (CSize)0x0;
  *(undefined4 *)(param_1 + 0x34) = 0x3f800000;
  *(undefined4 *)(param_1 + 0x38) = 0x3f800000;
  return param_1;
}



================================================================================
REQUESTED 0040fc50
ENTRY 0040fc50
NAME FUN_0040fc50
SIGNATURE undefined4 __fastcall FUN_0040fc50(int param_1)
BODY [[0040fc50, 004102e8]]


undefined4 __fastcall FUN_0040fc50(int param_1)

{
  int iVar1;
  void *pvVar2;
  undefined4 uVar3;
  undefined4 *puVar4;
  wchar_t *pwVar5;
  char *cp;
  ulong uVar6;
  uint uVar7;
  long lVar8;
  int *piVar9;
  undefined4 extraout_EAX;
  float10 fVar10;
  CDialogTemplate *pCVar11;
  int *piVar12;
  float fVar13;
  int local_ac;
  int local_a8;
  int local_a4;
  int local_a0;
  int local_9c;
  char local_95;
  int local_94;
  int local_90;
  int local_8c;
  int local_88;
  int local_84;
  int local_80;
  int local_7c;
  int local_78;
  int local_74;
  int local_70;
  int local_6c;
  int local_68;
  char local_61;
  int local_60;
  int local_5c;
  int local_58;
  int local_54;
  int local_50;
  int local_4c;
  char local_45;
  int local_44;
  int local_40;
  int local_3c;
  int local_38;
  int local_34;
  int local_30;
  char local_29;
  int local_24;
  CDialogTemplate local_20 [4];
  CDialogTemplate local_1c [4];
  CDialogTemplate local_18 [4];
  int local_14;
  CDialogTemplate local_10 [4];
  CDialogTemplate local_c [4];
  CDialogTemplate local_8 [4];
  
  FUN_0040cd80(&local_24,L"config.xml");
  FUN_0047cfe0(local_8,&local_24,1);
  FUN_0040dab0(&local_24);
  iVar1 = FUN_00417940((int *)local_8);
  if (iVar1 != -1) {
    FUN_00469690(&stack0xffffff48,(int *)local_8);
    FUN_0047bac0(local_c);
    FUN_0040cd80(&local_30,L"server");
    piVar9 = &local_30;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    local_29 = (char)uVar3;
    FUN_0040dab0(&local_30);
    if (local_29 != '\0') {
      FUN_0040cd80(&local_34,L"server");
      piVar9 = &local_34;
      pCVar11 = local_10;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
      FUN_0047b1a0(pvVar2,pCVar11,piVar9);
      FUN_0040dab0(&local_34);
      FUN_0040cd80(&local_38,L"ip");
      piVar9 = &local_38;
      piVar12 = &local_3c;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_10);
      puVar4 = (undefined4 *)FUN_0047a2b0(pvVar2,piVar12,piVar9);
      pwVar5 = (wchar_t *)FUN_004d2be0(puVar4);
      FUN_0040da90(&local_14,pwVar5);
      FUN_0040dab0(&local_3c);
      FUN_0040dab0(&local_38);
      cp = (char *)FUN_004d2be0(&local_14);
      uVar6 = inet_addr(cp);
      *(ulong *)(param_1 + 8) = uVar6;
      FUN_0040cd80(&local_40,L"port");
      uVar7 = (uint)*(ushort *)(param_1 + 0xc);
      piVar9 = &local_40;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_10);
      lVar8 = FUN_0047a650(pvVar2,piVar9,uVar7);
      *(short *)(param_1 + 0xc) = (short)lVar8;
      FUN_0040dab0(&local_40);
      FUN_0040dab0(&local_14);
      CDialogTemplate::~CDialogTemplate(local_10);
    }
    FUN_0040cd80(&local_44,L"iamsam");
    piVar9 = &local_44;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    *(char *)(param_1 + 0x18) = (char)uVar3;
    FUN_0040dab0(&local_44);
    FUN_0040cd80(&local_4c,L"login");
    piVar9 = &local_4c;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    local_45 = (char)uVar3;
    FUN_0040dab0(&local_4c);
    if (local_45 != '\0') {
      FUN_0040cd80(&local_50,L"login");
      piVar9 = &local_50;
      pCVar11 = local_18;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
      FUN_0047b1a0(pvVar2,pCVar11,piVar9);
      FUN_0040dab0(&local_50);
      FUN_0040cd80(&local_54,L"id");
      piVar9 = &local_54;
      piVar12 = &local_58;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_18);
      piVar9 = (int *)FUN_0047a2b0(pvVar2,piVar12,piVar9);
      FUN_0040c210((void *)(param_1 + 0x10),piVar9);
      FUN_0040dab0(&local_58);
      FUN_0040dab0(&local_54);
      FUN_0040cd80(&local_5c,L"password");
      piVar9 = &local_5c;
      piVar12 = &local_60;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_18);
      piVar9 = (int *)FUN_0047a2b0(pvVar2,piVar12,piVar9);
      FUN_0040c210((void *)(param_1 + 0x14),piVar9);
      FUN_0040dab0(&local_60);
      FUN_0040dab0(&local_5c);
      CDialogTemplate::~CDialogTemplate(local_18);
    }
    FUN_0040cd80(&local_68,L"screen");
    piVar9 = &local_68;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    local_61 = (char)uVar3;
    FUN_0040dab0(&local_68);
    if (local_61 != '\0') {
      FUN_0040cd80(&local_6c,L"screen");
      piVar9 = &local_6c;
      pCVar11 = local_1c;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
      FUN_0047b1a0(pvVar2,pCVar11,piVar9);
      FUN_0040dab0(&local_6c);
      FUN_0040cd80(&local_70,L"width");
      lVar8 = *(long *)(param_1 + 0x1c);
      piVar9 = &local_70;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_1c);
      lVar8 = FUN_0047a650(pvVar2,piVar9,lVar8);
      *(long *)(param_1 + 0x1c) = lVar8;
      FUN_0040dab0(&local_70);
      FUN_0040cd80(&local_74,L"height");
      lVar8 = *(long *)(param_1 + 0x20);
      piVar9 = &local_74;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_1c);
      lVar8 = FUN_0047a650(pvVar2,piVar9,lVar8);
      *(long *)(param_1 + 0x20) = lVar8;
      FUN_0040dab0(&local_74);
      FUN_0040cd80(&local_78,L"depth");
      lVar8 = *(long *)(param_1 + 0x24);
      piVar9 = &local_78;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_1c);
      lVar8 = FUN_0047a650(pvVar2,piVar9,lVar8);
      *(long *)(param_1 + 0x24) = lVar8;
      FUN_0040dab0(&local_78);
      FUN_0040cd80(&local_7c,L"adapter");
      lVar8 = *(long *)(param_1 + 0x28);
      piVar9 = &local_7c;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_1c);
      lVar8 = FUN_0047a650(pvVar2,piVar9,lVar8);
      *(long *)(param_1 + 0x28) = lVar8;
      FUN_0040dab0(&local_7c);
      CDialogTemplate::~CDialogTemplate(local_1c);
    }
    FUN_0040cd80(&local_80,L"datapackOff");
    piVar9 = &local_80;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    *(char *)(param_1 + 0x2c) = (char)uVar3;
    FUN_0040dab0(&local_80);
    FUN_0040cd80(&local_84,L"fullscreenOff");
    piVar9 = &local_84;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    *(char *)(param_1 + 0x2d) = (char)uVar3;
    FUN_0040dab0(&local_84);
    FUN_0040cd80(&local_88,L"gameinterfaceOff");
    piVar9 = &local_88;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    *(char *)(param_1 + 0x2e) = (char)uVar3;
    FUN_0040dab0(&local_88);
    FUN_0040cd80(&local_8c,L"bgmOff");
    piVar9 = &local_8c;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    *(char *)(param_1 + 0x2f) = (char)uVar3;
    FUN_0040dab0(&local_8c);
    FUN_0040cd80(&local_90,L"effectOff");
    piVar9 = &local_90;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    *(char *)(param_1 + 0x30) = (char)uVar3;
    FUN_0040dab0(&local_90);
    FUN_0040cd80(&local_94,L"adOff");
    piVar9 = &local_94;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    *(char *)(param_1 + 0x31) = (char)uVar3;
    FUN_0040dab0(&local_94);
    FUN_0040cd80(&local_9c,L"volume");
    piVar9 = &local_9c;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    local_95 = (char)uVar3;
    FUN_0040dab0(&local_9c);
    if (local_95 != '\0') {
      FUN_0040cd80(&local_a0,L"volume");
      piVar9 = &local_a0;
      pCVar11 = local_20;
      pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
      FUN_0047b1a0(pvVar2,pCVar11,piVar9);
      FUN_0040dab0(&local_a0);
      FUN_0040cd80(&local_a4,L"bgm");
      fVar13 = *(float *)(param_1 + 0x34);
      piVar9 = &local_a4;
      iVar1 = FUN_00427130((undefined4 *)local_20);
      fVar10 = FUN_0047a720(iVar1,piVar9,fVar13);
      *(float *)(param_1 + 0x34) = (float)fVar10;
      FUN_0040dab0(&local_a4);
      FUN_0040cd80(&local_a8,L"fx");
      fVar13 = *(float *)(param_1 + 0x38);
      piVar9 = &local_a8;
      iVar1 = FUN_00427130((undefined4 *)local_20);
      fVar10 = FUN_0047a720(iVar1,piVar9,fVar13);
      *(float *)(param_1 + 0x38) = (float)fVar10;
      FUN_0040dab0(&local_a8);
      CDialogTemplate::~CDialogTemplate(local_20);
    }
    FUN_0040cd80(&local_ac,L"recordOn");
    piVar9 = &local_ac;
    pvVar2 = (void *)FUN_00427130((undefined4 *)local_c);
    uVar3 = FUN_0047b3c0(pvVar2,piVar9);
    *(char *)(param_1 + 0x3c) = (char)uVar3;
    FUN_0040dab0(&local_ac);
    CDialogTemplate::~CDialogTemplate(local_c);
  }
  FUN_00410300();
  CDialogTemplate::~CDialogTemplate(local_8);
  return CONCAT31((int3)((uint)extraout_EAX >> 8),1);
}



================================================================================
REQUESTED 004103e0
ENTRY 004103e0
NAME FUN_004103e0
SIGNATURE undefined __fastcall FUN_004103e0(void * param_1)
BODY [[004103e0, 00410436]]


void __fastcall FUN_004103e0(void *param_1)

{
  uint uVar1;
  int *piVar2;
  undefined4 local_8;
  
  local_8 = 0;
  while( true ) {
    uVar1 = FUN_004126b0((int *)((int)param_1 + 0x38));
    if (uVar1 <= local_8) break;
    piVar2 = (int *)FUN_004126d0((void *)((int)param_1 + 0x38),local_8);
    if (*piVar2 != 0) {
      FUN_00412090(param_1,local_8);
    }
    local_8 = local_8 + 1;
  }
  return;
}



================================================================================
REQUESTED 00410440
ENTRY 00410440
NAME FUN_00410440
SIGNATURE undefined __fastcall FUN_00410440(int param_1)
BODY [[00410440, 004105fd]]


void __fastcall FUN_00410440(int param_1)

{
  bool bVar1;
  int *piVar2;
  undefined *puVar3;
  int iVar4;
  undefined1 local_28 [4];
  undefined1 local_24 [4];
  undefined1 local_20 [4];
  undefined1 local_1c [4];
  int local_18;
  int local_14;
  int local_10;
  int local_c;
  int local_8;
  
  piVar2 = (int *)FUN_004126d0((void *)(param_1 + 0x38),0);
  local_8 = *piVar2;
  FUN_004a54b0((void *)(param_1 + 0x28),&local_c);
  while( true ) {
    piVar2 = (int *)FUN_004ca260((void *)(param_1 + 0x28),local_20);
    bVar1 = FUN_004178c0(&local_c,piVar2);
    if (!bVar1) break;
    local_10 = FUN_00417d40(&local_c);
    (*(code *)**(undefined4 **)(*(int *)(local_10 + 0xc) + 0x174))();
    FUN_004d0fe0(&local_c,local_1c);
  }
  FUN_004a54b0((void *)(param_1 + 0x2c),&local_14);
  while( true ) {
    piVar2 = (int *)FUN_004ca260((void *)(param_1 + 0x2c),local_28);
    bVar1 = FUN_004178c0(&local_14,piVar2);
    if (!bVar1) break;
    local_18 = FUN_00417d40(&local_14);
    (*(code *)**(undefined4 **)(*(int *)(local_18 + 4) + 0x174))();
    FUN_004d0fe0(&local_14,local_24);
  }
  if (local_8 != 0) {
    puVar3 = FUN_004142e0();
    FUN_004a1c00((int)puVar3);
    if (*(int *)(param_1 + 0x1c) != 0) {
      FUN_00470e20(*(int *)(param_1 + 0x1c));
    }
    if (*(int *)(param_1 + 0x20) != 0) {
      FUN_0046cc50(*(int *)(param_1 + 0x20));
    }
    if (*(int *)(param_1 + 0x24) != 0) {
      FUN_0046e5c0();
    }
    if (*(int *)(param_1 + 0x34) != 0) {
      iVar4 = FUN_004126d0((void *)(param_1 + 0x38),0);
      if (*(char *)(iVar4 + 0x20) == '\0') {
        (*(code *)**(undefined4 **)(*(int *)(param_1 + 0x34) + 0x174))();
      }
    }
    if (*(int *)(param_1 + 0x30) != 0) {
      (*(code *)**(undefined4 **)(*(int *)(param_1 + 0x30) + 0x174))();
    }
    if (*(int *)(param_1 + 0x14) != 0) {
      (*(code *)**(undefined4 **)(*(int *)(param_1 + 0x14) + 0x174))();
    }
  }
  return;
}



================================================================================
REQUESTED 00410630
ENTRY 00410630
NAME FUN_00410630
SIGNATURE undefined __thiscall FUN_00410630(void * this, undefined4 param_1, undefined4 param_2)
BODY [[00410630, 00410674]]


void __thiscall FUN_00410630(void *this,undefined4 param_1,undefined4 param_2)

{
  undefined4 local_2c [8];
  undefined1 local_c;
  undefined1 local_8 [4];
  
  FUN_00412200((int)local_2c);
  local_2c[0] = param_2;
  local_c = 0;
  FUN_0040bb30(local_8,L"");
  FUN_004126f0((void *)((int)this + 0x38),local_2c);
  FUN_00412250((int)local_2c);
  return;
}



================================================================================
REQUESTED 00410850
ENTRY 00410850
NAME FUN_00410850
SIGNATURE undefined __thiscall FUN_00410850(void * this, int param_1)
BODY [[00410850, 0041117a]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall FUN_00410850(void *this,int param_1)

{
  bool bVar1;
  char cVar2;
  undefined4 *puVar3;
  int *piVar4;
  int iVar5;
  float *pfVar6;
  void *pvVar7;
  undefined *puVar8;
  uint uVar9;
  float *pfVar10;
  int *extraout_ECX;
  int *extraout_ECX_00;
  float10 fVar11;
  ulonglong uVar12;
  float fVar13;
  undefined4 uVar14;
  byte bVar15;
  undefined4 *local_158;
  char local_152;
  undefined1 local_151;
  undefined1 local_138 [12];
  undefined1 local_12c [8];
  undefined4 *local_124;
  undefined4 *local_120;
  undefined1 local_11c [4];
  undefined1 local_118 [4];
  undefined1 local_114 [8];
  undefined4 *local_10c;
  undefined4 *local_108;
  undefined1 local_104 [4];
  undefined1 local_100 [4];
  int *local_fc;
  uint local_f8;
  CDialogTemplate local_f4 [4];
  undefined4 local_f0 [15];
  CDialogTemplate local_b4 [4];
  float local_b0 [12];
  float local_80 [3];
  undefined4 local_74;
  undefined4 local_70;
  float local_6c;
  undefined4 *local_68;
  int local_64;
  int *local_60;
  int local_5c;
  float local_58 [9];
  uint local_34;
  int *local_30;
  float local_2c [9];
  float local_8;
  
  local_30 = (int *)FUN_004126d0((void *)((int)this + 0x38),0);
  local_30 = (int *)*local_30;
  fVar11 = FUN_00412340((int)local_30);
  local_8 = (float)fVar11;
  puVar3 = (undefined4 *)FUN_00412300((int)local_30);
  FUN_004137a0(local_2c,puVar3);
  puVar3 = (undefined4 *)FUN_00412320((int)local_30);
  FUN_004137a0(local_58,puVar3);
  FUN_004a54b0((void *)((int)this + 0x28),&local_5c);
  while( true ) {
    piVar4 = (int *)FUN_004ca260((void *)((int)this + 0x28),local_100);
    bVar1 = FUN_004178c0(&local_5c,piVar4);
    if (!bVar1) break;
    local_60 = (int *)FUN_00417d40(&local_5c);
    iVar5 = FUN_00427130(local_60);
    iVar5 = FUN_00413ad0(iVar5);
    if (iVar5 == 0) {
      local_10c = (undefined4 *)local_60[3];
      piVar4 = local_60;
      local_108 = local_10c;
      if (local_10c != (undefined4 *)0x0) {
        (**(code **)*local_10c)();
        piVar4 = extraout_ECX;
      }
      FUN_004a5570(&stack0xfffffea4,&local_5c);
      piVar4 = (int *)FUN_004125a0(local_114,piVar4);
      local_5c = *piVar4;
    }
    else {
      (**(code **)(*(int *)local_60[3] + 0x30))();
      FUN_004d0fe0(&local_5c,local_104);
    }
  }
  FUN_004a54b0((void *)((int)this + 0x2c),&local_64);
  while( true ) {
    piVar4 = (int *)FUN_004ca260((void *)((int)this + 0x2c),local_118);
    bVar1 = FUN_004178c0(&local_64,piVar4);
    if (!bVar1) break;
    local_68 = (undefined4 *)FUN_00417d40(&local_64);
    iVar5 = FUN_00427130(local_68);
    iVar5 = FUN_00413ad0(iVar5);
    if (iVar5 == 0) {
      local_124 = (undefined4 *)local_68[1];
      local_120 = local_124;
      if (local_124 == (undefined4 *)0x0) {
        piVar4 = (int *)0x0;
      }
      else {
        (**(code **)*local_124)();
        piVar4 = extraout_ECX_00;
      }
      FUN_004a5570(&stack0xfffffea4,&local_64);
      piVar4 = (int *)FUN_00412640(local_12c,piVar4);
      local_64 = *piVar4;
    }
    else {
      pfVar6 = (float *)FUN_004122e0((int)local_30);
      FUN_004748c0((void *)local_68[1],param_1,pfVar6);
      FUN_004d0fe0(&local_64,local_11c);
    }
  }
  if (local_30 != (int *)0x0) {
    if (*(int *)((int)this + 0x14) != 0) {
      local_70 = 0xaa;
      local_74 = 0xf0;
      if (local_8 <= _DAT_005710b4) {
        FUN_00474d80(*(int *)((int)this + 0x14));
      }
      else {
        pfVar6 = local_80;
        pvVar7 = (void *)FUN_00412360((int)local_30);
        FUN_00413650(pvVar7,pfVar6);
        puVar8 = FUN_0040c0f0();
        puVar3 = (undefined4 *)FUN_00413a80((int)puVar8);
        FUN_004137d0(local_b0,puVar3);
        FUN_00413800(local_b0,3,0,0,0);
        puVar3 = (undefined4 *)FUN_004138d0(local_138,local_b0,local_80);
        FUN_00412380(*(void **)((int)this + 0x14),puVar3);
        FUN_00474c10(*(void **)((int)this + 0x14),local_8,0xaa,0xf0);
        (**(code **)(**(int **)((int)this + 0x14) + 0x30))();
      }
    }
    if (*(int *)((int)this + 0x20) != 0) {
      cVar2 = (**(code **)(*local_30 + 100))();
      if ((cVar2 == '\0') || (cVar2 = (**(code **)(*local_30 + 0x40))(), cVar2 == '\0')) {
        local_151 = 0;
      }
      else {
        local_151 = 1;
      }
      fVar13 = local_8;
      puVar3 = (undefined4 *)FUN_004122e0((int)local_30);
      FUN_0046cd80(*(void **)((int)this + 0x20),param_1,local_2c,local_58,puVar3,local_151,fVar13);
    }
    if (*(int *)((int)this + 0x1c) != 0) {
      cVar2 = (**(code **)(*local_30 + 100))();
      if (cVar2 == '\0') {
        if (*(char *)((int)this + 0x18) != '\0') {
          FUN_00470b50(*(void **)((int)this + 0x1c),param_1,0);
        }
        *(undefined1 *)((int)this + 0x18) = 0;
      }
      else {
        if (*(char *)((int)this + 0x18) == '\0') {
          FUN_00470b20(*(void **)((int)this + 0x1c),param_1,0);
        }
        *(undefined1 *)((int)this + 0x18) = 1;
      }
      uVar9 = FUN_004123e0(this,2,local_30);
      if (((uVar9 & 0xff) == 0) || (uVar9 = FUN_004123e0(this,3,local_30), (uVar9 & 0xff) == 0)) {
        local_152 = '\0';
      }
      else {
        local_152 = '\x01';
      }
      iVar5 = FUN_00412360((int)local_30);
      fVar11 = (float10)FUN_004136f0(iVar5);
      fVar13 = (float)fVar11;
      puVar3 = (undefined4 *)FUN_004122e0((int)local_30);
      FUN_00470b80(*(void **)((int)this + 0x1c),param_1,local_2c,local_58,puVar3,fVar13,local_152);
    }
    local_6c = 10.0;
    if (*(int *)((int)this + 0x30) != 0) {
      cVar2 = (**(code **)(*local_30 + 0x38))();
      if ((cVar2 != '\0') &&
         (fVar11 = (float10)(**(code **)(*local_30 + 0x3c))(), (float10)local_6c < fVar11)) {
        FUN_0046bc60(*(void **)((int)this + 0x30),param_1);
      }
      (**(code **)(**(int **)((int)this + 0x30) + 0x30))();
    }
    cVar2 = (**(code **)(*local_30 + 0x68))();
    if (cVar2 == '\0') {
      iVar5 = FUN_004126d0((void *)((int)this + 0x38),0);
      if (*(char *)(iVar5 + 0x20) != '\0') {
        FUN_00412090(this,0);
      }
      iVar5 = FUN_004126d0((void *)((int)this + 0x38),0);
      *(undefined1 *)(iVar5 + 0x20) = 0;
    }
    else {
      iVar5 = FUN_004126d0((void *)((int)this + 0x38),0);
      if (*(char *)(iVar5 + 0x20) == '\0') {
        FUN_00411e00(this,0);
      }
      iVar5 = FUN_004126d0((void *)((int)this + 0x38),0);
      *(undefined1 *)(iVar5 + 0x20) = 1;
    }
    if (3000 < (uint)(param_1 - *(int *)((int)this + 0x10))) {
      *(int *)((int)this + 0x10) = param_1;
      iVar5 = FUN_004c53e0((void *)((int)this + 0x44));
      if (iVar5 != 0) {
        FUN_004127c0((int *)((int)this + 0x44));
      }
      FUN_00412ce0((int *)((int)this + 0x44));
    }
    cVar2 = (**(code **)(*local_30 + 0x5c))();
    if ((cVar2 != '\0') && (2000 < (uint)(param_1 - *(int *)((int)this + 0xc)))) {
      puVar3 = (undefined4 *)FUN_00478523(0x174);
      if (puVar3 == (undefined4 *)0x0) {
        local_158 = (undefined4 *)0x0;
      }
      else {
        local_158 = FUN_00497db0(puVar3);
      }
      FUN_0045b690(local_b4,(int)local_158,'\x01');
      iVar5 = FUN_004122c0((int)local_30);
      puVar3 = (undefined4 *)FUN_00413c30(iVar5);
      FUN_00413980(local_f0,puVar3);
      FUN_00469690(&stack0xfffffea4,(int *)local_b4);
      iVar5 = FUN_00427130((undefined4 *)((int)this + 0x48));
      FUN_00413b10(iVar5);
      puVar3 = local_f0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_b4);
      FUN_00413c50(pvVar7,puVar3);
      cVar2 = '\x01';
      piVar4 = FUN_0049a240((undefined4 *)((int)this + 8));
      FUN_0045b690(local_f4,(int)piVar4,cVar2);
      FUN_00469690(&stack0xfffffea4,(int *)local_f4);
      iVar5 = FUN_00427130((undefined4 *)local_b4);
      FUN_00413b10(iVar5);
      FUN_00412790((void *)((int)this + 0x44),(int *)local_b4);
      *(int *)((int)this + 0xc) = param_1;
      bVar15 = 0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_b4);
      FUN_004984d0(pvVar7,bVar15);
      bVar15 = 0;
      uVar14 = 0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_b4);
      FUN_00498b10(pvVar7,uVar14,bVar15);
      iVar5 = FUN_00427130((undefined4 *)local_b4);
      FUN_00498f50(iVar5);
      bVar15 = 0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_f4);
      FUN_004984d0(pvVar7,bVar15);
      bVar15 = 0;
      uVar14 = 0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_f4);
      FUN_00498b10(pvVar7,uVar14,bVar15);
      iVar5 = FUN_00427130((undefined4 *)local_f4);
      FUN_00498f50(iVar5);
      CDialogTemplate::~CDialogTemplate(local_f4);
      CDialogTemplate::~CDialogTemplate(local_b4);
    }
    FUN_0046e5d0(*(void **)((int)this + 0x24),param_1);
    if ((*(int *)((int)this + 0x34) != 0) &&
       (iVar5 = FUN_004126d0((void *)((int)this + 0x38),0), *(char *)(iVar5 + 0x20) == '\0')) {
      uVar12 = FUN_00478a48();
      FUN_004123c0(*(void **)((int)this + 0x34),0x78 - (int)uVar12);
      pfVar6 = (float *)FUN_00412360((int)local_30);
      pfVar10 = (float *)FUN_004122e0((int)local_30);
      FUN_0046f1e0(*(void **)((int)this + 0x34),param_1,local_2c,local_58,pfVar10,pfVar6);
    }
  }
  local_34 = FUN_004126b0((int *)((int)this + 0x38));
  if (1 < local_34) {
    for (local_f8 = 1; local_f8 < local_34; local_f8 = local_f8 + 1) {
      puVar3 = (undefined4 *)FUN_004126d0((void *)((int)this + 0x38),local_f8);
      local_fc = (int *)*puVar3;
      cVar2 = (**(code **)(*local_fc + 0x68))();
      if (cVar2 == '\0') {
        iVar5 = FUN_004126d0((void *)((int)this + 0x38),local_f8);
        if (*(char *)(iVar5 + 0x20) != '\0') {
          FUN_00412090(this,local_f8);
        }
        iVar5 = FUN_004126d0((void *)((int)this + 0x38),local_f8);
        *(undefined1 *)(iVar5 + 0x20) = 0;
      }
      else {
        iVar5 = FUN_004126d0((void *)((int)this + 0x38),local_f8);
        if (*(char *)(iVar5 + 0x20) == '\0') {
          FUN_00411e00(this,local_f8);
        }
        iVar5 = FUN_004126d0((void *)((int)this + 0x38),local_f8);
        *(undefined1 *)(iVar5 + 0x20) = 1;
      }
    }
  }
  return;
}



================================================================================
REQUESTED 004117a0
ENTRY 004117a0
NAME FUN_004117a0
SIGNATURE undefined __fastcall FUN_004117a0(void * param_1)
BODY [[004117a0, 00411984]]


void __fastcall FUN_004117a0(void *param_1)

{
  FUN_0046bd90(*(int *)((int)param_1 + 0x30));
  if ((*(int *)((int)param_1 + 0x14) != 0) &&
     (*(undefined4 **)((int)param_1 + 0x14) != (undefined4 *)0x0)) {
    (**(code **)**(undefined4 **)((int)param_1 + 0x14))(1);
  }
  *(undefined4 *)((int)param_1 + 0x14) = 0;
  if ((*(int *)((int)param_1 + 0x1c) != 0) &&
     (*(undefined4 **)((int)param_1 + 0x1c) != (undefined4 *)0x0)) {
    (**(code **)**(undefined4 **)((int)param_1 + 0x1c))(1);
  }
  *(undefined4 *)((int)param_1 + 0x1c) = 0;
  if ((*(int *)((int)param_1 + 0x30) != 0) &&
     (*(undefined4 **)((int)param_1 + 0x30) != (undefined4 *)0x0)) {
    (**(code **)**(undefined4 **)((int)param_1 + 0x30))(1);
  }
  *(undefined4 *)((int)param_1 + 0x30) = 0;
  if ((*(int *)((int)param_1 + 0x34) != 0) &&
     (*(undefined4 **)((int)param_1 + 0x34) != (undefined4 *)0x0)) {
    (**(code **)**(undefined4 **)((int)param_1 + 0x34))(1);
  }
  *(undefined4 *)((int)param_1 + 0x34) = 0;
  if ((*(int *)((int)param_1 + 0x20) != 0) &&
     (*(undefined4 **)((int)param_1 + 0x20) != (undefined4 *)0x0)) {
    (**(code **)**(undefined4 **)((int)param_1 + 0x20))(1);
  }
  *(undefined4 *)((int)param_1 + 0x20) = 0;
  if ((*(int *)((int)param_1 + 0x24) != 0) && (*(void **)((int)param_1 + 0x24) != (void *)0x0)) {
    FUN_004124b0(*(void **)((int)param_1 + 0x24),1);
  }
  *(undefined4 *)((int)param_1 + 0x24) = 0;
  FUN_004103e0(param_1);
  FUN_0044bde0(param_1,0);
  FUN_0044bde0((void *)((int)param_1 + 4),0);
  FUN_0044bde0((void *)((int)param_1 + 8),0);
  FUN_0044bde0((void *)((int)param_1 + 0x48),0);
  FUN_00412ce0((int *)((int)param_1 + 0x44));
  FUN_00412760((undefined4 *)((int)param_1 + 0x38));
  return;
}



