Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00417160
ENTRY 00417160
NAME FUN_00417160
SIGNATURE undefined __stdcall FUN_00417160(void)
BODY [[00417160, 004174eb]]


void FUN_00417160(void)

{
  bool bVar1;
  void *pvVar2;
  int iVar3;
  undefined4 *puVar4;
  undefined *this;
  undefined4 extraout_ECX;
  undefined4 extraout_ECX_00;
  undefined4 extraout_ECX_01;
  undefined4 extraout_ECX_02;
  uint uVar5;
  undefined4 extraout_ECX_03;
  undefined4 extraout_ECX_04;
  undefined4 extraout_ECX_05;
  undefined4 extraout_ECX_06;
  undefined1 *puVar6;
  undefined1 *puVar7;
  undefined4 uVar8;
  undefined4 uVar9;
  int iVar10;
  CDialogTemplate *pCVar11;
  undefined4 uVar12;
  uint *puVar13;
  int *piVar14;
  undefined4 uVar15;
  undefined4 *local_b4;
  undefined1 local_8c [44];
  CDialogTemplate local_60 [4];
  int local_5c;
  int local_58;
  int local_54;
  int local_50;
  CDialogTemplate local_4c [4];
  uint local_48;
  uint local_44;
  int local_40;
  int local_3c;
  uint local_38;
  void *local_34;
  uint local_30;
  uint local_2c;
  uint local_28;
  int local_24;
  void *local_20;
  CDialogTemplate local_1c [4];
  CDialogTemplate local_18 [4];
  CDialogTemplate local_14 [4];
  CDialogTemplate local_10 [4];
  CDialogTemplate local_c [4];
  CDialogTemplate local_8 [4];
  
  pCVar11 = local_14;
  puVar6 = &stack0xffffff44;
  pvVar2 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
  FUN_004193e0(pvVar2,pCVar11);
  pCVar11 = local_c;
  pvVar2 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
  FUN_00419440(pvVar2,pCVar11);
  pCVar11 = local_8;
  pvVar2 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
  FUN_004194a0(pvVar2,pCVar11);
  pCVar11 = local_18;
  pvVar2 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
  FUN_00419500(pvVar2,pCVar11);
  puVar7 = &stack0xffffff40;
  uVar12 = extraout_ECX;
  pvVar2 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
  FUN_004195c0(pvVar2,puVar6);
  uVar9 = extraout_ECX_00;
  pvVar2 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
  FUN_00419560(pvVar2,puVar7);
  uVar8 = extraout_ECX_01;
  FUN_004815c0(&stack0xffffff3c,(int *)local_c);
  uVar15 = extraout_ECX_02;
  FUN_004815c0(&stack0xffffff38,(int *)local_14);
  FUN_004a6eb0(local_1c,uVar15,uVar8,uVar9,uVar12);
  iVar3 = FUN_00427130((undefined4 *)local_1c);
  local_2c = FUN_004b9c00(iVar3);
  iVar3 = FUN_00427130((undefined4 *)local_1c);
  local_28 = FUN_004b0640(iVar3);
  iVar3 = FUN_00427130((undefined4 *)local_1c);
  local_20 = (void *)FUN_00418a60(iVar3);
  iVar3 = FUN_00427130((undefined4 *)local_1c);
  local_24 = FUN_004abcc0(iVar3);
  for (local_30 = 0; local_30 < local_28; local_30 = local_30 + 1) {
    pvVar2 = local_20;
    for (local_38 = 0; local_34 = pvVar2, local_38 < local_2c; local_38 = local_38 + 1) {
      FUN_00418970(&stack0xffffff44,(undefined4 *)&DAT_005b1924);
      bVar1 = FUN_00418800(local_34,(int)pvVar2);
      uVar5 = (uint)bVar1;
      if (uVar5 == 0) {
        FUN_00418970(&stack0xffffff44,(undefined4 *)&DAT_005b1930);
        bVar1 = FUN_00418800(local_34,uVar5);
        uVar5 = (uint)bVar1;
        if (uVar5 != 0) {
          FUN_00418970(&stack0xffffff44,(undefined4 *)((int)local_34 + 4));
          FUN_004187d0(local_34,local_8c,uVar5);
          local_5c = local_38 - 5;
          local_58 = local_30 - 8;
          local_54 = local_38 + 5;
          iVar3 = local_30 + 9;
          piVar14 = &local_5c;
          local_50 = iVar3;
          FUN_004815c0(&stack0xffffff40,(int *)local_1c);
          FUN_004189e0(local_60,iVar3,piVar14);
          puVar6 = &stack0xffffff44;
          uVar9 = extraout_ECX_03;
          pvVar2 = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
          FUN_00419560(pvVar2,puVar6);
          uVar8 = extraout_ECX_04;
          FUN_004815c0(&stack0xffffff40,(int *)local_8);
          uVar15 = extraout_ECX_05;
          FUN_004815c0(&stack0xffffff3c,(int *)local_60);
          FUN_00416ff0(uVar15,uVar8,uVar9);
          CDialogTemplate::~CDialogTemplate(local_60);
        }
      }
      else {
        local_48 = local_38;
        local_44 = local_30;
        iVar3 = local_38 + 0x2d;
        local_3c = local_30 + 0x14;
        puVar13 = &local_48;
        local_40 = iVar3;
        FUN_004815c0(&stack0xffffff40,(int *)local_1c);
        FUN_004189e0(local_4c,iVar3,(int *)puVar13);
        FUN_004815c0(&stack0xffffff44,(int *)local_18);
        FUN_004815c0(&stack0xffffff40,(int *)local_4c);
        FUN_004a6120();
        CDialogTemplate::~CDialogTemplate(local_4c);
      }
      pvVar2 = (void *)((int)local_34 + 4);
    }
    local_20 = (void *)((int)local_20 + local_24);
  }
  puVar4 = (undefined4 *)FUN_00478523(0x4c);
  if (puVar4 == (undefined4 *)0x0) {
    local_b4 = (undefined4 *)0x0;
  }
  else {
    local_b4 = FUN_00495300(puVar4);
  }
  FUN_0045b690(local_10,(int)local_b4,'\x01');
  puVar6 = &stack0xffffff44;
  iVar10 = 1;
  uVar8 = 0;
  iVar3 = 0;
  uVar15 = extraout_ECX_06;
  FUN_004815c0(&stack0xffffff34,(int *)local_1c);
  this = FUN_0040c0f0();
  FUN_004a4cc0(this,puVar6,uVar15,iVar3,uVar8,iVar10);
  iVar3 = FUN_00427130((undefined4 *)local_10);
  FUN_00413aa0(iVar3);
  uVar15 = 1;
  pvVar2 = (void *)FUN_00427130((undefined4 *)local_10);
  FUN_00497340(pvVar2,uVar15);
  uVar15 = 2;
  pvVar2 = (void *)FUN_00427130((undefined4 *)local_10);
  FUN_0044fdf0(pvVar2,uVar15);
  uVar15 = 0;
  pvVar2 = (void *)FUN_00427130((undefined4 *)local_10);
  FUN_00497360(pvVar2,uVar15);
  FUN_00469690(&stack0xffffff44,(int *)local_10);
  iVar3 = FUN_00427130((undefined4 *)&stack0x00000004);
  FUN_00418f00(iVar3);
  CDialogTemplate::~CDialogTemplate(local_10);
  CDialogTemplate::~CDialogTemplate(local_1c);
  CDialogTemplate::~CDialogTemplate(local_18);
  CDialogTemplate::~CDialogTemplate(local_8);
  CDialogTemplate::~CDialogTemplate(local_c);
  CDialogTemplate::~CDialogTemplate(local_14);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return;
}



