Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00431b70
ENTRY 00431b70
NAME FUN_00431b70
SIGNATURE undefined __stdcall FUN_00431b70(void)
BODY [[00431b70, 00431b7f]]


void FUN_00431b70(void)

{
  return;
}



================================================================================
REQUESTED 00431ba0
ENTRY 00431ba0
NAME FUN_00431ba0
SIGNATURE undefined __fastcall FUN_00431ba0(undefined4 param_1)
BODY [[00431ba0, 00431bb2]]


void __fastcall FUN_00431ba0(undefined4 param_1)

{
  _CIexp(param_1);
  return;
}



================================================================================
REQUESTED 00413730
ENTRY 00413730
NAME FUN_00413730
SIGNATURE undefined __fastcall FUN_00413730(undefined4 param_1)
BODY [[00413730, 00413742]]


void __fastcall FUN_00413730(undefined4 param_1)

{
  _CIsqrt(param_1);
  return;
}



================================================================================
REQUESTED 00428460
ENTRY 00428460
NAME FUN_00428460
SIGNATURE float10 __cdecl FUN_00428460(float * param_1, float * param_2)
BODY [[00428460, 0042848a]]


float10 __cdecl FUN_00428460(float *param_1,float *param_2)

{
  return (float10)param_1[2] * (float10)param_2[2] +
         (float10)param_1[1] * (float10)param_2[1] + (float10)*param_1 * (float10)*param_2;
}



================================================================================
REQUESTED 00428490
ENTRY 00428490
NAME FUN_00428490
SIGNATURE void * __cdecl FUN_00428490(void * param_1, float * param_2, float * param_3)
BODY [[00428490, 004284f5]]


void * __cdecl FUN_00428490(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,param_2[1] * param_3[2] - param_2[2] * param_3[1],
               param_2[2] * *param_3 - *param_2 * param_3[2],
               *param_2 * param_3[1] - param_2[1] * *param_3);
  return param_1;
}



================================================================================
REQUESTED 00428500
ENTRY 00428500
NAME FUN_00428500
SIGNATURE void * __cdecl FUN_00428500(void * param_1, float * param_2)
BODY [[00428500, 00428529]]


void * __cdecl FUN_00428500(void *param_1,float *param_2)

{
  float10 fVar1;
  
  fVar1 = (float10)FUN_004136f0(param_2);
  FUN_00428530(param_1,param_2,(float)fVar1);
  return param_1;
}



================================================================================
REQUESTED 00418680
ENTRY 00418680
NAME FUN_00418680
SIGNATURE float * __thiscall FUN_00418680(void * this, float * param_1)
BODY [[00418680, 004186c2]]


float * __thiscall FUN_00418680(void *this,float *param_1)

{
                    /* WARNING: Load size is inaccurate */
  *(float *)this = *this + *param_1;
  *(float *)((int)this + 4) = *(float *)((int)this + 4) + param_1[1];
  *(float *)((int)this + 8) = *(float *)((int)this + 8) + param_1[2];
  return (float *)this;
}



================================================================================
REQUESTED 00418790
ENTRY 00418790
NAME FUN_00418790
SIGNATURE void * __cdecl FUN_00418790(void * param_1, float * param_2, float param_3)
BODY [[00418790, 004187c5]]


void * __cdecl FUN_00418790(void *param_1,float *param_2,float param_3)

{
  FUN_004135a0(param_1,param_3 * *param_2,param_3 * param_2[1],param_3 * param_2[2]);
  return param_1;
}



================================================================================
REQUESTED 0042d980
ENTRY 0042d980
NAME FUN_0042d980
SIGNATURE void * __cdecl FUN_0042d980(void * param_1, float * param_2, float * param_3)
BODY [[0042d980, 0042da0f]]


void * __cdecl FUN_0042d980(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,param_2[2] * param_3[2] + param_2[1] * param_3[1] + *param_2 * *param_3,
               param_2[5] * param_3[2] + param_2[4] * param_3[1] + param_2[3] * *param_3,
               param_2[8] * param_3[2] + param_2[7] * param_3[1] + param_2[6] * *param_3);
  return param_1;
}



================================================================================
REQUESTED 00431ea0
ENTRY 00431ea0
NAME FUN_00431ea0
SIGNATURE float * __cdecl FUN_00431ea0(float * param_1, float * param_2)
BODY [[00431ea0, 00431ed1]]


float * __cdecl FUN_00431ea0(float *param_1,float *param_2)

{
  undefined4 local_c;
  
  if (*param_1 <= *param_2) {
    local_c = param_1;
  }
  else {
    local_c = param_2;
  }
  return local_c;
}



================================================================================
REQUESTED 0042afa0
ENTRY 0042afa0
NAME FUN_0042afa0
SIGNATURE float * __cdecl FUN_0042afa0(float * param_1, float * param_2)
BODY [[0042afa0, 0042afd1]]


float * __cdecl FUN_0042afa0(float *param_1,float *param_2)

{
  undefined4 local_c;
  
  if (*param_2 <= *param_1) {
    local_c = param_1;
  }
  else {
    local_c = param_2;
  }
  return local_c;
}



================================================================================
REQUESTED 004135a0
ENTRY 004135a0
NAME FUN_004135a0
SIGNATURE undefined4 * __thiscall FUN_004135a0(void * this, undefined4 param_1, undefined4 param_2, undefined4 param_3)
BODY [[004135a0, 004135c9]]


undefined4 * __thiscall
FUN_004135a0(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  *(undefined4 *)this = param_1;
  *(undefined4 *)((int)this + 4) = param_2;
  *(undefined4 *)((int)this + 8) = param_3;
  return (undefined4 *)this;
}



