Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00466ec0
ENTRY 00466ec0
NAME FUN_00466ec0
SIGNATURE undefined4 * __fastcall FUN_00466ec0(undefined4 * param_1)
BODY [[00466ec0, 00466fcb]]


undefined4 * __fastcall FUN_00466ec0(undefined4 *param_1)

{
  undefined4 *puVar1;
  undefined4 *local_10;
  
  FUN_004c1360(param_1);
  *param_1 = &PTR_FUN_0057415c;
  param_1[0x5d] = &PTR_FUN_00574140;
  FUN_004b30e0(param_1 + 0x82);
  FUN_004b30e0(param_1 + 0x83);
  _vector_constructor_iterator_(param_1 + 0x85,4,8,FUN_004b30e0);
  CSize::CSize((CSize *)(param_1 + 0x8d));
  CSize::CSize((CSize *)(param_1 + 0x93));
  CSize::CSize((CSize *)(param_1 + 0x96));
  FUN_0044bde0(param_1 + 0x82,0);
  puVar1 = (undefined4 *)FUN_00478523(0x688);
  if (puVar1 == (undefined4 *)0x0) {
    local_10 = (undefined4 *)0x0;
  }
  else {
    local_10 = FUN_004aaa20(puVar1);
  }
  FUN_0044bde0(param_1 + 0x83,(int)local_10);
  param_1[0x92] = 0x42c00000;
  FUN_0045ce30(param_1,0x3f800000);
  FUN_0045ce60(param_1,0x44480000);
  FUN_0045ce90(param_1,0x42b40000);
  return param_1;
}



================================================================================
REQUESTED 00467cf0
ENTRY 00467cf0
NAME FUN_00467cf0
SIGNATURE undefined __fastcall FUN_00467cf0(CTraceSnapshot * param_1)
BODY [[00467cf0, 00467d1e]]


void __fastcall FUN_00467cf0(CTraceSnapshot *param_1)

{
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)(param_1 + 500));
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)(param_1 + 0x1d8));
  FUN_004bdd50(param_1);
  return;
}



