Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00413650
ENTRY 00413650
NAME FUN_00413650
SIGNATURE void * __thiscall FUN_00413650(void * this, void * param_1)
BODY [[00413650, 0041368a]]


void * __thiscall FUN_00413650(void *this,void *param_1)

{
                    /* WARNING: Load size is inaccurate */
  FUN_004135a0(param_1,-*this,-*(float *)((int)this + 4),-*(float *)((int)this + 8));
  return param_1;
}



================================================================================
REQUESTED 00413750
ENTRY 00413750
NAME FUN_00413750
SIGNATURE float10 __fastcall FUN_00413750(float * param_1)
BODY [[00413750, 00413795]]


float10 __fastcall FUN_00413750(float *param_1)

{
  float fVar1;
  float10 fVar2;
  
  fVar2 = (float10)FUN_004136f0(param_1);
  fVar1 = (float)fVar2;
  *param_1 = *param_1 / fVar1;
  param_1[1] = param_1[1] / fVar1;
  param_1[2] = param_1[2] / fVar1;
  return (float10)fVar1;
}



================================================================================
REQUESTED 004285b0
ENTRY 004285b0
NAME FUN_004285b0
SIGNATURE undefined __thiscall FUN_004285b0(void * this, int param_1, undefined4 * param_2)
BODY [[004285b0, 004285ea]]


void __thiscall FUN_004285b0(void *this,int param_1,undefined4 *param_2)

{
  *(undefined4 *)((int)this + param_1 * 4) = *param_2;
  *(undefined4 *)((int)this + param_1 * 4 + 0xc) = param_2[1];
  *(undefined4 *)((int)this + param_1 * 4 + 0x18) = param_2[2];
  return;
}



================================================================================
REQUESTED 004137a0
ENTRY 004137a0
NAME FUN_004137a0
SIGNATURE undefined4 * __thiscall FUN_004137a0(void * this, undefined4 * param_1)
BODY [[004137a0, 004137c0]]


undefined4 * __thiscall FUN_004137a0(void *this,undefined4 *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  
  puVar2 = (undefined4 *)this;
  for (iVar1 = 9; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = *param_1;
    param_1 = param_1 + 1;
    puVar2 = puVar2 + 1;
  }
  return (undefined4 *)this;
}



================================================================================
REQUESTED 004135d0
ENTRY 004135d0
NAME FUN_004135d0
SIGNATURE undefined4 * __thiscall FUN_004135d0(void * this, undefined4 * param_1)
BODY [[004135d0, 00413601]]


undefined4 * __thiscall FUN_004135d0(void *this,undefined4 *param_1)

{
  *(undefined4 *)this = *param_1;
  *(undefined4 *)((int)this + 4) = param_1[1];
  *(undefined4 *)((int)this + 8) = param_1[2];
  return (undefined4 *)this;
}



================================================================================
REQUESTED 004136f0
ENTRY 004136f0
NAME FUN_004136f0
SIGNATURE undefined __fastcall FUN_004136f0(undefined4 param_1)
BODY [[004136f0, 0041372c]]


void __fastcall FUN_004136f0(undefined4 param_1)

{
  FUN_00413730(param_1);
  return;
}



