Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00418710
ENTRY 00418710
NAME FUN_00418710
SIGNATURE void * __cdecl FUN_00418710(void * param_1, float * param_2, float * param_3)
BODY [[00418710, 0041874d]]


void * __cdecl FUN_00418710(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,*param_2 + *param_3,param_2[1] + param_3[1],param_2[2] + param_3[2]);
  return param_1;
}



================================================================================
REQUESTED 00418750
ENTRY 00418750
NAME FUN_00418750
SIGNATURE void * __cdecl FUN_00418750(void * param_1, float * param_2, float * param_3)
BODY [[00418750, 0041878d]]


void * __cdecl FUN_00418750(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,*param_2 - *param_3,param_2[1] - param_3[1],param_2[2] - param_3[2]);
  return param_1;
}



================================================================================
REQUESTED 00418790
ENTRY 00418790
NAME FUN_00418790
SIGNATURE void * __cdecl FUN_00418790(void * param_1, float * param_2, float param_3)
BODY [[00418790, 004187c5]]


void * __cdecl FUN_00418790(void *param_1,float *param_2,float param_3)

{
  FUN_004135a0(param_1,param_3 * *param_2,param_3 * param_2[1],param_3 * param_2[2]);
  return param_1;
}



================================================================================
REQUESTED 00460790
ENTRY 00460790
NAME FUN_00460790
SIGNATURE void * __cdecl FUN_00460790(void * param_1, float * param_2, float * param_3)
BODY [[00460790, 004607bd]]


void * __cdecl FUN_00460790(void *param_1,float *param_2,float *param_3)

{
  FUN_0041e910(param_1,*param_2 + *param_3,param_2[1] + param_3[1]);
  return param_1;
}



================================================================================
REQUESTED 00479c30
ENTRY 00479c30
NAME FUN_00479c30
SIGNATURE undefined4 * __thiscall FUN_00479c30(void * this, undefined4 * param_1)
BODY [[00479c30, 00479c55]]


undefined4 * __thiscall FUN_00479c30(void *this,undefined4 *param_1)

{
  *(undefined4 *)this = *param_1;
  *(undefined4 *)((int)this + 4) = param_1[1];
  return (undefined4 *)this;
}



================================================================================
REQUESTED 0042b640
ENTRY 0042b640
NAME FUN_0042b640
SIGNATURE undefined __thiscall FUN_0042b640(void * this, float * param_1)
BODY [[0042b640, 0042b761]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall FUN_0042b640(void *this,float *param_1)

{
  float fVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  float fVar5;
  float fVar6;
  float fVar7;
  float fVar8;
  float fVar9;
  float fVar10;
  float fVar11;
  
  fVar4 = _DAT_00571948 * *(float *)((int)this + 4);
  fVar10 = _DAT_00571948 * *(float *)((int)this + 8);
  fVar11 = _DAT_00571948 * *(float *)((int)this + 0xc);
                    /* WARNING: Load size is inaccurate */
  fVar3 = fVar4 * *this;
                    /* WARNING: Load size is inaccurate */
  fVar1 = *this;
                    /* WARNING: Load size is inaccurate */
  fVar2 = *this;
  fVar4 = fVar4 * *(float *)((int)this + 4);
  fVar5 = fVar10 * *(float *)((int)this + 4);
  fVar6 = fVar11 * *(float *)((int)this + 4);
  fVar7 = fVar10 * *(float *)((int)this + 8);
  fVar8 = fVar11 * *(float *)((int)this + 8);
  fVar9 = fVar11 * *(float *)((int)this + 0xc);
  *param_1 = _DAT_00571490 - (fVar7 + fVar9);
  param_1[1] = fVar5 - fVar11 * fVar2;
  param_1[2] = fVar6 + fVar10 * fVar1;
  param_1[3] = fVar5 + fVar11 * fVar2;
  param_1[4] = _DAT_00571490 - (fVar4 + fVar9);
  param_1[5] = fVar8 - fVar3;
  param_1[6] = fVar6 - fVar10 * fVar1;
  param_1[7] = fVar8 + fVar3;
  param_1[8] = _DAT_00571490 - (fVar4 + fVar7);
  return;
}



================================================================================
REQUESTED 0042b770
ENTRY 0042b770
NAME FUN_0042b770
SIGNATURE void * __thiscall FUN_0042b770(void * this, void * param_1)
BODY [[0042b770, 0042b7b6]]


void * __thiscall FUN_0042b770(void *this,void *param_1)

{
                    /* WARNING: Load size is inaccurate */
  FUN_0042b7c0(param_1,-*this,-*(float *)((int)this + 4),-*(float *)((int)this + 8),
               -*(float *)((int)this + 0xc));
  return param_1;
}



================================================================================
REQUESTED 0042b800
ENTRY 0042b800
NAME FUN_0042b800
SIGNATURE float10 __cdecl FUN_0042b800(float * param_1, float * param_2)
BODY [[0042b800, 0042b838]]


float10 __cdecl FUN_0042b800(float *param_1,float *param_2)

{
  return (float10)param_1[3] * (float10)param_2[3] +
         (float10)param_1[2] * (float10)param_2[2] +
         (float10)param_1[1] * (float10)param_2[1] + (float10)*param_1 * (float10)*param_2;
}



================================================================================
REQUESTED 0042b840
ENTRY 0042b840
NAME FUN_0042b840
SIGNATURE void * __cdecl FUN_0042b840(void * param_1, float param_2, float * param_3, float * param_4)
BODY [[0042b840, 0042b878]]


void * __cdecl FUN_0042b840(void *param_1,float param_2,float *param_3,float *param_4)

{
  CSize local_14 [16];
  
  CSize::CSize(local_14);
  FUN_00481cd0((float *)local_14,param_2,param_3,param_4);
  FUN_0042b880(param_1,(undefined4 *)local_14);
  return param_1;
}



================================================================================
REQUESTED 00428500
ENTRY 00428500
NAME FUN_00428500
SIGNATURE void * __cdecl FUN_00428500(void * param_1, float * param_2)
BODY [[00428500, 00428529]]


void * __cdecl FUN_00428500(void *param_1,float *param_2)

{
  float10 fVar1;
  
  fVar1 = (float10)FUN_004136f0(param_2);
  FUN_00428530(param_1,param_2,(float)fVar1);
  return param_1;
}



================================================================================
REQUESTED 00428490
ENTRY 00428490
NAME FUN_00428490
SIGNATURE void * __cdecl FUN_00428490(void * param_1, float * param_2, float * param_3)
BODY [[00428490, 004284f5]]


void * __cdecl FUN_00428490(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,param_2[1] * param_3[2] - param_2[2] * param_3[1],
               param_2[2] * *param_3 - *param_2 * param_3[2],
               *param_2 * param_3[1] - param_2[1] * *param_3);
  return param_1;
}



================================================================================
REQUESTED 00428570
ENTRY 00428570
NAME FUN_00428570
SIGNATURE void * __thiscall FUN_00428570(void * this, void * param_1, int param_2)
BODY [[00428570, 004285a7]]


void * __thiscall FUN_00428570(void *this,void *param_1,int param_2)

{
  FUN_004135a0(param_1,*(undefined4 *)((int)this + param_2 * 4),
               *(undefined4 *)((int)this + param_2 * 4 + 0xc),
               *(undefined4 *)((int)this + param_2 * 4 + 0x18));
  return param_1;
}



================================================================================
REQUESTED 0044fcc0
ENTRY 0044fcc0
NAME FUN_0044fcc0
SIGNATURE undefined __thiscall FUN_0044fcc0(void * this, int param_1, undefined4 * param_2)
BODY [[0044fcc0, 0044fcfa]]


void __thiscall FUN_0044fcc0(void *this,int param_1,undefined4 *param_2)

{
  *(undefined4 *)((int)this + param_1 * 4) = *param_2;
  *(undefined4 *)((int)this + param_1 * 4 + 0x10) = param_2[1];
  *(undefined4 *)((int)this + param_1 * 4 + 0x20) = param_2[2];
  return;
}



================================================================================
REQUESTED 0044fc50
ENTRY 0044fc50
NAME FUN_0044fc50
SIGNATURE undefined __thiscall FUN_0044fc50(void * this, undefined4 * param_1, void * param_2, undefined4 * param_3, void * param_4)
BODY [[0044fc50, 0044fcbc]]


void __thiscall
FUN_0044fc50(void *this,undefined4 *param_1,void *param_2,undefined4 *param_3,void *param_4)

{
  undefined4 *puVar1;
  undefined1 local_4c [12];
  undefined1 local_40 [12];
  CSize local_34 [48];
  
  CSize::CSize(local_34);
  puVar1 = (undefined4 *)FUN_00413650(param_4,local_40);
  FUN_0044fcc0(local_34,0,puVar1);
  puVar1 = (undefined4 *)FUN_00413650(param_2,local_4c);
  FUN_0044fcc0(local_34,1,puVar1);
  FUN_0044fcc0(local_34,2,param_3);
  FUN_0044fcc0(local_34,3,param_1);
  FUN_00449c10(this,(float *)local_34);
  return;
}



================================================================================
REQUESTED 00449c10
ENTRY 00449c10
NAME FUN_00449c10
SIGNATURE undefined __thiscall FUN_00449c10(void * this, float * param_1)
BODY [[00449c10, 00449d27]]


void __thiscall FUN_00449c10(void *this,float *param_1)

{
  int iVar1;
  float *pfVar2;
  float *pfVar3;
  
  pfVar2 = param_1;
  pfVar3 = (float *)this;
  for (iVar1 = 0xc; iVar1 != 0; iVar1 = iVar1 + -1) {
    *pfVar3 = *pfVar2;
    pfVar2 = pfVar2 + 1;
    pfVar3 = pfVar3 + 1;
  }
  *(float *)((int)this + 0x30) = *param_1;
  *(float *)((int)this + 0x34) = param_1[4];
  *(float *)((int)this + 0x38) = param_1[8];
  *(float *)((int)this + 0x40) = param_1[1];
  *(float *)((int)this + 0x44) = param_1[5];
  *(float *)((int)this + 0x48) = param_1[9];
  *(float *)((int)this + 0x50) = param_1[2];
  *(float *)((int)this + 0x54) = param_1[6];
  *(float *)((int)this + 0x58) = param_1[10];
  *(float *)((int)this + 0x3c) =
       -(param_1[8] * param_1[0xb] + param_1[4] * param_1[7] + *param_1 * param_1[3]);
  *(float *)((int)this + 0x4c) =
       -(param_1[9] * param_1[0xb] + param_1[5] * param_1[7] + param_1[1] * param_1[3]);
  *(float *)((int)this + 0x5c) =
       -(param_1[10] * param_1[0xb] + param_1[6] * param_1[7] + param_1[2] * param_1[3]);
  return;
}



