Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 0042ef90
ENTRY 0042ef90
NAME FUN_0042ef90
SIGNATURE undefined1 __fastcall FUN_0042ef90(int param_1)
BODY [[0042ef90, 0042f455]]


undefined1 __fastcall FUN_0042ef90(int param_1)

{
  undefined1 uVar1;
  char cVar2;
  float *pfVar3;
  void *this;
  undefined4 *puVar4;
  float10 fVar5;
  float10 fVar6;
  CSize *pCVar7;
  float fVar8;
  float fVar9;
  undefined1 local_bc [12];
  float local_b0;
  float local_ac [2];
  undefined1 local_a4 [16];
  undefined1 local_94 [12];
  undefined1 local_88 [12];
  undefined1 local_7c [12];
  undefined1 local_70 [12];
  undefined1 local_64 [12];
  undefined1 local_58 [12];
  undefined1 local_4c [12];
  uint local_40;
  uint local_3c;
  float local_38;
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  CSize local_28 [12];
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  undefined4 local_c;
  uint local_8;
  
  *(undefined1 *)(param_1 + 0x301) = *(undefined1 *)(param_1 + 0x300);
  *(undefined1 *)(param_1 + 0x300) = 0;
  for (local_8 = 0; local_8 < 4; local_8 = local_8 + 1) {
    FUN_00426c20(local_28);
    CSize::CSize((CSize *)&local_34);
    local_34 = *(undefined4 *)(param_1 + 0x2c);
    local_30 = *(undefined4 *)(param_1 + 0x30);
    local_2c = *(undefined4 *)(param_1 + 0x34);
    fVar9 = 0.8;
    fVar8 = *(float *)(param_1 + 0x224 + local_8 * 4);
    pfVar3 = (float *)FUN_00418790(local_4c,(float *)(param_1 + 0x1c0),*(float *)(param_1 + 300));
    pfVar3 = (float *)FUN_00418790(local_58,pfVar3,fVar8);
    pfVar3 = (float *)FUN_00418790(local_64,pfVar3,fVar9);
    FUN_00418680(&local_34,pfVar3);
    fVar9 = 0.8;
    fVar8 = *(float *)(param_1 + 0x234 + local_8 * 4);
    pfVar3 = (float *)FUN_00418790(local_70,(float *)(param_1 + 0x1d8),*(float *)(param_1 + 0x130));
    pfVar3 = (float *)FUN_00418790(local_7c,pfVar3,fVar8);
    pfVar3 = (float *)FUN_00418790(local_88,pfVar3,fVar9);
    FUN_00418680(&local_34,pfVar3);
    pfVar3 = (float *)FUN_00418790(local_94,(float *)(param_1 + 0x1cc),*(float *)(param_1 + 0x2a8));
    FUN_00418680(&local_34,pfVar3);
    fVar8 = -2.0;
    pfVar3 = (float *)FUN_00418790(local_a4,(float *)(param_1 + 0x1cc),*(float *)(param_1 + 0x2a8));
    FUN_00418790(&stack0xffffff1c,pfVar3,fVar8);
    FUN_004135d0(&stack0xffffff10,&local_34);
    pCVar7 = local_28;
    this = (void *)FUN_00427130((undefined4 *)&stack0x00000004);
    cVar2 = FUN_00432fc0(this,(undefined4 *)pCVar7);
    *(char *)(param_1 + local_8 + 0x244) = cVar2;
    if (*(char *)(param_1 + local_8 + 0x244) == '\0') {
      *(undefined4 *)(param_1 + 0x298 + local_8 * 4) = 0;
      *(undefined4 *)(param_1 + 0x278 + local_8 * 4) = 0;
      *(undefined4 *)(param_1 + 0x288 + local_8 * 4) = 0;
    }
    else {
      *(undefined1 *)(param_1 + 0x300) = 1;
      *(undefined4 *)(param_1 + 0xd8) = local_c;
      puVar4 = (undefined4 *)(param_1 + 0x248 + local_8 * 0xc);
      *puVar4 = local_1c;
      puVar4[1] = local_18;
      puVar4[2] = local_14;
      fVar5 = FUN_00428460((float *)local_28,(float *)(param_1 + 0x1cc));
      fVar6 = FUN_00428460((float *)(param_1 + 0x2c),(float *)(param_1 + 0x1cc));
      local_38 = (float)((float10)(float)fVar5 - (fVar6 - (float10)*(float *)(param_1 + 0x2a8)));
      *(undefined4 *)(param_1 + 0x298 + local_8 * 4) =
           *(undefined4 *)(param_1 + 0x278 + local_8 * 4);
      local_ac[0] = *(float *)(param_1 + 0x2a8) + *(float *)(param_1 + 0x2a8);
      local_b0 = 0.0;
      pfVar3 = FUN_00431ea0(&local_38,local_ac);
      pfVar3 = FUN_0042afa0(&local_b0,pfVar3);
      *(float *)(param_1 + 0x278 + local_8 * 4) = *pfVar3;
      *(float *)(param_1 + 0x288 + local_8 * 4) =
           *(float *)(param_1 + 0x278 + local_8 * 4) - *(float *)(param_1 + 0x298 + local_8 * 4);
    }
  }
  *(undefined1 *)(param_1 + 0x1a4) = *(undefined1 *)(param_1 + 0x300);
  puVar4 = FUN_004135a0(local_bc,0,0,0);
  *(undefined4 *)(param_1 + 0x1a8) = *puVar4;
  *(undefined4 *)(param_1 + 0x1ac) = puVar4[1];
  *(undefined4 *)(param_1 + 0x1b0) = puVar4[2];
  if (*(char *)(param_1 + 0x300) == '\0') {
    if (*(char *)(param_1 + 0x301) != '\0') {
      *(undefined1 *)(param_1 + 0x301) = 0;
    }
  }
  else {
    local_3c = 0;
    for (local_40 = 0; local_40 < 4; local_40 = local_40 + 1) {
      if (*(char *)(param_1 + local_40 + 0x244) != '\0') {
        local_3c = local_3c + 1;
        FUN_00418680((void *)(param_1 + 0x1a8),(float *)(param_1 + 0x248 + local_40 * 0xc));
      }
    }
    FUN_004320c0((void *)(param_1 + 0x1a8),(float)local_3c);
    if (*(char *)(param_1 + 0x301) == '\0') {
      *(undefined1 *)(param_1 + 0x301) = 1;
    }
    else {
      *(undefined1 *)(param_1 + 0x301) = 0;
    }
  }
  uVar1 = *(undefined1 *)(param_1 + 0x300);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return uVar1;
}



================================================================================
REQUESTED 00430640
ENTRY 00430640
NAME FUN_00430640
SIGNATURE undefined __fastcall FUN_00430640(int param_1)
BODY [[00430640, 0043073d]]


void __fastcall FUN_00430640(int param_1)

{
  float *pfVar1;
  float10 fVar2;
  float fVar3;
  float fVar4;
  undefined1 local_58 [12];
  undefined1 local_4c [12];
  undefined1 local_40 [12];
  undefined1 local_34 [12];
  undefined1 local_28 [12];
  float local_1c [3];
  float local_10 [3];
  
  FUN_004135d0(local_1c,&DAT_005b16cc);
  FUN_004135d0(local_10,&DAT_005b16cc);
  pfVar1 = (float *)FUN_00418790(local_28,(float *)(param_1 + 0x5c),*(float *)(param_1 + 0x15c));
  FUN_00432070(local_1c,pfVar1);
  pfVar1 = (float *)FUN_00418790(local_34,(float *)(param_1 + 0x68),*(float *)(param_1 + 0x15c));
  FUN_00432070(local_10,pfVar1);
  if (*(char *)(param_1 + 0x300) != '\0') {
    fVar4 = *(float *)(param_1 + 0x314);
    fVar3 = *(float *)(param_1 + 0x160);
    fVar2 = (float10)FUN_004136f0(param_1 + 0x5c);
    pfVar1 = (float *)FUN_00418790(local_40,(float *)(param_1 + 0x5c),(float)fVar2);
    pfVar1 = (float *)FUN_00418790(local_4c,pfVar1,fVar3);
    pfVar1 = (float *)FUN_00418790(local_58,pfVar1,fVar4);
    FUN_00432070(local_1c,pfVar1);
  }
  FUN_00418680((void *)(param_1 + 0x200),local_1c);
  FUN_00418680((void *)(param_1 + 0x20c),local_10);
  return;
}



================================================================================
REQUESTED 00430740
ENTRY 00430740
NAME FUN_00430740
SIGNATURE undefined __fastcall FUN_00430740(int param_1)
BODY [[00430740, 00430827]]


void __fastcall FUN_00430740(int param_1)

{
  float *pfVar1;
  float fVar2;
  undefined1 local_58 [12];
  undefined1 local_4c [12];
  undefined1 local_40 [12];
  undefined1 local_34 [12];
  undefined1 local_28 [12];
  undefined1 local_1c [12];
  undefined1 local_10 [12];
  
  FUN_00418680((void *)(param_1 + 0x200),(float *)(param_1 + 0x308));
  fVar2 = *(float *)(param_1 + 0x1a0);
  pfVar1 = (float *)FUN_00428530(local_10,(float *)(param_1 + 0x200),*(float *)(param_1 + 0x128));
  pfVar1 = (float *)FUN_00418790(local_1c,pfVar1,fVar2);
  FUN_00418680((void *)(param_1 + 0x5c),pfVar1);
  fVar2 = *(float *)(param_1 + 0x1a0);
  pfVar1 = (float *)FUN_0042d980(local_28,(float *)(param_1 + 0x134),(float *)(param_1 + 0x68));
  pfVar1 = (float *)FUN_00428490(local_34,(float *)(param_1 + 0x68),pfVar1);
  pfVar1 = (float *)FUN_00418750(local_40,(float *)(param_1 + 0x20c),pfVar1);
  pfVar1 = (float *)FUN_0042d980(local_4c,(float *)(param_1 + 0x134),pfVar1);
  pfVar1 = (float *)FUN_00418790(local_58,pfVar1,fVar2);
  FUN_00418680((void *)(param_1 + 0x68),pfVar1);
  return;
}



================================================================================
REQUESTED 00430ed0
ENTRY 00430ed0
NAME FUN_00430ed0
SIGNATURE undefined __thiscall FUN_00430ed0(void * this, float param_1)
BODY [[00430ed0, 00431223]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall FUN_00430ed0(void *this,float param_1)

{
  float *pfVar1;
  void *pvVar2;
  undefined4 *puVar3;
  int iVar4;
  undefined4 *puVar5;
  float fVar6;
  undefined1 local_f0 [16];
  undefined1 local_e0 [16];
  undefined1 local_d0 [16];
  undefined1 local_c0 [12];
  undefined1 local_b4 [16];
  undefined1 local_a4 [16];
  undefined1 local_94 [16];
  undefined1 local_84 [16];
  undefined1 local_74 [16];
  undefined1 local_64 [16];
  undefined1 local_54 [12];
  undefined4 local_48;
  undefined4 local_44;
  undefined4 local_40;
  undefined4 local_3c;
  undefined4 local_38 [9];
  int local_14;
  undefined4 local_10;
  undefined4 local_c;
  float local_8;
  
  *(undefined1 *)((int)this + 0x2f8) = 0;
  *(undefined4 *)((int)this + 0x2fc) = 0;
  FUN_00482180((void *)((int)this + 0x1f0),(float *)((int)this + 0x38));
  FUN_0042b880(&local_48,(undefined4 *)((int)this + 0x1f0));
  FUN_004137a0(local_38,(undefined4 *)((int)this + 0x38));
  pfVar1 = (float *)FUN_00418790(local_54,(float *)((int)this + 0x5c),param_1);
  FUN_00418680((void *)((int)this + 0x2c),pfVar1);
  fVar6 = param_1 * _DAT_005710b8;
  pfVar1 = (float *)FUN_0042da70(local_64,(float *)((int)this + 0x1f0),(float *)((int)this + 0x68));
  pfVar1 = (float *)FUN_0042db30(local_74,pfVar1,fVar6);
  FUN_0042da10((void *)((int)this + 0x1f0),pfVar1);
  pfVar1 = (float *)((int)this + 0x38);
  pvVar2 = FUN_0042db80(local_84,(float *)((int)this + 0x1f0));
  FUN_0042b640(pvVar2,pfVar1);
  local_14 = 3;
  FUN_00428570((void *)((int)this + 0x38),&local_10,2);
  while ((iVar4 = local_14, local_8 < _DAT_005710b8 && (local_14 = local_14 + -1, 0 < iVar4))) {
    *(float *)((int)this + 0x68) = *(float *)((int)this + 0x68) * _DAT_00571d44;
    *(float *)((int)this + 0x6c) = *(float *)((int)this + 0x6c) * _DAT_00571d44;
    *(undefined4 *)((int)this + 0x1f0) = local_48;
    *(undefined4 *)((int)this + 500) = local_44;
    *(undefined4 *)((int)this + 0x1f8) = local_40;
    *(undefined4 *)((int)this + 0x1fc) = local_3c;
    puVar3 = local_38;
    puVar5 = (undefined4 *)((int)this + 0x38);
    for (iVar4 = 9; iVar4 != 0; iVar4 = iVar4 + -1) {
      *puVar5 = *puVar3;
      puVar3 = puVar3 + 1;
      puVar5 = puVar5 + 1;
    }
    fVar6 = param_1 * _DAT_005710b8;
    pfVar1 = (float *)FUN_0042da70(local_94,(float *)((int)this + 0x1f0),(float *)((int)this + 0x68)
                                  );
    pfVar1 = (float *)FUN_0042db30(local_a4,pfVar1,fVar6);
    FUN_0042da10((void *)((int)this + 0x1f0),pfVar1);
    pfVar1 = (float *)((int)this + 0x38);
    pvVar2 = FUN_0042db80(local_b4,(float *)((int)this + 0x1f0));
    FUN_0042b640(pvVar2,pfVar1);
    puVar3 = (undefined4 *)FUN_00428570((void *)((int)this + 0x38),local_c0,2);
    local_10 = *puVar3;
    local_c = puVar3[1];
    local_8 = (float)puVar3[2];
  }
  if (local_8 < _DAT_005710b8) {
    *(undefined4 *)((int)this + 0x68) = 0;
    *(undefined4 *)((int)this + 0x6c) = 0;
    *(undefined4 *)((int)this + 0x1f0) = local_48;
    *(undefined4 *)((int)this + 500) = local_44;
    *(undefined4 *)((int)this + 0x1f8) = local_40;
    *(undefined4 *)((int)this + 0x1fc) = local_3c;
    puVar3 = local_38;
    puVar5 = (undefined4 *)((int)this + 0x38);
    for (iVar4 = 9; iVar4 != 0; iVar4 = iVar4 + -1) {
      *puVar5 = *puVar3;
      puVar3 = puVar3 + 1;
      puVar5 = puVar5 + 1;
    }
    fVar6 = param_1 * _DAT_005710b8;
    pfVar1 = (float *)FUN_0042da70(local_d0,(float *)((int)this + 0x1f0),(float *)((int)this + 0x68)
                                  );
    pfVar1 = (float *)FUN_0042db30(local_e0,pfVar1,fVar6);
    FUN_0042da10((void *)((int)this + 0x1f0),pfVar1);
    pfVar1 = (float *)((int)this + 0x38);
    pvVar2 = FUN_0042db80(local_f0,(float *)((int)this + 0x1f0));
    FUN_0042b640(pvVar2,pfVar1);
  }
  return;
}



================================================================================
REQUESTED 00430830
ENTRY 00430830
NAME FUN_00430830
SIGNATURE undefined1 __thiscall FUN_00430830(void * this, void * param_1)
BODY [[00430830, 00430ec6]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 __thiscall FUN_00430830(void *this,void *param_1)

{
  uint uVar1;
  float *pfVar2;
  float *pfVar3;
  undefined4 *puVar4;
  float10 fVar5;
  float10 fVar6;
  undefined1 auStack_1e0 [4];
  undefined4 uStack_1dc;
  undefined1 auStack_1d4 [28];
  undefined4 uStack_1b8;
  float fVar7;
  float local_19c;
  float local_194;
  float local_17c;
  float local_178;
  float local_174;
  float local_170;
  float local_16c;
  float local_168;
  undefined1 local_164 [12];
  undefined1 local_158 [12];
  undefined1 local_14c [12];
  undefined1 local_140 [12];
  undefined1 local_134 [12];
  float local_128;
  float local_124;
  undefined1 local_120 [12];
  undefined1 local_114 [12];
  undefined1 local_108 [12];
  undefined1 local_fc [12];
  undefined1 local_f0 [12];
  undefined1 local_e4 [12];
  undefined1 local_d8 [24];
  float local_c0 [2];
  float local_b8;
  float local_b4 [2];
  float local_ac;
  float local_a8;
  float local_a4;
  float local_a0;
  float local_9c;
  float local_98 [3];
  float local_8c;
  float local_88;
  float local_84;
  float local_80;
  float local_7c;
  float local_78;
  float local_74;
  float local_70;
  float local_6c;
  char local_65;
  CSize local_64 [12];
  float local_58 [2];
  float local_50;
  undefined4 local_44 [3];
  undefined4 local_38 [3];
  undefined1 local_29;
  undefined4 local_28 [9];
  
  local_29 = 1;
  FUN_00426c20(local_64);
  FUN_004135a0(local_44,*(undefined4 *)((int)this + 300),*(undefined4 *)((int)this + 0x130),
               0x3f333333);
  FUN_004137a0(local_28,(undefined4 *)((int)this + 0x38));
  FUN_00418710(local_38,(float *)((int)this + 0x2c),(float *)((int)this + 0x1cc));
  uStack_1b8 = 0x4308b7;
  FUN_004135d0(&stack0xfffffe50,local_44);
  uStack_1dc = 0x4308c5;
  FUN_004137a0(auStack_1d4,local_28);
  FUN_004135d0(auStack_1e0,local_38);
  uVar1 = FUN_00433310(param_1,(undefined4 *)local_64);
  local_65 = (char)uVar1;
  while (local_65 != '\0') {
    fVar5 = FUN_00428460(local_58,(float *)((int)this + 0x5c));
    if (fVar5 < (float10)DAT_00571808) {
      *(undefined4 *)((int)this + 0x2c0) = 0;
      local_29 = 0;
      CSize::CSize((CSize *)&local_74);
      CSize::CSize((CSize *)&local_80);
      fVar5 = FUN_00428460((float *)((int)this + 0x5c),local_58);
      pfVar2 = (float *)FUN_00418790(local_d8,local_58,(float)fVar5);
      local_74 = *pfVar2;
      local_70 = pfVar2[1];
      local_6c = pfVar2[2];
      pfVar2 = (float *)FUN_00418750(local_e4,(float *)((int)this + 0x5c),&local_74);
      local_80 = *pfVar2;
      local_7c = pfVar2[1];
      local_78 = pfVar2[2];
      if (local_50 <= _DAT_00571d48) {
        *(undefined1 *)((int)this + 0x2dc) = 0;
        *(undefined1 *)((int)this + 0x2f8) = 1;
        fVar5 = (float10)FUN_004136f0(&local_74);
        *(float *)((int)this + 0x2fc) = (float)fVar5;
        FUN_00428500(local_98,&local_80);
        fVar5 = (float10)FUN_004136f0(&local_80);
        local_a8 = (float)fVar5;
        CSize::CSize((CSize *)&local_a4);
        local_124 = local_a8 * _DAT_00571d40;
        fVar5 = (float10)FUN_004136f0(&local_74);
        local_128 = (float)(fVar5 * (float10)_DAT_00571d3c);
        pfVar2 = FUN_00431ea0(&local_128,&local_124);
        pfVar2 = (float *)FUN_00418790(local_134,local_98,*pfVar2);
        pfVar3 = (float *)FUN_00418790(local_140,&local_74,-1.5);
        pfVar2 = (float *)FUN_00418750(local_14c,pfVar3,pfVar2);
        local_a4 = *pfVar2;
        local_a0 = pfVar2[1];
        fVar7 = pfVar2[2];
        local_9c = fVar7;
        pfVar2 = (float *)FUN_004135a0(local_158,0,0,0x3f800000);
        pfVar2 = (float *)FUN_00418790(local_164,pfVar2,fVar7);
        FUN_00432070(&local_a4,pfVar2);
        FUN_00418680((void *)((int)this + 0x5c),&local_a4);
        fVar5 = FUN_00428460(local_58,(float *)((int)this + 0x1d8));
        local_88 = (float)fVar5;
        fVar5 = FUN_00428460(local_58,(float *)((int)this + 0x1c0));
        local_8c = (float)fVar5;
        fVar5 = (float10)FUN_00431b70();
        fVar6 = (float10)FUN_00431b70();
        if ((float10)(float)fVar5 <= fVar6) {
          FUN_004135d0(local_c0,&DAT_005b16cc);
          if (local_8c <= DAT_00571808) {
            local_19c = 1.0;
          }
          else {
            local_19c = -1.0;
          }
          FUN_00428460(local_58,(float *)((int)this + 0x5c));
          fVar5 = (float10)FUN_00431b70();
          local_174 = (float)fVar5;
          local_178 = 30.0;
          local_17c = 1.0;
          local_19c = local_88 * local_19c;
          pfVar2 = FUN_00431ea0(&local_178,&local_174);
          pfVar2 = FUN_0042afa0(&local_17c,pfVar2);
          local_b8 = local_19c * *pfVar2;
          fVar5 = FUN_00428460(local_c0,(float *)((int)this + 0x68));
          if (fVar5 < (float10)_DAT_00571490 != (fVar5 == (float10)_DAT_00571490)) {
            FUN_00418680((void *)((int)this + 0x68),local_c0);
          }
        }
        else {
          FUN_004135d0(local_b4,&DAT_005b16cc);
          if (local_88 <= DAT_00571808) {
            local_194 = -1.0;
          }
          else {
            local_194 = 1.0;
          }
          FUN_00428460(local_58,(float *)((int)this + 0x5c));
          fVar5 = (float10)FUN_00431b70();
          local_168 = (float)fVar5;
          local_16c = 30.0;
          local_170 = 1.0;
          local_194 = local_8c * local_194;
          pfVar2 = FUN_00431ea0(&local_16c,&local_168);
          pfVar2 = FUN_0042afa0(&local_170,pfVar2);
          local_ac = local_194 * *pfVar2;
          fVar5 = FUN_00428460(local_b4,(float *)((int)this + 0x68));
          if (fVar5 < (float10)_DAT_00571490 != (fVar5 == (float10)_DAT_00571490)) {
            FUN_00418680((void *)((int)this + 0x68),local_b4);
          }
        }
      }
      else {
        pfVar2 = &local_80;
        pfVar3 = (float *)FUN_00418790(local_f0,&local_74,-0.2);
        puVar4 = (undefined4 *)FUN_00418710(local_fc,pfVar3,pfVar2);
        *(undefined4 *)((int)this + 0x5c) = *puVar4;
        *(undefined4 *)((int)this + 0x60) = puVar4[1];
        *(undefined4 *)((int)this + 100) = puVar4[2];
        fVar5 = (float10)FUN_004136f0(&local_74);
        *(float *)((int)this + 0x304) = (float)fVar5;
        pfVar3 = (float *)((int)this + 0x1c0);
        pfVar2 = (float *)FUN_00428490(local_108,local_58,(float *)((int)this + 0x1cc));
        fVar5 = FUN_00428460(pfVar2,pfVar3);
        local_84 = (float)fVar5;
        *(float *)((int)this + 0x68) = *(float *)((int)this + 0x68) - local_84 * _DAT_00571d44;
        pfVar2 = (float *)FUN_00413650((void *)((int)this + 0x1d8),local_114);
        pfVar3 = (float *)FUN_00428490(local_120,local_58,(float *)((int)this + 0x1cc));
        fVar5 = FUN_00428460(pfVar3,pfVar2);
        local_84 = (float)fVar5;
        *(float *)((int)this + 0x6c) = *(float *)((int)this + 0x6c) - local_84 * _DAT_00571d44;
      }
    }
    uStack_1b8 = 0x430e8e;
    FUN_004135d0(&stack0xfffffe50,local_44);
    uStack_1dc = 0x430e9c;
    FUN_004137a0(auStack_1d4,local_28);
    FUN_004135d0(auStack_1e0,local_38);
    uVar1 = FUN_00433310(param_1,(undefined4 *)local_64);
    local_65 = (char)uVar1;
  }
  return local_29;
}



