Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 0040b750
ENTRY 0040b750
NAME FUN_0040b750
SIGNATURE uint __fastcall FUN_0040b750(int * param_1)
BODY [[0040b750, 0040b7af]]


uint __fastcall FUN_0040b750(int *param_1)

{
  char cVar1;
  int iVar2;
  uint uVar3;
  byte *pbVar4;
  uint local_8;
  
  cVar1 = FUN_0040b7f0(param_1);
  if (cVar1 == '\0') {
    iVar2 = FUN_0040d150(param_1);
    uVar3 = iVar2 << 1;
    pbVar4 = (byte *)FUN_00427130(param_1);
    local_8 = FUN_00478840(0,pbVar4,uVar3);
    if (local_8 == 0) {
      local_8 = 1;
    }
    else if (local_8 == 0xffffffff) {
      local_8 = 2;
    }
  }
  else {
    local_8 = 0;
  }
  return local_8;
}



================================================================================
REQUESTED 00481220
ENTRY 00481220
NAME FUN_00481220
SIGNATURE void * __cdecl FUN_00481220(void * param_1, undefined4 param_2, uint param_3)
BODY [[00481220, 0048138c]]


void * __cdecl FUN_00481220(void *param_1,undefined4 param_2,uint param_3)

{
  int iVar1;
  uint uVar2;
  shared_ptr<class___ExceptionPtr> *psVar3;
  CDialogTemplate *pCVar4;
  int *piVar5;
  undefined4 uVar6;
  undefined4 *local_14;
  CDialogTemplate local_10 [4];
  undefined4 *local_c;
  CDialogTemplate local_8 [4];
  
  local_c = (undefined4 *)FUN_00478523(0xb0);
  if (local_c == (undefined4 *)0x0) {
    local_14 = (undefined4 *)0x0;
  }
  else {
    local_14 = FUN_00481390(local_c);
  }
  FUN_0045b690(local_8,(int)local_14,'\x01');
  piVar5 = &param_2;
  uVar2 = param_3;
  iVar1 = FUN_00427130((undefined4 *)local_8);
  uVar2 = FUN_00483f30((void *)(iVar1 + 8),piVar5,uVar2);
  if ((uVar2 & 0xff) == 0) {
    FUN_0045b690(param_1,0,'\x01');
    CDialogTemplate::~CDialogTemplate(local_8);
    FUN_0040dab0(&param_2);
  }
  else {
    iVar1 = FUN_00427130((undefined4 *)local_8);
    iVar1 = FUN_00484200(iVar1 + 8);
    if (iVar1 == -0x3e06888) {
      uVar2 = param_3 + 0x2593a9f1;
      uVar6 = 0xffffffff;
      pCVar4 = local_10;
      iVar1 = FUN_00427130((undefined4 *)local_8);
      psVar3 = (shared_ptr<class___ExceptionPtr> *)
               FUN_004842e0((void *)(iVar1 + 8),pCVar4,uVar6,uVar2);
      iVar1 = FUN_00427130((undefined4 *)local_8);
      std::shared_ptr<class___ExceptionPtr>::operator=
                ((shared_ptr<class___ExceptionPtr> *)(iVar1 + 0xac),psVar3);
      CDialogTemplate::~CDialogTemplate(local_10);
      iVar1 = FUN_00427130((undefined4 *)local_8);
      iVar1 = FUN_00417940((int *)(iVar1 + 0xac));
      if (iVar1 == -1) {
        FUN_0045b690(param_1,0,'\x01');
        CDialogTemplate::~CDialogTemplate(local_8);
        FUN_0040dab0(&param_2);
      }
      else {
        iVar1 = FUN_00427130((undefined4 *)local_8);
        *(uint *)(iVar1 + 0xa8) = param_3;
        FUN_00469690(param_1,(int *)local_8);
        CDialogTemplate::~CDialogTemplate(local_8);
        FUN_0040dab0(&param_2);
      }
    }
    else {
      FUN_0045b690(param_1,0,'\x01');
      CDialogTemplate::~CDialogTemplate(local_8);
      FUN_0040dab0(&param_2);
    }
  }
  return param_1;
}



================================================================================
REQUESTED 004845e0
ENTRY 004845e0
NAME FUN_004845e0
SIGNATURE undefined __cdecl FUN_004845e0(int param_1, int param_2, uint param_3, uint param_4)
BODY [[004845e0, 004845fc]]


void __cdecl FUN_004845e0(int param_1,int param_2,uint param_3,uint param_4)

{
  FUN_004851c0(param_1,param_2,param_3,param_4);
  return;
}



================================================================================
REQUESTED 00484730
ENTRY 00484730
NAME FUN_00484730
SIGNATURE undefined4 * __thiscall FUN_00484730(void * this, int * param_1)
BODY [[00484730, 004847c0]]


undefined4 * __thiscall FUN_00484730(void *this,int *param_1)

{
  bool bVar1;
  int *piVar2;
  undefined4 *puVar3;
  undefined4 *local_64;
  undefined4 local_5c;
  undefined4 local_58;
  undefined4 local_54;
  undefined4 local_50;
  undefined4 local_4c;
  undefined4 local_48;
  undefined4 local_44;
  undefined4 local_40;
  undefined1 local_3c [36];
  undefined1 local_18 [12];
  int local_c [2];
  
  FUN_004849d0(this,local_c,param_1);
  piVar2 = (int *)FUN_0041e840(this,local_18);
  bVar1 = FUN_004d34a0(local_c,piVar2);
  if (bVar1) {
    local_5c = 0;
    local_58 = 0;
    local_54 = 0;
    local_50 = 0;
    local_4c = 0;
    local_48 = 0;
    local_44 = 0;
    local_40 = 0;
    puVar3 = FUN_00484830(local_3c,param_1,&local_5c);
    local_64 = FUN_00484940(this,puVar3);
  }
  else {
    local_64 = (undefined4 *)FUN_00417de0(local_c);
  }
  local_64 = local_64 + 1;
  return local_64;
}



================================================================================
REQUESTED 00478840
ENTRY 00478840
NAME FUN_00478840
SIGNATURE uint __cdecl FUN_00478840(uint param_1, byte * param_2, uint param_3)
BODY [[00478840, 00478899] [004788a0, 00478968]]


uint __cdecl FUN_00478840(uint param_1,byte *param_2,uint param_3)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  int iVar12;
  int iVar13;
  int iVar14;
  int iVar15;
  int iVar16;
  int iVar17;
  uint uVar18;
  uint uVar19;
  
  uVar2 = param_1 & 0xffff;
  uVar19 = param_1 >> 0x10;
  if (param_2 != (byte *)0x0) {
    if (param_3 != 0) {
      do {
        uVar1 = param_3;
        if (0x15af < param_3) {
          uVar1 = 0x15b0;
        }
        param_3 = param_3 - uVar1;
        if (0xf < (int)uVar1) {
          uVar18 = uVar1 >> 4;
          uVar1 = uVar1 + uVar18 * -0x10;
          do {
            iVar3 = uVar2 + *param_2;
            iVar4 = iVar3 + (uint)param_2[1];
            iVar5 = iVar4 + (uint)param_2[2];
            iVar6 = iVar5 + (uint)param_2[3];
            iVar7 = iVar6 + (uint)param_2[4];
            iVar8 = iVar7 + (uint)param_2[5];
            iVar9 = iVar8 + (uint)param_2[6];
            iVar10 = iVar9 + (uint)param_2[7];
            iVar11 = iVar10 + (uint)param_2[8];
            iVar12 = iVar11 + (uint)param_2[9];
            iVar13 = iVar12 + (uint)param_2[10];
            iVar14 = iVar13 + (uint)param_2[0xb];
            iVar15 = iVar14 + (uint)param_2[0xc];
            iVar16 = iVar15 + (uint)param_2[0xd];
            iVar17 = iVar16 + (uint)param_2[0xe];
            uVar2 = iVar17 + (uint)param_2[0xf];
            uVar19 = uVar19 + iVar3 + iVar4 + iVar5 + iVar6 + iVar7 + iVar8 + iVar9 + iVar10 +
                     iVar11 + iVar12 + iVar13 + iVar14 + iVar15 + iVar16 + iVar17 + uVar2;
            param_2 = param_2 + 0x10;
            uVar18 = uVar18 - 1;
          } while (uVar18 != 0);
        }
        for (; uVar1 != 0; uVar1 = uVar1 - 1) {
          uVar2 = uVar2 + *param_2;
          param_2 = param_2 + 1;
          uVar19 = uVar19 + uVar2;
        }
        uVar2 = uVar2 % 0xfff1;
        uVar19 = uVar19 % 0xfff1;
      } while (param_3 != 0);
    }
    return uVar19 << 0x10 | uVar2;
  }
  return 1;
}



================================================================================
REQUESTED 00485010
ENTRY 00485010
NAME FUN_00485010
SIGNATURE void * __cdecl FUN_00485010(void * param_1)
BODY [[00485010, 00485163]]


void * __cdecl FUN_00485010(void *param_1)

{
  undefined4 uVar1;
  HANDLE hFile;
  DWORD DVar2;
  HANDLE hFileMappingObject;
  LPVOID pvVar3;
  undefined4 *puVar4;
  undefined4 uVar5;
  undefined4 uVar6;
  undefined4 uVar7;
  undefined4 uVar8;
  undefined4 uVar9;
  undefined4 uVar10;
  undefined4 *local_20;
  
  uVar10 = 0;
  uVar9 = 0x10000000;
  uVar8 = 3;
  uVar7 = 0;
  uVar6 = 1;
  uVar5 = 0x80000000;
  uVar1 = FUN_004d2be0((undefined4 *)&stack0x00000008);
  hFile = (HANDLE)(*(code *)PTR_FUN_005a6d5c)(uVar1,uVar5,uVar6,uVar7,uVar8,uVar9,uVar10);
  if (hFile == (HANDLE)0xffffffff) {
    FUN_0049bbe0(param_1,0,'\x01');
    FUN_0040dab0((int *)&stack0x00000008);
  }
  else {
    DVar2 = GetFileSize(hFile,(LPDWORD)0x0);
    hFileMappingObject = (HANDLE)(*(code *)PTR_FUN_005a6d58)(hFile,0,2,0,0,0);
    if (hFileMappingObject == (HANDLE)0x0) {
      CloseHandle(hFile);
      FUN_0049bbe0(param_1,0,'\x01');
      FUN_0040dab0((int *)&stack0x00000008);
    }
    else {
      pvVar3 = MapViewOfFile(hFileMappingObject,4,0,0,0);
      if (pvVar3 == (LPVOID)0x0) {
        CloseHandle(hFile);
        CloseHandle(hFileMappingObject);
        FUN_0049bbe0(param_1,0,'\x01');
        FUN_0040dab0((int *)&stack0x00000008);
      }
      else {
        puVar4 = (undefined4 *)FUN_00478523(0x14);
        if (puVar4 == (undefined4 *)0x0) {
          local_20 = (undefined4 *)0x0;
        }
        else {
          local_20 = FUN_00484fb0(puVar4);
        }
        local_20[1] = hFile;
        local_20[2] = hFileMappingObject;
        local_20[3] = pvVar3;
        local_20[4] = DVar2;
        FUN_0049bbe0(param_1,(int)local_20,'\x01');
        FUN_0040dab0((int *)&stack0x00000008);
      }
    }
  }
  return param_1;
}



================================================================================
REQUESTED 00484150
ENTRY 00484150
NAME FUN_00484150
SIGNATURE bool __fastcall FUN_00484150(int * param_1)
BODY [[00484150, 0048416c]]


bool __fastcall FUN_00484150(int *param_1)

{
  int iVar1;
  
  iVar1 = FUN_00417940(param_1);
  return iVar1 != -1;
}



================================================================================
REQUESTED 004846b0
ENTRY 004846b0
NAME FUN_004846b0
SIGNATURE List<struct_Concurrency::details::ListEntry,class_Concurrency::details::CollectionTypes::NoCount> * __thiscall FUN_004846b0(void * this, int param_1)
BODY [[004846b0, 004846e2]]


List<struct_Concurrency::details::ListEntry,class_Concurrency::details::CollectionTypes::NoCount> *
__thiscall FUN_004846b0(void *this,int param_1)

{
  List<struct_Concurrency::details::ListEntry,class_Concurrency::details::CollectionTypes::NoCount>
  *this_00;
  List<struct_Concurrency::details::ListEntry,class_Concurrency::details::CollectionTypes::NoCount>
  *pLVar1;
  CDialogTemplate local_8 [4];
  
  pLVar1 = (List<struct_Concurrency::details::ListEntry,class_Concurrency::details::CollectionTypes::NoCount>
            *)this;
  this_00 = (List<struct_Concurrency::details::ListEntry,class_Concurrency::details::CollectionTypes::NoCount>
             *)FUN_0049bbe0(local_8,param_1,'\x01');
  Concurrency::details::
  List<struct_Concurrency::details::ListEntry,class_Concurrency::details::CollectionTypes::NoCount>
  ::Swap(this_00,pLVar1);
  CDialogTemplate::~CDialogTemplate(local_8);
  return (List<struct_Concurrency::details::ListEntry,class_Concurrency::details::CollectionTypes::NoCount>
          *)this;
}



