Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004851c0
ENTRY 004851c0
NAME FUN_004851c0
SIGNATURE undefined __cdecl FUN_004851c0(int param_1, int param_2, uint param_3, uint param_4)
BODY [[004851c0, 0048527d]]


void __cdecl FUN_004851c0(int param_1,int param_2,uint param_3,uint param_4)

{
  int local_5c;
  uint local_58;
  uint local_4c [17];
  uint local_8;
  
  FUN_00485170(param_4,local_4c);
  for (local_8 = 0; local_8 + 0x40 <= param_3; local_8 = local_8 + 0x40) {
    for (local_58 = 0; local_58 < 0x10; local_58 = local_58 + 1) {
      *(uint *)(param_1 + local_8 + local_58 * 4) =
           *(uint *)(param_2 + local_8 + local_58 * 4) ^ local_4c[local_58];
    }
  }
  local_5c = 0;
  for (; local_8 < param_3; local_8 = local_8 + 1) {
    *(byte *)(param_1 + local_8) =
         *(byte *)(param_2 + local_8) ^ *(byte *)((int)local_4c + local_5c);
    local_5c = local_5c + 1;
  }
  return;
}



================================================================================
REQUESTED 00484200
ENTRY 00484200
NAME FUN_00484200
SIGNATURE undefined4 __fastcall FUN_00484200(int param_1)
BODY [[00484200, 00484210]]


undefined4 __fastcall FUN_00484200(int param_1)

{
  return *(undefined4 *)(param_1 + 0x38);
}



================================================================================
REQUESTED 004842e0
ENTRY 004842e0
NAME FUN_004842e0
SIGNATURE void * __thiscall FUN_004842e0(void * this, void * param_1, undefined4 param_2, uint param_3)
BODY [[004842e0, 004845b6]]


void * __thiscall FUN_004842e0(void *this,void *param_1,undefined4 param_2,uint param_3)

{
  uint uVar1;
  bool bVar2;
  int *piVar3;
  int iVar4;
  void *pvVar5;
  undefined4 *local_60;
  undefined4 *local_5c;
  byte *local_58;
  undefined4 *local_54;
  undefined1 local_30 [8];
  uint local_28;
  uint local_24;
  int local_20;
  byte *local_1c;
  undefined4 *local_18;
  int local_14;
  byte *local_10;
  int local_c [2];
  
  FUN_004bc850((void *)((int)this + 0x8c),local_c,&param_2);
  piVar3 = (int *)FUN_004bc810((void *)((int)this + 0x8c),local_30);
  bVar2 = FUN_004d34a0(local_c,piVar3);
  if (bVar2) {
    FUN_0049bbe0(param_1,0,'\x01');
  }
  else {
    iVar4 = FUN_004096b0(local_c);
    local_14 = iVar4 + 4;
    if (*(int *)(iVar4 + 0x10) == 0) {
      pvVar5 = (void *)FUN_00478523(0x10);
      if (pvVar5 == (void *)0x0) {
        local_54 = (undefined4 *)0x0;
      }
      else {
        local_54 = FUN_00484600(pvVar5,0,*(undefined4 *)(local_14 + 0xc),0);
      }
      FUN_0049bbe0(param_1,(int)local_54,'\x01');
    }
    else {
      iVar4 = FUN_00427130((undefined4 *)this);
      iVar4 = FUN_004b0640(iVar4);
      local_10 = (byte *)(iVar4 + *(int *)(local_14 + 4) * 0x100);
      local_1c = (byte *)0x0;
      uVar1 = local_24;
      if ((*(uint *)(local_14 + 0x10) & 2) != 0) {
        local_1c = (byte *)thunk_FUN_00478523(*(size_t *)(local_14 + 0xc));
        local_20 = *(int *)(local_14 + 0xc);
        local_24 = FUN_004e1a70(local_1c,&local_20,(int)local_10,*(undefined4 *)(local_14 + 8));
        if ((local_24 != 0) || (uVar1 = 0, local_20 != *(int *)(local_14 + 0xc))) {
          if (local_1c != (byte *)0x0) {
            operator_delete__(local_1c);
            local_1c = (byte *)0x0;
          }
          FUN_0049bbe0(param_1,0,'\x01');
          return param_1;
        }
      }
      local_24 = uVar1;
      if ((*(uint *)(local_14 + 0x10) & 4) != 0) {
        if (local_1c == (byte *)0x0) {
          local_1c = (byte *)thunk_FUN_00478523(*(size_t *)(local_14 + 0xc));
          FUN_004845e0((int)local_1c,(int)local_10,*(uint *)(local_14 + 0xc),param_3);
        }
        else {
          FUN_004845e0((int)local_1c,(int)local_1c,*(uint *)(local_14 + 0xc),param_3);
        }
      }
      if ((*(uint *)(local_14 + 0x10) & 1) != 0) {
        if (local_1c == (byte *)0x0) {
          local_58 = local_10;
        }
        else {
          local_58 = local_1c;
        }
        local_28 = FUN_00478840(0,local_58,*(uint *)(local_14 + 0xc));
        if (*(uint *)(local_14 + 0x14) != local_28) {
          if (local_1c != (byte *)0x0) {
            operator_delete__(local_1c);
            local_1c = (byte *)0x0;
          }
          FUN_0049bbe0(param_1,0,'\x01');
          return param_1;
        }
      }
      if (local_1c == (byte *)0x0) {
        pvVar5 = (void *)FUN_00478523(0x10);
        if (pvVar5 == (void *)0x0) {
          local_60 = (undefined4 *)0x0;
        }
        else {
          local_60 = FUN_00484600(pvVar5,local_10,*(undefined4 *)(local_14 + 0xc),0);
        }
        local_18 = local_60;
      }
      else {
        pvVar5 = (void *)FUN_00478523(0x10);
        if (pvVar5 == (void *)0x0) {
          local_5c = (undefined4 *)0x0;
        }
        else {
          local_5c = FUN_00484600(pvVar5,local_1c,*(undefined4 *)(local_14 + 0xc),1);
        }
        local_18 = local_5c;
      }
      FUN_0049bbe0(param_1,(int)local_18,'\x01');
    }
  }
  return param_1;
}



================================================================================
REQUESTED 00484830
ENTRY 00484830
NAME FUN_00484830
SIGNATURE undefined4 * __thiscall FUN_00484830(void * this, undefined4 * param_1, undefined4 * param_2)
BODY [[00484830, 0048485d]]


undefined4 * __thiscall FUN_00484830(void *this,undefined4 *param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 *puVar2;
  
  *(undefined4 *)this = *param_1;
  puVar2 = (undefined4 *)this;
  for (iVar1 = 8; puVar2 = puVar2 + 1, iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = *param_2;
    param_2 = param_2 + 1;
  }
  return (undefined4 *)this;
}



================================================================================
REQUESTED 004849d0
ENTRY 004849d0
NAME FUN_004849d0
SIGNATURE void * __thiscall FUN_004849d0(void * this, void * param_1, int * param_2)
BODY [[004849d0, 004849f8]]


void * __thiscall FUN_004849d0(void *this,void *param_1,int *param_2)

{
  undefined4 *puVar1;
  
  puVar1 = FUN_00484aa0(this,param_2);
  default_error_condition(param_1,puVar1,this);
  return param_1;
}



================================================================================
REQUESTED 00484940
ENTRY 00484940
NAME FUN_00484940
SIGNATURE undefined4 * __thiscall FUN_00484940(void * this, undefined4 * param_1)
BODY [[00484940, 004849c5]]


undefined4 * __thiscall FUN_00484940(void *this,undefined4 *param_1)

{
  void *pvVar1;
  uint uVar2;
  void **ppvVar3;
  undefined4 *puVar4;
  
  FUN_004a2190(this,*(int *)((int)this + 0x10) + 1);
  uVar2 = FUN_004a2160(this,param_1);
  ppvVar3 = _STL::vector<void*,class__STL::allocator<void*>_>::operator[]
                      ((vector<void*,class__STL::allocator<void*>_> *)((int)this + 4),uVar2);
  pvVar1 = *ppvVar3;
  puVar4 = FUN_00484a30(param_1);
  *puVar4 = pvVar1;
  ppvVar3 = _STL::vector<void*,class__STL::allocator<void*>_>::operator[]
                      ((vector<void*,class__STL::allocator<void*>_> *)((int)this + 4),uVar2);
  *ppvVar3 = puVar4;
  *(int *)((int)this + 0x10) = *(int *)((int)this + 0x10) + 1;
  return puVar4 + 1;
}



================================================================================
REQUESTED 00484a10
ENTRY 00484a00
NAME FUN_00484a00
SIGNATURE void * __thiscall FUN_00484a00(void * this, uint param_1)
BODY [[00484a00, 00484a2b]]


void * __thiscall FUN_00484a00(void *this,uint param_1)

{
  FUN_00484fd0((int)this);
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}



================================================================================
REQUESTED 00484b00
ENTRY 00484aa0
NAME FUN_00484aa0
SIGNATURE undefined4 * __thiscall FUN_00484aa0(void * this, int * param_1)
BODY [[00484aa0, 00484b2a]]


undefined4 * __thiscall FUN_00484aa0(void *this,int *param_1)

{
  bool bVar1;
  uint uVar2;
  uint uVar3;
  void **ppvVar4;
  int *piVar5;
  int *piVar6;
  undefined4 *local_8;
  
  uVar2 = FUN_0044a700(*param_1);
  uVar3 = _STL::vector<void*,class__STL::allocator<void*>_>::size
                    ((vector<void*,class__STL::allocator<void*>_> *)((int)this + 4));
  ppvVar4 = _STL::vector<void*,class__STL::allocator<void*>_>::operator[]
                      ((vector<void*,class__STL::allocator<void*>_> *)((int)this + 4),uVar2 % uVar3)
  ;
  local_8 = (undefined4 *)*ppvVar4;
  while( true ) {
    if (local_8 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    piVar6 = param_1;
    piVar5 = (int *)FUN_0044a700(local_8 + 1);
    bVar1 = FUN_00409700(piVar5,piVar6);
    if (bVar1) break;
    local_8 = (undefined4 *)*local_8;
  }
  return local_8;
}



