Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004ba9c0
ENTRY 004ba9c0
NAME FUN_004ba9c0
SIGNATURE void * __cdecl FUN_004ba9c0(void * param_1, int param_2)
BODY [[004ba9c0, 004ba9e7]]


void * __cdecl FUN_004ba9c0(void *param_1,int param_2)

{
  int iVar1;
  void *pvVar2;
  
  iVar1 = param_2 + 4;
  pvVar2 = FUN_004014a0(param_1,param_2);
  FUN_004014a0(pvVar2,iVar1);
  return param_1;
}



