Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00401c20
ENTRY 00401c20
NAME FUN_00401c20
SIGNATURE undefined __thiscall FUN_00401c20(void * this, undefined4 param_1)
BODY [[00401c20, 00401c41]]


void __thiscall FUN_00401c20(void *this,undefined4 param_1)

{
  (**(code **)(**(int **)((int)this + 8) + 8))(param_1);
  return;
}



================================================================================
REQUESTED 0041a9a0
ENTRY 0041a9a0
NAME FUN_0041a9a0
SIGNATURE undefined __thiscall FUN_0041a9a0(void * this, void * param_1)
BODY [[0041a9a0, 0041a9cb]]


void __thiscall FUN_0041a9a0(void *this,void *param_1)

{
  FUN_004abfa0();
  FUN_00401430(param_1,(void *)((int)this + 8));
  return;
}



================================================================================
REQUESTED 00426d80
ENTRY 00426d80
NAME FUN_00426d80
SIGNATURE int __fastcall FUN_00426d80(int * param_1)
BODY [[00426d80, 00426d9d]]


int __fastcall FUN_00426d80(int *param_1)

{
  return (param_1[1] - *param_1) / 0x38;
}



================================================================================
REQUESTED 00426da0
ENTRY 00426da0
NAME FUN_00426da0
SIGNATURE int __thiscall FUN_00426da0(void * this, int param_1)
BODY [[00426da0, 00426dbc]]


int __thiscall FUN_00426da0(void *this,int param_1)

{
  int iVar1;
  
  iVar1 = FUN_00427130((undefined4 *)this);
  return iVar1 + param_1 * 0x38;
}



================================================================================
REQUESTED 00426d00
ENTRY 00426d00
NAME FUN_00426d00
SIGNATURE int __thiscall FUN_00426d00(void * this, int param_1)
BODY [[00426d00, 00426d1c]]


int __thiscall FUN_00426d00(void *this,int param_1)

{
  int iVar1;
  
  iVar1 = FUN_00427130((undefined4 *)this);
  return iVar1 + param_1 * 0xc;
}



================================================================================
REQUESTED 00426d20
ENTRY 00426d20
NAME FUN_00426d20
SIGNATURE int __thiscall FUN_00426d20(void * this, int param_1)
BODY [[00426d20, 00426d3c]]


int __thiscall FUN_00426d20(void *this,int param_1)

{
  int iVar1;
  
  iVar1 = FUN_00427130((undefined4 *)this);
  return iVar1 + param_1 * 6;
}



================================================================================
REQUESTED 00426d60
ENTRY 00426d60
NAME FUN_00426d60
SIGNATURE int __thiscall FUN_00426d60(void * this, int param_1)
BODY [[00426d60, 00426d7c]]


int __thiscall FUN_00426d60(void *this,int param_1)

{
  int iVar1;
  
  iVar1 = FUN_00427130((undefined4 *)this);
  return iVar1 + param_1 * 0x24;
}



================================================================================
REQUESTED 00428770
ENTRY 00428770
NAME FUN_00428770
SIGNATURE void * __thiscall FUN_00428770(void * this, void * param_1)
BODY [[00428770, 0042878e]]


void * __thiscall FUN_00428770(void *this,void *param_1)

{
  FUN_004815c0(param_1,(int *)((int)this + 0xc));
  return param_1;
}



