Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00412300
ENTRY 00412300
NAME FUN_00412300
SIGNATURE int __fastcall FUN_00412300(int param_1)
BODY [[00412300, 00412310]]


int __fastcall FUN_00412300(int param_1)

{
  return param_1 + 0x38;
}



================================================================================
REQUESTED 00412320
ENTRY 00412320
NAME FUN_00412320
SIGNATURE int __fastcall FUN_00412320(int param_1)
BODY [[00412320, 00412332]]


int __fastcall FUN_00412320(int param_1)

{
  return param_1 + 0xa4;
}



================================================================================
REQUESTED 004122e0
ENTRY 004122e0
NAME FUN_004122e0
SIGNATURE int __fastcall FUN_004122e0(int param_1)
BODY [[004122e0, 004122f0]]


int __fastcall FUN_004122e0(int param_1)

{
  return param_1 + 0x2c;
}



================================================================================
REQUESTED 00412360
ENTRY 00412360
NAME FUN_00412360
SIGNATURE int __fastcall FUN_00412360(int param_1)
BODY [[00412360, 00412370]]


int __fastcall FUN_00412360(int param_1)

{
  return param_1 + 0x5c;
}



================================================================================
REQUESTED 004136f0
ENTRY 004136f0
NAME FUN_004136f0
SIGNATURE undefined __fastcall FUN_004136f0(undefined4 param_1)
BODY [[004136f0, 0041372c]]


void __fastcall FUN_004136f0(undefined4 param_1)

{
  FUN_00413730(param_1);
  return;
}



================================================================================
REQUESTED 004137a0
ENTRY 004137a0
NAME FUN_004137a0
SIGNATURE undefined4 * __thiscall FUN_004137a0(void * this, undefined4 * param_1)
BODY [[004137a0, 004137c0]]


undefined4 * __thiscall FUN_004137a0(void *this,undefined4 *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  
  puVar2 = (undefined4 *)this;
  for (iVar1 = 9; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = *param_1;
    param_1 = param_1 + 1;
    puVar2 = puVar2 + 1;
  }
  return (undefined4 *)this;
}



