Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00470110
ENTRY 00470110
NAME FUN_00470110
SIGNATURE undefined __thiscall FUN_00470110(void * this, float * param_1, float * param_2, undefined4 * param_3, float * param_4)
BODY [[00470110, 0047037f]]


void __thiscall
FUN_00470110(void *this,float *param_1,float *param_2,undefined4 *param_3,float *param_4)

{
  void *pvVar1;
  float *pfVar2;
  float10 fVar3;
  int iVar4;
  int iVar5;
  float fVar6;
  undefined4 uVar7;
  float fVar8;
  undefined1 local_a0 [12];
  undefined1 local_94 [12];
  undefined1 local_88 [12];
  undefined1 local_7c [12];
  float local_70 [3];
  float *local_64;
  float local_60;
  float local_5c;
  float local_58;
  float local_54 [12];
  undefined2 *local_24;
  float local_20;
  float local_1c [3];
  float local_10;
  float local_c;
  float local_8;
  
  *(undefined1 *)((int)this + 0x1a0) = 1;
  *(undefined4 *)((int)this + 0x1a4) = 0;
  uVar7 = 0x2000;
  iVar5 = 0;
  iVar4 = 0;
  pvVar1 = (void *)FUN_00427130((undefined4 *)((int)this + 400));
  local_64 = (float *)FUN_00418820(pvVar1,iVar4,iVar5,uVar7);
  uVar7 = 0x2000;
  iVar5 = 0;
  iVar4 = 0;
  pvVar1 = (void *)FUN_00427130((undefined4 *)((int)this + 0x198));
  local_24 = (undefined2 *)FUN_004188d0(pvVar1,iVar4,iVar5,uVar7);
  FUN_00449b00(local_54,param_1,param_3);
  FUN_004135a0(local_70,0xbf800000,0,0);
  FUN_0042d980(&local_60,param_2,local_70);
  FUN_0042d980(local_1c,param_1,local_70);
  fVar3 = FUN_00428460(&local_60,local_1c);
  local_20 = (float)fVar3;
  if (local_20 < (float)s_333___Y_00574914._0_4_) {
    local_20 = 0.7;
  }
  fVar8 = 0.5;
  fVar6 = *(float *)((int)this + 0x1a8);
  pfVar2 = (float *)FUN_00418790(local_7c,&local_60,local_20);
  pfVar2 = (float *)FUN_00418790(local_88,pfVar2,fVar6);
  pfVar2 = (float *)FUN_00418790(local_94,pfVar2,fVar8);
  local_60 = *pfVar2;
  local_5c = pfVar2[1];
  local_58 = pfVar2[2];
  FUN_004138d0(&local_10,local_54,param_4);
  *local_64 = local_10 + local_60;
  local_64[1] = local_c + local_5c;
  local_64[2] = local_8 + local_58 + *(float *)((int)this + 0x1ac);
  local_64[3] = 0.0;
  local_64[4] = 0.0;
  *local_24 = 0;
  pfVar2 = (float *)FUN_00413650(&local_60,local_a0);
  local_60 = *pfVar2;
  local_5c = pfVar2[1];
  local_58 = pfVar2[2];
  local_64[5] = local_10 + local_60;
  local_64[6] = local_c + local_5c;
  local_64[7] = local_8 + local_58 + *(float *)((int)this + 0x1ac);
  local_64[8] = 4.99999;
  local_64[9] = 0.0;
  local_24[1] = 1;
  *(undefined4 *)((int)this + 0x1b4) = 0;
  iVar4 = FUN_00427130((undefined4 *)((int)this + 400));
  FUN_00418890(iVar4);
  iVar4 = FUN_00427130((undefined4 *)((int)this + 0x198));
  FUN_00418930(iVar4);
  *(undefined4 *)((int)this + 0x194) = 2;
  *(undefined4 *)((int)this + 0x19c) = 2;
  return;
}



================================================================================
REQUESTED 00470380
ENTRY 00470380
NAME FUN_00470380
SIGNATURE undefined __fastcall FUN_00470380(int param_1)
BODY [[00470380, 004703a8] [00470462, 00470465]]


void __fastcall FUN_00470380(int param_1)

{
  *(undefined1 *)(param_1 + 0x1a0) = 0;
  return;
}



================================================================================
REQUESTED 00470770
ENTRY 00470770
NAME FUN_00470770
SIGNATURE undefined __thiscall FUN_00470770(void * this, uint param_1, float * param_2, float * param_3, undefined4 * param_4, float * param_5, float param_6)
BODY [[00470770, 004707cd]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall
FUN_00470770(void *this,uint param_1,float *param_2,float *param_3,undefined4 *param_4,
            float *param_5,float param_6)

{
  if ((*(int *)((int)this + 0x1a4) < 100) && (*(char *)((int)this + 0x1a0) != '\0')) {
    FUN_00470470(this,param_2,param_3,param_4,param_5,(float)param_1 * param_6 * _DAT_00571a2c);
  }
  return;
}



