Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00470470
ENTRY 00470470
NAME FUN_00470470
SIGNATURE undefined __thiscall FUN_00470470(void * this, float * param_1, float * param_2, undefined4 * param_3, float * param_4, float param_5)
BODY [[00470470, 0047076b]]


void __thiscall
FUN_00470470(void *this,float *param_1,float *param_2,undefined4 *param_3,float *param_4,
            float param_5)

{
  int iVar1;
  void *pvVar2;
  float *pfVar3;
  float10 fVar4;
  int iVar5;
  float fVar6;
  undefined4 uVar7;
  float fVar8;
  undefined1 local_a0 [12];
  undefined1 local_94 [12];
  undefined1 local_88 [12];
  undefined1 local_7c [12];
  float local_70 [3];
  float *local_64;
  float local_60;
  float local_5c;
  float local_58;
  float local_54 [12];
  short *local_24;
  float local_20;
  float local_1c [3];
  float local_10;
  float local_c;
  float local_8;
  
  FUN_00449b00(local_54,param_1,param_3);
  uVar7 = 0x1000;
  iVar5 = 2;
  iVar1 = *(int *)((int)this + 0x1a4) + 2;
  pvVar2 = (void *)FUN_00427130((undefined4 *)((int)this + 400));
  local_64 = (float *)FUN_00418820(pvVar2,iVar1,iVar5,uVar7);
  uVar7 = 0x1000;
  iVar5 = 2;
  iVar1 = *(int *)((int)this + 0x1a4) + 2;
  pvVar2 = (void *)FUN_00427130((undefined4 *)((int)this + 0x198));
  local_24 = (short *)FUN_004188d0(pvVar2,iVar1,iVar5,uVar7);
  FUN_004135a0(local_70,0xbf800000,0,0);
  FUN_0042d980(&local_60,param_2,local_70);
  FUN_0042d980(local_1c,param_1,local_70);
  fVar4 = FUN_00428460(&local_60,local_1c);
  local_20 = (float)fVar4;
  if (local_20 < (float)s_333___Y_00574914._0_4_) {
    local_20 = 0.7;
  }
  fVar8 = 0.5;
  fVar6 = *(float *)((int)this + 0x1a8);
  pfVar3 = (float *)FUN_00418790(local_7c,&local_60,local_20);
  pfVar3 = (float *)FUN_00418790(local_88,pfVar3,fVar6);
  pfVar3 = (float *)FUN_00418790(local_94,pfVar3,fVar8);
  local_60 = *pfVar3;
  local_5c = pfVar3[1];
  local_58 = pfVar3[2];
  FUN_004138d0(&local_10,local_54,param_4);
  *local_64 = local_10 + local_60;
  local_64[1] = local_c + local_5c;
  local_64[2] = local_8 + local_58 + *(float *)((int)this + 0x1ac);
  local_64[3] = 0.0;
  local_64[4] = param_5 + *(float *)((int)this + 0x1b4);
  *local_24 = (short)*(undefined4 *)((int)this + 0x1a4) + 2;
  pfVar3 = (float *)FUN_00413650(&local_60,local_a0);
  local_60 = *pfVar3;
  local_5c = pfVar3[1];
  local_58 = pfVar3[2];
  local_64[5] = local_10 + local_60;
  local_64[6] = local_c + local_5c;
  local_64[7] = local_8 + local_58 + *(float *)((int)this + 0x1ac);
  local_64[8] = 0.499999;
  local_64[9] = param_5 + *(float *)((int)this + 0x1b4);
  local_24[1] = (short)*(undefined4 *)((int)this + 0x1a4) + 3;
  iVar1 = FUN_00427130((undefined4 *)((int)this + 400));
  FUN_00418890(iVar1);
  iVar1 = FUN_00427130((undefined4 *)((int)this + 0x198));
  FUN_00418930(iVar1);
  *(float *)((int)this + 0x1b4) = param_5 + *(float *)((int)this + 0x1b4);
  *(int *)((int)this + 0x1a4) = *(int *)((int)this + 0x1a4) + 2;
  *(int *)((int)this + 0x194) = *(int *)((int)this + 0x194) + 2;
  *(int *)((int)this + 0x19c) = *(int *)((int)this + 0x19c) + 2;
  if (100 < *(int *)((int)this + 0x1a4) + 0xe) {
    *(undefined1 *)((int)this + 0x1a0) = 0;
  }
  return;
}



================================================================================
REQUESTED 00410850
ENTRY 00410850
NAME FUN_00410850
SIGNATURE undefined __thiscall FUN_00410850(void * this, int param_1)
BODY [[00410850, 0041117a]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall FUN_00410850(void *this,int param_1)

{
  bool bVar1;
  char cVar2;
  undefined4 *puVar3;
  int *piVar4;
  int iVar5;
  float *pfVar6;
  void *pvVar7;
  undefined *puVar8;
  uint uVar9;
  float *pfVar10;
  int *extraout_ECX;
  int *extraout_ECX_00;
  float10 fVar11;
  ulonglong uVar12;
  float fVar13;
  undefined4 uVar14;
  byte bVar15;
  undefined4 *local_158;
  char local_152;
  undefined1 local_151;
  undefined1 local_138 [12];
  undefined1 local_12c [8];
  undefined4 *local_124;
  undefined4 *local_120;
  undefined1 local_11c [4];
  undefined1 local_118 [4];
  undefined1 local_114 [8];
  undefined4 *local_10c;
  undefined4 *local_108;
  undefined1 local_104 [4];
  undefined1 local_100 [4];
  int *local_fc;
  uint local_f8;
  CDialogTemplate local_f4 [4];
  undefined4 local_f0 [15];
  CDialogTemplate local_b4 [4];
  float local_b0 [12];
  float local_80 [3];
  undefined4 local_74;
  undefined4 local_70;
  float local_6c;
  undefined4 *local_68;
  int local_64;
  int *local_60;
  int local_5c;
  float local_58 [9];
  uint local_34;
  int *local_30;
  float local_2c [9];
  float local_8;
  
  local_30 = (int *)FUN_004126d0((void *)((int)this + 0x38),0);
  local_30 = (int *)*local_30;
  fVar11 = FUN_00412340((int)local_30);
  local_8 = (float)fVar11;
  puVar3 = (undefined4 *)FUN_00412300((int)local_30);
  FUN_004137a0(local_2c,puVar3);
  puVar3 = (undefined4 *)FUN_00412320((int)local_30);
  FUN_004137a0(local_58,puVar3);
  FUN_004a54b0((void *)((int)this + 0x28),&local_5c);
  while( true ) {
    piVar4 = (int *)FUN_004ca260((void *)((int)this + 0x28),local_100);
    bVar1 = FUN_004178c0(&local_5c,piVar4);
    if (!bVar1) break;
    local_60 = (int *)FUN_00417d40(&local_5c);
    iVar5 = FUN_00427130(local_60);
    iVar5 = FUN_00413ad0(iVar5);
    if (iVar5 == 0) {
      local_10c = (undefined4 *)local_60[3];
      piVar4 = local_60;
      local_108 = local_10c;
      if (local_10c != (undefined4 *)0x0) {
        (**(code **)*local_10c)();
        piVar4 = extraout_ECX;
      }
      FUN_004a5570(&stack0xfffffea4,&local_5c);
      piVar4 = (int *)FUN_004125a0(local_114,piVar4);
      local_5c = *piVar4;
    }
    else {
      (**(code **)(*(int *)local_60[3] + 0x30))();
      FUN_004d0fe0(&local_5c,local_104);
    }
  }
  FUN_004a54b0((void *)((int)this + 0x2c),&local_64);
  while( true ) {
    piVar4 = (int *)FUN_004ca260((void *)((int)this + 0x2c),local_118);
    bVar1 = FUN_004178c0(&local_64,piVar4);
    if (!bVar1) break;
    local_68 = (undefined4 *)FUN_00417d40(&local_64);
    iVar5 = FUN_00427130(local_68);
    iVar5 = FUN_00413ad0(iVar5);
    if (iVar5 == 0) {
      local_124 = (undefined4 *)local_68[1];
      local_120 = local_124;
      if (local_124 == (undefined4 *)0x0) {
        piVar4 = (int *)0x0;
      }
      else {
        (**(code **)*local_124)();
        piVar4 = extraout_ECX_00;
      }
      FUN_004a5570(&stack0xfffffea4,&local_64);
      piVar4 = (int *)FUN_00412640(local_12c,piVar4);
      local_64 = *piVar4;
    }
    else {
      pfVar6 = (float *)FUN_004122e0((int)local_30);
      FUN_004748c0((void *)local_68[1],param_1,pfVar6);
      FUN_004d0fe0(&local_64,local_11c);
    }
  }
  if (local_30 != (int *)0x0) {
    if (*(int *)((int)this + 0x14) != 0) {
      local_70 = 0xaa;
      local_74 = 0xf0;
      if (local_8 <= _DAT_005710b4) {
        FUN_00474d80(*(int *)((int)this + 0x14));
      }
      else {
        pfVar6 = local_80;
        pvVar7 = (void *)FUN_00412360((int)local_30);
        FUN_00413650(pvVar7,pfVar6);
        puVar8 = FUN_0040c0f0();
        puVar3 = (undefined4 *)FUN_00413a80((int)puVar8);
        FUN_004137d0(local_b0,puVar3);
        FUN_00413800(local_b0,3,0,0,0);
        puVar3 = (undefined4 *)FUN_004138d0(local_138,local_b0,local_80);
        FUN_00412380(*(void **)((int)this + 0x14),puVar3);
        FUN_00474c10(*(void **)((int)this + 0x14),local_8,0xaa,0xf0);
        (**(code **)(**(int **)((int)this + 0x14) + 0x30))();
      }
    }
    if (*(int *)((int)this + 0x20) != 0) {
      cVar2 = (**(code **)(*local_30 + 100))();
      if ((cVar2 == '\0') || (cVar2 = (**(code **)(*local_30 + 0x40))(), cVar2 == '\0')) {
        local_151 = 0;
      }
      else {
        local_151 = 1;
      }
      fVar13 = local_8;
      puVar3 = (undefined4 *)FUN_004122e0((int)local_30);
      FUN_0046cd80(*(void **)((int)this + 0x20),param_1,local_2c,local_58,puVar3,local_151,fVar13);
    }
    if (*(int *)((int)this + 0x1c) != 0) {
      cVar2 = (**(code **)(*local_30 + 100))();
      if (cVar2 == '\0') {
        if (*(char *)((int)this + 0x18) != '\0') {
          FUN_00470b50(*(void **)((int)this + 0x1c),param_1,0);
        }
        *(undefined1 *)((int)this + 0x18) = 0;
      }
      else {
        if (*(char *)((int)this + 0x18) == '\0') {
          FUN_00470b20(*(void **)((int)this + 0x1c),param_1,0);
        }
        *(undefined1 *)((int)this + 0x18) = 1;
      }
      uVar9 = FUN_004123e0(this,2,local_30);
      if (((uVar9 & 0xff) == 0) || (uVar9 = FUN_004123e0(this,3,local_30), (uVar9 & 0xff) == 0)) {
        local_152 = '\0';
      }
      else {
        local_152 = '\x01';
      }
      iVar5 = FUN_00412360((int)local_30);
      fVar11 = (float10)FUN_004136f0(iVar5);
      fVar13 = (float)fVar11;
      puVar3 = (undefined4 *)FUN_004122e0((int)local_30);
      FUN_00470b80(*(void **)((int)this + 0x1c),param_1,local_2c,local_58,puVar3,fVar13,local_152);
    }
    local_6c = 10.0;
    if (*(int *)((int)this + 0x30) != 0) {
      cVar2 = (**(code **)(*local_30 + 0x38))();
      if ((cVar2 != '\0') &&
         (fVar11 = (float10)(**(code **)(*local_30 + 0x3c))(), (float10)local_6c < fVar11)) {
        FUN_0046bc60(*(void **)((int)this + 0x30),param_1);
      }
      (**(code **)(**(int **)((int)this + 0x30) + 0x30))();
    }
    cVar2 = (**(code **)(*local_30 + 0x68))();
    if (cVar2 == '\0') {
      iVar5 = FUN_004126d0((void *)((int)this + 0x38),0);
      if (*(char *)(iVar5 + 0x20) != '\0') {
        FUN_00412090(this,0);
      }
      iVar5 = FUN_004126d0((void *)((int)this + 0x38),0);
      *(undefined1 *)(iVar5 + 0x20) = 0;
    }
    else {
      iVar5 = FUN_004126d0((void *)((int)this + 0x38),0);
      if (*(char *)(iVar5 + 0x20) == '\0') {
        FUN_00411e00(this,0);
      }
      iVar5 = FUN_004126d0((void *)((int)this + 0x38),0);
      *(undefined1 *)(iVar5 + 0x20) = 1;
    }
    if (3000 < (uint)(param_1 - *(int *)((int)this + 0x10))) {
      *(int *)((int)this + 0x10) = param_1;
      iVar5 = FUN_004c53e0((void *)((int)this + 0x44));
      if (iVar5 != 0) {
        FUN_004127c0((int *)((int)this + 0x44));
      }
      FUN_00412ce0((int *)((int)this + 0x44));
    }
    cVar2 = (**(code **)(*local_30 + 0x5c))();
    if ((cVar2 != '\0') && (2000 < (uint)(param_1 - *(int *)((int)this + 0xc)))) {
      puVar3 = (undefined4 *)FUN_00478523(0x174);
      if (puVar3 == (undefined4 *)0x0) {
        local_158 = (undefined4 *)0x0;
      }
      else {
        local_158 = FUN_00497db0(puVar3);
      }
      FUN_0045b690(local_b4,(int)local_158,'\x01');
      iVar5 = FUN_004122c0((int)local_30);
      puVar3 = (undefined4 *)FUN_00413c30(iVar5);
      FUN_00413980(local_f0,puVar3);
      FUN_00469690(&stack0xfffffea4,(int *)local_b4);
      iVar5 = FUN_00427130((undefined4 *)((int)this + 0x48));
      FUN_00413b10(iVar5);
      puVar3 = local_f0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_b4);
      FUN_00413c50(pvVar7,puVar3);
      cVar2 = '\x01';
      piVar4 = FUN_0049a240((undefined4 *)((int)this + 8));
      FUN_0045b690(local_f4,(int)piVar4,cVar2);
      FUN_00469690(&stack0xfffffea4,(int *)local_f4);
      iVar5 = FUN_00427130((undefined4 *)local_b4);
      FUN_00413b10(iVar5);
      FUN_00412790((void *)((int)this + 0x44),(int *)local_b4);
      *(int *)((int)this + 0xc) = param_1;
      bVar15 = 0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_b4);
      FUN_004984d0(pvVar7,bVar15);
      bVar15 = 0;
      uVar14 = 0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_b4);
      FUN_00498b10(pvVar7,uVar14,bVar15);
      iVar5 = FUN_00427130((undefined4 *)local_b4);
      FUN_00498f50(iVar5);
      bVar15 = 0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_f4);
      FUN_004984d0(pvVar7,bVar15);
      bVar15 = 0;
      uVar14 = 0;
      pvVar7 = (void *)FUN_00427130((undefined4 *)local_f4);
      FUN_00498b10(pvVar7,uVar14,bVar15);
      iVar5 = FUN_00427130((undefined4 *)local_f4);
      FUN_00498f50(iVar5);
      CDialogTemplate::~CDialogTemplate(local_f4);
      CDialogTemplate::~CDialogTemplate(local_b4);
    }
    FUN_0046e5d0(*(void **)((int)this + 0x24),param_1);
    if ((*(int *)((int)this + 0x34) != 0) &&
       (iVar5 = FUN_004126d0((void *)((int)this + 0x38),0), *(char *)(iVar5 + 0x20) == '\0')) {
      uVar12 = FUN_00478a48();
      FUN_004123c0(*(void **)((int)this + 0x34),0x78 - (int)uVar12);
      pfVar6 = (float *)FUN_00412360((int)local_30);
      pfVar10 = (float *)FUN_004122e0((int)local_30);
      FUN_0046f1e0(*(void **)((int)this + 0x34),param_1,local_2c,local_58,pfVar10,pfVar6);
    }
  }
  local_34 = FUN_004126b0((int *)((int)this + 0x38));
  if (1 < local_34) {
    for (local_f8 = 1; local_f8 < local_34; local_f8 = local_f8 + 1) {
      puVar3 = (undefined4 *)FUN_004126d0((void *)((int)this + 0x38),local_f8);
      local_fc = (int *)*puVar3;
      cVar2 = (**(code **)(*local_fc + 0x68))();
      if (cVar2 == '\0') {
        iVar5 = FUN_004126d0((void *)((int)this + 0x38),local_f8);
        if (*(char *)(iVar5 + 0x20) != '\0') {
          FUN_00412090(this,local_f8);
        }
        iVar5 = FUN_004126d0((void *)((int)this + 0x38),local_f8);
        *(undefined1 *)(iVar5 + 0x20) = 0;
      }
      else {
        iVar5 = FUN_004126d0((void *)((int)this + 0x38),local_f8);
        if (*(char *)(iVar5 + 0x20) == '\0') {
          FUN_00411e00(this,local_f8);
        }
        iVar5 = FUN_004126d0((void *)((int)this + 0x38),local_f8);
        *(undefined1 *)(iVar5 + 0x20) = 1;
      }
    }
  }
  return;
}



================================================================================
REQUESTED 00411180
ENTRY 00411180
NAME FUN_00411180
SIGNATURE undefined __fastcall FUN_00411180(undefined4 * param_1)
BODY [[00411180, 0041179f]]


void __fastcall FUN_00411180(undefined4 *param_1)

{
  undefined *puVar1;
  int *piVar2;
  int *piVar3;
  int iVar4;
  void *pvVar5;
  undefined4 *puVar6;
  undefined4 *puVar7;
  undefined4 extraout_ECX;
  undefined4 extraout_ECX_00;
  undefined4 extraout_ECX_01;
  CDialogTemplate *pCVar8;
  undefined4 uVar9;
  undefined4 uVar10;
  char cVar11;
  undefined4 uVar12;
  void *local_144;
  undefined4 *local_140;
  CMFCOutlookBarPaneAdapter *local_13c;
  CMFCOutlookBarPaneAdapter *local_138;
  undefined4 *local_134;
  CMFCOutlookBarPaneAdapter *local_130;
  undefined1 local_118 [12];
  undefined1 local_10c [12];
  undefined4 *local_100;
  void *local_f8;
  CDialogTemplate local_f4 [4];
  CMFCOutlookBarPaneAdapter *local_f0;
  undefined1 local_ec [12];
  undefined1 local_e0 [12];
  undefined4 *local_d4;
  CMFCOutlookBarPaneAdapter *local_d0;
  int local_c0 [3];
  int local_b4 [3];
  int local_a8 [3];
  int local_9c [3];
  int local_90 [3];
  int local_84;
  CDialogTemplate local_80 [4];
  int local_7c;
  undefined4 local_78 [3];
  int local_6c [6];
  CDialogTemplate local_54 [4];
  undefined4 local_50 [3];
  CDialogTemplate local_44 [4];
  int local_40 [6];
  CDialogTemplate local_28 [4];
  CDialogTemplate local_24 [4];
  CDialogTemplate local_20 [4];
  int local_1c [6];
  
  FUN_0040cd80(&local_84,L"booster");
  piVar2 = &local_84;
  pCVar8 = local_54;
  puVar1 = FUN_0040ec80();
  FUN_00420340(puVar1,pCVar8,piVar2);
  FUN_0040dab0(&local_84);
  piVar2 = (int *)FUN_00427130((undefined4 *)local_54);
  uVar12 = 0x7331;
  uVar9 = extraout_ECX;
  FUN_0040cd80(&stack0xfffffeb0,L"effect");
  piVar3 = (int *)FUN_0040c190(local_90,uVar9,uVar12);
  FID_conflict_operator_(&stack0xfffffeb0,piVar3);
  (**(code **)(*piVar2 + 0x3c))();
  FUN_0040c020(local_90);
  cVar11 = '\x01';
  iVar4 = FUN_00427130((undefined4 *)local_44);
  FUN_00412d50(local_40,iVar4,cVar11);
  FUN_00412dd0(local_40,param_1);
  FUN_00469690(&stack0xfffffea8,(int *)local_54);
  pvVar5 = (void *)FUN_00427130(param_1);
  FUN_00411990(pvVar5);
  puVar6 = local_50;
  pvVar5 = (void *)FUN_00427130(param_1);
  FUN_00413ca0(pvVar5,puVar6);
  FUN_00413610(local_50,1.2);
  puVar6 = local_50;
  pvVar5 = (void *)FUN_00427130(param_1);
  FUN_00413cc0(pvVar5,puVar6);
  FUN_0040cd80(local_9c,L"boosterwave");
  piVar2 = local_9c;
  pCVar8 = local_20;
  puVar1 = FUN_0040ec80();
  FUN_00420340(puVar1,pCVar8,piVar2);
  FUN_0040dab0(local_9c);
  piVar2 = (int *)FUN_00427130((undefined4 *)local_20);
  uVar12 = 0x7331;
  uVar9 = extraout_ECX_00;
  FUN_0040cd80(&stack0xfffffea0,L"effect");
  piVar3 = (int *)FUN_0040c190(local_a8,uVar9,uVar12);
  FID_conflict_operator_(&stack0xfffffea0,piVar3);
  (**(code **)(*piVar2 + 0x3c))();
  FUN_0040c020(local_a8);
  cVar11 = '\x01';
  iVar4 = FUN_00427130((undefined4 *)local_28);
  FUN_00412d50(local_6c,iVar4,cVar11);
  FUN_00412dd0(local_6c,param_1 + 1);
  FUN_00469690(&stack0xfffffe98,(int *)local_20);
  pvVar5 = (void *)FUN_00427130(param_1 + 1);
  FUN_00411990(pvVar5);
  FUN_0040cd80(local_b4,L"shockwave");
  piVar2 = local_b4;
  pCVar8 = local_24;
  puVar1 = FUN_0040ec80();
  FUN_00420340(puVar1,pCVar8,piVar2);
  FUN_0040dab0(local_b4);
  piVar2 = (int *)FUN_00427130((undefined4 *)local_24);
  uVar12 = 0x7331;
  uVar9 = extraout_ECX_01;
  FUN_0040cd80(&stack0xfffffe90,L"effect");
  piVar3 = (int *)FUN_0040c190(local_c0,uVar9,uVar12);
  FID_conflict_operator_(&stack0xfffffe90,piVar3);
  (**(code **)(*piVar2 + 0x3c))();
  FUN_0040c020(local_c0);
  cVar11 = '\x01';
  iVar4 = FUN_00427130((undefined4 *)local_80);
  FUN_00412d50(local_1c,iVar4,cVar11);
  FUN_00412dd0(local_1c,param_1 + 2);
  FUN_00469690(&stack0xfffffe88,(int *)local_24);
  pvVar5 = (void *)FUN_00427130(param_1 + 2);
  FUN_00411990(pvVar5);
  FUN_00469690(&stack0xfffffe88,param_1 + 2);
  FUN_0046a720();
  piVar2 = (int *)FUN_004126d0(param_1 + 0xe,0);
  local_7c = *piVar2;
  local_d0 = (CMFCOutlookBarPaneAdapter *)FUN_00478523(0xc84);
  if (local_d0 == (CMFCOutlookBarPaneAdapter *)0x0) {
    local_130 = (CMFCOutlookBarPaneAdapter *)0x0;
  }
  else {
    local_130 = FUN_00474970(local_d0);
  }
  param_1[5] = local_130;
  local_d4 = (undefined4 *)FUN_00478523(0x388);
  if (local_d4 == (undefined4 *)0x0) {
    local_134 = (undefined4 *)0x0;
  }
  else {
    local_134 = FUN_00470860(local_d4);
  }
  param_1[7] = local_134;
  puVar6 = FUN_004135a0(local_e0,0x3f1c28f6,0x3f000000,0);
  puVar7 = FUN_004135a0(local_ec,0xbf1c28f6,0x3f000000,0);
  FUN_00470ad0((void *)param_1[7],puVar7,puVar6);
  local_f0 = (CMFCOutlookBarPaneAdapter *)FUN_00478523(0x1a0);
  if (local_f0 == (CMFCOutlookBarPaneAdapter *)0x0) {
    local_138 = (CMFCOutlookBarPaneAdapter *)0x0;
  }
  else {
    local_138 = FUN_0046b180(local_f0);
  }
  param_1[0xc] = local_138;
  FUN_0046bd00((void *)param_1[0xc],local_7c);
  puVar6 = local_78;
  iVar4 = 0;
  pCVar8 = local_f4;
  pvVar5 = (void *)FUN_004122c0(local_7c);
  puVar7 = (undefined4 *)FUN_00413e40(pvVar5,pCVar8,iVar4);
  pvVar5 = (void *)FUN_00427130(puVar7);
  FUN_00413c80(pvVar5,puVar6);
  CDialogTemplate::~CDialogTemplate(local_f4);
  puVar6 = (undefined4 *)0x468;
  uVar9 = 0x4115e9;
  local_f8 = (void *)FUN_00478523(0x468);
  if (local_f8 == (void *)0x0) {
    local_13c = (CMFCOutlookBarPaneAdapter *)0x0;
  }
  else {
    puVar6 = (undefined4 *)FUN_004122e0(local_7c);
    uVar9 = 1;
    pCVar8 = (CDialogTemplate *)0x411611;
    local_13c = FUN_0046eb70(local_f8,1,puVar6);
  }
  param_1[0xd] = local_13c;
  FUN_004135d0(&stack0xfffffe80,local_78);
  FUN_00412480((void *)param_1[0xd],0,pCVar8,uVar9,puVar6);
  FUN_0046fc40((void *)param_1[0xd],local_7c);
  local_100 = (undefined4 *)FUN_00478523(0x2c);
  if (local_100 == (undefined4 *)0x0) {
    local_140 = (undefined4 *)0x0;
  }
  else {
    local_140 = FUN_0046cae0(local_100);
  }
  param_1[8] = local_140;
  uVar10 = 0xbe4ccccd;
  uVar12 = 0;
  uVar9 = 0;
  puVar6 = FUN_004135a0(local_10c,0xbf3851ec,0x3f333333,0);
  FUN_0046cbc0((void *)param_1[8],puVar6,uVar9,uVar12,uVar10);
  uVar10 = 0x3e4ccccd;
  uVar12 = 0;
  uVar9 = 0;
  puVar6 = FUN_004135a0(local_118,0x3f3851ec,0x3f333333,0);
  FUN_0046cbc0((void *)param_1[8],puVar6,uVar9,uVar12,uVar10);
  pvVar5 = (void *)FUN_00478523(0x20);
  if (pvVar5 == (void *)0x0) {
    local_144 = (void *)0x0;
  }
  else {
    local_144 = FUN_0046df50(pvVar5,param_1 + 0xe);
  }
  param_1[9] = local_144;
  FUN_00412da0(local_1c);
  CDialogTemplate::~CDialogTemplate(local_80);
  CDialogTemplate::~CDialogTemplate(local_24);
  FUN_00412da0(local_6c);
  CDialogTemplate::~CDialogTemplate(local_28);
  CDialogTemplate::~CDialogTemplate(local_20);
  FUN_00412da0(local_40);
  CDialogTemplate::~CDialogTemplate(local_44);
  CDialogTemplate::~CDialogTemplate(local_54);
  return;
}



