Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00470050
ENTRY 00470050
NAME FUN_00470050
SIGNATURE undefined4 __fastcall FUN_00470050(int param_1)
BODY [[00470050, 004700dc]]


undefined4 __fastcall FUN_00470050(int param_1)

{
  shared_ptr<class___ExceptionPtr> *psVar1;
  undefined4 extraout_EAX;
  CDialogTemplate *pCVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  undefined4 uVar6;
  int iVar7;
  CDialogTemplate local_c [4];
  CDialogTemplate local_8 [4];
  
  *(undefined4 *)(param_1 + 0x1a4) = 0;
  iVar7 = 0;
  uVar6 = 0x102;
  uVar5 = 0x208;
  uVar4 = 0x66;
  uVar3 = 0x14;
  pCVar2 = local_8;
  FUN_0040c0f0();
  psVar1 = (shared_ptr<class___ExceptionPtr> *)FUN_004a4b90(pCVar2,uVar3,uVar4,uVar5,uVar6,iVar7);
  std::shared_ptr<class___ExceptionPtr>::operator=
            ((shared_ptr<class___ExceptionPtr> *)(param_1 + 400),psVar1);
  CDialogTemplate::~CDialogTemplate(local_8);
  iVar7 = 0;
  uVar4 = 0x208;
  uVar3 = 0x6a;
  pCVar2 = local_c;
  FUN_0040c0f0();
  psVar1 = (shared_ptr<class___ExceptionPtr> *)FUN_004a4bf0(pCVar2,uVar3,uVar4,iVar7);
  std::shared_ptr<class___ExceptionPtr>::operator=
            ((shared_ptr<class___ExceptionPtr> *)(param_1 + 0x198),psVar1);
  CDialogTemplate::~CDialogTemplate(local_c);
  return CONCAT31((int3)((uint)extraout_EAX >> 8),1);
}



================================================================================
REQUESTED 004700e0
ENTRY 004700e0
NAME FUN_004700e0
SIGNATURE undefined __fastcall FUN_004700e0(int param_1)
BODY [[004700e0, 0047010a]]


void __fastcall FUN_004700e0(int param_1)

{
  FUN_004179a0((void *)(param_1 + 400),0);
  FUN_00417a50((void *)(param_1 + 0x198),0);
  return;
}



================================================================================
REQUESTED 004709f0
ENTRY 004709f0
NAME FUN_004709f0
SIGNATURE undefined4 __fastcall FUN_004709f0(int param_1)
BODY [[004709f0, 00470a3f]]


undefined4 __fastcall FUN_004709f0(int param_1)

{
  undefined4 uVar1;
  
  *(undefined4 *)(param_1 + 0x340) = 0x32;
  *(undefined1 *)(param_1 + 0x34c) = 0;
  *(undefined4 *)(param_1 + 0x354) = 1000;
  *(undefined1 *)(param_1 + 0x34d) = 0;
  *(undefined4 *)(param_1 + 0x35c) = 1000;
  uVar1 = FUN_00470f50(param_1);
  return CONCAT31((int3)((uint)uVar1 >> 8),1);
}



================================================================================
REQUESTED 00470a40
ENTRY 00470a40
NAME FUN_00470a40
SIGNATURE undefined __fastcall FUN_00470a40(int param_1)
BODY [[00470a40, 00470acb]]


void __fastcall FUN_00470a40(int param_1)

{
  undefined4 *puVar1;
  int local_8;
  
  for (local_8 = 0; local_8 < 0x32; local_8 = local_8 + 1) {
    puVar1 = *(undefined4 **)(param_1 + 0x1a0 + local_8 * 8);
    if (puVar1 != (undefined4 *)0x0) {
      (**(code **)*puVar1)(1);
    }
    puVar1 = *(undefined4 **)(param_1 + 0x10 + local_8 * 8);
    if (puVar1 != (undefined4 *)0x0) {
      (**(code **)*puVar1)(1);
    }
  }
  return;
}



