Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00455c80
ENTRY 00455c80
NAME FUN_00455c80
SIGNATURE undefined __fastcall FUN_00455c80(void * param_1)
BODY [[00455c80, 00456c05]]


void __fastcall FUN_00455c80(void *param_1)

{
  int iVar1;
  undefined *puVar2;
  undefined4 *puVar3;
  int *piVar4;
  int *piVar5;
  shared_ptr<class___ExceptionPtr> *psVar6;
  undefined4 uVar7;
  uint uVar8;
  void *pvVar9;
  float *pfVar10;
  int iVar11;
  undefined4 extraout_ECX;
  undefined4 extraout_ECX_00;
  undefined4 extraout_ECX_01;
  undefined4 extraout_ECX_02;
  undefined4 extraout_ECX_03;
  undefined4 extraout_ECX_04;
  undefined4 extraout_ECX_05;
  undefined4 extraout_ECX_06;
  undefined4 extraout_ECX_07;
  undefined4 extraout_ECX_08;
  CDialogTemplate *pCVar12;
  undefined1 *puVar13;
  undefined1 *puVar14;
  wchar_t *pwVar15;
  undefined4 uVar16;
  undefined1 uVar17;
  uint uVar18;
  char cVar19;
  undefined4 uVar20;
  undefined4 *local_1e0;
  undefined4 *local_1c0;
  CDialogTemplate local_1b4 [4];
  CDialogTemplate local_1b0 [8];
  CDialogTemplate local_1a8 [12];
  CDialogTemplate local_19c [4];
  int local_198;
  CDialogTemplate local_194 [4];
  int local_190 [2];
  int local_188 [2];
  undefined4 *local_180;
  int local_170 [3];
  CDialogTemplate local_164 [28];
  CDialogTemplate local_148 [8];
  int local_140 [3];
  CDialogTemplate local_134 [4];
  int local_130 [2];
  CDialogTemplate local_128 [8];
  int local_120 [3];
  CDialogTemplate local_114 [4];
  int local_110 [2];
  CDialogTemplate local_108 [8];
  int local_100 [3];
  CDialogTemplate local_f4 [4];
  int local_f0 [2];
  CDialogTemplate local_e8 [8];
  int local_e0 [3];
  CDialogTemplate local_d4 [4];
  int local_d0 [2];
  CDialogTemplate local_c8 [8];
  int local_c0 [3];
  CDialogTemplate local_b4 [4];
  int local_b0 [2];
  CDialogTemplate local_a8 [8];
  int local_a0 [3];
  CDialogTemplate local_94 [4];
  int local_90;
  int local_8c [4];
  undefined4 *local_7c;
  int local_74 [6];
  CDialogTemplate local_5c [4];
  CDialogTemplate local_58 [4];
  undefined4 local_54;
  undefined4 local_50;
  undefined4 local_4c;
  undefined4 local_48;
  undefined1 local_44 [16];
  uint local_34;
  uint local_30;
  shared_ptr<class___ExceptionPtr> local_2c [4];
  int local_28;
  CDialogTemplate local_24 [4];
  CDialogTemplate local_20 [4];
  int local_1c [6];
  
  FUN_00469690(&stack0xfffffe10,(int *)&stack0x00000004);
  FUN_0044d460(param_1);
  FUN_00427130((undefined4 *)&stack0x00000004);
  local_28 = __RTDynamicCast();
  local_7c = (undefined4 *)FUN_00478523(0x78);
  if (local_7c == (undefined4 *)0x0) {
    local_1c0 = (undefined4 *)0x0;
  }
  else {
    local_1c0 = FUN_00424010(local_7c);
  }
  FUN_0044bde0((void *)((int)param_1 + 200),(int)local_1c0);
  FUN_00469690(&stack0xfffffe10,(int *)(local_28 + 0x14));
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 200));
  FUN_004240f0(iVar1);
  cVar19 = '\x01';
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x4c));
  FUN_0045b690(&stack0xfffffe10,iVar1,cVar19);
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 200));
  FUN_00453fc0(iVar1);
  FUN_0045b5d0(&stack0xfffffe10,(undefined4 *)((int)param_1 + 200));
  puVar2 = FUN_0042af90();
  FUN_0042bb70((int)puVar2);
  FUN_0040cd80(local_8c,L"");
  FUN_00461c90((int *)(local_28 + 8),local_8c,0x11);
  FUN_0040dab0(local_8c);
  FUN_004b30e0((undefined4 *)local_2c);
  FUN_0040cd80(&local_90,L"kart");
  piVar4 = &local_90;
  pCVar12 = local_94;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar12,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar20 = 0x766177;
  uVar7 = extraout_ECX;
  FUN_0040cd80(&stack0xfffffe08,L"motor");
  piVar5 = (int *)FUN_0040c190(local_a0,uVar7,uVar20);
  FID_conflict_operator_(&stack0xfffffe08,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_a8);
  CDialogTemplate::~CDialogTemplate(local_94);
  FUN_0040c020(local_a0);
  FUN_0040dab0(&local_90);
  FUN_00469690(&stack0xfffffe00,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0xf4) = uVar7;
  uVar18 = 3;
  uVar8 = *(uint *)((int)param_1 + 0xf4);
  puVar2 = FUN_0041e9f0();
  uVar8 = FUN_004da090(puVar2,uVar8,uVar18);
  *(uint *)((int)param_1 + 0xf8) = uVar8;
  uVar7 = 0;
  iVar1 = *(int *)((int)param_1 + 0xf8);
  puVar2 = FUN_0041e9f0();
  FUN_004dae60(puVar2,iVar1,uVar7);
  iVar1 = *(int *)((int)param_1 + 0xf8);
  puVar2 = FUN_0041e9f0();
  FUN_004da4d0(puVar2,iVar1);
  FUN_0040cd80(local_b0,L"kart");
  piVar4 = local_b0;
  pCVar12 = local_b4;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar12,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar20 = 0x766177;
  uVar7 = extraout_ECX_00;
  FUN_0040cd80(&stack0xfffffdf8,L"drift");
  piVar5 = (int *)FUN_0040c190(local_c0,uVar7,uVar20);
  FID_conflict_operator_(&stack0xfffffdf8,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_c8);
  CDialogTemplate::~CDialogTemplate(local_b4);
  FUN_0040c020(local_c0);
  FUN_0040dab0(local_b0);
  FUN_00469690(&stack0xfffffdf0,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x100) = uVar7;
  *(undefined1 *)((int)param_1 + 0x108) = 0;
  FUN_0040cd80(local_d0,L"kart");
  piVar4 = local_d0;
  pCVar12 = local_d4;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar12,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar20 = 0x766177;
  uVar7 = extraout_ECX_01;
  FUN_0040cd80(&stack0xfffffde8,L"crash");
  piVar5 = (int *)FUN_0040c190(local_e0,uVar7,uVar20);
  FID_conflict_operator_(&stack0xfffffde8,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_e8);
  CDialogTemplate::~CDialogTemplate(local_d4);
  FUN_0040c020(local_e0);
  FUN_0040dab0(local_d0);
  FUN_00469690(&stack0xfffffde0,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x10c) = uVar7;
  FUN_0040cd80(local_f0,L"kart");
  piVar4 = local_f0;
  pCVar12 = local_f4;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar12,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar20 = 0x766177;
  uVar7 = extraout_ECX_02;
  FUN_0040cd80(&stack0xfffffdd8,L"shock");
  piVar5 = (int *)FUN_0040c190(local_100,uVar7,uVar20);
  FID_conflict_operator_(&stack0xfffffdd8,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_108);
  CDialogTemplate::~CDialogTemplate(local_f4);
  FUN_0040c020(local_100);
  FUN_0040dab0(local_f0);
  FUN_00469690(&stack0xfffffdd0,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x110) = uVar7;
  FUN_0040cd80(local_110,L"booster");
  piVar4 = local_110;
  pCVar12 = local_114;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420520(puVar2,pCVar12,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar20 = 0x766177;
  uVar7 = extraout_ECX_03;
  FUN_0040cd80(&stack0xfffffdc8,L"booster");
  piVar5 = (int *)FUN_0040c190(local_120,uVar7,uVar20);
  FID_conflict_operator_(&stack0xfffffdc8,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_128);
  CDialogTemplate::~CDialogTemplate(local_114);
  FUN_0040c020(local_120);
  FUN_0040dab0(local_110);
  FUN_00469690(&stack0xfffffdc0,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x114) = uVar7;
  FUN_0040cd80(local_130,L"etc");
  piVar4 = local_130;
  pCVar12 = local_134;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_00420490(puVar2,pCVar12,piVar4);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar20 = 0x766177;
  uVar7 = extraout_ECX_04;
  FUN_0040cd80(&stack0xfffffdb8,L"wrongway");
  piVar5 = (int *)FUN_0040c190(local_140,uVar7,uVar20);
  FID_conflict_operator_(&stack0xfffffdb8,piVar5);
  psVar6 = (shared_ptr<class___ExceptionPtr> *)(**(code **)(*piVar4 + 0x3c))();
  std::shared_ptr<class___ExceptionPtr>::operator=(local_2c,psVar6);
  CDialogTemplate::~CDialogTemplate(local_148);
  CDialogTemplate::~CDialogTemplate(local_134);
  FUN_0040c020(local_140);
  FUN_0040dab0(local_130);
  FUN_00469690(&stack0xfffffdb0,(int *)local_2c);
  puVar2 = FUN_0041e9f0();
  uVar7 = FUN_004d9810((int)puVar2);
  *(undefined4 *)((int)param_1 + 0x118) = uVar7;
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)local_2c);
  local_30 = 0;
  while( true ) {
    iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    uVar8 = FUN_004496b0((int *)(iVar1 + 0x18));
    if (uVar8 <= local_30) break;
    uVar17 = 1;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + local_30 * 4 + 0x54));
    FUN_00453fa0(pvVar9,uVar17);
    piVar4 = (int *)FUN_00427130((undefined4 *)((int)param_1 + local_30 * 4 + 0x54));
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 200));
    FUN_00424530(pvVar9,piVar4);
    local_30 = local_30 + 1;
  }
  *(undefined1 *)((int)param_1 + 0xcc) = 0;
  *(undefined4 *)((int)param_1 + 0xd4) = 0;
  *(undefined1 *)((int)param_1 + 0xcd) = 0;
  *(undefined4 *)((int)param_1 + 0xd0) = 0;
  *(undefined4 *)((int)param_1 + 0xdc) = 0;
  *(undefined4 *)((int)param_1 + 0xe0) = 0;
  *(undefined4 *)((int)param_1 + 0xe4) = 0;
  *(undefined4 *)((int)param_1 + 0xe8) = 0;
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
  puVar3 = (undefined4 *)(iVar1 + 0xc);
  puVar2 = FUN_00459710();
  pvVar9 = FUN_00420fb0(puVar2,puVar3);
  *(undefined4 *)((int)param_1 + 0xd8) = *(undefined4 *)((int)pvVar9 + 0xc);
  uVar7 = *(undefined4 *)((int)param_1 + 0xd8);
  pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 200));
  FUN_004247e0(pvVar9,uVar7);
  iVar1 = FUN_0044fac0((int)param_1);
  FUN_00455230(iVar1);
  cVar19 = '\x01';
  uVar16 = 0;
  uVar20 = 0;
  uVar7 = extraout_ECX_05;
  FUN_0040cd80(&stack0xfffffda4,L"ChaseCameraman");
  FUN_0044f810(param_1,uVar7,uVar20,uVar16,cVar19);
  uVar7 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
  pvVar9 = (void *)FUN_00453ff0((int)param_1);
  FUN_00497320(pvVar9,uVar7);
  *(undefined4 *)((int)param_1 + 0x11c) = 0;
  *(undefined4 *)((int)param_1 + 0x120) = 0;
  *(undefined4 *)((int)param_1 + 0xec) = 3;
  uVar8 = *(uint *)((int)param_1 + 0xec);
  pvVar9 = (void *)FUN_0044fac0((int)param_1);
  FUN_00455670(pvVar9,uVar8);
  for (local_34 = 0; local_34 < *(uint *)((int)param_1 + 0xec); local_34 = local_34 + 1) {
    uVar18 = 6;
    uVar8 = local_34;
    pvVar9 = (void *)FUN_0044fac0((int)param_1);
    FUN_00455770(pvVar9,uVar8,uVar18);
  }
  FUN_0040cd80(&stack0xfffffdb0,L"start");
  iVar1 = FUN_0044fac0((int)param_1);
  FUN_0044ba20(iVar1);
  FUN_0040cd80(&stack0xfffffdb0,L"finish");
  iVar1 = FUN_0044fac0((int)param_1);
  FUN_0044ba20(iVar1);
  FUN_0040cd80(&stack0xfffffdb0,L"finallap");
  iVar1 = FUN_0044fac0((int)param_1);
  FUN_0044ba20(iVar1);
  FUN_0040cd80(&stack0xfffffdb0,L"1lap");
  iVar1 = FUN_0044fac0((int)param_1);
  FUN_0044ba20(iVar1);
  pCVar12 = local_164;
  puVar2 = FUN_0040ec80();
  puVar3 = (undefined4 *)FUN_004391a0(puVar2,pCVar12);
  piVar4 = (int *)FUN_00427130(puVar3);
  uVar20 = 0x7331;
  uVar7 = extraout_ECX_06;
  FUN_0040cd80(&stack0xfffffda8,L"readyCamera");
  piVar5 = (int *)FUN_0040c190(local_170,uVar7,uVar20);
  FID_conflict_operator_(&stack0xfffffda8,piVar5);
  (**(code **)(*piVar4 + 0x3c))();
  CDialogTemplate::~CDialogTemplate(local_164);
  FUN_0040c020(local_170);
  cVar19 = '\x01';
  iVar1 = FUN_00427130((undefined4 *)local_24);
  FUN_00412d50(local_1c,iVar1,cVar19);
  FUN_004b30e0((undefined4 *)local_20);
  FUN_00412dd0(local_1c,local_20);
  cVar19 = '\x01';
  uVar16 = 0;
  uVar20 = 0;
  uVar7 = extraout_ECX_07;
  FUN_0040cd80(&stack0xfffffd94,L"KartReCameraman");
  FUN_0044f810(param_1,uVar7,uVar20,uVar16,cVar19);
  uVar7 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
  pvVar9 = (void *)FUN_00453ff0((int)param_1);
  FUN_00497340(pvVar9,uVar7);
  FUN_00469690(&stack0xfffffda0,(int *)local_20);
  iVar1 = FUN_00453ff0((int)param_1);
  FUN_00445590(iVar1);
  uVar17 = 1;
  pvVar9 = (void *)FUN_00453ff0((int)param_1);
  FUN_004a1ac0(pvVar9,uVar17);
  *(undefined1 *)((int)param_1 + 0x124) = 0;
  local_180 = (undefined4 *)FUN_00478523(0x1c);
  if (local_180 == (undefined4 *)0x0) {
    local_1e0 = (undefined4 *)0x0;
  }
  else {
    local_1e0 = FUN_004593b0(local_180);
  }
  FUN_0044bde0((void *)((int)param_1 + 0x128),(int)local_1e0);
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
  piVar4 = (int *)(iVar1 + 0xc);
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x128));
  FUN_0040c210((void *)(iVar1 + 8),piVar4);
  *(undefined4 *)((int)param_1 + 300) = 0;
  FUN_0044bde0((void *)((int)param_1 + 0x150),0);
  FUN_00459480((int)&local_54);
  local_54 = 0;
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
  puVar3 = (undefined4 *)FUN_004122e0(iVar1);
  local_50 = *puVar3;
  local_4c = puVar3[1];
  local_48 = puVar3[2];
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
  pfVar10 = (float *)FUN_00412300(iVar1);
  FUN_00482180(local_44,pfVar10);
  puVar3 = &local_54;
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x128));
  FUN_00459560((void *)(iVar1 + 0x10),puVar3);
  pCVar12 = local_58;
  puVar2 = FUN_0040ec80();
  FUN_0042c530(puVar2,pCVar12);
  piVar4 = (int *)FUN_00427130((undefined4 *)local_58);
  pwVar15 = L".sav";
  iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
  piVar5 = (int *)FUN_00412510(local_188,(int *)(iVar1 + 0xc),pwVar15);
  FUN_0047dcc0(&stack0xfffffd98,piVar5);
  (**(code **)(*piVar4 + 0x3c))();
  FUN_0040dab0(local_188);
  iVar1 = FUN_00417940((int *)local_5c);
  if (iVar1 != -1) {
    cVar19 = '\0';
    iVar1 = FUN_00427130((undefined4 *)local_5c);
    FUN_00412d50(local_74,iVar1,cVar19);
    FUN_00412dd0(local_74,(void *)((int)param_1 + 0x150));
    FUN_00412da0(local_74);
  }
  CDialogTemplate::~CDialogTemplate(local_5c);
  CDialogTemplate::~CDialogTemplate(local_58);
  iVar1 = FUN_00417940((int *)((int)param_1 + 0x150));
  if (iVar1 != -1) {
    cVar19 = '\x01';
    uVar7 = extraout_ECX_08;
    FUN_0049bbe0(&stack0xfffffd8c,0,'\x01');
    iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
    iVar1 = FUN_00459340(iVar1);
    iVar11 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
    iVar11 = FUN_00459320(iVar11);
    piVar4 = local_190;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x54));
    piVar4 = (int *)FUN_004592f0(pvVar9,piVar4);
    pCVar12 = local_194;
    puVar2 = FUN_00417e20();
    psVar6 = (shared_ptr<class___ExceptionPtr> *)
             FUN_00414cb0(puVar2,pCVar12,piVar4,iVar11,iVar1,uVar7,cVar19);
    std::shared_ptr<class___ExceptionPtr>::operator=
              ((shared_ptr<class___ExceptionPtr> *)((int)param_1 + 0x154),psVar6);
    CDialogTemplate::~CDialogTemplate(local_194);
    FUN_0040dab0(local_190);
    uVar7 = 0;
    iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
    iVar1 = FUN_00459390(iVar1);
    piVar4 = &local_198;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x54));
    piVar4 = (int *)FUN_00459360(pvVar9,piVar4);
    pCVar12 = local_19c;
    FUN_00417e20();
    psVar6 = (shared_ptr<class___ExceptionPtr> *)FUN_00416320(pCVar12,piVar4,iVar1,uVar7);
    std::shared_ptr<class___ExceptionPtr>::operator=
              ((shared_ptr<class___ExceptionPtr> *)((int)param_1 + 0x158),psVar6);
    CDialogTemplate::~CDialogTemplate(local_19c);
    FUN_0040dab0(&local_198);
    FUN_00469690(&stack0xfffffd90,(int *)((int)param_1 + 0x158));
    puVar13 = &stack0xfffffd90;
    puVar14 = &stack0xfffffd90;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x154));
    FUN_0044cec0(pvVar9);
    iVar1 = 3;
    puVar2 = FUN_00419810();
    FUN_00418bb0(puVar2,puVar13,iVar1);
    iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x154));
    FUN_00459f50(iVar1);
    uVar7 = 0x3d400000;
    pCVar12 = local_1a8;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x154));
    puVar3 = (undefined4 *)FUN_00418fa0(pvVar9,pCVar12);
    pvVar9 = (void *)FUN_00427130(puVar3);
    FUN_0044fdf0(pvVar9,uVar7);
    CDialogTemplate::~CDialogTemplate(local_1a8);
    iVar1 = 3;
    puVar2 = FUN_00419810();
    FUN_00418bb0(puVar2,puVar14,iVar1);
    iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x158));
    FUN_00459f50(iVar1);
    uVar7 = 0x3d400000;
    pCVar12 = local_1b0;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x158));
    puVar3 = (undefined4 *)FUN_00418fa0(pvVar9,pCVar12);
    pvVar9 = (void *)FUN_00427130(puVar3);
    FUN_0044fdf0(pvVar9,uVar7);
    CDialogTemplate::~CDialogTemplate(local_1b0);
    piVar4 = (int *)FUN_00427130((undefined4 *)((int)param_1 + 0x44));
    FUN_0045b5d0(&stack0xfffffd90,(undefined4 *)((int)param_1 + 0x154));
    puVar3 = (undefined4 *)(**(code **)(*piVar4 + 0x1c))();
    iVar1 = FUN_00427130(puVar3);
    FUN_00413b10(iVar1);
    CDialogTemplate::~CDialogTemplate(local_1b4);
    uVar17 = 0;
    pvVar9 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x154));
    FUN_0042b8c0(pvVar9,uVar17);
    iVar1 = FUN_00427130((undefined4 *)((int)param_1 + 0x150));
    uVar7 = FUN_00427130((undefined4 *)(iVar1 + 0x10));
    *(undefined4 *)((int)param_1 + 0x15c) = uVar7;
  }
  CDialogTemplate::~CDialogTemplate(local_20);
  FUN_00412da0(local_1c);
  CDialogTemplate::~CDialogTemplate(local_24);
  CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
  return;
}



================================================================================
REQUESTED 0044d460
ENTRY 0044d460
NAME FUN_0044d460
SIGNATURE undefined __fastcall FUN_0044d460(void * param_1)
BODY [[0044d460, 0044ec5e]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall FUN_0044d460(void *param_1)

{
  bool bVar1;
  bool bVar2;
  char cVar3;
  undefined4 *puVar4;
  undefined4 uVar5;
  void *pvVar6;
  void *this;
  shared_ptr<class___ExceptionPtr> *psVar7;
  undefined *puVar8;
  int *piVar9;
  int iVar10;
  int iVar11;
  undefined4 *puVar12;
  undefined4 *puVar13;
  undefined4 *puVar14;
  uint uVar15;
  DWORD *pDVar16;
  int *piVar17;
  undefined4 extraout_ECX;
  undefined4 extraout_ECX_00;
  float10 fVar18;
  CDialogTemplate *pCVar19;
  undefined4 uVar20;
  undefined1 *puVar21;
  int *piVar22;
  byte bVar23;
  undefined1 uVar24;
  float fVar25;
  long lVar26;
  wchar_t *pwVar27;
  char local_2cc;
  int local_2c8;
  undefined4 *local_2c0;
  undefined4 *local_2bc;
  undefined4 *local_2b8;
  float local_2b4;
  undefined4 *local_2b0;
  undefined4 *local_2a4;
  CSize local_286;
  CSize local_285;
  undefined1 local_284 [68];
  int local_240 [3];
  int local_234;
  int local_230;
  int local_22c;
  int local_228;
  int local_224;
  int local_220;
  int local_21c;
  int local_218;
  int local_214;
  CDialogTemplate local_210 [4];
  int local_20c;
  CDialogTemplate local_208 [7];
  char local_201;
  CDialogTemplate local_200 [4];
  int local_1fc;
  char local_1f5;
  CDialogTemplate local_1f4 [4];
  int local_1f0 [2];
  CSize local_1e5 [21];
  undefined4 *local_1d0;
  undefined4 *local_1cc;
  int local_1c8;
  CTraceSnapshot local_1c4 [8];
  int local_1bc;
  CTraceSnapshot local_1b8 [8];
  int local_1b0;
  CTraceSnapshot local_1ac [8];
  int local_1a4;
  CTraceSnapshot local_1a0 [8];
  int local_198;
  CTraceSnapshot local_194 [8];
  undefined1 local_18c [12];
  undefined1 local_180 [12];
  undefined1 local_174 [12];
  undefined1 local_168 [16];
  CDialogTemplate local_158 [8];
  int local_150;
  int local_14c;
  int local_148 [2];
  int local_140;
  int local_13c;
  int local_138;
  int local_134;
  undefined4 *local_130;
  int local_12c;
  int local_128;
  int local_124;
  int local_120 [6];
  undefined4 *local_108;
  void *local_100;
  int local_fc [2];
  int local_f4;
  CDialogTemplate local_f0 [4];
  CDialogTemplate local_ec [4];
  uint local_e8;
  int local_e4 [3];
  int local_d8 [3];
  int local_cc;
  undefined4 local_c8;
  float local_c4;
  float local_c0;
  float local_bc;
  long local_b8;
  CDialogTemplate local_b4 [7];
  char local_ad;
  float local_ac;
  CDialogTemplate local_a8 [4];
  void *local_a4;
  uint local_a0;
  CDialogTemplate local_9c [4];
  uint local_98;
  CDialogTemplate local_94 [4];
  int local_90;
  CDialogTemplate local_8c [4];
  uint local_88;
  uint local_84;
  void *local_80;
  undefined4 local_7c;
  undefined4 local_78;
  undefined4 local_74;
  undefined4 local_70;
  undefined4 local_6c;
  undefined4 local_68;
  CSize local_64;
  undefined1 local_63;
  undefined1 local_62;
  undefined1 local_61;
  CDialogTemplate local_60 [4];
  CDialogTemplate local_5c [4];
  CDialogTemplate local_58 [4];
  float local_54;
  CDialogTemplate local_50 [4];
  CDialogTemplate local_4c [4];
  undefined4 *local_48;
  CDialogTemplate local_44 [4];
  CDialogTemplate local_40 [4];
  CDialogTemplate local_3c [4];
  CDialogTemplate local_38 [4];
  undefined4 local_34 [8];
  CDialogTemplate local_14 [4];
  int local_10 [3];
  
  puVar4 = (undefined4 *)FUN_004c5370(param_1,local_ec);
  uVar5 = FUN_00427130(puVar4);
  pvVar6 = (void *)FUN_0044fac0((int)param_1);
  FUN_0044b020(pvVar6,uVar5);
  CDialogTemplate::~CDialogTemplate(local_ec);
  pvVar6 = param_1;
  this = (void *)FUN_0044fac0((int)param_1);
  FUN_0044b060(this,pvVar6);
  psVar7 = (shared_ptr<class___ExceptionPtr> *)FUN_0044fbb0(local_f0,(undefined4 *)&stack0x00000004)
  ;
  std::shared_ptr<class___ExceptionPtr>::operator=
            ((shared_ptr<class___ExceptionPtr> *)((int)param_1 + 0x50),psVar7);
  CDialogTemplate::~CDialogTemplate(local_f0);
  puVar8 = FUN_0042af90();
  FUN_0042ba60((int)puVar8);
  puVar8 = FUN_0044c040();
  cVar3 = FUN_0044f9b0((int)puVar8);
  if (cVar3 != '\0') {
    FUN_0040cd80(&local_f4,L".");
    FUN_0047da30(local_44,&local_f4);
    FUN_0040dab0(&local_f4);
    piVar9 = (int *)FUN_00427130((undefined4 *)local_44);
    (**(code **)(*piVar9 + 4))();
    FUN_0040cd80(local_fc,L"save.krd");
    piVar9 = (int *)FUN_00427130((undefined4 *)local_3c);
    FUN_0047dcc0(&stack0xfffffd1c,local_fc);
    (**(code **)(*piVar9 + 0x3c))();
    FUN_0040dab0(local_fc);
    local_100 = (void *)FUN_00478523(0x18);
    if (local_100 == (void *)0x0) {
      local_2a4 = (undefined4 *)0x0;
    }
    else {
      cVar3 = '\0';
      iVar10 = FUN_00427130((undefined4 *)local_40);
      local_2a4 = FUN_00412d50(local_100,iVar10,cVar3);
    }
    local_48 = local_2a4;
    puVar8 = FUN_0042af90();
    FUN_0044fa70(puVar8,local_2a4);
    CDialogTemplate::~CDialogTemplate(local_40);
    CDialogTemplate::~CDialogTemplate(local_3c);
    CDialogTemplate::~CDialogTemplate(local_44);
  }
  iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
  std::shared_ptr<class___ExceptionPtr>::operator=
            ((shared_ptr<class___ExceptionPtr> *)((int)param_1 + 0x44),
             (shared_ptr<class___ExceptionPtr> *)(iVar10 + 0x10));
  piVar9 = (int *)FUN_00427130((undefined4 *)((int)param_1 + 0x44));
  (**(code **)(*piVar9 + 0x1c))();
  puVar8 = FUN_0042af90();
  FUN_0044fa40((int)puVar8);
  piVar9 = (int *)FUN_00427130((undefined4 *)((int)param_1 + 0x44));
  (**(code **)(*piVar9 + 0x1c))();
  iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
  FUN_00469690(local_14,(int *)(iVar10 + 0x14));
  local_108 = (undefined4 *)FUN_00478523(0x58);
  if (local_108 == (undefined4 *)0x0) {
    local_2b0 = (undefined4 *)0x0;
  }
  else {
    local_2b0 = FUN_00432220(local_108);
  }
  FUN_0044bde0((void *)((int)param_1 + 0x4c),(int)local_2b0);
  puVar21 = &stack0xfffffd20;
  pvVar6 = (void *)FUN_00427130((undefined4 *)local_14);
  FUN_004c5370(pvVar6,puVar21);
  puVar21 = &stack0xfffffd20;
  iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x4c));
  FUN_0042d910(iVar10);
  FUN_0045b5d0(&stack0xfffffd20,(undefined4 *)((int)param_1 + 0x4c));
  puVar8 = FUN_0042af90();
  FUN_0042bb70((int)puVar8);
  bVar23 = 0;
  pvVar6 = (void *)FUN_00427130((undefined4 *)local_38);
  FUN_004984d0(pvVar6,bVar23);
  bVar23 = 0;
  uVar5 = 0;
  pvVar6 = (void *)FUN_00427130((undefined4 *)local_38);
  FUN_00498b10(pvVar6,uVar5,bVar23);
  iVar10 = FUN_00427130((undefined4 *)local_38);
  FUN_00498f50(iVar10);
  FUN_00469690(&stack0xfffffd20,(int *)local_38);
  FUN_004a9150();
  pvVar6 = (void *)FUN_00427130((undefined4 *)local_14);
  FUN_004c5370(pvVar6,puVar21);
  iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
  FUN_00401f80(&stack0xfffffd1c,(int *)(iVar10 + 0xc));
  pvVar6 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x4c));
  FUN_00432340(pvVar6);
  FUN_0040cd80(local_120,L"track");
  piVar9 = local_120;
  pCVar19 = local_4c;
  pvVar6 = (void *)FUN_00427130((undefined4 *)local_14);
  FUN_004bae10(pvVar6,pCVar19,piVar9);
  FUN_0040dab0(local_120);
  pCVar19 = local_5c;
  pvVar6 = (void *)FUN_00427130((undefined4 *)local_4c);
  FUN_00428770(pvVar6,pCVar19);
  FUN_0040cd80(&local_124,L"camera");
  piVar9 = &local_124;
  pCVar19 = local_58;
  pvVar6 = (void *)FUN_00427130((undefined4 *)local_5c);
  FUN_0047b1a0(pvVar6,pCVar19,piVar9);
  FUN_0040dab0(&local_124);
  iVar10 = FUN_00417940((int *)local_58);
  if (iVar10 == -1) {
    local_2b4 = 300.0;
  }
  else {
    FUN_0040cd80(&local_128,L"far");
    fVar25 = 300.0;
    piVar9 = &local_128;
    iVar11 = FUN_00427130((undefined4 *)local_58);
    fVar18 = FUN_0047a720(iVar11,piVar9,fVar25);
    local_2b4 = (float)fVar18;
  }
  *(float *)((int)param_1 + 0xc0) = local_2b4;
  if (iVar10 != -1) {
    FUN_0040dab0(&local_128);
  }
  bVar2 = false;
  bVar1 = false;
  local_54 = _DAT_00571490 / *(float *)((int)param_1 + 0xc0);
  FUN_0040cd80(&local_12c,L"fog");
  piVar9 = &local_12c;
  pCVar19 = local_50;
  pvVar6 = (void *)FUN_00427130((undefined4 *)local_5c);
  FUN_0047b1a0(pvVar6,pCVar19,piVar9);
  FUN_0040dab0(&local_12c);
  iVar10 = FUN_00417940((int *)local_50);
  if (iVar10 != -1) {
    local_130 = (undefined4 *)FUN_00478523(0x20);
    if (local_130 == (undefined4 *)0x0) {
      local_2b8 = (undefined4 *)0x0;
    }
    else {
      local_2b8 = FUN_00493e70(local_130);
    }
    FUN_0045b690(local_60,(int)local_2b8,'\x01');
    uVar5 = 3;
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_60);
    FUN_004a1ae0(pvVar6,uVar5);
    FUN_0040cd80(&local_134,L"mode");
    lVar26 = 1;
    piVar9 = &local_134;
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_50);
    lVar26 = FUN_0047a650(pvVar6,piVar9,lVar26);
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_60);
    FUN_00497320(pvVar6,lVar26);
    FUN_0040dab0(&local_134);
    CSize::CSize(&local_64);
    FUN_0040cd80(&local_138,L"r");
    lVar26 = 0xff;
    piVar9 = &local_138;
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_50);
    lVar26 = FUN_0047a650(pvVar6,piVar9,lVar26);
    local_62 = (undefined1)lVar26;
    FUN_0040dab0(&local_138);
    FUN_0040cd80(&local_13c,L"g");
    lVar26 = 0xff;
    piVar9 = &local_13c;
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_50);
    lVar26 = FUN_0047a650(pvVar6,piVar9,lVar26);
    local_63 = (undefined1)lVar26;
    FUN_0040dab0(&local_13c);
    FUN_0040cd80(&local_140,L"b");
    lVar26 = 0xff;
    piVar9 = &local_140;
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_50);
    lVar26 = FUN_0047a650(pvVar6,piVar9,lVar26);
    local_64 = SUB41(lVar26,0);
    FUN_0040dab0(&local_140);
    local_61 = 0xff;
    FUN_00418970(&stack0xfffffd20,(undefined4 *)&local_64);
    iVar10 = FUN_00427130((undefined4 *)local_60);
    FUN_0044fda0(iVar10);
    iVar10 = FUN_00427130((undefined4 *)local_60);
    iVar10 = FUN_004b0640(iVar10);
    if (iVar10 == 3) {
      FUN_0040cd80(local_148,L"start");
      fVar25 = 0.5;
      piVar9 = local_148;
      iVar10 = FUN_00427130((undefined4 *)local_50);
      fVar18 = FUN_0047a720(iVar10,piVar9,fVar25);
      fVar25 = (float)(fVar18 * (float10)*(float *)((int)param_1 + 0xc0));
      pvVar6 = (void *)FUN_00427130((undefined4 *)local_60);
      FUN_0044fdd0(pvVar6,fVar25);
      FUN_0040dab0(local_148);
      FUN_0040cd80(&local_14c,L"end");
      fVar25 = 1.0;
      piVar9 = &local_14c;
      iVar10 = FUN_00427130((undefined4 *)local_50);
      fVar18 = FUN_0047a720(iVar10,piVar9,fVar25);
      fVar25 = (float)(fVar18 * (float10)*(float *)((int)param_1 + 0xc0));
      pvVar6 = (void *)FUN_00427130((undefined4 *)local_60);
      FUN_00497340(pvVar6,fVar25);
      FUN_0040dab0(&local_14c);
    }
    else {
      FUN_0040cd80(&local_150,L"density");
      fVar25 = 1.0;
      piVar9 = &local_150;
      iVar10 = FUN_00427130((undefined4 *)local_50);
      fVar18 = FUN_0047a720(iVar10,piVar9,fVar25);
      fVar25 = (float)(fVar18 * (float10)local_54);
      pvVar6 = (void *)FUN_00427130((undefined4 *)local_60);
      FUN_0044fdf0(pvVar6,fVar25);
      FUN_0040dab0(&local_150);
    }
    FUN_00469690(&stack0xfffffd20,(int *)local_60);
    iVar10 = FUN_00427130((undefined4 *)local_38);
    FUN_0044fe10(iVar10);
    FUN_00469690(&stack0xfffffd20,(int *)local_60);
    pCVar19 = local_158;
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_14);
    puVar4 = (undefined4 *)FUN_004c5370(pvVar6,pCVar19);
    iVar10 = FUN_00427130(puVar4);
    FUN_0044fe10(iVar10);
    CDialogTemplate::~CDialogTemplate(local_158);
    CDialogTemplate::~CDialogTemplate(local_60);
  }
  CDialogTemplate::~CDialogTemplate(local_50);
  CDialogTemplate::~CDialogTemplate(local_58);
  CDialogTemplate::~CDialogTemplate(local_5c);
  CDialogTemplate::~CDialogTemplate(local_4c);
  iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x44));
  local_80 = (void *)FUN_00418620(iVar10);
  puVar4 = FUN_004135a0(local_168,0x3f800000,0,0);
  puVar12 = FUN_004135a0(local_174,0,0,0x3f800000);
  puVar13 = FUN_004135a0(local_180,0,0x3f800000,0);
  puVar14 = FUN_004135a0(local_18c,0x42c80000,0x42c80000,0x41a00000);
  FUN_0044fc50(local_80,puVar14,puVar13,puVar12,puVar4);
  FUN_004a98a0(local_80,1.5,*(float *)((int)param_1 + 0xc0),0x42960000,0.75);
  local_7c = 0;
  local_78 = 0;
  puVar8 = FUN_0044c040();
  local_74 = FUN_0044bcf0((int)puVar8);
  puVar8 = FUN_0044c040();
  local_70 = FUN_0049e8c0((int)puVar8);
  local_6c = 0;
  local_68 = 0x3f800000;
  FUN_0044fd00(local_80,&local_7c);
  FUN_0044bde0((void *)((int)param_1 + 0x78),0);
  *(undefined4 *)((int)param_1 + 0x7c) = 0x42960000;
  *(undefined4 *)((int)param_1 + 0xb4) = 0;
  for (local_84 = 0; local_84 < 8; local_84 = local_84 + 1) {
  }
  local_88 = 0;
  while( true ) {
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    uVar15 = FUN_004496b0((int *)(iVar10 + 0x18));
    if (uVar15 <= local_88) break;
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    iVar10 = FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    piVar9 = (int *)(iVar10 + 8);
    pCVar19 = local_94;
    FUN_00417e20();
    FUN_00415040(pCVar19,piVar9);
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    iVar10 = FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    piVar9 = (int *)(iVar10 + 4);
    pCVar19 = local_8c;
    FUN_00417e20();
    FUN_004165b0(pCVar19,piVar9);
    FUN_004bf5d0(&local_90);
    FUN_0040cd80(&local_198,L"kartName");
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    iVar10 = FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    piVar9 = (int *)FUN_00462620(local_194,&local_198,(int *)(iVar10 + 8));
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_94);
    FUN_0047a3d0(pvVar6,piVar9);
    CTraceSnapshot::~CTraceSnapshot(local_194);
    FUN_0040dab0(&local_198);
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    FUN_00479eb0(&local_90,L"%d");
    FUN_0040cd80(&local_1a4,L"kartColor");
    piVar9 = (int *)FUN_00462620(local_1a0,&local_1a4,&local_90);
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_94);
    FUN_0047a3d0(pvVar6,piVar9);
    CTraceSnapshot::~CTraceSnapshot(local_1a0);
    FUN_0040dab0(&local_1a4);
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    FUN_00479eb0(&local_90,L"%d");
    FUN_0040cd80(&local_1b0,L"kartNumber");
    piVar9 = (int *)FUN_00462620(local_1ac,&local_1b0,&local_90);
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_94);
    FUN_0047a3d0(pvVar6,piVar9);
    CTraceSnapshot::~CTraceSnapshot(local_1ac);
    FUN_0040dab0(&local_1b0);
    FUN_0040cd80(&local_1bc,L"characterName");
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    iVar10 = FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    piVar9 = (int *)FUN_00462620(local_1b8,&local_1bc,(int *)(iVar10 + 4));
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_94);
    FUN_0047a3d0(pvVar6,piVar9);
    CTraceSnapshot::~CTraceSnapshot(local_1b8);
    FUN_0040dab0(&local_1bc);
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    FUN_00479eb0(&local_90,L"%d");
    FUN_0040cd80(&local_1c8,L"characterColor");
    piVar9 = (int *)FUN_00462620(local_1c4,&local_1c8,&local_90);
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_94);
    FUN_0047a3d0(pvVar6,piVar9);
    CTraceSnapshot::~CTraceSnapshot(local_1c4);
    FUN_0040dab0(&local_1c8);
    if (local_88 == 0) {
      local_1cc = (undefined4 *)FUN_00478523(0x324);
      if (local_1cc == (undefined4 *)0x0) {
        local_2bc = (undefined4 *)0x0;
      }
      else {
        local_2bc = FUN_0042de00(local_1cc);
      }
      FUN_0044bde0((void *)((int)param_1 + local_88 * 4 + 0x54),(int)local_2bc);
    }
    else {
      local_1d0 = (undefined4 *)FUN_00478523(0x1b8);
      if (local_1d0 == (undefined4 *)0x0) {
        local_2c0 = (undefined4 *)0x0;
      }
      else {
        local_2c0 = FUN_0042d220(local_1d0);
      }
      FUN_0044bde0((void *)((int)param_1 + local_88 * 4 + 0x54),(int)local_2c0);
    }
    piVar9 = (int *)FUN_00427130((undefined4 *)((int)param_1 + local_88 * 4 + 0x54));
    FUN_004815c0(&stack0xfffffd20,(int *)local_94);
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    iVar10 = FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    FUN_00469690(&stack0xfffffd1c,(int *)(iVar10 + 0x14));
    (**(code **)(*piVar9 + 0x34))();
    FUN_00469690(&stack0xfffffd20,(int *)((int)param_1 + 0x4c));
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + local_88 * 4 + 0x54));
    FUN_0044f9d0(iVar10);
    uVar15 = local_88;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    iVar10 = FUN_004496d0((void *)(iVar10 + 0x18),uVar15);
    uVar5 = *(undefined4 *)(iVar10 + 0x10);
    pvVar6 = (void *)FUN_00427130((undefined4 *)((int)param_1 + local_88 * 4 + 0x54));
    FUN_0044fa20(pvVar6,uVar5);
    iVar11 = 0;
    puVar21 = &stack0xfffffd1c;
    uVar5 = extraout_ECX;
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + local_88 * 4 + 0x54));
    pvVar6 = (void *)FUN_004122c0(iVar10);
    FUN_0043d830(pvVar6,puVar21);
    FUN_00417e20();
    FUN_00416f40(uVar5,iVar11);
    uVar5 = 0;
    pvVar6 = (void *)FUN_00427130((undefined4 *)((int)param_1 + local_88 * 4 + 0x54));
    FUN_0044fa00(pvVar6,uVar5);
    FUN_0045b5d0(&stack0xfffffd20,(undefined4 *)((int)param_1 + local_88 * 4 + 0x54));
    puVar8 = FUN_0042af90();
    FUN_0042bb70((int)puVar8);
    FUN_0040dab0(&local_90);
    CDialogTemplate::~CDialogTemplate(local_8c);
    CDialogTemplate::~CDialogTemplate(local_94);
    local_88 = local_88 + 1;
  }
  if (param_1 == (void *)0x0) {
    local_2c8 = 0;
  }
  else {
    local_2c8 = (int)param_1 + 0x40;
  }
  puVar8 = FUN_00417e20();
  FUN_00416300(puVar8,local_2c8);
  uVar5 = CSize::CSize(local_1e5);
  FUN_00401310(local_10,uVar5);
  FUN_00493460();
  piVar9 = local_10;
  pvVar6 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x4c));
  FUN_00433570(pvVar6,piVar9);
  local_98 = 0;
  while( true ) {
    iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
    uVar15 = FUN_004496b0((int *)(iVar10 + 0x18));
    if (uVar15 <= local_98) break;
    uVar5 = FUN_00427130((undefined4 *)((int)param_1 + local_98 * 4 + 0x54));
    local_34[local_98] = uVar5;
    local_98 = local_98 + 1;
  }
  iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x50));
  uVar15 = FUN_004496b0((int *)(iVar10 + 0x18));
  puVar4 = local_34;
  puVar8 = FUN_0044fb20();
  FUN_00410320(puVar8,(int)puVar4,uVar15);
  FUN_00469690(&stack0xfffffd20,(int *)local_38);
  puVar8 = FUN_0044fb20();
  FUN_00410820((int)puVar8);
  piVar9 = local_10;
  puVar8 = FUN_0044fb20();
  FUN_00410600(puVar8,piVar9);
  iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
  puVar4 = (undefined4 *)FUN_00412300(iVar10);
  iVar10 = FUN_00427130((undefined4 *)((int)param_1 + 0x54));
  pDVar16 = (DWORD *)FUN_004122e0(iVar10);
  puVar8 = FUN_0044fbf0();
  FUN_004dd010(puVar8,pDVar16,puVar4);
  FUN_0040cd80(local_1f0,L"surround");
  piVar9 = local_1f0;
  pCVar19 = local_9c;
  puVar8 = FUN_0040ec80();
  FUN_00420490(puVar8,pCVar19,piVar9);
  FUN_0040dab0(local_1f0);
  local_a0 = 0;
  do {
    iVar10 = FUN_00427130((undefined4 *)local_14);
    uVar15 = FUN_0044cf50(iVar10);
    if (uVar15 <= local_a0) {
      CDialogTemplate::~CDialogTemplate(local_9c);
      puVar8 = FUN_0044c040();
      cVar3 = FUN_0044f990((int)puVar8);
      if (cVar3 != '\0') {
        uVar5 = CSize::CSize(&local_285);
        FUN_00401310(local_e4,uVar5);
        FUN_00493460();
        piVar9 = local_e4;
        pvVar6 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x4c));
        FUN_004336a0(pvVar6,piVar9);
        (*(code *)PTR_FUN_005a6d90)();
        local_e8 = 0;
        while (uVar15 = size(local_e4), local_e8 < uVar15) {
          puVar4 = (undefined4 *)FUN_0044cfd0(local_e4,local_e8);
          FUN_004d2be0(puVar4);
          (*(code *)PTR_FUN_005a6d90)();
          (*(code *)PTR_FUN_005a6d90)();
          local_e8 = local_e8 + 1;
        }
        (*(code *)PTR_FUN_005a6d90)();
        FUN_00401330(local_e4);
      }
      uVar5 = CSize::CSize(&local_286);
      FUN_00401310(local_d8,uVar5);
      FUN_00493460();
      piVar9 = local_d8;
      pvVar6 = (void *)FUN_00427130((undefined4 *)((int)param_1 + 0x4c));
      FUN_00433740(pvVar6,piVar9);
      piVar9 = local_d8;
      puVar8 = FUN_0044fb40();
      FUN_0041e130(puVar8,piVar9);
      FUN_00441000(local_d8);
      FUN_00469690(&stack0xfffffd20,(int *)((int)param_1 + 0x44));
      iVar10 = FUN_0044fac0((int)param_1);
      FUN_0044fa90(iVar10);
      piVar9 = (int *)FUN_0044fac0((int)param_1);
      FUN_00469690(&stack0xfffffd20,(int *)&stack0x00000004);
      (**(code **)(*piVar9 + 4))();
      FUN_00401330(local_10);
      CDialogTemplate::~CDialogTemplate(local_14);
      CDialogTemplate::~CDialogTemplate(local_38);
      CDialogTemplate::~CDialogTemplate((CDialogTemplate *)&stack0x00000004);
      return;
    }
    uVar20 = 0;
    pCVar19 = local_1f4;
    uVar15 = local_a0;
    pvVar6 = (void *)FUN_00427130((undefined4 *)local_14);
    puVar4 = (undefined4 *)FUN_0044cf70(pvVar6,pCVar19,uVar15);
    uVar5 = FUN_00427130(puVar4);
    local_a4 = (void *)__RTDynamicCast(uVar5,uVar20);
    CDialogTemplate::~CDialogTemplate(local_1f4);
    if (local_a4 == (void *)0x0) {
LAB_0044e581:
      local_2cc = '\0';
    }
    else {
      bVar2 = true;
      pwVar27 = L"sound";
      iVar10 = 5;
      pvVar6 = (void *)FUN_00418620((int)local_a4);
      pvVar6 = FUN_0040ce80(&local_1fc,pvVar6,iVar10);
      cVar3 = FUN_0040ce00(pvVar6,pwVar27);
      if (cVar3 == '\0') goto LAB_0044e581;
      bVar2 = true;
      bVar1 = true;
      piVar9 = (int *)FUN_00428770(local_a4,local_200);
      iVar10 = FUN_00417940(piVar9);
      if (iVar10 == -1) goto LAB_0044e581;
      local_2cc = '\x01';
    }
    local_1f5 = local_2cc;
    if (bVar1) {
      bVar1 = false;
      CDialogTemplate::~CDialogTemplate(local_200);
    }
    if (bVar2) {
      bVar2 = false;
      FUN_0040dab0(&local_1fc);
    }
    if (local_1f5 != '\0') {
      FUN_0040cd80(&local_20c,L"sound");
      piVar9 = &local_20c;
      puVar4 = (undefined4 *)FUN_00428770(local_a4,local_208);
      pvVar6 = (void *)FUN_00427130(puVar4);
      uVar15 = FUN_0047b3c0(pvVar6,piVar9);
      local_201 = '\x01' - ((uVar15 & 0xff) != 0);
      CDialogTemplate::~CDialogTemplate(local_208);
      FUN_0040dab0(&local_20c);
      if (local_201 == '\0') {
        FUN_0040cd80(&local_214,L"sound");
        piVar9 = &local_214;
        pCVar19 = local_a8;
        puVar4 = (undefined4 *)FUN_00428770(local_a4,local_210);
        pvVar6 = (void *)FUN_00427130(puVar4);
        FUN_0047b1a0(pvVar6,pCVar19,piVar9);
        CDialogTemplate::~CDialogTemplate(local_210);
        FUN_0040dab0(&local_214);
        FUN_0040cd80(&local_218,L"");
        FUN_0040cd80(&local_21c,L"filename");
        piVar9 = &local_218;
        piVar17 = &local_21c;
        piVar22 = &local_cc;
        pvVar6 = (void *)FUN_00427130((undefined4 *)local_a8);
        FUN_0047a7f0(pvVar6,piVar22,piVar17,piVar9);
        FUN_0040dab0(&local_21c);
        FUN_0040dab0(&local_218);
        FUN_0040cd80(&local_220,L"maxVolume");
        fVar25 = 1.0;
        piVar9 = &local_220;
        iVar10 = FUN_00427130((undefined4 *)local_a8);
        fVar18 = FUN_0047a720(iVar10,piVar9,fVar25);
        local_c4 = (float)fVar18;
        FUN_0040dab0(&local_220);
        FUN_0040cd80(&local_224,L"maxRadius");
        fVar25 = 0.0;
        piVar9 = &local_224;
        iVar10 = FUN_00427130((undefined4 *)local_a8);
        fVar18 = FUN_0047a720(iVar10,piVar9,fVar25);
        local_ac = (float)fVar18;
        FUN_0040dab0(&local_224);
        FUN_0040cd80(&local_228,L"minVolume");
        fVar25 = 0.0;
        piVar9 = &local_228;
        iVar10 = FUN_00427130((undefined4 *)local_a8);
        fVar18 = FUN_0047a720(iVar10,piVar9,fVar25);
        local_c0 = (float)fVar18;
        FUN_0040dab0(&local_228);
        FUN_0040cd80(&local_22c,L"minRadius");
        fVar25 = 1.0;
        piVar9 = &local_22c;
        iVar10 = FUN_00427130((undefined4 *)local_a8);
        fVar18 = FUN_0047a720(iVar10,piVar9,fVar25);
        local_bc = (float)fVar18;
        FUN_0040dab0(&local_22c);
        FUN_0040cd80(&local_230,L"spacing");
        lVar26 = 0;
        piVar9 = &local_230;
        pvVar6 = (void *)FUN_00427130((undefined4 *)local_a8);
        local_b8 = FUN_0047a650(pvVar6,piVar9,lVar26);
        FUN_0040dab0(&local_230);
        FUN_0040cd80(&local_234,L"panning");
        uVar24 = 1;
        piVar9 = &local_234;
        pvVar6 = (void *)FUN_00427130((undefined4 *)local_a8);
        local_ad = FUN_0047a470(pvVar6,piVar9,uVar24);
        FUN_0040dab0(&local_234);
        cVar3 = FUN_0040b7f0(&local_cc);
        if (cVar3 == '\0') {
          piVar9 = (int *)FUN_00427130((undefined4 *)local_9c);
          uVar20 = 0x766177;
          uVar5 = extraout_ECX_00;
          FUN_00401f80(&stack0xfffffd18,&local_cc);
          piVar17 = (int *)FUN_0040c190(local_240,uVar5,uVar20);
          FID_conflict_operator_(&stack0xfffffd18,piVar17);
          (**(code **)(*piVar9 + 0x3c))(local_b4);
          FUN_0040c020(local_240);
          FUN_00469690(&stack0xfffffd20,(int *)local_b4);
          puVar8 = FUN_0044fbf0();
          uVar5 = FUN_004dd100((int)puVar8);
          local_c8 = uVar5;
          cVar3 = local_ad;
          puVar8 = FUN_0044fbf0();
          FUN_004dd560(puVar8,uVar5,cVar3);
          pvVar6 = FUN_0044fe40(local_a4,local_284);
          puVar4 = (undefined4 *)((int)pvVar6 + 0x24);
          uVar5 = local_c8;
          puVar8 = FUN_0044fbf0();
          FUN_004dd610(puVar8,uVar5,puVar4);
          uVar5 = local_c8;
          fVar25 = local_c4;
          puVar8 = FUN_0044fbf0();
          FUN_004dd660(puVar8,uVar5,fVar25);
          uVar5 = local_c8;
          fVar25 = local_ac;
          puVar8 = FUN_0044fbf0();
          FUN_004dd6a0(puVar8,uVar5,fVar25);
          uVar5 = local_c8;
          fVar25 = local_c0;
          puVar8 = FUN_0044fbf0();
          FUN_004dd6e0(puVar8,uVar5,fVar25);
          uVar5 = local_c8;
          fVar25 = local_bc;
          puVar8 = FUN_0044fbf0();
          FUN_004dd720(puVar8,uVar5,fVar25);
          uVar5 = local_c8;
          lVar26 = local_b8;
          puVar8 = FUN_0044fbf0();
          FUN_004dd5d0(puVar8,uVar5,lVar26);
          cVar3 = '\x01';
          uVar5 = local_c8;
          puVar8 = FUN_0044fbf0();
          FUN_004dd4a0(puVar8,uVar5,cVar3);
          CDialogTemplate::~CDialogTemplate(local_b4);
          FUN_0040dab0(&local_cc);
          CDialogTemplate::~CDialogTemplate(local_a8);
        }
        else {
          (*(code *)PTR_FUN_005a6d90)();
          puVar4 = (undefined4 *)FUN_00418620((int)local_a4);
          FUN_004d2be0(puVar4);
          (*(code *)PTR_FUN_005a6d90)();
          (*(code *)PTR_FUN_005a6d90)();
          FUN_0040dab0(&local_cc);
          CDialogTemplate::~CDialogTemplate(local_a8);
        }
      }
      else {
        (*(code *)PTR_FUN_005a6d90)();
        puVar4 = (undefined4 *)FUN_00418620((int)local_a4);
        FUN_004d2be0(puVar4);
        (*(code *)PTR_FUN_005a6d90)();
        (*(code *)PTR_FUN_005a6d90)();
      }
    }
    local_a0 = local_a0 + 1;
  } while( true );
}



================================================================================
REQUESTED 0046ce50
ENTRY 0046ce50
NAME FUN_0046ce50
SIGNATURE undefined __fastcall FUN_0046ce50(int param_1)
BODY [[0046ce50, 0046d03e]]


void __fastcall FUN_0046ce50(int param_1)

{
  void *pvVar1;
  undefined *this;
  int iVar2;
  undefined4 *puVar3;
  int *piVar4;
  undefined4 uStack_44;
  undefined1 uVar5;
  undefined4 uVar6;
  undefined4 *local_38;
  undefined4 *local_34;
  int local_30;
  undefined4 *local_2c;
  int local_24;
  int local_20 [3];
  undefined4 *local_14;
  undefined4 *local_10;
  CDragListBox *local_c;
  undefined4 *local_8;
  
  uStack_44 = 0x46ce61;
  local_8 = (undefined4 *)FUN_00478523(0x20);
  if (local_8 == (undefined4 *)0x0) {
    local_2c = (undefined4 *)0x0;
  }
  else {
    local_2c = FUN_00493650(local_8);
  }
  uStack_44 = 0x46ce90;
  FUN_0044bde0((void *)(param_1 + 0x1c),(int)local_2c);
  uVar6 = 5;
  uStack_44 = 0x46ce9d;
  pvVar1 = (void *)FUN_00427130((undefined4 *)(param_1 + 0x1c));
  uStack_44 = 0x46cea4;
  FUN_00497320(pvVar1,uVar6);
  uVar6 = 6;
  uStack_44 = 0x46ceb1;
  pvVar1 = (void *)FUN_00427130((undefined4 *)(param_1 + 0x1c));
  uStack_44 = 0x46ceb8;
  FUN_0046d4b0(pvVar1,uVar6);
  uVar6 = 8;
  uStack_44 = 0x46cec5;
  pvVar1 = (void *)FUN_00427130((undefined4 *)(param_1 + 0x1c));
  uStack_44 = 0x46cecc;
  FUN_00497340(pvVar1,uVar6);
  uVar5 = 1;
  uStack_44 = 0x46ced9;
  pvVar1 = (void *)FUN_00427130((undefined4 *)(param_1 + 0x1c));
  uStack_44 = 0x46cee0;
  FUN_004a1ac0(pvVar1,uVar5);
  uVar5 = 0xff;
  uStack_44 = 0x46cef0;
  pvVar1 = (void *)FUN_00427130((undefined4 *)(param_1 + 0x1c));
  uStack_44 = 0x46cef7;
  FUN_0046d4d0(pvVar1,uVar5);
  uStack_44 = 0x46cefe;
  local_c = (CDragListBox *)FUN_00478523(0xc);
  if (local_c == (CDragListBox *)0x0) {
    local_30 = 0;
  }
  else {
    local_30 = CDragListBox::CDragListBox(local_c);
  }
  uStack_44 = 0x46cf2d;
  FUN_0044bde0((void *)(param_1 + 0x20),local_30);
  uVar6 = 1;
  uStack_44 = 0x46cf3a;
  pvVar1 = (void *)FUN_00427130((undefined4 *)(param_1 + 0x20));
  uStack_44 = 0x46cf41;
  FUN_004a1ae0(pvVar1,uVar6);
  uStack_44 = 0x46cf48;
  local_10 = (undefined4 *)FUN_00478523(0x10);
  if (local_10 == (undefined4 *)0x0) {
    local_34 = (undefined4 *)0x0;
  }
  else {
    local_34 = FUN_004977e0(local_10);
  }
  uStack_44 = 0x46cf77;
  FUN_0044bde0((void *)(param_1 + 0x28),(int)local_34);
  uVar5 = 0;
  uStack_44 = 0x46cf84;
  pvVar1 = (void *)FUN_00427130((undefined4 *)(param_1 + 0x28));
  uStack_44 = 0x46cf8b;
  FUN_00426a80(pvVar1,uVar5);
  uStack_44 = 0x46cf92;
  local_14 = (undefined4 *)FUN_00478523(0x4c);
  if (local_14 == (undefined4 *)0x0) {
    local_38 = (undefined4 *)0x0;
  }
  else {
    local_38 = FUN_00495300(local_14);
  }
  uStack_44 = 0x46cfc1;
  FUN_0044bde0((void *)(param_1 + 0x24),(int)local_38);
  uVar6 = 4;
  uStack_44 = 0x46cfce;
  pvVar1 = (void *)FUN_00427130((undefined4 *)(param_1 + 0x24));
  uStack_44 = 0x46cfd5;
  FUN_004a1ae0(pvVar1,uVar6);
  uStack_44 = 0x46cfe2;
  FUN_0040cd80(local_20,L"drift");
  uStack_44 = 0x46cfef;
  FUN_0040cd80(&local_24,L"drift");
  puVar3 = &uStack_44;
  piVar4 = local_20;
  this = FUN_0040ec80();
  FUN_00420340(this,puVar3,piVar4);
  FUN_0046a490(&stack0xffffffc0,&local_24);
  uStack_44 = 0x46d023;
  iVar2 = FUN_00427130((undefined4 *)(param_1 + 0x24));
  uStack_44 = 0x46d02a;
  FUN_00413aa0(iVar2);
  FUN_0040dab0(&local_24);
  FUN_0040dab0(local_20);
  return;
}



