Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 0042f460
ENTRY 0042f460
NAME FUN_0042f460
SIGNATURE undefined __fastcall FUN_0042f460(int param_1)
BODY [[0042f460, 0042f6b0]]


void __fastcall FUN_0042f460(int param_1)

{
  float *pfVar1;
  float10 fVar2;
  float fVar3;
  undefined1 local_78 [12];
  undefined1 local_6c [12];
  undefined1 local_60 [12];
  undefined1 local_54 [12];
  undefined1 local_48 [12];
  undefined1 local_3c [12];
  float local_30;
  float local_2c;
  float local_28;
  float local_24;
  float local_20;
  float local_1c;
  uint local_18;
  float afStack_14 [4];
  
  for (local_18 = 0; local_18 < 4; local_18 = local_18 + 1) {
    if (*(char *)(param_1 + local_18 + 0x244) == '\0') {
      afStack_14[local_18] = 0.0;
    }
    else if (*(float *)(param_1 + 0x288 + local_18 * 4) <= DAT_00571808) {
      afStack_14[local_18] =
           (*(float *)(param_1 + 0x288 + local_18 * 4) / *(float *)(param_1 + 0x1a0)) *
           *(float *)(param_1 + 0x220) +
           *(float *)(param_1 + 0x218) * *(float *)(param_1 + 0x278 + local_18 * 4);
    }
    else {
      afStack_14[local_18] =
           (*(float *)(param_1 + 0x288 + local_18 * 4) / *(float *)(param_1 + 0x1a0)) *
           *(float *)(param_1 + 0x21c) +
           *(float *)(param_1 + 0x218) * *(float *)(param_1 + 0x278 + local_18 * 4);
    }
    if (afStack_14[local_18] <= DAT_00571808) {
      afStack_14[local_18] = 0.0;
    }
    else {
      fVar2 = FUN_00428460((float *)(param_1 + 0x248 + local_18 * 0xc),(float *)(param_1 + 0x1cc));
      afStack_14[local_18] = (float)(fVar2 * (float10)afStack_14[local_18]);
    }
    pfVar1 = (float *)FUN_00418790(local_3c,(float *)(param_1 + 0x1cc),afStack_14[local_18]);
    FUN_00418680((void *)(param_1 + 0x200),pfVar1);
    CSize::CSize((CSize *)&local_24);
    CSize::CSize((CSize *)&local_30);
    pfVar1 = (float *)FUN_004135a0(local_48,*(float *)(param_1 + 300) *
                                            *(float *)(param_1 + 0x224 + local_18 * 4),
                                   -*(float *)(param_1 + 0x130) *
                                   *(float *)(param_1 + 0x234 + local_18 * 4),0);
    local_30 = *pfVar1;
    local_2c = pfVar1[1];
    local_28 = pfVar1[2];
    fVar3 = 0.1;
    pfVar1 = (float *)FUN_004135a0(local_54,0,0,afStack_14[local_18]);
    pfVar1 = (float *)FUN_00428490(local_60,&local_30,pfVar1);
    pfVar1 = (float *)FUN_00418790(local_6c,pfVar1,fVar3);
    local_24 = *pfVar1;
    local_20 = pfVar1[1];
    local_1c = pfVar1[2];
    FUN_00418680((void *)(param_1 + 0x20c),&local_24);
  }
  pfVar1 = (float *)FUN_00418790(local_78,(float *)(param_1 + 0x1b4),*(float *)(param_1 + 0x128));
  FUN_00418680((void *)(param_1 + 0x200),pfVar1);
  return;
}



