Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00495bd0
ENTRY 00495bd0
NAME FUN_00495bd0
SIGNATURE undefined __thiscall FUN_00495bd0(void * this, int param_1, char param_2)
BODY [[00495bd0, 00495ef9]]


void __thiscall FUN_00495bd0(void *this,int param_1,char param_2)

{
  int iVar1;
  int *piVar2;
  void *this_00;
  undefined4 local_14;
  
  FUN_004b0da0();
  *(undefined4 *)((int)this + 8) = *(undefined4 *)(param_1 + 8);
  *(undefined4 *)((int)this + 0x10) = *(undefined4 *)(param_1 + 0x10);
  *(undefined4 *)((int)this + 0x14) = *(undefined4 *)(param_1 + 0x14);
  *(undefined4 *)((int)this + 0x18) = *(undefined4 *)(param_1 + 0x18);
  *(undefined4 *)((int)this + 0x1c) = *(undefined4 *)(param_1 + 0x1c);
  *(undefined4 *)((int)this + 0x20) = *(undefined4 *)(param_1 + 0x20);
  *(undefined4 *)((int)this + 0x24) = *(undefined4 *)(param_1 + 0x24);
  *(undefined4 *)((int)this + 0x3c) = *(undefined4 *)(param_1 + 0x3c);
  if (param_2 == '\0') {
    std::shared_ptr<class___ExceptionPtr>::operator=
              ((shared_ptr<class___ExceptionPtr> *)((int)this + 0xc),
               (shared_ptr<class___ExceptionPtr> *)(param_1 + 0xc));
    iVar1 = FUN_00417940((int *)(param_1 + 0x28));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a240((undefined4 *)(param_1 + 0x28));
      FUN_0044bde0((void *)((int)this + 0x28),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x2c));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a240((undefined4 *)(param_1 + 0x2c));
      FUN_0044bde0((void *)((int)this + 0x2c),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x30));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a240((undefined4 *)(param_1 + 0x30));
      FUN_0044bde0((void *)((int)this + 0x30),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x34));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a240((undefined4 *)(param_1 + 0x34));
      FUN_0044bde0((void *)((int)this + 0x34),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x38));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a240((undefined4 *)(param_1 + 0x38));
      FUN_0044bde0((void *)((int)this + 0x38),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x40));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a240((undefined4 *)(param_1 + 0x40));
      FUN_0044bde0((void *)((int)this + 0x40),(int)piVar2);
    }
    std::shared_ptr<class___ExceptionPtr>::operator=
              ((shared_ptr<class___ExceptionPtr> *)((int)this + 0x44),
               (shared_ptr<class___ExceptionPtr> *)(param_1 + 0x44));
  }
  else {
    std::shared_ptr<class___ExceptionPtr>::operator=
              ((shared_ptr<class___ExceptionPtr> *)((int)this + 0xc),
               (shared_ptr<class___ExceptionPtr> *)(param_1 + 0xc));
    iVar1 = FUN_00417940((int *)(param_1 + 0x28));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a200((undefined4 *)(param_1 + 0x28));
      FUN_0044bde0((void *)((int)this + 0x28),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x2c));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a200((undefined4 *)(param_1 + 0x2c));
      FUN_0044bde0((void *)((int)this + 0x2c),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x30));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a200((undefined4 *)(param_1 + 0x30));
      FUN_0044bde0((void *)((int)this + 0x30),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x34));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a200((undefined4 *)(param_1 + 0x34));
      FUN_0044bde0((void *)((int)this + 0x34),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x38));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a200((undefined4 *)(param_1 + 0x38));
      FUN_0044bde0((void *)((int)this + 0x38),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x40));
    if (iVar1 != -1) {
      piVar2 = FUN_0049a200((undefined4 *)(param_1 + 0x40));
      FUN_0044bde0((void *)((int)this + 0x40),(int)piVar2);
    }
    iVar1 = FUN_00417940((int *)(param_1 + 0x44));
    if (iVar1 != -1) {
      this_00 = (void *)FUN_00478523(0x28);
      if (this_00 == (void *)0x0) {
        local_14 = (undefined4 *)0x0;
      }
      else {
        iVar1 = FUN_00427130((undefined4 *)(param_1 + 0x44));
        local_14 = FUN_0047a0a0(this_00,iVar1);
      }
      FUN_0040e9c0((void *)((int)this + 0x44),(int)local_14);
    }
  }
  FUN_00495f80((int)this);
  return;
}



================================================================================
REQUESTED 00496000
ENTRY 00496000
NAME FUN_00496000
SIGNATURE undefined4 * __thiscall FUN_00496000(void * this, uint param_1)
BODY [[00496000, 0049602b]]


undefined4 * __thiscall FUN_00496000(void *this,uint param_1)

{
  FUN_004953f0((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return (undefined4 *)this;
}



================================================================================
REQUESTED 00495f40
ENTRY 00495f40
NAME FUN_00495f40
SIGNATURE undefined __thiscall FUN_00495f40(void * this, CDataExchange * param_1)
BODY [[00495f40, 00495f58]]


void __thiscall FUN_00495f40(void *this,CDataExchange *param_1)

{
  FUN_004965a0(this,param_1);
  return;
}



================================================================================
REQUESTED 00495f00
ENTRY 00495f00
NAME FUN_00495f00
SIGNATURE undefined __thiscall FUN_00495f00(void * this, CDataExchange * param_1)
BODY [[00495f00, 00495f18]]


void __thiscall FUN_00495f00(void *this,CDataExchange *param_1)

{
  FUN_00496080(this,param_1);
  return;
}



================================================================================
REQUESTED 00495f60
ENTRY 00495f60
NAME FUN_00495f60
SIGNATURE undefined __thiscall FUN_00495f60(void * this, CDataExchange * param_1)
BODY [[00495f60, 00495f78]]


void __thiscall FUN_00495f60(void *this,CDataExchange *param_1)

{
  FUN_00496810(this,param_1);
  return;
}



================================================================================
REQUESTED 00495f20
ENTRY 00495f20
NAME FUN_00495f20
SIGNATURE undefined __thiscall FUN_00495f20(void * this, CDataExchange * param_1)
BODY [[00495f20, 00495f38]]


void __thiscall FUN_00495f20(void *this,CDataExchange *param_1)

{
  FUN_004962f0(this,param_1);
  return;
}



