Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004965a0
ENTRY 004965a0
NAME FUN_004965a0
SIGNATURE undefined __thiscall FUN_004965a0(void * this, CDataExchange * param_1)
BODY [[004965a0, 0049680e]]


void __thiscall FUN_004965a0(void *this,CDataExchange *param_1)

{
  char local_c;
  char local_b;
  char local_a;
  char local_9;
  char local_8;
  char local_7;
  char local_6;
  char local_5;
  
  CFindReplaceDialog::DoDataExchange((CFindReplaceDialog *)this,param_1);
  FUN_004024a0(param_1,(undefined4 *)((int)this + 8),4);
  FUN_00417900((void *)((int)this + 0xc),0);
  FUN_00402690(param_1,&local_5);
  if (local_5 != '\0') {
    FUN_00496b10((int *)param_1,(void *)((int)this + 0xc));
  }
  FUN_004024a0(param_1,(undefined4 *)((int)this + 0x10),4);
  FUN_004024a0(param_1,(undefined4 *)((int)this + 0x14),4);
  FUN_004024a0(param_1,(undefined4 *)((int)this + 0x18),4);
  FUN_004024a0(param_1,(undefined4 *)((int)this + 0x1c),4);
  FUN_004024a0(param_1,(undefined4 *)((int)this + 0x20),4);
  FUN_00406820(param_1,(undefined4 *)((int)this + 0x24));
  FUN_0044bde0((void *)((int)this + 0x28),0);
  FUN_00402690(param_1,&local_6);
  if (local_6 != '\0') {
    FUN_0041bd20((int *)param_1,(void *)((int)this + 0x28));
  }
  FUN_0044bde0((void *)((int)this + 0x2c),0);
  FUN_00402690(param_1,&local_7);
  if (local_7 != '\0') {
    FUN_0041bd20((int *)param_1,(void *)((int)this + 0x2c));
  }
  FUN_0044bde0((void *)((int)this + 0x30),0);
  FUN_00402690(param_1,&local_8);
  if (local_8 != '\0') {
    FUN_0041bd20((int *)param_1,(void *)((int)this + 0x30));
  }
  FUN_0044bde0((void *)((int)this + 0x34),0);
  FUN_00402690(param_1,&local_9);
  if (local_9 != '\0') {
    FUN_0041bd20((int *)param_1,(void *)((int)this + 0x34));
  }
  FUN_0044bde0((void *)((int)this + 0x38),0);
  FUN_00402690(param_1,&local_a);
  if (local_a != '\0') {
    FUN_0041bd20((int *)param_1,(void *)((int)this + 0x38));
  }
  FUN_00406820(param_1,(undefined4 *)((int)this + 0x3c));
  FUN_0044bde0((void *)((int)this + 0x40),0);
  FUN_00402690(param_1,&local_b);
  if (local_b != '\0') {
    FUN_0041bd20((int *)param_1,(void *)((int)this + 0x40));
  }
  FUN_0040e9c0((void *)((int)this + 0x44),0);
  FUN_00402690(param_1,&local_c);
  if (local_c != '\0') {
    FUN_0041bc80((int *)param_1,(void *)((int)this + 0x44));
  }
  FUN_00495f80((int)this);
  return;
}



================================================================================
REQUESTED 00496080
ENTRY 00496080
NAME FUN_00496080
SIGNATURE undefined __thiscall FUN_00496080(void * this, CDataExchange * param_1)
BODY [[00496080, 004962ee]]


void __thiscall FUN_00496080(void *this,CDataExchange *param_1)

{
  char local_c;
  char local_b;
  char local_a;
  char local_9;
  char local_8;
  char local_7;
  char local_6;
  char local_5;
  
  CFindReplaceDialog::DoDataExchange((CFindReplaceDialog *)this,param_1);
  FUN_00401c50(param_1,(int)this + 8,4);
  FUN_00417900((void *)((int)this + 0xc),0);
  FUN_00493b20(param_1,&local_5);
  if (local_5 != '\0') {
    FUN_00496ac0((int *)param_1,(void *)((int)this + 0xc));
  }
  FUN_00401c50(param_1,(int)this + 0x10,4);
  FUN_00401c50(param_1,(int)this + 0x14,4);
  FUN_00401c50(param_1,(int)this + 0x18,4);
  FUN_00401c50(param_1,(int)this + 0x1c,4);
  FUN_00401c50(param_1,(int)this + 0x20,4);
  FUN_004014a0(param_1,(int)this + 0x24);
  FUN_0044bde0((void *)((int)this + 0x28),0);
  FUN_00493b20(param_1,&local_6);
  if (local_6 != '\0') {
    FUN_00419ce0((int *)param_1,(void *)((int)this + 0x28));
  }
  FUN_0044bde0((void *)((int)this + 0x2c),0);
  FUN_00493b20(param_1,&local_7);
  if (local_7 != '\0') {
    FUN_00419ce0((int *)param_1,(void *)((int)this + 0x2c));
  }
  FUN_0044bde0((void *)((int)this + 0x30),0);
  FUN_00493b20(param_1,&local_8);
  if (local_8 != '\0') {
    FUN_00419ce0((int *)param_1,(void *)((int)this + 0x30));
  }
  FUN_0044bde0((void *)((int)this + 0x34),0);
  FUN_00493b20(param_1,&local_9);
  if (local_9 != '\0') {
    FUN_00419ce0((int *)param_1,(void *)((int)this + 0x34));
  }
  FUN_0044bde0((void *)((int)this + 0x38),0);
  FUN_00493b20(param_1,&local_a);
  if (local_a != '\0') {
    FUN_00419ce0((int *)param_1,(void *)((int)this + 0x38));
  }
  FUN_004014a0(param_1,(int)this + 0x3c);
  FUN_0044bde0((void *)((int)this + 0x40),0);
  FUN_00493b20(param_1,&local_b);
  if (local_b != '\0') {
    FUN_00419ce0((int *)param_1,(void *)((int)this + 0x40));
  }
  FUN_0040e9c0((void *)((int)this + 0x44),0);
  FUN_00493b20(param_1,&local_c);
  if (local_c != '\0') {
    FUN_00419c20((int *)param_1,(void *)((int)this + 0x44));
  }
  FUN_00495f80((int)this);
  return;
}



================================================================================
REQUESTED 00496810
ENTRY 00496810
NAME FUN_00496810
SIGNATURE undefined __thiscall FUN_00496810(void * this, CDataExchange * param_1)
BODY [[00496810, 00496abc]]


void __thiscall FUN_00496810(void *this,CDataExchange *param_1)

{
  int iVar1;
  
  CFindReplaceDialog::DoDataExchange((CFindReplaceDialog *)this,param_1);
  FUN_00402500(param_1,(undefined4 *)((int)this + 8),4);
  iVar1 = FUN_00417940((int *)((int)this + 0xc));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_00496b40((int *)param_1,(undefined4 *)((int)this + 0xc));
  }
  FUN_00402500(param_1,(undefined4 *)((int)this + 0x10),4);
  FUN_00402500(param_1,(undefined4 *)((int)this + 0x14),4);
  FUN_00402500(param_1,(undefined4 *)((int)this + 0x18),4);
  FUN_00402500(param_1,(undefined4 *)((int)this + 0x1c),4);
  FUN_00402500(param_1,(undefined4 *)((int)this + 0x20),4);
  FUN_00406980(param_1,*(undefined4 *)((int)this + 0x24));
  iVar1 = FUN_00417940((int *)((int)this + 0x28));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0((int *)param_1,(undefined4 *)((int)this + 0x28));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x2c));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0((int *)param_1,(undefined4 *)((int)this + 0x2c));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x30));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0((int *)param_1,(undefined4 *)((int)this + 0x30));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x34));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0((int *)param_1,(undefined4 *)((int)this + 0x34));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x38));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0((int *)param_1,(undefined4 *)((int)this + 0x38));
  }
  FUN_00406980(param_1,*(undefined4 *)((int)this + 0x3c));
  iVar1 = FUN_00417940((int *)((int)this + 0x40));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_004a03c0((int *)param_1,(undefined4 *)((int)this + 0x40));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x44));
  if (iVar1 == -1) {
    FUN_00493b40(param_1,0);
  }
  else {
    FUN_00493b40(param_1,1);
    FUN_0041c440((int *)param_1,(undefined4 *)((int)this + 0x44));
  }
  return;
}



================================================================================
REQUESTED 004962f0
ENTRY 004962f0
NAME FUN_004962f0
SIGNATURE undefined __thiscall FUN_004962f0(void * this, CDataExchange * param_1)
BODY [[004962f0, 0049659c]]


void __thiscall FUN_004962f0(void *this,CDataExchange *param_1)

{
  int iVar1;
  
  CFindReplaceDialog::DoDataExchange((CFindReplaceDialog *)this,param_1);
  FUN_00401ce0(param_1,(int)this + 8,4);
  iVar1 = FUN_00417940((int *)((int)this + 0xc));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00496af0((int *)param_1,(undefined4 *)((int)this + 0xc));
  }
  FUN_00401ce0(param_1,(int)this + 0x10,4);
  FUN_00401ce0(param_1,(int)this + 0x14,4);
  FUN_00401ce0(param_1,(int)this + 0x18,4);
  FUN_00401ce0(param_1,(int)this + 0x1c,4);
  FUN_00401ce0(param_1,(int)this + 0x20,4);
  FUN_004066c0(param_1,*(undefined4 *)((int)this + 0x24));
  iVar1 = FUN_00417940((int *)((int)this + 0x28));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250((int *)param_1,(undefined4 *)((int)this + 0x28));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x2c));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250((int *)param_1,(undefined4 *)((int)this + 0x2c));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x30));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250((int *)param_1,(undefined4 *)((int)this + 0x30));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x34));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250((int *)param_1,(undefined4 *)((int)this + 0x34));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x38));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250((int *)param_1,(undefined4 *)((int)this + 0x38));
  }
  FUN_004066c0(param_1,*(undefined4 *)((int)this + 0x3c));
  iVar1 = FUN_00417940((int *)((int)this + 0x40));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_00495250((int *)param_1,(undefined4 *)((int)this + 0x40));
  }
  iVar1 = FUN_00417940((int *)((int)this + 0x44));
  if (iVar1 == -1) {
    FUN_00402670(param_1,0);
  }
  else {
    FUN_00402670(param_1,1);
    FUN_0041ae20((int *)param_1,(undefined4 *)((int)this + 0x44));
  }
  return;
}



