Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 004529d0
ENTRY 004529d0
NAME FUN_004529d0
SIGNATURE undefined __thiscall FUN_004529d0(void * this, uint param_1, int param_2, int param_3, char param_4)
BODY [[004529d0, 00452b93]]


void __thiscall FUN_004529d0(void *this,uint param_1,int param_2,int param_3,char param_4)

{
  void *this_00;
  float10 fVar1;
  float local_20;
  float local_18;
  
  this_00 = (void *)FUN_00427130((undefined4 *)((int)this + param_2 * 4 + 0x50));
  switch(param_3) {
  case 0:
  case 1:
    if (param_4 == '\0') {
      if (((param_3 == 0) && (fVar1 = FUN_00454010((int)this_00), (float10)DAT_00571808 < fVar1)) ||
         ((param_3 == 1 && (fVar1 = FUN_00454010((int)this_00), fVar1 < (float10)DAT_00571808)))) {
        FUN_00431940(this_00,0);
      }
    }
    else if (param_3 == 0) {
      FUN_00431940(this_00,0x3f800000);
    }
    else {
      FUN_00431940(this_00,0xbf800000);
    }
    goto LAB_00452a8d;
  case 2:
    if (param_4 == '\0') {
      local_18 = 0.0;
    }
    else {
      local_18 = 1.0;
    }
    FUN_00431960(this_00,local_18 != DAT_00571808);
    if (((*(int *)((int)this + 0x114) != 0) && (param_1 <= *(int *)((int)this + 0x114) + 100U)) &&
       (*(int *)((int)this + 0x114) - 100U <= param_1)) {
      FUN_00431ab0(this_00,1000);
    }
    break;
  case 3:
    if (param_4 == '\0') {
      local_20 = 0.0;
    }
    else {
      local_20 = 1.0;
    }
    FUN_004319f0(this_00,local_20 != DAT_00571808);
    break;
  case 4:
    *(char *)((int)this + 0xd0) = param_4 != '\0';
LAB_00452a8d:
    if (param_4 == '\0') {
      FUN_00431a30(this_00,'\0');
    }
    else if ((*(char *)((int)this + 0xd0) != '\0') &&
            (fVar1 = FUN_00454010((int)this_00), (float10)DAT_00571808 != fVar1)) {
      FUN_00431a30(this_00,'\x01');
    }
  }
  return;
}



================================================================================
REQUESTED 00457ac0
ENTRY 00457ac0
NAME FUN_00457ac0
SIGNATURE undefined __thiscall FUN_00457ac0(void * this, uint param_1, int param_2, int param_3, char param_4)
BODY [[00457ac0, 00457ce9]]


void __thiscall FUN_00457ac0(void *this,uint param_1,int param_2,int param_3,char param_4)

{
  char cVar1;
  int *this_00;
  void *this_01;
  float10 fVar2;
  int iVar3;
  uint uVar4;
  float local_20;
  float local_18;
  
  this_00 = (int *)FUN_00427130((undefined4 *)((int)this + param_2 * 4 + 0x50));
  switch(param_3) {
  case 0:
  case 1:
    if (param_4 == '\0') {
      if (((param_3 == 0) && (fVar2 = FUN_00454010((int)this_00), (float10)DAT_00571808 < fVar2)) ||
         ((param_3 == 1 && (fVar2 = FUN_00454010((int)this_00), fVar2 < (float10)DAT_00571808)))) {
        FUN_00431940(this_00,0);
      }
    }
    else if (param_3 == 0) {
      FUN_00431940(this_00,0x3f800000);
    }
    else {
      FUN_00431940(this_00,0xbf800000);
    }
    goto LAB_00457b7d;
  case 2:
    if (param_4 == '\0') {
      local_18 = 0.0;
    }
    else {
      local_18 = 1.0;
    }
    FUN_00431960(this_00,local_18 != DAT_00571808);
    if (((*(int *)((int)this + 0xe0) != 0) && (param_1 <= *(int *)((int)this + 0xe0) + 100U)) &&
       (*(int *)((int)this + 0xe0) - 100U <= param_1)) {
      FUN_00431ab0(this_00,1000);
    }
    break;
  case 3:
    if (param_4 == '\0') {
      local_20 = 0.0;
    }
    else {
      local_20 = 1.0;
    }
    FUN_004319f0(this_00,local_20 != DAT_00571808);
  case 5:
    if (((param_4 != '\0') && (cVar1 = (**(code **)(*this_00 + 0x68))(), cVar1 == '\0')) &&
       (*(int *)((int)this + 0xec) != 0)) {
      *(int *)((int)this + 0xec) = *(int *)((int)this + 0xec) + -1;
      FUN_00431ab0(this_00,3000);
      uVar4 = 0xffffffff;
      iVar3 = *(int *)((int)this + 0xec);
      this_01 = (void *)FUN_0044fac0((int)this);
      FUN_00455770(this_01,iVar3,uVar4);
    }
    break;
  case 4:
    *(char *)((int)this + 0xcc) = param_4 != '\0';
LAB_00457b7d:
    if (param_4 == '\0') {
      FUN_00431a30(this_00,'\0');
    }
    else if ((*(char *)((int)this + 0xcc) != '\0') &&
            (fVar2 = FUN_00454010((int)this_00), (float10)DAT_00571808 != fVar2)) {
      FUN_00431a30(this_00,'\x01');
    }
  }
  return;
}



================================================================================
REQUESTED 00431ab0
ENTRY 00431ab0
NAME FUN_00431ab0
SIGNATURE undefined1 __thiscall FUN_00431ab0(void * this, undefined4 param_1)
BODY [[00431ab0, 00431af3]]


undefined1 __thiscall FUN_00431ab0(void *this,undefined4 param_1)

{
  if (*(float *)((int)this + 0x2e4) != DAT_00571808) {
    *(undefined4 *)((int)this + 0x158) = param_1;
    *(undefined1 *)((int)this + 0xe5) = 1;
  }
  return *(undefined1 *)((int)this + 0xe5);
}



================================================================================
REQUESTED 00431b00
ENTRY 00431b00
NAME FUN_00431b00
SIGNATURE undefined1 __fastcall FUN_00431b00(int param_1)
BODY [[00431b00, 00431b3b]]


undefined1 __fastcall FUN_00431b00(int param_1)

{
  undefined1 local_c;
  
  if ((*(char *)(param_1 + 0xe5) == '\0') && (*(char *)(param_1 + 0x2d4) == '\0')) {
    local_c = 0;
  }
  else {
    local_c = 1;
  }
  return local_c;
}



================================================================================
REQUESTED 0042e750
ENTRY 0042e750
NAME FUN_0042e750
SIGNATURE undefined __thiscall FUN_0042e750(void * this, uint param_1)
BODY [[0042e750, 0042ed05]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall FUN_0042e750(void *this,uint param_1)

{
  bool bVar1;
  char cVar2;
  void *pvVar3;
  float *pfVar4;
  uint *puVar5;
  float10 fVar6;
  uint uVar7;
  wchar_t *pwVar8;
  float fVar9;
  undefined1 local_68;
  undefined1 local_64;
  undefined1 local_60;
  char local_4c;
  uint local_48;
  float local_3c;
  float local_38;
  float local_34 [2];
  int local_2c;
  char local_25;
  uint local_24;
  uint local_20;
  uint local_1c;
  undefined4 local_18;
  char local_11;
  undefined4 local_10;
  uint local_c;
  undefined4 local_8;
  
  bVar1 = false;
  if (*(char *)((int)this + 0x119) != '\0') {
    FUN_00428d30(this,param_1);
    return;
  }
  local_10 = 5;
  if (*(int *)((int)this + 0x120) == 0) {
    local_c = 0;
    *(uint *)((int)this + 0x120) = param_1;
  }
  else {
    if (*(uint *)((int)this + 0x120) < param_1) {
      local_48 = param_1 - *(int *)((int)this + 0x120);
    }
    else {
      local_48 = 0;
    }
    local_c = local_48;
    *(uint *)((int)this + 0x120) = param_1;
  }
  local_8 = *(undefined4 *)((int)this + 0x160);
  local_18 = *(undefined4 *)((int)this + 0x164);
  local_11 = '\0';
                    /* WARNING: Load size is inaccurate */
  local_1c = local_c;
  cVar2 = (**(code **)(*this + 0x40))();
  if (cVar2 != '\0') {
    bVar1 = true;
    pwVar8 = L"점프";
                    /* WARNING: Load size is inaccurate */
    pvVar3 = (void *)(**(code **)(*this + 0x44))(&local_2c);
    cVar2 = FUN_0040ce00(pvVar3,pwVar8);
    if (cVar2 != '\0') {
      local_4c = '\x01';
      goto LAB_0042e851;
    }
  }
  local_4c = '\0';
LAB_0042e851:
  local_25 = local_4c;
  if (bVar1) {
    FUN_0040dab0(&local_2c);
  }
  if (local_25 != '\0') {
    local_11 = '\x01';
    *(undefined4 *)((int)this + 0x160) = 0x3f000000;
    *(undefined4 *)((int)this + 0x164) = 0x45bb8000;
  }
  *(undefined1 *)((int)this + 0xce) = 0;
  *(undefined1 *)((int)this + 0xdc) = 0;
  *(undefined1 *)((int)this + 0xe4) = 0;
  *(undefined4 *)((int)this + 0xd0) = 0;
  *(undefined4 *)((int)this + 0xe0) = 0;
  *(undefined1 *)((int)this + 0xd4) = 0;
  *(undefined4 *)((int)this + 0xd8) = 0;
  FUN_00431c60((undefined4 *)((int)this + 0x318));
  if (*(char *)((int)this + 0xcd) == '\0') {
    FUN_00431bf0((void *)((int)this + 0x318),(undefined4 *)((int)this + 0x2c));
    while (local_c != 0) {
      if (local_c < 5) {
        local_20 = local_c;
      }
      else {
        local_20 = 5;
      }
      local_c = local_c - local_20;
      FUN_0042eda0(this,(float)local_20 * _DAT_00571a2c);
      FUN_00469690(&stack0xffffff94,(int *)((int)this + 0x1c));
      cVar2 = FUN_0042ef90((int)this);
      if (cVar2 == '\0') {
        FUN_004305b0((int)this);
      }
      else {
        FUN_0042f460((int)this);
        FUN_0042f6c0((int)this);
        FUN_0042fc40((int)this);
      }
      FUN_00430640((int)this);
      FUN_00430740((int)this);
      FUN_00430ed0(this,(float)local_20 * _DAT_00571a2c);
      pvVar3 = (void *)FUN_00427130((undefined4 *)((int)this + 0x1c));
      FUN_00430830(this,pvVar3);
      if ((*(char *)((int)this + 0xce) == '\0') && (*(char *)((int)this + 0x2f8) == '\0')) {
        local_60 = 0;
      }
      else {
        local_60 = 1;
      }
      *(undefined1 *)((int)this + 0xce) = local_60;
      if ((*(char *)((int)this + 0xdc) == '\0') && (*(char *)((int)this + 0x301) == '\0')) {
        local_64 = 0;
      }
      else {
        local_64 = 1;
      }
      *(undefined1 *)((int)this + 0xdc) = local_64;
      if ((((*(char *)((int)this + 0xe4) != '\0') || (*(char *)((int)this + 0x2c8) != '\0')) ||
          (*(char *)((int)this + 0x2c9) != '\0')) || (DAT_00571808 < *(float *)((int)this + 0x2d0)))
      {
        local_68 = 1;
      }
      else {
        local_68 = 0;
      }
      *(undefined1 *)((int)this + 0xe4) = local_68;
      pfVar4 = FUN_0042afa0((float *)((int)this + 0xd0),(float *)((int)this + 0x2fc));
      *(float *)((int)this + 0xd0) = *pfVar4;
      pfVar4 = FUN_0042afa0((float *)((int)this + 0xe0),(float *)((int)this + 0x304));
      *(float *)((int)this + 0xe0) = *pfVar4;
      FUN_00431bf0((void *)((int)this + 0x318),(undefined4 *)((int)this + 0x2c));
    }
    *(undefined1 *)((int)this + 0xd4) = *(undefined1 *)((int)this + 0x300);
    if (*(char *)((int)this + 0xd4) == '\0') {
      *(undefined4 *)((int)this + 0xd8) = 0;
    }
  }
  else {
    *(undefined4 *)((int)this + 0x5c) = DAT_005b16cc;
    *(undefined4 *)((int)this + 0x60) = DAT_005b16d0;
    *(undefined4 *)((int)this + 100) = DAT_005b16d4;
    *(undefined4 *)((int)this + 0x68) = DAT_005b16cc;
    *(undefined4 *)((int)this + 0x6c) = DAT_005b16d0;
    *(undefined4 *)((int)this + 0x70) = DAT_005b16d4;
    *(undefined4 *)((int)this + 0x200) = DAT_005b16cc;
    *(undefined4 *)((int)this + 0x204) = DAT_005b16d0;
    *(undefined4 *)((int)this + 0x208) = DAT_005b16d4;
    *(undefined4 *)((int)this + 0x20c) = DAT_005b16cc;
    *(undefined4 *)((int)this + 0x210) = DAT_005b16d0;
    *(undefined4 *)((int)this + 0x214) = DAT_005b16d4;
  }
  fVar9 = *(float *)((int)this + 0x2c4) * _DAT_00571d14;
  pvVar3 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
  FUN_00432150(pvVar3,fVar9);
  fVar6 = (float10)FUN_004136f0((int)this + 0x5c);
  fVar9 = (float)fVar6;
  pvVar3 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
  FUN_00432170(pvVar3,fVar9);
  for (local_24 = 0; local_24 < 4; local_24 = local_24 + 1) {
    local_34[0] = *(float *)((int)this + local_24 * 4 + 0x278) - *(float *)((int)this + 0x2a8);
    local_38 = 0.1;
    local_3c = -0.1;
    pfVar4 = FUN_00431ea0(&local_38,local_34);
    pfVar4 = FUN_0042afa0(&local_3c,pfVar4);
    fVar9 = *pfVar4;
    uVar7 = local_24;
    pvVar3 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
    FUN_00432190(pvVar3,uVar7,fVar9);
  }
  if (*(int *)((int)this + 0x158) != 0) {
    puVar5 = FUN_00427bc0((uint *)((int)this + 0x158),&local_1c);
    *(uint *)((int)this + 0x158) = *(int *)((int)this + 0x158) - *puVar5;
    if (*(int *)((int)this + 0x158) == 0) {
      *(undefined1 *)((int)this + 0xe5) = 0;
    }
  }
  if (local_11 != '\0') {
    *(undefined4 *)((int)this + 0x160) = local_8;
    *(undefined4 *)((int)this + 0x164) = local_18;
  }
  FUN_00428d30(this,param_1);
  return;
}



