Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 0042e750
ENTRY 0042e750
NAME FUN_0042e750
SIGNATURE undefined __thiscall FUN_0042e750(void * this, uint param_1)
BODY [[0042e750, 0042ed05]]


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall FUN_0042e750(void *this,uint param_1)

{
  bool bVar1;
  char cVar2;
  void *pvVar3;
  float *pfVar4;
  uint *puVar5;
  float10 fVar6;
  uint uVar7;
  wchar_t *pwVar8;
  float fVar9;
  undefined1 local_68;
  undefined1 local_64;
  undefined1 local_60;
  char local_4c;
  uint local_48;
  float local_3c;
  float local_38;
  float local_34 [2];
  int local_2c;
  char local_25;
  uint local_24;
  uint local_20;
  uint local_1c;
  undefined4 local_18;
  char local_11;
  undefined4 local_10;
  uint local_c;
  undefined4 local_8;
  
  bVar1 = false;
  if (*(char *)((int)this + 0x119) != '\0') {
    FUN_00428d30(this,param_1);
    return;
  }
  local_10 = 5;
  if (*(int *)((int)this + 0x120) == 0) {
    local_c = 0;
    *(uint *)((int)this + 0x120) = param_1;
  }
  else {
    if (*(uint *)((int)this + 0x120) < param_1) {
      local_48 = param_1 - *(int *)((int)this + 0x120);
    }
    else {
      local_48 = 0;
    }
    local_c = local_48;
    *(uint *)((int)this + 0x120) = param_1;
  }
  local_8 = *(undefined4 *)((int)this + 0x160);
  local_18 = *(undefined4 *)((int)this + 0x164);
  local_11 = '\0';
                    /* WARNING: Load size is inaccurate */
  local_1c = local_c;
  cVar2 = (**(code **)(*this + 0x40))();
  if (cVar2 != '\0') {
    bVar1 = true;
    pwVar8 = L"점프";
                    /* WARNING: Load size is inaccurate */
    pvVar3 = (void *)(**(code **)(*this + 0x44))(&local_2c);
    cVar2 = FUN_0040ce00(pvVar3,pwVar8);
    if (cVar2 != '\0') {
      local_4c = '\x01';
      goto LAB_0042e851;
    }
  }
  local_4c = '\0';
LAB_0042e851:
  local_25 = local_4c;
  if (bVar1) {
    FUN_0040dab0(&local_2c);
  }
  if (local_25 != '\0') {
    local_11 = '\x01';
    *(undefined4 *)((int)this + 0x160) = 0x3f000000;
    *(undefined4 *)((int)this + 0x164) = 0x45bb8000;
  }
  *(undefined1 *)((int)this + 0xce) = 0;
  *(undefined1 *)((int)this + 0xdc) = 0;
  *(undefined1 *)((int)this + 0xe4) = 0;
  *(undefined4 *)((int)this + 0xd0) = 0;
  *(undefined4 *)((int)this + 0xe0) = 0;
  *(undefined1 *)((int)this + 0xd4) = 0;
  *(undefined4 *)((int)this + 0xd8) = 0;
  FUN_00431c60((undefined4 *)((int)this + 0x318));
  if (*(char *)((int)this + 0xcd) == '\0') {
    FUN_00431bf0((void *)((int)this + 0x318),(undefined4 *)((int)this + 0x2c));
    while (local_c != 0) {
      if (local_c < 5) {
        local_20 = local_c;
      }
      else {
        local_20 = 5;
      }
      local_c = local_c - local_20;
      FUN_0042eda0(this,(float)local_20 * _DAT_00571a2c);
      FUN_00469690(&stack0xffffff94,(int *)((int)this + 0x1c));
      cVar2 = FUN_0042ef90((int)this);
      if (cVar2 == '\0') {
        FUN_004305b0((int)this);
      }
      else {
        FUN_0042f460((int)this);
        FUN_0042f6c0((int)this);
        FUN_0042fc40((int)this);
      }
      FUN_00430640((int)this);
      FUN_00430740((int)this);
      FUN_00430ed0(this,(float)local_20 * _DAT_00571a2c);
      pvVar3 = (void *)FUN_00427130((undefined4 *)((int)this + 0x1c));
      FUN_00430830(this,pvVar3);
      if ((*(char *)((int)this + 0xce) == '\0') && (*(char *)((int)this + 0x2f8) == '\0')) {
        local_60 = 0;
      }
      else {
        local_60 = 1;
      }
      *(undefined1 *)((int)this + 0xce) = local_60;
      if ((*(char *)((int)this + 0xdc) == '\0') && (*(char *)((int)this + 0x301) == '\0')) {
        local_64 = 0;
      }
      else {
        local_64 = 1;
      }
      *(undefined1 *)((int)this + 0xdc) = local_64;
      if ((((*(char *)((int)this + 0xe4) != '\0') || (*(char *)((int)this + 0x2c8) != '\0')) ||
          (*(char *)((int)this + 0x2c9) != '\0')) || (DAT_00571808 < *(float *)((int)this + 0x2d0)))
      {
        local_68 = 1;
      }
      else {
        local_68 = 0;
      }
      *(undefined1 *)((int)this + 0xe4) = local_68;
      pfVar4 = FUN_0042afa0((float *)((int)this + 0xd0),(float *)((int)this + 0x2fc));
      *(float *)((int)this + 0xd0) = *pfVar4;
      pfVar4 = FUN_0042afa0((float *)((int)this + 0xe0),(float *)((int)this + 0x304));
      *(float *)((int)this + 0xe0) = *pfVar4;
      FUN_00431bf0((void *)((int)this + 0x318),(undefined4 *)((int)this + 0x2c));
    }
    *(undefined1 *)((int)this + 0xd4) = *(undefined1 *)((int)this + 0x300);
    if (*(char *)((int)this + 0xd4) == '\0') {
      *(undefined4 *)((int)this + 0xd8) = 0;
    }
  }
  else {
    *(undefined4 *)((int)this + 0x5c) = DAT_005b16cc;
    *(undefined4 *)((int)this + 0x60) = DAT_005b16d0;
    *(undefined4 *)((int)this + 100) = DAT_005b16d4;
    *(undefined4 *)((int)this + 0x68) = DAT_005b16cc;
    *(undefined4 *)((int)this + 0x6c) = DAT_005b16d0;
    *(undefined4 *)((int)this + 0x70) = DAT_005b16d4;
    *(undefined4 *)((int)this + 0x200) = DAT_005b16cc;
    *(undefined4 *)((int)this + 0x204) = DAT_005b16d0;
    *(undefined4 *)((int)this + 0x208) = DAT_005b16d4;
    *(undefined4 *)((int)this + 0x20c) = DAT_005b16cc;
    *(undefined4 *)((int)this + 0x210) = DAT_005b16d0;
    *(undefined4 *)((int)this + 0x214) = DAT_005b16d4;
  }
  fVar9 = *(float *)((int)this + 0x2c4) * _DAT_00571d14;
  pvVar3 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
  FUN_00432150(pvVar3,fVar9);
  fVar6 = (float10)FUN_004136f0((int)this + 0x5c);
  fVar9 = (float)fVar6;
  pvVar3 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
  FUN_00432170(pvVar3,fVar9);
  for (local_24 = 0; local_24 < 4; local_24 = local_24 + 1) {
    local_34[0] = *(float *)((int)this + local_24 * 4 + 0x278) - *(float *)((int)this + 0x2a8);
    local_38 = 0.1;
    local_3c = -0.1;
    pfVar4 = FUN_00431ea0(&local_38,local_34);
    pfVar4 = FUN_0042afa0(&local_3c,pfVar4);
    fVar9 = *pfVar4;
    uVar7 = local_24;
    pvVar3 = (void *)FUN_00427130((undefined4 *)((int)this + 0x18));
    FUN_00432190(pvVar3,uVar7,fVar9);
  }
  if (*(int *)((int)this + 0x158) != 0) {
    puVar5 = FUN_00427bc0((uint *)((int)this + 0x158),&local_1c);
    *(uint *)((int)this + 0x158) = *(int *)((int)this + 0x158) - *puVar5;
    if (*(int *)((int)this + 0x158) == 0) {
      *(undefined1 *)((int)this + 0xe5) = 0;
    }
  }
  if (local_11 != '\0') {
    *(undefined4 *)((int)this + 0x160) = local_8;
    *(undefined4 *)((int)this + 0x164) = local_18;
  }
  FUN_00428d30(this,param_1);
  return;
}



================================================================================
REQUESTED 0042de00
ENTRY 0042de00
NAME FUN_0042de00
SIGNATURE undefined4 * __fastcall FUN_0042de00(undefined4 * param_1)
BODY [[0042de00, 0042e153]]


undefined4 * __fastcall FUN_0042de00(undefined4 *param_1)

{
  undefined4 uVar1;
  CSize local_5;
  
  FUN_00428820(param_1);
  *param_1 = &PTR_FUN_00571a7c;
  CSize::CSize((CSize *)(param_1 + 0x4d));
  CSize::CSize((CSize *)(param_1 + 0x6a));
  CSize::CSize((CSize *)(param_1 + 0x6d));
  CSize::CSize((CSize *)(param_1 + 0x70));
  CSize::CSize((CSize *)(param_1 + 0x73));
  CSize::CSize((CSize *)(param_1 + 0x76));
  CSize::CSize((CSize *)(param_1 + 0x7c));
  CSize::CSize((CSize *)(param_1 + 0x80));
  CSize::CSize((CSize *)(param_1 + 0x83));
  _vector_constructor_iterator_(param_1 + 0x92,0xc,4,CSize::CSize);
  CSize::CSize((CSize *)(param_1 + 0xc2));
  uVar1 = CSize::CSize(&local_5);
  FUN_00401310(param_1 + 0xc6,uVar1);
  FUN_00493460();
  param_1[0x48] = 0;
  param_1[0xaa] = 0x3f000000;
  param_1[0xa1] = 0x3f000000;
  param_1[0xa0] = 0x3f000000;
  param_1[0x9f] = 0x3f000000;
  param_1[0x9e] = 0x3f000000;
  param_1[0x89] = 0x3f800000;
  param_1[0x8d] = 0x3f800000;
  param_1[0x8a] = 0xbf800000;
  param_1[0x8e] = 0x3f800000;
  param_1[0x8b] = 0x3f800000;
  param_1[0x8f] = 0xbf800000;
  param_1[0x8c] = 0xbf800000;
  param_1[0x90] = 0xbf800000;
  FUN_00482180(param_1 + 0x7c,(float *)(param_1 + 0xe));
  param_1[0x80] = DAT_005b16cc;
  param_1[0x81] = DAT_005b16d0;
  param_1[0x82] = DAT_005b16d4;
  param_1[0x83] = DAT_005b16cc;
  param_1[0x84] = DAT_005b16d0;
  param_1[0x85] = DAT_005b16d4;
  param_1[0x56] = 0;
  param_1[0xb9] = 0;
  param_1[0xba] = 0;
  param_1[0xbb] = 0;
  *(undefined1 *)(param_1 + 0xb2) = 0;
  *(undefined1 *)((int)param_1 + 0x2c9) = 0;
  *(undefined1 *)((int)param_1 + 0x2ca) = 0;
  param_1[0xb3] = 0;
  param_1[0xb4] = 0;
  *(undefined1 *)(param_1 + 0xbe) = 0;
  *(undefined1 *)(param_1 + 0xc0) = 1;
  *(undefined1 *)((int)param_1 + 0x301) = 0;
  param_1[0xab] = 0;
  param_1[0xac] = 0;
  param_1[0xad] = 0;
  param_1[0xae] = 0;
  param_1[0xaf] = 0;
  param_1[0xb1] = 0;
  param_1[0xb0] = 0;
  *(undefined1 *)(param_1 + 0xb5) = 0;
  param_1[0xb6] = 0;
  *(undefined1 *)(param_1 + 0xb7) = 0;
  param_1[0xb8] = 0;
  *(undefined1 *)(param_1 + 0x49) = 0;
  *(undefined1 *)(param_1 + 0xbc) = 0;
  param_1[0xbd] = 0;
  param_1[0xc2] = DAT_005b16cc;
  param_1[0xc3] = DAT_005b16d0;
  param_1[0xc4] = DAT_005b16d4;
  param_1[0xc5] = 0x3f800000;
  return param_1;
}



================================================================================
REQUESTED 004305b0
ENTRY 004305b0
NAME FUN_004305b0
SIGNATURE undefined __fastcall FUN_004305b0(int param_1)
BODY [[004305b0, 0043063d]]


void __fastcall FUN_004305b0(int param_1)

{
  float *pfVar1;
  undefined1 local_1c [12];
  undefined1 local_10 [12];
  
  *(undefined1 *)(param_1 + 0x2ca) = 0;
  *(undefined1 *)(param_1 + 0x2c8) = 0;
  *(undefined1 *)(param_1 + 0x2c9) = 0;
  pfVar1 = (float *)FUN_00418790(local_10,(float *)(param_1 + 0x1b4),*(float *)(param_1 + 0x128));
  FUN_00418680((void *)(param_1 + 0x200),pfVar1);
  pfVar1 = (float *)FUN_00418790(local_1c,(float *)(param_1 + 0x68),30.0);
  FUN_00432070((void *)(param_1 + 0x20c),pfVar1);
  *(undefined4 *)(param_1 + 0x2c0) = 0;
  return;
}



================================================================================
REQUESTED 00430740
ENTRY 00430740
NAME FUN_00430740
SIGNATURE undefined __fastcall FUN_00430740(int param_1)
BODY [[00430740, 00430827]]


void __fastcall FUN_00430740(int param_1)

{
  float *pfVar1;
  float fVar2;
  undefined1 local_58 [12];
  undefined1 local_4c [12];
  undefined1 local_40 [12];
  undefined1 local_34 [12];
  undefined1 local_28 [12];
  undefined1 local_1c [12];
  undefined1 local_10 [12];
  
  FUN_00418680((void *)(param_1 + 0x200),(float *)(param_1 + 0x308));
  fVar2 = *(float *)(param_1 + 0x1a0);
  pfVar1 = (float *)FUN_00428530(local_10,(float *)(param_1 + 0x200),*(float *)(param_1 + 0x128));
  pfVar1 = (float *)FUN_00418790(local_1c,pfVar1,fVar2);
  FUN_00418680((void *)(param_1 + 0x5c),pfVar1);
  fVar2 = *(float *)(param_1 + 0x1a0);
  pfVar1 = (float *)FUN_0042d980(local_28,(float *)(param_1 + 0x134),(float *)(param_1 + 0x68));
  pfVar1 = (float *)FUN_00428490(local_34,(float *)(param_1 + 0x68),pfVar1);
  pfVar1 = (float *)FUN_00418750(local_40,(float *)(param_1 + 0x20c),pfVar1);
  pfVar1 = (float *)FUN_0042d980(local_4c,(float *)(param_1 + 0x134),pfVar1);
  pfVar1 = (float *)FUN_00418790(local_58,pfVar1,fVar2);
  FUN_00418680((void *)(param_1 + 0x68),pfVar1);
  return;
}



================================================================================
REQUESTED 00431960
ENTRY 00431960
NAME FUN_00431960
SIGNATURE undefined __thiscall FUN_00431960(void * this, char param_1)
BODY [[00431960, 004319e1]]


void __thiscall FUN_00431960(void *this,char param_1)

{
  if (param_1 == '\0') {
    *(undefined4 *)((int)this + 0x2e4) = 0;
    *(undefined4 *)((int)this + 0x158) = 0;
    *(undefined1 *)((int)this + 0xe5) = 0;
  }
  else {
    *(undefined4 *)((int)this + 0x2e4) = 0x3f800000;
    if (DAT_00571808 < *(float *)((int)this + 0x2e0)) {
      *(undefined4 *)((int)this + 0x2e0) = 0;
      *(undefined4 *)((int)this + 0x2d8) = 0x3f000000;
      *(undefined1 *)((int)this + 0x2d4) = 1;
    }
  }
  return;
}



================================================================================
REQUESTED 00431a30
ENTRY 00431a30
NAME FUN_00431a30
SIGNATURE undefined __thiscall FUN_00431a30(void * this, char param_1)
BODY [[00431a30, 00431aae]]


void __thiscall FUN_00431a30(void *this,char param_1)

{
  if (param_1 == '\0') {
    *(undefined1 *)((int)this + 0x2c8) = 0;
  }
  else if (*(float *)((int)this + 0x2d0) < DAT_00571808 !=
           (*(float *)((int)this + 0x2d0) == DAT_00571808)) {
    *(undefined1 *)((int)this + 0x2c8) = 1;
    *(undefined1 *)((int)this + 0x2ca) = 1;
    *(bool *)((int)this + 0x2dc) = DAT_00571808 < *(float *)((int)this + 0x1e4);
  }
  return;
}



================================================================================
REQUESTED 0042eda0
ENTRY 0042eda0
NAME FUN_0042eda0
SIGNATURE undefined __thiscall FUN_0042eda0(void * this, float param_1)
BODY [[0042eda0, 0042ef81]]


void __thiscall FUN_0042eda0(void *this,float param_1)

{
  undefined4 *puVar1;
  void *this_00;
  float *pfVar2;
  float10 fVar3;
  undefined1 *puVar4;
  float local_38;
  undefined1 local_34 [12];
  undefined1 local_28 [12];
  undefined1 local_1c [12];
  undefined1 local_10 [12];
  
  *(undefined4 *)((int)this + 0x200) = DAT_005b16cc;
  *(undefined4 *)((int)this + 0x204) = DAT_005b16d0;
  *(undefined4 *)((int)this + 0x208) = DAT_005b16d4;
  *(undefined4 *)((int)this + 0x20c) = DAT_005b16cc;
  *(undefined4 *)((int)this + 0x210) = DAT_005b16d0;
  *(undefined4 *)((int)this + 0x214) = DAT_005b16d4;
  *(float *)((int)this + 0x1a0) = param_1;
  puVar1 = (undefined4 *)FUN_00428570((void *)((int)this + 0x38),local_10,0);
  *(undefined4 *)((int)this + 0x1c0) = *puVar1;
  *(undefined4 *)((int)this + 0x1c4) = puVar1[1];
  *(undefined4 *)((int)this + 0x1c8) = puVar1[2];
  puVar4 = local_28;
  this_00 = FUN_00428570((void *)((int)this + 0x38),local_1c,1);
  puVar1 = (undefined4 *)FUN_00413650(this_00,puVar4);
  *(undefined4 *)((int)this + 0x1d8) = *puVar1;
  *(undefined4 *)((int)this + 0x1dc) = puVar1[1];
  *(undefined4 *)((int)this + 0x1e0) = puVar1[2];
  puVar1 = (undefined4 *)FUN_00428570((void *)((int)this + 0x38),local_34,2);
  *(undefined4 *)((int)this + 0x1cc) = *puVar1;
  *(undefined4 *)((int)this + 0x1d0) = puVar1[1];
  *(undefined4 *)((int)this + 0x1d4) = puVar1[2];
  fVar3 = FUN_00428460((float *)((int)this + 0x5c),(float *)((int)this + 0x1d8));
  *(float *)((int)this + 0x1e4) = (float)fVar3;
  fVar3 = FUN_00428460((float *)((int)this + 0x5c),(float *)((int)this + 0x1c0));
  *(float *)((int)this + 0x1e8) = (float)fVar3;
  fVar3 = (float10)FUN_004136f0((int)this + 0x5c);
  *(float *)((int)this + 0x1ec) = (float)fVar3;
  if (DAT_00571808 < *(float *)((int)this + 0x2e0)) {
    *(float *)((int)this + 0x2e0) = *(float *)((int)this + 0x2e0) - param_1;
    local_38 = 0.0;
    pfVar2 = FUN_0042afa0(&local_38,(float *)((int)this + 0x2e0));
    *(float *)((int)this + 0x2e0) = *pfVar2;
  }
  if ((*(char *)((int)this + 0x2d4) != '\0') &&
     (*(float *)((int)this + 0x2d8) = *(float *)((int)this + 0x2d8) - param_1,
     *(float *)((int)this + 0x2d8) < DAT_00571808 != (*(float *)((int)this + 0x2d8) == DAT_00571808)
     )) {
    *(undefined4 *)((int)this + 0x2d8) = 0;
    *(undefined1 *)((int)this + 0x2d4) = 0;
  }
  return;
}



