Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00428490
ENTRY 00428490
NAME FUN_00428490
SIGNATURE void * __cdecl FUN_00428490(void * param_1, float * param_2, float * param_3)
BODY [[00428490, 004284f5]]


void * __cdecl FUN_00428490(void *param_1,float *param_2,float *param_3)

{
  FUN_004135a0(param_1,param_2[1] * param_3[2] - param_2[2] * param_3[1],
               param_2[2] * *param_3 - *param_2 * param_3[2],
               *param_2 * param_3[1] - param_2[1] * *param_3);
  return param_1;
}



================================================================================
REQUESTED 004285b0
ENTRY 004285b0
NAME FUN_004285b0
SIGNATURE undefined __thiscall FUN_004285b0(void * this, int param_1, undefined4 * param_2)
BODY [[004285b0, 004285ea]]


void __thiscall FUN_004285b0(void *this,int param_1,undefined4 *param_2)

{
  *(undefined4 *)((int)this + param_1 * 4) = *param_2;
  *(undefined4 *)((int)this + param_1 * 4 + 0xc) = param_2[1];
  *(undefined4 *)((int)this + param_1 * 4 + 0x18) = param_2[2];
  return;
}



================================================================================
REQUESTED 0042b330
ENTRY 0042b330
NAME FUN_0042b330
SIGNATURE undefined __thiscall FUN_0042b330(void * this, int param_1, undefined4 * param_2)
BODY [[0042b330, 0042b36a]]


void __thiscall FUN_0042b330(void *this,int param_1,undefined4 *param_2)

{
  *param_2 = *(undefined4 *)((int)this + param_1 * 4);
  param_2[1] = *(undefined4 *)((int)this + param_1 * 4 + 0xc);
  param_2[2] = *(undefined4 *)((int)this + param_1 * 4 + 0x18);
  return;
}



