Selected KartRider.exe decompilations
Generated by Ghidra; names and types remain provisional.

================================================================================
REQUESTED 00497b10
ENTRY 00497b10
NAME FUN_00497b10
SIGNATURE undefined __fastcall FUN_00497b10(undefined4 * param_1)
BODY [[00497b10, 00497b2b]]


void __fastcall FUN_00497b10(undefined4 *param_1)

{
  *param_1 = &PTR_FUN_00575dec;
  FUN_004b0d80(param_1);
  return;
}



================================================================================
REQUESTED 00497c80
ENTRY 00497c80
NAME FUN_00497c80
SIGNATURE undefined __thiscall FUN_00497c80(void * this, CDataExchange * param_1)
BODY [[00497c80, 00497ca9]]


void __thiscall FUN_00497c80(void *this,CDataExchange *param_1)

{
  CFindReplaceDialog::DoDataExchange((CFindReplaceDialog *)this,param_1);
  FUN_00401c50(param_1,(int)this + 8,1);
  return;
}



================================================================================
REQUESTED 00497cb0
ENTRY 00497cb0
NAME FUN_00497cb0
SIGNATURE undefined __thiscall FUN_00497cb0(void * this, CDataExchange * param_1)
BODY [[00497cb0, 00497cd9]]


void __thiscall FUN_00497cb0(void *this,CDataExchange *param_1)

{
  CFindReplaceDialog::DoDataExchange((CFindReplaceDialog *)this,param_1);
  FUN_00401ce0(param_1,(int)this + 8,1);
  return;
}



================================================================================
REQUESTED 00497ce0
ENTRY 00497ce0
NAME FUN_00497ce0
SIGNATURE undefined __thiscall FUN_00497ce0(void * this, CDataExchange * param_1)
BODY [[00497ce0, 00497d09]]


void __thiscall FUN_00497ce0(void *this,CDataExchange *param_1)

{
  CFindReplaceDialog::DoDataExchange((CFindReplaceDialog *)this,param_1);
  FUN_004024a0(param_1,(undefined4 *)((int)this + 8),1);
  return;
}



================================================================================
REQUESTED 00497d10
ENTRY 00497d10
NAME FUN_00497d10
SIGNATURE undefined __thiscall FUN_00497d10(void * this, CDataExchange * param_1)
BODY [[00497d10, 00497d39]]


void __thiscall FUN_00497d10(void *this,CDataExchange *param_1)

{
  CFindReplaceDialog::DoDataExchange((CFindReplaceDialog *)this,param_1);
  FUN_00402500(param_1,(undefined4 *)((int)this + 8),1);
  return;
}



