#ifndef KART_TRACK_SCENE_RESOURCES_H
#define KART_TRACK_SCENE_RESOURCES_H

#define IDR_TRACK_SCENE_DESERT_I01 201
#define IDR_TRACK_SCENE_DESERT_I02 202
#define IDR_TRACK_SCENE_DESERT_R01 203
#define IDR_TRACK_SCENE_FOREST_I01 204
#define IDR_TRACK_SCENE_FOREST_I02 205
#define IDR_TRACK_SCENE_FOREST_R02 206
#define IDR_TRACK_SCENE_ICE_I01 207
#define IDR_TRACK_SCENE_ICE_I02 208
#define IDR_TRACK_SCENE_ICE_R01 209
#define IDR_TRACK_SCENE_VILLAGE_I01 210
#define IDR_TRACK_SCENE_VILLAGE_I02 211
#define IDR_TRACK_SCENE_VILLAGE_R01 212
#define IDR_TRACK_SCENE_VILLAGE_R03 213

#ifndef RC_INVOKED
#include "kart_demo_data.h"

/* Parallel to TRACKS[] in src/kart_demo_data.c, so entry i belongs to
   kart_demo_track_at(i). */
static const int KART_TRACK_SCENE_RESOURCE_IDS[] = {
    0, /* flat_test: synthetic, no mesh */
    IDR_TRACK_SCENE_DESERT_I01,
    IDR_TRACK_SCENE_DESERT_I02,
    IDR_TRACK_SCENE_DESERT_R01,
    IDR_TRACK_SCENE_FOREST_I01,
    IDR_TRACK_SCENE_FOREST_I02,
    IDR_TRACK_SCENE_FOREST_R02,
    IDR_TRACK_SCENE_ICE_I01,
    IDR_TRACK_SCENE_ICE_I02,
    IDR_TRACK_SCENE_ICE_R01,
    IDR_TRACK_SCENE_VILLAGE_I01,
    IDR_TRACK_SCENE_VILLAGE_I02,
    IDR_TRACK_SCENE_VILLAGE_R01,
    IDR_TRACK_SCENE_VILLAGE_R03,
};

#define KART_TRACK_SCENE_CAPACITY \
    (sizeof(KART_TRACK_SCENE_RESOURCE_IDS) / \
     sizeof(KART_TRACK_SCENE_RESOURCE_IDS[0]))

_Static_assert(
    KART_TRACK_SCENE_CAPACITY == KART_DEMO_TRACK_COUNT,
    "one scene resource id per track, in TRACKS[] order; use 0 for a track "
    "with no decoded mesh");
#endif

#endif
